= Arithmetic


The following keywords can be used for arithmetic operations between <<_value_variables,value variables>>,
concept variables referencing attributes, and constants:

//#todo reimplement the links to examples
// tag::arithmetics[]
1. `()` -- parentheses.
See an xref:typeql::data/examples.adoc#_using_parentheses[example].
2. `^` -- exponentiation (power).
See an xref:typeql::data/examples.adoc#_using_exponentiation[example].
3. `*` -- multiplication.
See an xref:typeql::data/examples.adoc#_using_multiplication[example].
4. `/` -- division.
See an xref:typeql::data/examples.adoc#_using_division[example].
5. `%` -- https://en.wikipedia.org/wiki/Modulo[modulo,window=_blank]. Returns the remainder of a division.
See an xref:typeql::data/examples.adoc#_using_modulo[example].
6. `+` -- addition.
See an xref:typeql::data/examples.adoc#_using_addition[example].
7. `-` -- subtraction.
See an xref:typeql::data/examples.adoc#_using_subtraction[example].
// end::arithmetics[]

[IMPORTANT]
====
The above list is sorted by the order in which those operations are applied in an expression.
====

.Arithmetic example
[,typeql]
----
$f isa file, has size-kb $s;
?mb = $s/1024;
?mb > 1;
----

In the above example, we designed a pattern to match instances of data for `file` type owning `size-kb` attribute
with a value that, after dividing it by `1024` (to get megabytes out of kilobytes), is bigger than `1`.