= Built-in operations

== Arithmetic expression

[#_expression]
An arithmetic expression describes a computation of a value in a query.
It can be used only in a `match` clause or a body of a function to set a value for a variable
and can contain any combination of the following elements:

* a variable containing a value (e.g., `$sum`) or a concept with a value (attribute),
* a literal value (e.g., `4`),
* an arithmetic operation (e.g., `+`),
* a xref:values/built-in.adoc[built-in function] (e.g., `max()`),
* a user-defined xref:functions/overview.adoc[function].

.Expression example
[,typeql]
----
$y = round(($x + 1) / 2);
----

In the above example, the variable `$y` is bound to the value calculated by adding `1` to the value of `$x`,
dividing the result by two, and then applying the built-in <<_round_function,round>> function.

[#_operations]
== Arithmetic operations

TypeQL includes the following arithmetic operations for values, presented in the order of operations in an expression:

// tag::arithmetics[]
1. `()` -- parentheses.
2. `^` -- exponentiation (power).
3. `*` -- multiplication.
4. `/` -- division.
5. `%` -- https://en.wikipedia.org/wiki/Modulo[modulo,window=_blank] (the remainder of a division).
6. `+` -- addition.
7. `-` -- subtraction.
// end::arithmetics[]

.Arithmetic example
[,typeql]
----
$size-gb = (($size-kb + $overhead)/ 1024) / 1024;
----

In the above example, the variable `size-gb` is bound to the result of a complex arithmetic expression.
The expression takes the value of the `$size-kb` variable, adds it to a value of the `$o` variable,
then divides the result by `1024`, and finally divides the result by `1024` again.
It represents a conversion of kilobytes into gigabytes.

Arithmetic operations are often used in a combination with xref:values/comparators.adoc[comparators]
to set a constraint on data to match by a pattern.

== Built-in functions

There are multiple built-in functions available in TypeQL for value operations:

* `min()`, `max()` -- to find the minimum or maximum value out of all presented comma-separated values
+
.Example
[,typeql]
----
$maximum = max(100, $x, $a);
----

* `ceil()`, `floor()`-- to round up or down the inputted number
+
.Example
[,typeql]
----
$int = floor(100.7);
----

* `round()` -- to round half up a number
+
.Example
[,typeql]
----
$int = round(100.7);
----

* `abs()` -- to find absolute value of a number
+
.Example
[,typeql]
----
$x = abs($s - 1000);
----
