= Built-in operations

== Arithmetic

== Expressions

Arithmetic expressions can be used to set a value of a value variable based on other values used in a query.
To use arithmetic operations, start a statement with a value variable and an equal sign, followed by an expression.

[#_expression]
An expression describes a computation of a value in a query.
It can be used only in a `match` clause or a `condition` of a rule
and can contain any combination of the following elements:

* a xref:concepts/variables.adoc[concept variable] representing an attribute (e.g., `$size-kb`),
* a variable containing a value (e.g., `$sum`),
* a literal value (e.g., `4`),
* xref:values/built-in.adoc[built-in function] (e.g., `max()`).

.Expression example
[,typeql]
----
?x = $s + 1;
----

In the above example, the value variable `?x` is bound to the value of the attribute in `$s` added `1`.

[#_operations]
== Operations

TypeQL includes the following arithmetic operations for values, presented in the order of operations in an expression:

//#todo reimplement the links to examples
// tag::arithmetics[]
1. `()` -- parentheses.
2. `^` -- exponentiation (power).
3. `*` -- multiplication.
4. `/` -- division.
5. `%` -- https://en.wikipedia.org/wiki/Modulo[modulo,window=_blank] (the remainder of a division).
6. `+` -- addition.
7. `-` -- subtraction.
// end::arithmetics[]

.Arithmetic example
[,typeql]
----
?gb = (($s + ?o)/ 1024) / 1024;
----

In the above example, the value variable `?gb` is bound to the result of a complex arithmetic expression.
The expression takes the value of concept variable `$s`, adds it to a value of value variable `?o`,
then divides the result by `1024`, and finally divides the result by `1024` again.

Arithmetic operations are often used in a combination with xref:values/comparators.adoc[comparators] and
xref:{page-component-version}@learn::5-defining-schemas/5.4-defining-rules.adoc[rules].

== Min / Max functions

Use the `max()` function to find the maximum value out of all provided input arguments,
or the `min()` to find the minimum.

.Example
[,typeql]
----
?maximum = max(100, $x, ?a);
----

== Ceil / Floor functions

Use the `ceil()` function to round up the input value, or the `floor()` to round down.

.Example
[,typeql]
----
?int = floor(100.7);
----

== Round function

Use the `round()` function to round the input value up to a closest integer (half-way up).

.Example
[,typeql]
----
?int = round(100.7);
----

== Abs function

Use the `abs()` function to produce an absolute value of the input value.

.Example
[,typeql]
----
?x = abs($s - 1000);
----

The above example bound the `?x` value variable to the absolute value of subtraction of `1000` from the value of `$s`.
