= Comparators

Comparing operators or comparators can be used in a `match` clause of a TypeQL query
to compare by value two variables or a variable with a literal value.
A variable must represent an attribute, since only attributes have values.

Comparators return a boolean result of comparison.
For a TypeQL pattern that means they set a constraint on values that can be assigned to a variable used in a statement
with a comparator.

== Numeric comparators

The following numeric comparators are available in TypeQL: `==`, `!=`, `>`, `>=`, `<`, and `+<=+`.

[#_equality_comparator]
=== Equality comparator

include::partial$iam-database-links.adoc[]

Use the double equal sign (`==`) to declare equality between two values.
The comparator returns True only if values to the left and right are equal.

For example, let's find all files with a `size` attribute of value equal to `100`:

.Example
[,typeql]
----
match
$file isa file,
    has path $filepath,
    has size-kb $size;
$size == 100;
fetch $filepath;
----

=== Inequality comparator

include::partial$iam-database-links.adoc[]

Use the exclamation mark with a single equal sign (`!=`) to declare inequality between two values.
The comparator returns True only if values to the left and right are *not* equal.

For example, to find all files, that have `filepath` attribute of any value except the `README.md`:

.Example
[,typeql]
----
match
$file isa file, has path $filepath;
$filepath != "README.md";
fetch $filepath;
----

=== Greater than / Less than comparators

include::partial$iam-database-links.adoc[]

Use the greater than sign (`>`) to declare the value/variable on the left from it as strictly greater
than the one on the right from it.
For a relaxed comparison, use the greater than and equal signs together (`>=`).

Use the less than sign (`<`) to declare the value/variable on the left from it as strictly less
than the one on the right from it.
For a relaxed comparison, use the less than and equal signs together (`+<=+`).

For example, use the following query to find all files that have an attribute of the `size` type
and value less than or equal to `50`.

.Example
[,typeql]
----
match
$file isa file,
    has path $filepath,
    has size-kb $size;
$size ≤ 100;
get $filepath;
----

== String comparators

The following string comparators are available in TypeQL: `contains` and `like`.

=== Contains

Use the `contains` keyword to declare that the subject (on the left side)
contains an object (on the right side) as a substring.

[IMPORTANT]
====
The `contains` comparator is not case-sensitive.
====

.Example
[,typeql]
----
match
$p isa person, has full-name $name;
$name contains "kevin";
fetch $p: full-name;
----

=== Like

Use the `like` keyword followed by a regular expression pattern
to declare that the subject has a string value that matches the regular expression.

.Example
[,typeql]
----
match
$p isa person, has full-name $name;
$name like "^(Kevin Morrison|Pearle Goodman)$";
fetch $p: full-name;
----
