= Concept variables

== Usage

Concept variables in TypeQL represent unknown xref:typeql::concepts/types.adoc[types] and
xref:typeql::concepts/data-instances.adoc[data instances] in data query patterns.
When solving a pattern, each solution consists of variable/concept pairs for every query variable.
Substituting variables with respective concepts from a solution should ensure that the pattern equals True.

Some TypeQL statements can imply type restrictions on a concept variable via type inference, for example:

* `sub`, `sub!`, `type`, and `owns` can be applied only to types;
* `isa`, `has`, and `is` can be used only with data instances to the left from them;
* Any value operations, including xref:typeql::values/arithmetic.adoc[arithmetic operations],
xref:typeql::values/comparators.adoc[comparators],
xref:typeql::values/functions.adoc[built-in functions] can be applied only to attributes.

== Examples

=== Attributes of an entity

Given the schema from the xref:typeql::concepts/types.adoc#_example[Types page example],
let's see a simple example of how to insert some data with an Insert query:

.Inserting data example
[,typeql]
----
include::home::attachment$quickstart-data.tql[lines=1]
----

To retrieve this data, we can use a Fetch query to get a JSON with attribute values:

.Fetching values example
[,typeql]
----
match
$x isa person;
fetch $x: id, full-name, email;
----

Note that the `match` clause matches all entities of the `person` type
and the `fetch` clause then projects into a JSON values of attributes owned by every matched person.

The resulted JSON should look like this:

[,json]
----
{
    "x": {
        "email": [ { "value": "masako.holley@vaticle.com", "type": { "label": "email", "root": "attribute", "value_type": "string" } } ],
        "full-name": [ { "value": "Masako Holley", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } ],
        "id": [ { "value": 1, "type": { "label": "id", "root": "attribute", "value_type": "long" } } ],
        "type": { "label": "person", "root": "entity" }
    }
}
----

=== Variablizing types

We can replace any type in a pattern with a concept variable and then retrieve such a variable to get the type:

.Fetching types example
[,typeql]
----
match
$x isa person, has $a;
$a isa! $type;
fetch $type;
----

[,json]
----
{ "type": { "label": "full-name", "root": "attribute", "value_type": "string" } }
{ "type": { "label": "email", "root": "attribute", "value_type": "string" } }
----
