= Concepts overview
:page-no-toc: 1

[#_blank_heading]
== {blank}

TypeQL can be used for polymorphic queries with patterns containing
xref:concepts/concept-variables.adoc[concept variables] and
xref:values/value-variables.adoc[value variables].
A concept variable can represent any type or data instance in a database.
To limit the set of possible concepts represented by a concept variable,
add constraints with TypeQL keywords, like `sub`, `isa`, `has`, etc.

////
.See an example
[%collapsible]
====
For example, by using the `sub` keyword we can limit a concept variable to be a subtype of some type.
If both sides of `sub` are variables with no additional constraints, then the only requirement for them both to be types.

.Query example
[,typeql]
----
match
$x sub $t;
get $x;
----

The same approach can be used with the `isa` keyword,
but the variable to the left of it is considered to be a data instance instead of a type.
====
////

[cols-3]
--
.xref:concepts/types.adoc[]
[.clickable]
****
Root types and type hierarchy, abstract types.
****

.xref:concepts/data-instances.adoc[]
[.clickable]
****
Data representation in TypeQL.
****

.xref:concepts/concept-variables.adoc[]
[.clickable]
****
Query variables to represent types and data.
****
--
