= Types

TypeQL is a polymorphic query language that supports strong typing and uses types defined in the schema of a database
to construct queries to the database.

[#_type_hierarchy]
== Type hierarchy

Types are defined with TypeQL in the schema of a database.
Types are used to design data queries to a database and are modeled with the use of the
xref:{page-component-version}@learn::9-modeling-schemas/9.1-the-pera-model.adoc[PERA model].

To create a new type in a schema, subtype one of the existing types with a xref:statements/sub.adoc[] statement.
A subtype inherits the abilities of its supertype.
A type can be <<_abstract_types,abstract>> or concrete.

By default, a schema has three built-in root types.
Root types are abstract types and need to be subtyped to use them.

.Root types
[cols="^.^1, ^.^3, ^.^4",options="header"]
|===
| Root type label | A subtype of the root type | A data instance of a subtype

| `entity`
| Entity type
| Entity

| `relation`
| Relation type
| Relation

| `attribute`
| Attribute type
| Attribute
|===

Since data instances can be named after their respective root type,
we try to prevent ambiguity by providing relevant context or specifically calling them as root types,
e.g. the `attribute` root type.

[#_abstract_types]
== Abstract types

Abstract types can't be used to insert data instances, but can be subtyped and queried for.

To make a type abstract, use the `@abstract` xref:annotations/abstract.adoc[annotation] in its definition.

// .Abstract type definition example
// [,typeql]
// ----
// define
//
// subject sub entity @abstract;
// ----
//#todo Double-check the syntax

[#_example]
== Usage in a Define query

Let's define a simple schema for users:

.Define query example
[,typeql]
----
include::{page-component-version}@home::attachment$quickstart-schema.tql[]
----

== Usage in a Fetch query

Now let's fetch all types from the database:

.Fetch query example
[,typeql]
----
match
$x sub! $y;
fetch
$x;
----

This simple pattern lets us match all types from a database:

.Output
[,json]
----
{ "x": { "label": "user", "root": "entity" } }
{ "x": { "label": "entity", "root": "entity" } }
{ "x": { "label": "attribute", "root": "attribute", "value_type": "object" } }
{ "x": { "label": "relation", "root": "relation" } }
{ "x": { "label": "person", "root": "entity" } }
{ "x": { "label": "email", "root": "attribute", "value_type": "string" } }
{ "x": { "label": "full-name", "root": "attribute", "value_type": "string" } }
{ "x": { "label": "id", "root": "attribute", "value_type": "long" } }
----
