= Variables

Variables represent unknown xref:concepts/overview.adoc[concepts] or
xref:values/overview.adoc[values] to be used in a statement of a TypeQL data query.

== Syntax

A variable can be invoked in a pattern with a dollar sign (`$`) followed by the variable's label:

[,typeql]
----
$<variable-label>
----

== Behavior

When solving a pattern, each solution includes a value or a concept for every variable in a query,
except for some of the optionals.
Substituting variables with respective concepts or values from a solution makes pattern a True statement.

Some TypeQL statements can imply type restrictions on a concept variable via type inference, for example:

* `sub`, `sub!`, `type`, and `owns` can be applied only to types;
* `isa`, `has`, and `is` can be used only with data instances to the left from them;
* Any value operations, including
xref:values/comparators.adoc[comparators],
xref:values/built-in.adoc[built-in functions] can be applied only to attributes or values.

== Usage in a query

Let's use the `has` keyword to retrieve all attributes that owned by anything.

.Fetching attributes
[,typeql]
----
match
$x has $a;
fetch
$a;
----

The resulted JSONs contain results of different types and look like this:

[,typeql]
----
{ "a": { "value": "Masako Holley", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "a": { "value": "masako.holley@typedb.com", "type": { "label": "email", "root": "attribute", "value_type": "string" } } }
{ "a": { "value": 1, "type": { "label": "id", "root": "attribute", "value_type": "long" } } }
----

== Usage with types

We can replace any type in a pattern with a concept variable and then retrieve such a variable to get the type
(or rather all possible types):

.Fetching types example
[,typeql]
----
match
$x isa person, has $a;
$a isa! $type;
fetch $type;
----

Here we are matching all entities (`$x`) of the `person` type and all attributes that they have (`$a`).
But then we match and fetch only the exact type of every attribute.

The resulted JSONs look like this:

[,json]
----
{ "type": { "label": "full-name", "root": "attribute", "value_type": "string" } }
{ "type": { "label": "email", "root": "attribute", "value_type": "string" } }
----
