= Rust driver
:page-aliases: clients::rust-driver.adoc, clients::rust-driver/overview.adoc
:Summary: Overview for TypeDB Rust driver.
:keywords: typedb, client, driver, rust
:pageTitle: TypeDB Rust driver

The TypeDB Rust driver was developed by Vaticle to enable TypeDB support for Rust software and developers.

[cols-3]
--
.link:https://github.com/vaticle/typedb-driver/tree/development/rust[Source code,window=_blank]
[.clickable]
****

****

.link:https://github.com/vaticle/typedb-driver/releases[Releases,window=_blank]
[.clickable]
****

****

.link:https://crates.io/crates/typedb-driver[Crates.io]
[.clickable]
****

****
--

[#_install_rust]
== Install

See the
<<_version_compatibility>> table to check what versions of TypeDB and Rust driver are compatible.

For Linux: the minimum version of `glibc` is `2.25.0`.

To install TypeDB Rust driver, select `sync` or `async` and follow the instructions below:

[tabs]
====
async::
+
--
[,bash]
----
cargo add typedb-driver
----
--

sync::
+
--
[,bash]
----
cargo add typedb-driver -F sync
----
--
====

== Quickstart

See below a short example of Rust code that connects to a local TypeDB Core,
creates a database named `access-management-db`, defines a schema, inserts some data, and then reads it.

[,rust]
----
use typedb_driver::{
    concept::{Attribute, Concept, Value},
    Connection, DatabaseManager, Error, Options, Promise, Session, SessionType, TransactionType
};

let connection = Connection::new_core("localhost:1729")?;
let databases = DatabaseManager::new(connection);

databases.create("access-management-db").await?;

let session = Session::new(databases.get("access-management-db").await?, SessionType::Schema).await?;
let tx = session.transaction(TransactionType::Write).await?;
tx.query().define("define subject sub entity;").await?;
tx.commit().await?;
drop(session);

let session = Arc::new(Session::new(databases.get("access-management-db").await?, SessionType::Data).await?);
futures::future::try_join_all(access_management_data_batches.into_iter().map(|batch| {
    let session = session.clone();
    async move {
        let tx = session.transaction(TransactionType::Write).await?;
        batch.iter().try_for_each(|query| tx.query().insert(query).map(|_| ()))?;
        tx.commit().await
    }
})).await?;

let tx = session.transaction(TransactionType::Read).await?;
let mut stream = tx.query().get("match $x isa thing; get;")?;
----
//#todo Fix the code above to make it working after copy-pasting it. Add async note??

For more code examples, see the Tutorial and Driver API links below.

== Learn more

[cols-2]
--
.xref:drivers::rust/tutorial.adoc[Tutorial]
[.clickable]
****
This tutorial will help you learn how to use the Rust driver.
****

.xref:rust/api-reference.adoc[API reference]
[.clickable]
****
Driver API reference for the Rust language.
****
--

include::../java/overview.adoc[tag=questions]

//Use the xref:rust/api-reference.adoc[API reference] page for the documentation of the methods and objects used in the driver.

[#_version_compatibility]
== Version Compatibility

[cols="^.^3,^.^2,^.^3,^.^3,^.^1"]
|===
| Rust driver | Protocol encoding version | TypeDB Core | TypeDB Cloud | Rust

| 2.26.5
| 3
| 2.26.3
| 2.26.0
| 1.68.0+

| 2.25.8
| 3
| 2.25.7
| 2.25.7
| 1.68.0+

| 2.24.15
| 2
| 2.24.17
| 2.24.17
| 1.68.0+
|===
