= Deleting data
:page-aliases: {page-version}@manual::writing/delete.adoc

This page explains how to delete data from a TypeDB database.

== Overview

A delete stage is used to delete data from a TypeDB database.
It can be used in a xref:{page-version}@typeql::pipelines/index.adoc[pipeline] to operate variables declared on a preceding `match` stage.

Refer to the xref:{page-version}@typeql::pipelines/delete.adoc[] page for detailed explanation and more examples.

== Running deletes

To delete data, open a `write` xref:{page-version}@manual::queries/transactions.adoc[transaction].
This allows you to read and write data to your database while keeping the schema secure.

Delete stages begin with the `delete` keyword. They also require input data: for each row in the input the delete statements in the body of the delete stage will be executed.

A delete stage produces output rows by removing from each input row the concepts that are deleted when applying the stage's delete statements to that input.

[NOTE]
====
In some circumstances, when a data instance is deleted for one input row, it may still appear in other input rows in non-deleted form. Using deleted instances after they were deleted will lead to a runtime error.
====

== Delete statements

=== Deleting instances

To delete a data instance (an xref:{page-version}@typeql::statements/entity.adoc[entity], a xref:{page-version}@typeql::statements/relation.adoc[relation], or an xref:{page-version}@typeql::statements/attribute.adoc[attribute]), declare a `$var` for this instance and add `delete $var`:

[#_user_deletion]
.User deletion example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-single-user;delete-keyword;delete-single-user]
----

The pipeline will act in two stages:

- The first stage will match all `user` s with `username` "User"
- The second stage will delete the matched `user` s

[NOTE]
====
Deletes may cascade: when deleting instance, relations and attributes that reference these instance may be cleaned up on commit.

* relations without role players will be cleaned up.
* attributes without owners will be cleaned up (unless their attribute type is marked as independent).

[#_independent_example]
For example, the xref:{page-version}@typeql::annotations/independent.adoc[`@independent` annotation] can help preserving attributes (`username`) in the database even if their owners are deleted.
====


=== Delete ownership references

To delete only a specific ownership reference, connecting an attribute to an owner, mention what you want to delete and what instance it relates to.
In case of an ownership instance, write an expression like `has $attribute of $owner` using the xref:{page-version}@typeql::statements/has.adoc[`has`] statement and the xref:{page-version}@typeql::keywords.adoc[keyword] `of` pointing to the owner:

[#_email_has_deletion]
.User's ownership of an attribute deletion example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-email;delete-keyword;delete-users-email]
----

[NOTE]
====
This query only deletes the owner reference between `$email` and `$a`, not the attribute itself!
However, if `email` s are <<_independent_example, not `@independent`>> and there are no users with this `email` on commit, the attribute will be cleaned up.
====

=== Delete player references

Similarly, a connection between a relation and its role players can be deleted.
A single role or multiple roles can be deleted using the following query:

.Deletion of a relation linking example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-friendship;delete-keyword;delete-users-friendship;delete-single-user-friendship]
----

[NOTE]
====
The `has` and `links` keywords are, in face, optional in `delete` stages. They may sometimes be required for ambiguity resolution and generally improve readability.
====

== Response interpretation

A delete stage takes the input from the previous pipeline stages, processes the deletions and returns the concepts remaining from the input. Deleted concepts are not shown in the produced output row. This way, another pipeline stage can take this as an input and continue data processing.

For example, the <<_user_deletion, example of a `user` instance deletion>> where there are no concepts left for the output produces the following TypeDB Console's response:

.Result with empty columns
[,typeql]
----
No columns to show
----

At the same time, <<_email_has_deletion, a `has` deletion>> does not affect the output, as both concepts are still in the database until a commit:

.Result after a `has` deletion
[,typeql]
----
   ------------
    $email | alice@typedb.com isa email
    $u     | iid 0x1e00030000000000000002 isa user
   ------------
----

However, if you <<_email_deletion, delete the `email` itself>>:

.Result after an attribute deletion
[,typeql]
----
   ------------
    $u     | iid 0x1e00030000000000000002 isa user
   ------------
----

== Preserving or reverting changes

include::{page-version}@manual::page$CRUD/inserting.adoc[tag=preserving-reverting-changes]

== Having troubles?

include::{page-version}@manual::page$CRUD/inserting.adoc[tag=having-troubles]