= Deleting data
:page-aliases: {page-version}@manual::writing/delete.adoc

This page explains how to delete data from a TypeDB database.

== Understanding delete pipeline stages

A delete stage is used to delete data from a TypeDB database.
It can be used in a xref:{page-version}@typeql::pipelines/index.adoc[pipeline] to operate variables declared on a preceding `match` stage.

Refer to the xref:{page-version}@typeql::pipelines/delete.adoc[] page for detailed explanation and more examples.

== Sending delete pipelines

[NOTE]
====
The examples below can be combined with the following schema file.
A part of this file is defined in the respective xref:{page-version}@manual::schema/index.adoc[definition manuals].
Also, the data deleted in these examples is inserted in the xref:{page-version}@manual::CRUD/inserting.adoc[insertion manual].

[[schema-include]]
.See the schema.tql
[%collapsible]
=====
.schema.tql
[,typeql]
----
include::{page-version}@home::example$tql/schema_small.tql[]
----
=====
====

=== Delete an instance

To delete data, open a `write` xref:{page-version}@manual::queries/transactions.adoc[transaction].
This allows you to read and write data to your database while keeping the schema secure.

Every deletion begins with an `delete`, but also requires some input, so a preceding `match` stage is needed to produce concepts incoming to the `delete` stage.
The logic is similar to xref:{page-version}@manual::CRUD/inserting.adoc#match_insert[inserting data based on a match]: the variables, declared in the `match` stage, can be used in the `delete` stage to control the deletion process.

Similarly, multiple statements can be combined to delete multiple instances or connections.

To delete a type instance (an xref:{page-version}@typeql::statements/entity.adoc[entity], a xref:{page-version}@typeql::statements/relation.adoc[relation], or an xref:{page-version}@typeql::statements/attribute.adoc[attribute]), declare a `$var` for this instance and add `delete $var`:

[#_user_deletion]
.User deletion example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-single-user;delete-keyword;delete-single-user]
----

The following pipeline will act in two stages:

- The first stage will match all `user` s with `username` "User" (as `username` is a key in the <<schema-include, schema>>, you can be ensured that only one `user` will be found).
- The second stage will delete the matched `user` s (the only `user` with `username` "User").

[NOTE]
====
Take into account that default relations and attributes without certain xref:{page-version}@typeql::annotations/index.adoc[annotations] can be cleaned up on commit if they are not relating or owned by any other instance, so deleting a single entity can lead for more cascading cleanups.
[#_independent_example]
For example, the xref:{page-version}@typeql::annotations/independent.adoc[`@independent` annotation] can help preserving attributes (`username`) in the database even if their owners are deleted.
====

Similarly to xref:{page-version}@manual::CRUD/inserting.adoc#constraints_verification_time[`insert` stages], `delete` s have the same sets of data constraints to check after every operation or before a commit.

=== Delete an instance's ownership

To delete only a specific trait instance, mention what you want to delete and what instance it relates to.
In case of an ownership instance, write an expression like `has $attribute of $owner` using the xref:{page-version}@typeql::statements/has.adoc[`has`] statement and the xref:{page-version}@typeql::keywords.adoc[keyword] `of` pointing to the owner:

[#_email_has_deletion]
.User's ownership of an attribute deletion example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-email;delete-keyword;delete-users-email]
----

[NOTE]
====
This query only deletes the `has` between `$email` and `$a`, not the attribute itself!
However, if `email` s are <<_independent_example, not `@independent`>> and there will be no users with this `email` on commit, the attribute will also be deleted.
====

The verbose way to delete both the ownership and the attribute is:

.User's ownership of an attribute with the attribute itself deletion example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-email;delete-keyword;delete-users-email;delete-single-email]
----

However, it is redundant as the deletion of an instance also deletes all its connections.
Thus, it can be written as:

[#_email_deletion]
.Deletion of an attribute example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-email;delete-keyword;delete-single-email]
----

=== Delete a relation connection

Similarly, a connection between a relation and its roleplayers can be deleted.
A single role or multiple roles can be deleted using the following query:

.Deletion of a relation linking example
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=match-keyword;match-users-friendship;delete-keyword;delete-users-friendship;delete-single-user-friendship]
----

[NOTE]
====
The `has` and `links` keywords are optional, but sometimes required for ambiguity resolution and are generally better for readability.
====

== Response interpretation

A delete stage takes the input from the previous pipeline stages, processes the deletions and returns the concepts left from the input. All the deleted concepts are not shown in the output. This way, another pipeline stage can take this as an input and continue data processing.

For example, the <<_user_deletion, example of a `user` instance deletion>> where there are no concepts left for the output produces the following TypeDB Console's response:

.Result with empty columns
[,typeql]
----
No columns to show
----

At the same time, <<_email_has_deletion, a `has` deletion>> does not affect the output, as both concepts are still in the database until a commit:

.Result after a `has` deletion
[,typeql]
----
   ------------
    $email | alice@typedb.com isa email
    $u     | iid 0x1e00030000000000000002 isa user
   ------------
----

However, if you <<_email_deletion, delete the `email` itself>>:

.Result after an attribute deletion
[,typeql]
----
   ------------
    $u     | iid 0x1e00030000000000000002 isa user
   ------------
----

== Preserving or reverting changes

include::{page-version}@manual::page$CRUD/inserting.adoc[tag=preserving-reverting-changes]

== Having troubles?

include::{page-version}@manual::page$CRUD/inserting.adoc[tag=having-troubles]