= Deleting data
:page-aliases: {page-version}@manual::writing/delete.adoc

In this guide, you'll see how to delete data from a database using Studio, Console, or one of the drivers.

== Understanding delete pipeline stages

A delete stage is used to delete data from a TypeDB database. It can be used in a xref:{page-version}@typeql::pipelines/index.adoc[pipeline] to operate variables declared on a preceding `match` stage.

Refer to the xref:{page-version}@typeql::pipelines/insert.adoc[] page for detailed explanation and more examples.

== Sending delete queries

[NOTE]
====
The examples below can be combined with the following schema file. A part of this file is defined in the respective xref:{page-version}@manual::schema/index.adoc[definition manuals]. Also, the data deleted in these examples is inserted in the xref:{page-version}@manual::CRUD/inserting.adoc[insertion manual].

[[schema-include]]
.See the schema.tql
[%collapsible]
=====
.schema.tql
[,typeql]
----
include::{page-version}@home::example$tql/schema_small.tql[]
----
=====
====

The easiest way to send an insert query is to use Studio or Console:

[tabs]
====
Studio::
+
--
Follow the xref:{page-version}@manual::studio.adoc#_connect_to_typedb[Studio manual]
to connect to TypeDB and select a project folder.
Then use the steps below:

. Use a drop-down list in the top toolbar to select a database.
. Switch to the `write` transaction type.
. Open a new tab and insert or type in an insert stage, for example:
+
.TypeQL Delete query
[,typeql]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=simple-delete]
----
. Run the query by clicking the image:{page-version}@home::studio-icons/svg/studio_run.svg[width=24]
btn:[Run Query] button.
. Commit the changes by clicking the image:{page-version}@home::studio-icons/svg/studio_check.svg[width=24] btn:[Commit query] button.
--

Console::
+
--
. Open a `write` transaction to the selected database (e.g., `sample_db`):
+
[,bash]
----
transaction sample_db data write
----
. Send the delete query:
+
[,bash]
----
include::{page-version}@manual::example$tql/delete_data.tql[tags=simple-delete
----
+
Push btn:[Enter] twice to send the query.
. Commit the changes:
+
[,bash]
----
commit
----
--
====

To send a delete query programmatically, use xref:{page-version}@drivers::index.adoc[drivers]:

[tabs]
====
Rust::
+
--
Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to a TypeDB server.

[subs="macros, post_replacements, replacements"]
++++
Open a write transaction to the selected database and use the
xref:{page-version}@drivers::rust/api-reference.adoc#_struct_Transaction_query__[transaction.query()]
method:
++++

// TODO: Reference a single partials file.
[,rust,indent=0]
----
let transaction = driver.transaction(DB_NAME, TransactionType::Write).await.unwrap();
{
    let delete_query = r#"
include::{page-version}@manual::example$tql/delete_data.tql[tags=simple-delete]
    "#;
    let _answer = transaction.query(delete_query).await.unwrap();
    transaction.commit().await.unwrap();
}
----
--

Python::
+
--
Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to a TypeDB server.

[subs="macros, post_replacements, replacements"]
++++
Open a write transaction to the selected database and use the
xref:{page-version}@drivers::python/api-reference.adoc#_Transaction_query[transaction.query()]
method:
++++

// TODO: Reference a single partials file.
[,python,indent=0]
----
with driver.transaction(DB_NAME, TransactionType.WRITE) as tx:
    delete_query = """
include::{page-version}@manual::example$tql/delete_data.tql[tags=simple-delete]
    """
    tx.query(delete_query).resolve()
    tx.commit()
----
--

Java::
+
--
Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to a TypeDB server.

[subs="macros, post_replacements, replacements"]
++++
Open a write transaction to the selected database and use the
xref:{page-version}@drivers::java/api-reference.adoc#_Transaction_query__java_lang_String[transaction.query()]
method:
++++

// TODO: Reference a single partials file.
[,java,indent=0]
----
try (TypeDBTransaction tx = session.transaction(DB_NAME, Transaction.Type.WRITE)) {
    String deleteQuery = """
include::{page-version}@manual::example$tql/delete_data.tql[tags=simple-delete]
    """;
    tx.query(deleteQuery).resolve();
    tx.commit();
}
----
--

// TODO: Update and reintroduce
// Node.js::
// +
// --
// Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
// to connect the `driver` to a TypeDB server.
//
// [subs="macros, post_replacements, replacements"]
// ++++
// Open a data session to the selected database,
// open a write transaction, and use the
// xref:2.x@drivers::nodejs/api-reference.adoc#_QueryManager_delete__query_string__options_TypeDBOptions[transaction.query.delete()]
// method:
// ++++
//
// [,js, indent=0]
// ----
// include::{page-version}@manual::partial$nodejs-manual-code.js[tags=delete]
// ----
// --

// TODO: Update and reintroduce
// C#::
// +
// --
// Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
// to connect the `driver` to a TypeDB server.
//
// [subs="macros, post_replacements, replacements"]
// ++++
// Open a data session to the selected database,
// open a write transaction, and use the
// xref:2.x@drivers::csharp/api-reference.adoc#_VoidPromise_TypeDB_Driver_Api_IQueryManager_Delete___string_query_[transaction.Query.Delete()]
// method:
// ++++
//
// [,csharp,indent=0]
// ----
// include::{page-version}@manual::partial$csharp-manual-code.cs[tags=delete]
// ----
// --

// TODO: Update and reintroduce
// C++::
// +
// --
// Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
// to connect the `driver` to a TypeDB server.
//
// [subs="macros, post_replacements, replacements"]
// ++++
// Open a data session to the selected database,
// open a write transaction, and use the
// xref:2.x@drivers::cpp/api-reference.adoc#_VoidFuture_TypeDBQueryManagermatchDelete___const_stdstring__query__const_Options__options__Options_____const[transaction.query.delete()]
// method:
// ++++
//
// [,cpp,indent=0]
// ----
// include::{page-version}@manual::partial$cpp-manual-code.cpp[tags=options,indent=0]
// include::{page-version}@manual::partial$cpp-manual-code.cpp[tags=delete,indent=0]
// ----
// --

// TODO: Update and reintroduce
// C::
// +
// --
// Follow the xref:{page-version}@manual::connecting/connection.adoc[connection guide]
// to connect the `driver` to a TypeDB server.
//
// [subs="macros, post_replacements, replacements"]
// ++++
// Open a data session to the selected database,
// open a write transaction, and use the
// xref:2.x@drivers::c/api-reference.adoc#_query_delete[query_delete()]
// method:
// ++++
//
// [,c,indent=0]
// ----
// include::{page-version}@manual::partial$c-manual-code.c[tags=options,indent=0]
// include::{page-version}@manual::partial$c-manual-code.c[tags=delete,indent=0]
// ----
// --
====

== Response interpretation

// TODO: ???
