= Lesson 2: Environment setup
:page-aliases: learn::2-environment-setup/2-environment-setup.adoc
:page-preamble-card: 1

In this lesson, we'll set up the environment needed to work through this course. We'll begin by downloading and running a *Docker image* that will deploy a *TypeDB Core server* preloaded with a *sample database*. Then, we'll install *TypeDB Studio*, which we'll be using to manage databases and execute queries. We'll also go through a quick tutorial to get an overview of the key features of Studio that we'll need throughout this course.

== Recommended prerequisites

* You should complete xref:learn::1-why-typedb/1-why-typedb.adoc[Lesson 1] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::2-environment-setup/2.1-sample-deployment.adoc[]
[.clickable]
****
Deploy the sample database and install TypeDB Studio.
****

.xref:learn::2-environment-setup/2.2-using-typedb-studio.adoc[]
[.clickable]
****
Learn how to run example queries from TypeDB Studio.
****
--
