= Downloads
:keywords: typedb, clients, drivers, download, save, file, distributive, installator, bin, archive, mac, windows, docker, linux
:longTailKeywords: typedb client on linux, typedb client on mac, typedb client on windows, download typedb client, download typedb driver, download driver, download studio, download console
:pageTitle: Downloads
:summary: Download any version of TypeDB Client here.
:tabs-sync-option:
:repo: https://github.com/vaticle/typedb-studio/releases/

// tag::clients-download[]
== TypeDB Console

TypeDB Console is distributed with both TypeDB Core and TypeDB Cloud.

Make sure to download an archive with keyword `all` in its name: xref:typedb:resources:releases.adoc[Download]
TypeDB and find TypeDB Console in the same archive.

[NOTE]
====
There is also a *server-only* version available for download from the
https://github.com/vaticle/typedb/releases[GitHub,window=_blank]. It has `server` keyword instead of `all` in its name.
====

////
[NOTE]
====
Make sure not to download server only version: the archive should have the keyword `all` in its name.
====
////

[#_typedb_studio_download]
== TypeDB Studio

.Latest version
[cols="^.^1,^.^2,^.^2,^.^2",caption="",options="header"]
|===
|Release notes |Windows |Linux |macOS

include::partial$latest-version.adoc[]
|===

.See all versions
[%collapsible]
====
.All versions
[cols="^.^1,^.^2,^.^2,^.^2",caption="",options="header"]
|===
|Release notes |Windows |Linux |macOS

include::partial$all-versions.adoc[]

|===
====

== TypeDB drivers
// tag::drivers-download[]
[tabs]
====
Rust::
+
--
Please follow the xref:drivers:ROOT:rust/overview.adoc#_install_rust[installation guide] to add TypeDB Rust driver to a
project/application.

To download TypeDB Rust driver, you can use any of the following options:

- `cargo add typedb-driver`
- https://crates.io/crates/typedb-driver/[,window=_blank]

For more information on the driver versions, check the
xref:drivers:ROOT:rust/overview.adoc#_version_compatibility[version compatibility] table and
https://github.com/vaticle/typedb-driver/releases[release notes,window=_blank].
--

Python::
+
--
Please follow the xref:drivers:ROOT:python/overview.adoc#_install_python[installation guide] to add TypeDB Python driver to a
project/application.

To download TypeDB Python driver, you can use any of the following options:

- `pip install typedb-driver`
- https://pypi.org/project/typedb-driver#files[,window=_blank]

For more information on the driver versions, check the
xref:drivers:ROOT:python/overview.adoc#_version_compatibility[version compatibility] table and
https://github.com/vaticle/typedb-driver/releases[release notes,window=_blank].
--

Java::
+
--
Please follow the xref:drivers:ROOT:java/overview.adoc#_install_java[installation guide] to add TypeDB Java driver to a
project/application.

Alternatively, you can download TypeDB Java driver by the following link:

- https://repo.vaticle.com/service/rest/repository/browse/maven/com/vaticle/typedb/typedb-driver/

For more information on the driver versions, check the
xref:drivers:ROOT:java/overview.adoc#_version_compatibility[version compatibility] table and
https://github.com/vaticle/typedb-driver/releases[release notes,window=_blank].
--

Node.js::
+
--
Please follow the xref:drivers:ROOT:nodejs/overview.adoc#_install_nodejs[installation guide] to add TypeDB Node.js driver to a
project/application.

To download TypeDB Node.js driver, you can use the following command:

- `npm install typedb-driver`

For more information on the driver versions, check the
xref:drivers:ROOT:nodejs/overview.adoc#_version_compatibility[version compatibility] table and
https://github.com/vaticle/typedb-driver/releases[release notes,window=_blank].
--
====
// end::drivers-download[]
// end::clients-download[]
