== Check the transaction's type

=== Syntax

[source,javascript]
----
transaction.type;
----

=== Description

Checks the transaction's type (READ or WRITE)

=== Returns

* TransactionType

== Check if the transaction is open

=== Syntax

[source,javascript]
----
transaction.isOpen();
----

=== Returns

* boolean

== Access Concept API methods

=== Syntax

[source,javascript]
----
transaction.concepts;
----

=== Description

Gets the [`ConceptManager`]  for this Transaction, providing access to all Concept API methods.

=== Returns

* [`ConceptManager`] 

== Access Concept API - Logic methods

=== Syntax

[source,javascript]
----
transaction.logic;
----

=== Description

Gets the [`LogicManager`]  for this Transaction, providing access to all Concept API - Logic methods.

=== Returns

* [`LogicManager`] 

== Access Query API methods

=== Syntax

[source,javascript]
----
transaction.query;
----

=== Description

Gets the [`QueryManager`]  for this Transaction, from which any TypeQL query can be executed.

=== Returns

* [`QueryManager`] 

== Commit a write transaction

=== Syntax

[source,javascript]
----
await transaction.commit();
----

=== Description

Commits the changes made via this transaction to the TypeDB database.
**Whether or not the transaction is commited successfully, it gets closed after the commit call.**

=== Returns

* void

== Rollback a write transaction

=== Syntax

[source,javascript]
----
await transaction.rollback();
----

=== Description

Rolls back the uncommitted changes made via this transaction.

=== Returns

* void

== Close a read transaction

=== Syntax

[source,javascript]
----
await transaction.close();
----

=== Description

Closes the transaction.

=== Returns

* void

