= Functions

== Introduction

// tag::description[]
Functions provide powerful abstractions of query logic, and a cornerstone of the functional database programming model.
Functions calls can be nested, recursive, negated, and they natively embed into TypeQL’s declarative patterns.
// end::description[]

== Function types

The following table illustrates the types of functions based on two dimensions: number of rows and number of columns returned.

[cols="^.1,^.2,^.2",options="header"]
.Categorizing functions based on their output type
|===
|  **Rows/Columns** | 1 column | Multiple columns
| **Up to 1 row** | scalar function

type signature `... -> A`

returns `$a`
| tuple function

type signature `... -> A, B`

returns `$a, $b`
| **Multiple rows** | (scalar) stream function

type signature `... -> { A }`

returns `{ $a }`
| (tuple) stream function

type signature `... -> { A, B }`

returns `{ $a, $b }`
|===

== Explore functions

[cols-3]
--
.xref:{page-version}@typeql::functions/writing.adoc[]
[.clickable]
****
Learn how to write functions.
****

.xref:{page-version}@typeql::functions/stream.adoc[]
[.clickable]
****
Learn how to work with stream-return functions.
****

.xref:{page-version}@typeql::functions/single.adoc[]
[.clickable]
****
Learn how to work with scalar functions.
****
--
