= Functions

== Introduction

// tag::description[]
Functions provide powerful abstractions of query logic, and a cornerstone of the functional database programming model.
Functions calls can be nested, recursive, negated, and they natively embed into TypeQL’s declarative patterns.
// end::description[]

== Function types

The following table illustrates the types of functions based on two dimensions: number of rows and number of columns returned.

[cols="^.1,^.2,^.2",options="header"]
|===
|  **Rows/Columns** | Up to 1 column | Multiple columns
| **Up to 1 row** | Single-return scalar (`$a`) | Single-return tuple (`$a, $b`)
| **Multiple rows** | Stream-return scalar (`{ $a }`) | Stream-return tuple (`{ $a, $b }`)
|===

== Explore functions

[cols-3]
--
.xref:{page-version}@typeql::functions/writing.adoc[]
[.clickable]
****
Learn how to write functions.
****

.xref:{page-version}@typeql::functions/stream-return.adoc[]
[.clickable]
****
Learn how to work with stream-return functions.
****

.xref:{page-version}@typeql::functions/single-return.adoc[]
[.clickable]
****
Learn how to work with single-return functions.
****
--
