= Writing functions

== Syntax

[[declaration]]
=== Declaring a function

Functions in TypeQL are declared using the keyword `fun`.
A function declaration consists of:

- A function *signature* which itself consists of:
* A function name.
* Typed *input arguments* (optional).
* A *return type*.
- A xref:{page-version}@typeql::pipelines/index.adoc#pipeline_kinds[read pipeline] as the *function body*.
- A *return statement* that produces results of the specified return type.

.Function Declaration Syntax
[,typeql]
----
fun <function-name> ( <optional-arguments> ) -> <return-types>:
<read-pipeline>
return <return-statement>
----

- `<function-name>` is a valid label (i.e. a not reserved keyword or a TypeQL xref:{page-version}@typeql::expressions/literals.adoc[literal]).
- `<optional-arguments>` is a list of zero of more typed variables, written in the format `$a : A, $b : B, ...`
- `<return-types>` consists of at least one `<return-type>` and can be:
* a xref:{page-version}@typeql::functions/stream.adoc[stream] tuple type, written in the format `{ A, B, ... }`.
* a xref:{page-version}@typeql::functions/tuple.adoc[tuple] type, written in the format `A, B, ...`.

+
[NOTE]
====
The types `A, B, ...` above can be either user-defined types (e.g. an entity type `user`) or primitive value types (e.g. `boolean`).
====
- `<read-pipeline>` includes any read xref:{page-version}@typeql::pipelines/index.adoc[pipeline].
- `<return-statement>` may consist of variables, xref:{page-version}@typeql::expressions/function_calls.adoc[function calls], and built-in reductions:
* Scalar return statements are of the form
`$a;`.
* Tuple return statements are of the form  `$a, $b, <built-in-reduction>, scalar_fun($c), ...;` (see xref:{page-version}@typeql::pipelines/reduce.adoc[reduce] for available built-in reductions).
* Stream return statements are of the form `{ $a, $b, scalar_fun($c), ... };`.

+
--
[NOTE]
====
*Positions matter!* Returns of functions are assigned by position.
====
--

[[calling]]
=== Calling a function

.Function Calling Syntax
[,typeql]
----
<function-name>(<arguments>)
----

`<arguments>` to a function call are of the form `$a, $b, ...`. They are always *variables* (and not expressions).

Function can be called:

1. as part of an xref:{page-version}@typeql::expressions/index.adoc[expression]. For example:
+
--
[,typeql]
.Scalar expression comparison
----
$x + 1 < f1($y) + f2($y);
----
[,typeql]
.Scalar expression assignment
----
let $x = scalar_fun($a, $b) / 2; # f3 is
----
--
1. as part of a tuple or stream assignment, for example:
+
--
[,typeql]
.Tuple assignment
----
let $x, $y = tuple_fun($a, $b);
----
.Stream assignment
[,typeql]
----
let $x, $y in stream_fun($a, $b);
----
--

== Usage

=== Ambiguity

Every function should have a unique name.
It's not allowed to declare two functions with the same name even if they have totally different arguments and return types.

[#query_level_functions]
=== Using Functions at Query-Level

Functions can be defined temporarily at the query level using the `with` clause.
Such functions exist only for the duration of the query and are not persisted in the database.

Multiple `with` clauses can be used, each defining a single function.
All `with` clauses must precede the query pipeline.

.Querying with Functions
[,typeql]
----
with <f1-declaration>
with <f2-declaration>
...
with <fN-declaration>
match
  $f1 = f1();
  $f2 = f2();
  ...
  $fN = fN();
----

For example, the following read pipeline defines and uses a temporary function using the `with` clause:

[,typeql]
----
include::{page-version}@typeql::example$tql/read_statements_functions.tql[tag=with-fun]
----

=== Using Functions in definition queries

==== Define

In addition to <<query_level_functions, temporary query-level functions>>, functions can be persisted in schemas.
Replace the keyword `with` with `define` and execute the query in a schema transaction:

// tag::define[]
[,typeql]
----
include::{page-version}@typeql::example$tql/schema_statements_functions.tql[tags=define-keyword;with-fun-defined]
----
// end::define[]

Once persisted, these functions can be called directly in read queries:

[,typeql]
----
include::{page-version}@typeql::example$tql/read_statements_functions.tql[tag=with-fun-match]
----

==== Redefine

// tag::redefine[]
Everything except for the function name can be redefined using redefine queries.

[,typeql]
----
include::{page-version}@typeql::example$tql/redefine_statements_functions.tql[tags=redefine-keyword;with-fun-redefined]
----
// end::redefine[]

==== Undefine

// tag::undefine[]
To undefine a function, specify the `fun` keyword and its name.

[,typeql]
----
include::{page-version}@typeql::example$tql/undefine_statements_functions.tql[tags=undefine-keyword;with-fun-undefined]
----
// end::undefine[]

== Learn More

[cols=2]
--
.xref:{page-version}@typeql::pipelines/index.adoc[]
[.clickable]
****
Learn more about function bodies - pipelines.
****

.xref:{page-version}@typeql::functions/stream.adoc[]
[.clickable]
****
Understand how to work with stream functions.
****

.xref:{page-version}@typeql::functions/tuple.adoc[]
[.clickable]
****
Explore single functions and their usage.
****
--
