= TypeDB Cloud API Reference
:page-toclevels: 2

[#accesslevels]
== Access levels

[options="header"]
|===
| Project access level | Available cluster actions
| Admin                | Destroy
| Write                | Deploy, Suspend, Resume
| Read                 | Get, List
|===

== Clusters

=== Deploy

[cols="h,3a"]
|===
| Required access | *write* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `POST`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters/deploy`
| Request body    | include::{page-version}@manual:resources:partial$cloud-api/cluster-deploy.json.adoc[]
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=single]
|===

[NOTE]
====
Clusters deployed through the API will have a default user with the username `admin` and the password `password`.
We recommend xref:{page-version}@manual::users/passwords.adoc[updating the default password] before using the cluster -
which can also be done through the TypeDB Cloud UI by clicking the "Connect" button on the cluster's page.
====

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters/deploy \
    --header 'Authorization: Bearer {ACCESS-TOKEN}' \
    --json '{"id":"api-cluster","serverCount":1,"storageSizeGB":10,"provider":"gcp","region":"europe-west2","isFree":true,"machineType":"c2d-highcpu-2","storageType":"standard-rwo","version":"3.0.5"}'
----

Request Body::
+
[source,json]
----
{
    "id":"api-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "provider":"gcp",
    "region":"europe-west2",
    "isFree":true,
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "version":"3.0.5"
}
----
====

*Example response:*
[source,json]
----
{
    "id":"api-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"starting",
    "createdAt":1738256490070,
    "organization":"new-organization",
    "project":"default",
    "version":"3.0.5",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "pending"
        }
    ]
}
----

[options="header"]
|===
| Field | Allowed Values
| `id` | The cluster's ID must be unique within its project,
and consist only of lowercase alphanumeric characters, optionally separated by underscores and hyphens.
| `serverCount` | An odd integer value between 1 and 9.
TypeDB version 3.0 and onwards can currently only have one server.
| `storageSizeGB` | An integer value between 10 and 1000.
| `provider` | Must be either `gcp`, `aws`, or `azure`
| `isFree` | If set to `true`, must use a valid free machine type, and have at most 1 server and 10GB of storage.
You may only have one free cluster per organization.

If set to `false`, there must be a valid payment method on the organization.
| `region` | See <<regionsmachinetypes,below>>
| `machineType` | See <<regionsmachinetypes,below>>
| `storageType` | See <<storagetypes,below>>
| `version` a| Currently available versions are:

* `2.29.3`
* `3.0.5`
|===

[#regionsmachinetypes]
.GCP regions and machine types
[%collapsible]
====
[options="header"]
|===
| Machine Types    | Free Available | Regions
| c2d-highcpu-2    | Yes            |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-4    | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-8    | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-16   | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
|===
====

.AWS regions and machine types
[%collapsible]
====
[options="header",cols=",,a"]
|===
| Machine Types    | Free Available | Regions
| c7g.large        | Yes            |
* eu-west-2
| c7g.xlarge       | No             |
* eu-west-2
| c7g.2xlarge      | No             |
* eu-west-2
| c7g.4xlarge      | No             |
* eu-west-2
| c8g.large        | Yes            |
* us-west-2
* us-east-1
* eu-central-1
| c8g.xlarge       | No             |
* us-west-2
* us-east-1
* eu-central-1
| c8g.2xlarge      | No             |
* us-west-2
* us-east-1
* eu-central-1
| c8g.4xlarge      | No             |
* us-west-2
* us-east-1
* eu-central-1
|===
====

.Azure regions and machine types
[%collapsible]
====
[options="header",cols=",,a"]
|===
| Machine Types    | Free Available | Regions
| Standard_F2s_v2  | Yes            |
* East US
* West US 3
* Germany West Central
| Standard_F4s_v2  | No             |
* East US
* West US 3
* Germany West Central
| Standard_F8s_v2  | No             |
* East US
* West US 3
* Germany West Central
| Standard_F16s_v2 | No             |
* East US
* West US 3
* Germany West Central
|===
====

.Storage Types
[#storagetypes]
[%collapsible]
====
[options="header"]
|===
| Provider | Storage Type
| GCP      | standard-rwo
| AWS      | gp2
| Azure    | default
|===
====

=== Get

[cols="h,3a"]
|===
| Required access | *read* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `GET`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID`
| Request body    | None
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=single]
|===

*Example request:*
[source,console]
----
curl --request GET \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"running",
    "createdAt":1738256490070,
    "organization":"new-organization",
    "project":"default",
    "version":"3.0.5",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----

=== List

[cols="h,3a"]
|===
| Required access | *read* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `GET`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters`
| Request body    | None
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=list]
|===

*Example request:*
[source,console]
----
curl --request GET \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

*Example response:*
[source,json]
----
[
    {
        "id":"new-cluster",
        "serverCount":1,
        "storageSizeGB":10,
        "isFree":true,
        "status":"running",
        "createdAt":1738256490070,
        "organization":"new-organization",
        "project":"default",
        "version":"3.0.5",
        "provider":"gcp",
        "region":"europe-west2",
        "machineType":"c2d-highcpu-2",
        "storageType":"standard-rwo",
        "servers": [
            {
              "address": "abc123-0.cluster.typedb.com:80",
              "status": "running"
            }
        ]
    },
    {
        "id":"cluster-two",
        "serverCount":1,
        "storageSizeGB":10,
        "isFree":false,
        "status":"suspended",
        "createdAt":1738256490090,
        "organization":"new-organization",
        "project":"default",
        "version":"3.0.5",
        "provider":"aws",
        "region":"eu-west-2",
        "machineType":"c7g.large",
        "storageType":"gp2",
        "servers": []
    }
]
----


=== Suspend

[cols="h,3a"]
|===
| Required access | *write* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `POST`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID/suspend`
| Request body    | None
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=single]
|===

*Example request:*
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID/suspend \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"suspending",
    "createdAt":1738256490070,
    "organization":"new-organization",
    "project":"default",
    "version":"3.0.5",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----

=== Resume

[cols="h,3a"]
|===
| Required access | *write* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `POST`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID/resume`
| Request body    | None
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=single]
|===

*Request:*
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID/resume \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"resuming",
    "createdAt":1738256490070,
    "organization":"new-organization",
    "project":"default",
    "version":"3.0.5",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "pending"
        }
    ]
}
----

=== Destroy

[cols="h,3a"]
|===
| Required access | *admin* to `org/ORG_ID/projects/PROJECT_ID`
| Method          | `DELETE`
| URL             | `/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID`
| Request body    | None
| Response body   | include::{page-version}@manual:resources:partial$cloud-api/cluster-response.json.adoc[tags=single]
|===

*Example request:*
[source,console]
----
curl --request DELETE \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters/CLUSTER_ID \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"destroying",
    "createdAt":1738256490070,
    "organization":"new-organization",
    "project":"default",
    "version":"3.0.5",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----
