= Connect to server
:tabs-sync-option:
:experimental:

This guide covers establishing a network connection to a
<<_connect_to_typedb_cloud,TypeDB Cloud>> or
<<_connect_to_typedb_core,TypeDB Core>> deployment with Studio, Console, or driver.

////
TypeDB accepts connections via gRPC based
https://github.com/vaticle/typedb-protocol[TypeDB RPC protocol,window=_blank].
It is implemented by TypeDB drivers and TypeDB clients.

All released clients and drivers support connection to both TypeDB Cloud and TypeDB Core.
////

//To connect to TypeDB, you can use any TypeDB client or driver.
//Select a client/driver, make sure it's installed,
//and see below a practical guide on how to connect to TypeDB Core and TypeDB Cloud.

[#_connect_to_typedb_core]
== Connect to TypeDB Core

A network connection to TypeDB Core requires the address and port of the server to connect to.

[tabs]
====
Studio::
+
--
Run Studio and follow instructions below:

. Click btn:[Connect to TypeDB] on the right side of the top toolbar.
. Make sure the `TypeDB Core` option is selected in the `Server` field.
. Enter the address and port of the server to connect to (e.g., `localhost:1729`).
. Click btn:[Connect].
--

Console::
+
--
Run Console using the `--core` argument to set the address and port to connect to:

.Connect to TypeDB Core
[,bash]
----
typedb console --core=<server-address>
----
--
====

For programmatic access, use one of the TypeDB xref:manual::installing/drivers.adoc[drivers] via native API:

.Drivers
[tabs]
====
Rust::
+
--
.Connect to TypeDB Core
[,rust]
----
let driver = Connection::new_core("127.0.0.1:1729");
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Python::
+
--
.Connect to TypeDB Core
[,python]
----
driver = TypeDB.core_driver("127.0.0.1:1729")
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Java::
+
--
.Connect to TypeDB Core
[,java]
----
TypeDBDriver driver = TypeDB.coreDriver("127.0.0.1:1729");
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Node.js::
+
--
.Connect to TypeDB Core
[,js]
----
const driver = await TypeDB.coreDriver("127.0.0.1:1729");
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C++::
+
--
.Connect to TypeDB Core
[,cpp]
----
TypeDB::Driver driver = TypeDB::Driver::coreDriver("127.0.0.1:1729");
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
====

After connecting to TypeDB Core, see how to xref:connecting/database.adoc[create a database] and manage
xref:connecting/session.adoc[sessions] and
xref:connecting/transaction.adoc[transactions].

[#_connect_to_typedb_cloud]
== Connect to TypeDB Cloud

A network connection to a TypeDB Cloud cluster requires address and port of at least one server in the cluster,
as well as username and password of a user.

For your first connection, use the following default user credentials:

* Username: `admin`
* Password: `password`

[IMPORTANT]
=====
Make sure to xref:typedb::managing/user-management.adoc#_first_login[change the password]
for the `admin` account on your first login.
A TypeDB Cloud deployment will deny all other operations until the password is changed from its default value.
=====

[tabs]
====
Studio::
+
--
Run Studio and follow instructions below:

. Click btn:[Connect to TypeDB] on the right side of the top toolbar.
. Click btn:[Manage Cloud Addresses] button.
. Add address and port for at least one server from your TypeDB Cloud deployment. Close the Address management window.
. Fill in the `Username` and `Password` fields with valid user credentials.
. Turn on the `Enable TLS` option and leave the `CA Certificate` field empty. +
_For self-hosted deployments, encryption parameters may vary._
. Click `Connect`.

On your first login you will be asked to change the password for the `admin` account.
--

Console::
+
--
Run Console using the `--cloud` argument to set a list of addresses and ports to connect to:

.TypeDB Cloud connection
[,bash]
----
typedb console --cloud=<server-address> --username=<username> --password --tls-enabled=true
----

You will be prompted for a password.

On your first login,
xref:typedb::managing/user-management.adoc#_first_login[change the password] for the `admin` account.
--
====

For programmatic access, use one of the TypeDB xref:manual::installing/drivers.adoc[drivers] via native API:

.Drivers
[tabs]
====
Rust::
+
--
.Connect to TypeDB Cloud
[,rust]
----
let driver = Connection::new_cloud(&["127.0.0.1:1729"], Credential::with_tls("admin", "password", None).unwrap());
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Python::
+
--
.Connect to TypeDB Cloud
[,python]
----
driver = TypeDB.cloud_driver("127.0.0.1:1729", TypeDBCredential("admin", "password", tls_enabled=True))
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Java::
+
--
.Connect to TypeDB Cloud
[,java]
----
TypeDBDriver driver = TypeDB.cloudDriver("127.0.0.1:1729", new TypeDBCredential("admin", "password", true ));
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Node.js::
+
--
.Connect to TypeDB Cloud
[,js]
----
const driver = await TypeDB.cloudDriver("127.0.0.1:1729", new TypeDBCredential("admin","password"));
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C++::
+
--
.Connect to TypeDB Cloud
[,cpp]
----
TypeDB::Driver driver = TypeDB::Driver::cloudDriver({"127.0.0.1:1729"}, TypeDB::Credential("admin", "password", true));
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
====

After connecting to TypeDB Cloud and
xref:typedb::managing/user-management.adoc#_first_login[changing the default password] for the `admin` account,
see how to xref:connecting/database.adoc[create a database] and manage
xref:connecting/session.adoc[sessions] and
xref:connecting/transaction.adoc[transactions].
