= Drivers connection guide
:tabs-sync-option:

////
TypeDB accepts client connections via gRPC based
https://github.com/vaticle/typedb-protocol[TypeDB driver RPC,window=_blank] protocol.

A library that implements this protocol and provides a native API to access TypeDB is called a TypeDB driver.

A TypeDB Client is any software that can connect to a TypeDB,
including TypeDB drivers and standalone software applications that use TypeDB drivers.
////

This guide covers connecting to a TypeDB deployment.
Any released TypeDB driver is capable of connecting to both
<<_connecting_to_typedb_core,TypeDB Core>> and
<<_connecting_to_typedb_cloud,TypeDB Cloud>>.
Before trying to connect to TypeDB, make sure that a driver of your choice is properly
xref:guides::installing/overview.adoc[installed].

[#_connecting_to_typedb_core]
== Connecting to TypeDB Core

A network connection to TypeDB Core is established by initializing a driver with server address.

.Connecting to TypeDB Core
[tabs]
====
Rust::
+
--
.Connect to TypeDB Core
[,rust]
----
let driver = Connection::new_core("127.0.0.1:1729");
----
--

Python::
+
--
.Connect to TypeDB Core
[,python]
----
driver = TypeDB.core_driver("127.0.0.1:1729")
----
--

Java::
+
--
.Connect to TypeDB Core
[,java]
----
TypeDBDriver driver = TypeDB.coreDriver("127.0.0.1:1729");
----
--

Node.js::
+
--
.Connect to TypeDB Core
[,js]
----
const driver = await TypeDB.coreDriver("127.0.0.1:1729");
----
--

C++::
+
--
.Connect to TypeDB Core
[,js]
----
TypeDB::Driver driver = TypeDB::Driver::coreDriver("127.0.0.1:1729");
----
--
====

For a more comprehensive code example, see the xref:typedb::tutorials/sample-app.adoc[] page.

[#_connecting_to_typedb_cloud]
== Connecting to TypeDB Cloud

A network connection to TypeDB Cloud is established by initializing a driver with multiple parameters:

* A list of addresses for servers in a cluster;
* Credential for user identification and authentication;
* Optional encryption parameters.

.Connecting to TypeDB Cloud
[tabs]
====
Rust::
+
--
.Connect to TypeDB Cloud
[,rust]
----
let driver = Connection::new_cloud(&["127.0.0.1:1729"], Credential::with_tls("admin", "password", None).unwrap());
----
--

Python::
+
--
.Connect to TypeDB Cloud
[,python]
----
driver = TypeDB.cloud_driver("127.0.0.1:1729", TypeDBCredential("admin", "password", tls_enabled=True))
----
--

Java::
+
--
.Connect to TypeDB Cloud
[,java]
----
TypeDBDriver driver = TypeDB.cloudDriver("127.0.0.1:1729", new TypeDBCredential("admin", "password", true ));
----
--

Node.js::
+
--
.Connect to TypeDB Cloud
[,js]
----
const driver = await TypeDB.cloudDriver("127.0.0.1:1729", new TypeDBCredential("admin","password"));
----
--

C++::
+
--
.Connect to TypeDB Cloud
[,js]
----
TypeDB::Driver driver = TypeDB::Driver::cloudDriver({"127.0.0.1:1729"}, TypeDB::Credential("admin", "password", true));
----
--
====

For self-hosted deployments, encryption parameters may vary.

//#todo Add Learn more/ Further guides links at the end
