= Programming objects
:page-no-toc: 1

[#_blank_heading]
== {blank}

//TypeDB can retrieve data by projecting values to JSON objects.

You can use ORM-like objects to manipulate schema and data of a TypeDB databases
and process explanations of inferred data.
//To get these stateful objects, you can use either TypeQL Get query or driver API methods.

See below practical guides on how to use stateful schema objects, stateful data objects, and explanation objects.

Make sure to xref:home::install/overview.adoc#_typedb_drivers[install] one of the TypeDB drivers before proceeding.

// tag::nav-blocks[]
[cols-2]
--
.xref:manual::objects/schema.adoc[]
[.clickable]
****
How to use driver API methods to manipulate schema types and rules.
****

.xref:manual::objects/data.adoc[]
[.clickable]
****
How to use driver API methods to manipulate data.
****

.xref:manual::objects/explanation.adoc[]
[.clickable]
****
How to use driver API methods to get explanation of rule-based inference.
****
--
// end::nav-blocks[]
