= Schema objects

Driver APIs provide a set of methods to programmatically manipulate <<_types,types>> and
<<_rules,rules>> in the schema of a TypeDB database.

This page assumes you've already followed instructions from the xref:manual::defining/define.adoc[] page.
Here, you'll see how to use driver API methods and stateful objects to programmatically manipulate types and rules
in a database schema using one of the TypeDB drivers.

[#_types]
== Types

A type object has many useful methods to traverse the type hierarchy, find related types,
and manipulate types definitions/properties.
To manipulate a type with driver API methods,
you need to get a stateful object that represents the type in the database.

[#_get_query]
=== Get a type

To get a type object from a TypeDB database,
you can use a TypeQL Get query or one of the driver API methods.

==== Get the type by its label

Use type's label to retrieve the type object.
For example, to get a stateful object of the `user` entity type, use:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let user = transaction.concept().get_entity_type("user".to_owned()).resolve()?.ok_or("No user type.").unwrap();
----

For more information,
see the xref:drivers::rust/api-reference.adoc#_struct_ConceptManager[ConceptManager class] methods.
--

Python::
+
--
.Example
[,python]
----
user = transaction.concepts.get_entity_type("user").resolve()
----
For more information,
see the xref:drivers::python/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

Java::
+
--
.Example
[,java]
----
EntityType user = transaction.concepts().getEntityType("user").resolve();
----
For more information,
see the xref:drivers::java/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

Node.js::
+
--
.Example
[,js]
----
let user = await transaction.concepts.getEntityType("user");
----
For more information,
see the xref:drivers::nodejs/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

C++::
+
--
.Example
[,cpp]
----
auto user = transaction.concepts.getEntityType("user").get();
----
For more information,
see the xref:drivers::cpp/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--
====

==== Query for types

Send a xref:typeql::data/get.adoc[Get query] that returns type concept(s).

.Example of a Get query for entity types
[,typeql]
----
match
$x sub entity;
get $x;
----

The above example retrieves all entity types in a database (as subtypes of the `entity` root type).
For instructions on how to send a Get query and process the response, see the
xref:manual::reading/get.adoc#_how_to_send_a_get_query[Get query] page.

=== Add a type

To add a new type into the schema of a database,
use a TypeQL xref:typeql::schema/define.adoc[Define query] or one of the put type methods:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let mut admin = transaction.concept().put_entity_type("admin".to_owned()).resolve()?;
----
For more information,
see the xref:drivers::rust/api-reference.adoc#_struct_ConceptManager[ConceptManager class] methods.
--

Python::
+
--
.Example
[,python]
----
admin = transaction.concepts.put_entity_type("admin").resolve()
----
For more information,
see the xref:drivers::python/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

Java::
+
--
.Example
[,java]
----
EntityType admin = transaction.concepts().putEntityType("admin").resolve();
----
For more information,
see the xref:drivers::java/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

Node.js::
+
--
.Example
[,js]
----
let admin = await transaction.concepts.putEntityType("admin");
----
For more information,
see the xref:drivers::nodejs/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--

C++::
+
--
.Example
[,cpp]
----
auto admin = transaction.concepts.putEntityType("admin").get();
----
For more information,
see the xref:drivers::cpp/api-reference.adoc#_ConceptManager[ConceptManager class] methods.
--
====

[#_type_object_methods]
=== Type manipulation

A stateful type object has many useful methods to manipulate the type or traverse the type hierarchy of a schema:
get/set label, get/set supertype, get subtypes, get ownerships, get roles played, etc.

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
drop(admin.set_supertype(&transaction, user).resolve());
----
For more information on methods, available for manipulating Type objects,
see the xref:drivers::rust/api-reference.adoc#_schema_header[Schema class] methods.
--

Python::
+
--
.Example
[,python]
----
admin.set_supertype(transaction, user)
----
For more information on methods, available for manipulating Type objects,
see the xref:drivers::python/api-reference.adoc#_schema_header[Schema class] methods.
--

Java::
+
--
.Example
[,java]
----
admin.set_supertype(transaction, user)
----
For more information on methods, available for manipulating Type objects,
see the xref:drivers::java/api-reference.adoc#_schema_header[Schema class] methods.
--

Node.js::
+
--
.Example
[,python]
----
admin.set_supertype(transaction, user)
----
For more information on methods, available for manipulating Type objects,
see the xref:drivers::python/api-reference.adoc#_schema_header[Schema class] methods.
--

C++::
+
--
.Example
[,python]
----
admin.set_supertype(transaction, user)
----
For more information on methods, available for manipulating Type objects,
see the xref:drivers::python/api-reference.adoc#_schema_header[Schema class] methods.
--
====

[#_example_of_type_manipulation]
=== Full example

See below a comprehensive example of types manipulation:
retrieving a type by its label, adding type, changing supertype, and retrieving all subtypes of a type.

[tabs]
====
Rust::
+
--
[,rust,indent=0]
----
include::manual::partial$rust-manual-code.rs[tags=databases,indent=8]
include::manual::partial$rust-manual-code.rs[tags=types-api]
----
--

Python::
+
--
[,python,indent=0]
----
include::manual::partial$python-manual-code.py[tags=types-api]
----
--

Java::
+
--
[,java,indent=0]
----
include::manual::partial$java-manual-code.java[tags=types-api]
----
--

Node.js::
+
--
[,js,indent=0]
----
include::manual::partial$nodejs-manual-code.js[tags=types-api]
----
--

C++::
+
--
[,cpp,indent=0]
----
include::manual::partial$cpp-manual-code.cpp[tags=types-api]
----
--
====

The above example set the `user` type as the supertype to the `admin` type, making `admin` a subtype of `user`.

For an additional example of programmatic type manipulations,
see the xref:manual::defining/schema-editing.adoc#_modify_with_driver_api[Schema editing] page.

[#_rules]
== Rules

A rule object has `label`, `when`, and `then` properties and just a few methods.

To manipulate a rule with driver API methods,
you need to get a stateful object that represents the rule in the database.

[#_get_a_rule_object]
=== Get a rule

Rules can be defined with a TypeQL query (see xref:typeql::schema/define.adoc[]), but they can't be retrieved with one.
To get a rule object from a TypeDB database, you need to use the Logic class methods of a driver API.

==== Get rule by label

Retrieve a rule by its label:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let new_rule = transaction.logic().get_rule("Employee".to_owned()).resolve()?.ok_or("Rule not found.").unwrap()
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::rust/api-reference.adoc#_struct_LogicManager_get_rule__label_String[get_rule()]
method in driver API reference.
++++
--

Python::
+
--
.Example
[,python]
----
new_rule = transaction.logic.get_rule("Employee").resolve():
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::python/api-reference.adoc#_LogicManager_get_rule__label_str[get_rule()]
method in driver API reference.
++++
--

Java::
+
--
.Example
[,java]
----
Rule oldRule = transaction.logic().getRule("Employee").resolve();
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::java/api-reference.adoc#_LogicManager_getRule__java_lang_String[getRule()]
method in driver API reference.
++++
--

Node.js::
+
--
.Example
[,python]
----
let new_rule = await transaction.logic.getRule("Employee")
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::nodejs/api-reference.adoc#_LogicManager_getRule__label_string[get_rule()]
method in driver API reference.
++++
--

C++::
+
--
.Example
[,python]
----
auto new_rule = transaction.logic.getRule("Employee").get().value()
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::cpp/api-reference.adoc#_OptionalRuleFuture_TypeDBLogicManagergetRule_const_stdstring_label_const[getRule()]
method in driver API reference.
++++
--
====

==== Get all rules

Retrieve all rules in a schema:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let rules = transaction.logic().get_rules()?;
for rule in rules {
    println!("Rule label: {}", rule?.label);
    println!("  Condition: {}", rule?.when.to_string());
    println!("  Conclusion: {}", rule?.then.to_string());
}
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::rust/api-reference.adoc#_struct_LogicManager_get_rules__[get_rules()]
method in driver API reference.
++++
--

Python::
+
--
.Example
[,python]
----
rules = transaction.logic.get_rules()
for rule in rules:
    print("Rule label:", rule.label)
    print("  Condition:", rule.when)
    print("  Conclusion:", rule.then)
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::python/api-reference.adoc#_LogicManager_get_rules__[get_rules()]
method in driver API reference.
++++
--

Java::
+
--
.Example
[,java]
----
transaction.logic().getRules().forEach(result -> {
    System.out.println("Rule label: " + result.getLabel());
    System.out.println("  Condition: " + result.getWhen().toString());
    System.out.println("  Conclusion: " + result.getThen().toString());
});
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::java/api-reference.adoc#_LogicManager_getRules__[getRules()]
method in driver API reference.
++++
--

Node.js::
+
--
.Example
[,js]
----
await transaction.logic.getRules().forEach(rule => {
    console.log("Rule label: " + rule.label);
    console.log("  Condition: " + rule.when);
    console.log("  Conclusion: " + rule.then);
});
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::nodejs/api-reference.adoc#_LogicManager_getRules__[getRules()]
method in driver API reference.
++++
--

C++::
+
--
.Example
[,cpp]
----
auto rules = transaction.logic.getRules();
for (auto& rule : rules) {
    std::cout << rule.label() << std::endl;
    std::cout << rule.when() << std::endl;
    std::cout << rule.then() << std::endl;
}
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::cpp/api-reference.adoc#_RuleIterable_TypeDBLogicManagergetRules_const[getRules()]
method in driver API reference.
++++
--
====

=== Add a rule

Use the following methods to add a rule to the schema of a database:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let condition = typeql::parse_pattern("{$u isa user, has email $e; $e contains '@vaticle.com';}")?.into_conjunction();
let conclusion = typeql::parse_pattern("$u has name 'Employee'")?.into_statement();
let mut new_rule = transaction.logic().put_rule("Employee".to_string(), condition, conclusion).resolve()?;
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::rust/api-reference.adoc#_struct_LogicManager_put_rule__label_String__when_Conjunction__then_Statement[put_rule()]
method in driver API reference.
++++
--

Python::
+
--
.Example
[,python]
----
new_rule = transaction.logic.put_rule("Employee", "{$u isa user, has email $e; $e contains '@vaticle.com';}", "$u has name 'Employee'").resolve()
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::python/api-reference.adoc#_LogicManager_put_rule__label_str__when_str__then_str[put_rule()]
method in driver API reference.
++++
--

Java::
+
--
.Example
[,java]
----
Pattern condition = TypeQL.parsePattern("{$u isa user, has email $e; $e contains '@vaticle.com';}");
Pattern conclusion = TypeQL.parsePattern("$u has name 'Employee'");
Rule newRule = transaction.logic().putRule("Employee", condition, conclusion).resolve();
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::java/api-reference.adoc#_LogicManager_putRule__java_lang_String__com_vaticle_typeql_lang_pattern_Pattern__com_vaticle_typeql_lang_pattern_Pattern[putRule()]
method in driver API reference.
++++
--

Node.js::
+
--
.Example
[,js]
----
let new_rule = await transaction.logic.putRule("Employee","{$u isa user, has email $e; $e contains '@vaticle.com';}","$u has name 'Employee'");
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::nodejs/api-reference.adoc#_LogicManager_putRule__label_string__when_string__then_string[putRule()]
method in driver API reference.
++++
--

C++::
+
--
.Example
[,cpp]
----
new_rule = transaction.logic.put_rule("Employee", "{$u isa user, has email $e; $e contains '@vaticle.com';}", "$u has name 'Employee'").resolve()
----

[subs="macros, post_replacements, replacements"]
++++
For more information, see the
xref:drivers::cpp/api-reference.adoc#_RuleFuture_TypeDBLogicManagerputRule_const_stdstring_label_const_stdstring_when_const_stdstring_then_const[putRule()]
method in driver API reference.
++++
--
====

=== Rule manipulation

A stateful rule object has just a few methods: get/set label, delete, and is_deleted.

[tabs]
====
Rust::
+
--
.Example
[,rust]
----
let _ = new_rule.delete(&transaction).resolve();
----
The above example deletes the type, which type object is stored in the variable, from the schema of a database.
You need to commit transaction to persist the changes.

[subs="macros, post_replacements, replacements"]
++++
For more information on methods, available for manipulating Rule objects, see the
xref:drivers::rust/api-reference.adoc#_struct_Rule[Rule class] methods.
++++
--

Python::
+
--
.Example
[,python]
----
new_rule.delete(transaction).resolve()
----

The above example deletes the type, which type object is stored in the variable, from the schema of a database.
You need to commit transaction to persist the changes.

[subs="macros, post_replacements, replacements"]
++++
For more information on methods, available for manipulating Rule objects, see the
xref:drivers::python/api-reference.adoc#_Rule[Rule class] methods.
++++
--

Java::
+
--
.Example
[,java]
----
newRule.delete(Transaction).resolve();
----

The above example deletes the type, which type object is stored in the variable, from the schema of a database.
You need to commit transaction to persist the changes.

[subs="macros, post_replacements, replacements"]
++++
For more information on methods, available for manipulating Rule objects, see the
xref:drivers::java/api-reference.adoc#_Rule[Rule class] methods.
++++
--

Node.js::
+
--
.Example
[,js]
----
await new_rule.delete(transaction);
----

The above example deletes the type, which type object is stored in the variable, from the schema of a database.
You need to commit transaction to persist the changes.

[subs="macros, post_replacements, replacements"]
++++
For more information on methods, available for manipulating Rule objects, see the
xref:drivers::nodejs/api-reference.adoc#_Rule[Rule class] methods.
++++
--

C++::
+
--
.Example
[,cpp]
----
(void) new_rule.get().deleteRule(transaction).get();
----

The above example deletes the type, which type object is stored in the variable, from the schema of a database.
You need to commit transaction to persist the changes.

[subs="macros, post_replacements, replacements"]
++++
For more information on methods, available for manipulating Rule objects, see the
xref:drivers::cpp/api-reference.adoc#_Rule[Rule class] methods.
++++
--
====

=== Full example

See below a comprehensive example of rules manipulation:
retrieving all rules, printing label, condition (when) and conclusion(then), adding a new rule,
retrieving a rule by its label, and deleting a rule.

[tabs]
====
Rust::
+
--
[,rust,indent=0]
----
include::manual::partial$rust-manual-code.rs[tags=rules-api]
----
--

Python::
+
--
[,python,indent=0]
----
include::manual::partial$python-manual-code.py[tags=rules-api]
----
--

Java::
+
--
[,java,indent=0]
----
include::manual::partial$java-manual-code.java[tags=rules-api]
----
--

Node.js::
+
--
[,js,indent=0]
----
include::manual::partial$nodejs-manual-code.js[tags=rules-api]
----
--

C++::
+
--
[,cpp,indent=0]
----
include::manual::partial$cpp-manual-code.cpp[tags=rules-api]
----
--
====

== Learn more

[cols-1]
--
.xref:drivers::overview.adoc[]
[.clickable]
****
Learn more about TypeDB drivers: list of available drivers, installation guides, API reference.
****
--

For more information about driver API methods, see the API reference of the relevant driver:

include::manual::reading/get.adoc[tags=drivers-api]


