== Retrieve valuetype (Local)

=== Syntax

[source,javascript]
----
attributeType.valueType;
----

=== Description

Retrieves the valuetype of this AttributeType.

=== Returns

* AttributeType.ValueType (STRING | DATETIME | LONG | DOUBLE | BOOLEAN)

== Set supertype

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx).setSupertype(attributeType);
----

=== Description

Sets the supplied AttributeType as the supertype of the current AttributeType

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| attributeType | The AttributeType to set as the supertype of this AttributeType | AttributeType | True | N/A
|===

=== Returns

* void

== Retrieve all subtypes

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx).getSubtypes()
----

=== Description

Retrieves all direct and indirect subtypes of the AttributeType.

=== Returns

* [`Stream`]  of [`AttributeType`] 

== Retrieve all instances of this AttributeType

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx).getInstances()
----

=== Description

Retrieves all direct and indirect Attributes that are instances of this Type.

=== Returns

* [`Stream`]  of [`Attribute`] 

== Retrieve direct and inherited owners of this Type of Attribute

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx).getOwners(annotations: Annotation[]);
----

=== Description

Retrieve all Things that own an attribute of this type.
Optionally, only fetches Things that own an attribute of this type with annotation set provided.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value

| Annotation
| Only retrieve things that have an attribute of this type with the exact annotation set.
a|
* `ThingType.Annotation.KEY`
* `ThingType.Annotations.UNIQUE`
| False | N/A
|===

=== Returns

* [`Stream`]  of [`Thing`] 

== Retrieve direct owners of this Type of Attribute

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx).getOwnersExplicit(onlyKey)
----

=== Description

Retrieve all Things that directly own an attribute of this type. Optionally, only fetches Things that own an attribute of this type as a key.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| onlyKey | If true, only retrieve things that have an attribute of this type as a key. | boolean | False | False
|===

=== Returns

* [`Stream`]  of [`Thing`] 

== Get a Remote version of the AttributeType.

=== Syntax

[source,javascript]
----
attributeType.asRemote(tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| transaction | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `RemoteAttributeType`

== Check if value is of type boolean

=== Syntax

[source,javascript]
----
attributeType.isBoolean();
----

=== Description

Returns true if the value for attributes of this type is of type boolean. Otherwise, returns false.

== Check if value is of type long

=== Syntax

[source,javascript]
----
attributeType.isLong();
----

=== Description

Returns true if the value for attributes of this type is of type long. Otherwise, returns false.

== Check if value is of type double

=== Syntax

[source,javascript]
----
attributeType.isDouble();
----

=== Description

Returns true if the value for attributes of this type is of type double. Otherwise, returns false.

== Check if value is of type string

=== Syntax

[source,javascript]
----
attributeType.isString();
----

=== Description

Returns true if the value for attributes of this type is of type string. Otherwise, returns false.

== Check if value is of type datetime

=== Syntax

[source,javascript]
----
attributeType.isDateTime();
----

=== Description

Returns true if the value for attributes of this type datetime. Otherwise, returns false.

