== Get a Remote version of the role type.

=== Syntax

[source,javascript]
----
roleType.asRemote(tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| tx | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `RemoteRoleType`

== Retrieve scope (Local)

=== Syntax

[source,javascript]
----
roleType.label.scope;
----

=== Description

Retrieves the scope (defined relation label) of the role type.

=== Returns

* String

== Retrieve scoped label (Local)

=== Syntax

[source,javascript]
----
roleType.label.scopedName;
----

=== Description

Retrieves the scoped label (relation:role) of the role type.

=== Returns

* String

== Retrieve direct supertype

=== Syntax

[source,javascript]
----
await type.asRemote(tx).getSupertype();
----

=== Description

Retrieves the most immediate supertype of the role type.

=== Returns

* [`RoleType`] 
* `null`

== Retrieve all supertypes

=== Syntax

[source,javascript]
----
type.asRemote(tx).getSupertypes()
----

=== Description

Retrieves all supertypes of the role type.

=== Returns

* [`Stream`]  of [`RoleType`] 

== Retrieve all subtypes

=== Syntax

[source,javascript]
----
type.asRemote(tx).getSubtypes()
----

=== Description

Retrieves all direct and indirect subtypes of the type.

=== Returns

* [`Stream`]  of [`RoleType`] 

== Retrieve relation

=== Syntax

[source,javascript]
----
await role.asRemote(tx).getRelationType();
----

=== Description

Retrieves the Relation instance that this role is directly related to.

=== Returns

* [`RelationType`] 

== Retrieve relation types

=== Syntax

[source,javascript]
----
await role.asRemote(tx).getRelationTypes();
----

=== Description

Retrieves the RelationTypes that this role is related to.

=== Returns

* [`Stream`]  of [`RelationType`] 

== Retrieve role players

=== Syntax

[source,javascript]
----
await role.asRemote(tx).getPlayers();
----

=== Description

Retrieves the ThingTypes whose instances play this role.

=== Returns

* [`Stream`]  of [`ThingType`](/docs/concept-api/type?tab=nodejs)

