= Defining functions

This page explains how to define functions within TypeDB schemas.

== Overview

include::{page-version}@typeql::functions/index.adoc[tag=description]

Functions can be defined in two ways:

1. We can define functions with "`globally`" in the schema of your database. Functions defined in the schema can be used in any data pipeline.
1. Or, we can define functions "`locally`" as part of a specific data pipeline. Such functions can only be called from within their parent pipeline.

The function definition syntax in both cases is identical. This page focuses on defining functions in schemas. For local functions in data pipeline see the xref:{page-version}@typeql::pipelines/with.adoc[with stage] reference.

== Defining functions

Similar to xref:{page-version}@manual::schema/types.adoc[type definitions], functions can be stored in a database schema using `schema` xref:{page-version}@manual::queries/transactions.adoc[transactions].
Three types of schema definition queries are available for working with functions:

* `define fun <function_name> <function_signature>: <function_body>`.
A `define` query adds a new function to the schema for future use.

* `undefine fun <function_name>`.
An `undefine` query removes a function from the schema.

* `redefine <function_name> <function_signature>: <function_body>`.
A `redefine` query updates an existing function in the schema.

=== Function signatures

Function signatures determine:

* The tuple of typed input variables, e.g., `$x : user, $y : string, $z : bool` (these variables can then be used in the function body)
* The tuple of output types, e.g. `post, integer, integer`, which can either be a *stream* of output tuples (indicated by surrounding brackets `{ ... }`) or a *scalar* tuple, meaning the function return _at most_ one tuple.

.Example signatures
[,typeql]
----
( $x : user, $y : string, $z : bool ) -> post, integer, integer      # scalar output
( $x : user, $y : string, $z : bool ) -> { post, integer, integer }  # stream output
( ) -> integer                                                       # empty input
----

=== Function body

The function body comprises

- A TypeQL xref:{page-version}@typeql::pipelines/index.adoc[read pipeline] (which may have multiple stages, like `match`, `sort`, `reduce`)
- A *return statement* starting with the keyword `return`

For xref:{page-version}@typeql::functions/stream.adoc[stream functions], `return` will be followed simply by a `<tuple>` of variables that are to be returned.

For xref:{page-version}@typeql::functions/scalar.adoc[scalar functions], the `return` statements will contain some sort of reduction of the answer set to (zero or) one answer:

- `return first <tuple>` returns the first answer only, and similarly, `return last ...` returns the last.
- `return <aggr>, ...` returns a built-in aggregation result (like sums, counts, means, ...)


== Examples

=== Computing values

[#_stream_arithmetic_example]
.Stream arithmetic function definition
[,typeql]
----
include::{page-version}@manual::example$tql/schema.tql[tags=define-keyword;fun-stream-return-value]
----

If you are certain that `$z` will only match a single value (or if only one value is needed), the `first` or `last` keywords can be used to ensure the function returns a xref:{page-version}@typeql::functions/scalar.adoc[scalar result].

.Single arithmetic function definition
[,typeql]
----
include::{page-version}@manual::example$tql/schema.tql[tags=define-keyword;fun-single-return-value]
----

=== Querying for data instances

[#_stream_example]
.Stream function definition returning data instances
[,typeql]
----
include::{page-version}@manual::example$tql/schema.tql[tags=define-keyword;fun-stream-return-type]
----

=== Functions within functions

.Tuple function definition with inner function calls
[,typeql]
----
include::{page-version}@manual::example$tql/schema.tql[tags=define-keyword;fun-square;fun-aggregate-single-tuple-return]
----

[NOTE]
====
The output type here is not a stream because each tuple component is derived from an aggregation, which produces a single result.
====

Refer to <<using_functions>> for more details on calling functions.

== Modifying functions

=== Function undefinition

To undefine a function from a schema, you only need its name, which uniquely identifies it.
The following query removes <<_stream_arithmetic_example, a function defined earlier>>:

[,typeql]
----
include::{page-version}@manual::example$tql/undefine_schema.tql[tags=undefine-keyword;fun-stream-return-value-undefined]
----

=== Function redefinition

To redefine an existing function, use the same `define` syntax with the `redefine` keyword.
The query below updates <<_stream_example, a previously defined function>> to accept a `username` instead of a specific `user`:

[#_redefine_example]
[,typeql]
----
include::{page-version}@manual::example$tql/redefine_schema.tql[tags=redefine-keyword;fun-stream-return-type-redefined]
----

[NOTE]
====
You can only redefine existing functions.
The function name must remain the same.
To change the name, define a new function and undefine the old one.
====

[#using_functions]
== Calling functions from patterns

Functions can be called in queries as other xref:{page-version}@typeql::statements/index.adoc[statements].
As shown in previous examples, to call a function, reference its name and pass the required arguments (if applicable) within parentheses.

For functions returning a single result, use a simple assignment to bind the output variable to the function's result:

[,typeql]
----
include::{page-version}@manual::example$tql/read_queries.tql[tag=fun-single-scalar-return-value]
----

[NOTE]
====
The xref:{page-version}@typeql::statements/let-eq.adoc[`let` keyword] is required for value assignment in this example.
====

For functions returning a stream, use xref:{page-version}@typeql::statements/let-in.adoc[`let ... in` statements] to bind variables:

[,typeql]
----
include::{page-version}@manual::example$tql/read_queries.tql[tag=fun-stream-scalar-return-type]
----

To handle tuple results, bind the appropriate number of variables to unpack the function’s output:

[,typeql]
----
include::{page-version}@manual::example$tql/read_queries.tql[tag=fun-stream-tuple-return-type]
----

For further details, refer to the xref:{page-version}@typeql::functions/index.adoc[TypeQL documentation].

[IMPORTANT]
====
The arguments in a function call are *positional* (i.e., arguments in the function call in a pattern are lined up with function arguments in its defined function signature).
Assigning a function output tuples to variables in a patterns is also positional.
====
