== Check the transaction's type

=== Syntax

[source,python]
----
transaction.transaction_type()
----

=== Description

Checks the transaction's type (READ or WRITE)

=== Returns

* TransactionType

== Check if the transaction is open

=== Syntax

[source,python]
----
transaction.is_open()
----

=== Returns

* boolean

== Access Concept API methods

=== Syntax

[source,python]
----
transaction.concepts();
----

=== Description

Gets the [`ConceptManager`]  for this Transaction, providing access to all Concept API methods.

=== Returns

* [`ConceptManager`] 

== Access Concept API - Logic methods

=== Syntax

[source,python]
----
transaction.logic();
----

=== Description

Gets the [`LogicManager`]  for this Transaction, providing access to all Concept API - Logic methods.

=== Returns

* [`LogicManager`] 

== Access Query API methods

=== Syntax

[source,python]
----
transaction.query();
----

=== Description

Gets the [`QueryManager`]  for this Transaction, from which any TypeQL query can be executed.

=== Returns

* [`QueryManager`] 

== Commit a write transaction

=== Syntax

[source,python]
----
transaction.commit()
----

=== Description

Commits the changes made via this transaction to the TypeDB database.
**Whether or not the transaction is commited successfully, it gets closed after the commit call.**

=== Returns

* None

== Rollback a write transaction

=== Syntax

[source,python]
----
transaction.rollback()
----

=== Description

Rolls back the uncommitted changes made via this transaction.

=== Returns

* None

== Close a read transaction

=== Syntax

[source,python]
----
transaction.close()
----

=== Description

Closes the transaction.

=== Returns

* None

