= TypeDB Cloud
:page-aliases: {page-version}@home::install/cloud.adoc

TypeDB Cloud is our platform for automatically deploying TypeDB onto the cloud provider of your choice.

== Deploying a cluster

1. Sign up for TypeDB Cloud at https://cloud.typedb.com/sign-up
2. Navigate to the **Clusters** dashboard and click the **Deploy** button
3. Configure your cluster, and click **Deploy**

== Cluster configuration

Paid clusters can be configured during deployment to select different technical specifications.
We offer a series of recommended configurations,
or you can enable advanced configuration for more options.

== After deploying

Once your cluster is deployed, you will be able to set the password for the default `admin` user.
Make sure to save this password somewhere safe, as you will need it to access your cluster.

Once your password is set, information on connecting to TypeDB Cloud can be found by staying on that page or
xref:{page-version}@manual::connect/cloud.adoc[viewing the documentation]
