= Install TypeDB Console CLI

TypeDB Console is a standalone TypeDB client with a command line interface (CLI).
It serves as a lightweight and powerful CLI tool to manage and query TypeDB databases.

The TypeDB Console CLI is packaged and distributed together with the TypeDB CE database server.

== Install

include::{page-version}@home::partial$console_install.adoc[tag=install]

== Run

TypeDB Console can connect to TypeDB CE, TypeDB Cloud instances, or TypeDB Enterprise deployments.
Running TypeDB Console initiates a network connection to a TypeDB server.

.Connect to TypeDB
[source,console]
----
typedb console --address=<server-address> --username=<username>
----

You will be prompted for a password.

Use `--tls-disabled` to connect to a server without encryption.

[NOTE]
=====
The default username and password are `admin` and `password`.
After connecting for the first time, you will be able to change the password.
=====

As a result, you get a welcome message from TypeDB Console followed by a command line prompt.

----
Welcome to TypeDB Console.

>>
----

== Getting Started

After installation, you can connect to TypeDB servers. For detailed connection instructions and usage guides, see:

* xref:{page-version}@tools::console.adoc[] - Complete Console documentation and connection guide
