= Node.js driver
:page-aliases: clients::nodejs-driver.adoc, clients::nodejs-driver/overview.adoc
:Summary: Overview for TypeDB Node.js driver.
:keywords: typedb, driver, node.js
:pageTitle: TypeDB Node.js driver

The Node.js driver was developed by Vaticle to enable TypeDB support for Node.js software and developers.

[cols-3]
--
.link:https://github.com/vaticle/typedb-driver/tree/development/nodejs[Source code,window=_blank]
[.clickable]
****

****

.link:https://github.com/vaticle/typedb-driver/releases[Releases,window=_blank]
[.clickable]
****

****

.link:https://www.npmjs.com/package/typedb-driver/[npm page,window=_blank]
[.clickable]
****

****
--

[#_install_nodejs]
== Install

See the
<<_version_compatibility>> table to check what versions of TypeDB and Python driver are compatible.


To install TypeDB Python driver:

[,bash]
----
npm install typedb-driver
----

.See the command for older versions (<2.24.0)
[%collapsible]
====
[,bash]
----
npm install typedb-client
----
====

== Quickstart

See below a short example of Node.Js code that connects to a local TypeDB Core,
creates a database named `access-management-db`, defines a schema, inserts some data, and then reads it.

[,js]
----
let driver, session, tx;
try {
    driver = await TypeDB.coreDriver("localhost:1729");
    await driver.databases().create("access-management-db");

    session = await client.session("access-management-db", SessionType.SCHEMA);
    tx = await session.transaction(TransactionType.WRITE);
    tx.query().define(accessManagementSchema);
    await tx.commit();
    await session.close();

    session = await client.session("access-management-db", SessionType.DATA);
    for (const batch of accessManagementDataBatches) {
        tx = await session.transaction(TransactionType.WRITE);
        for (const query of batch) {
            tx.query().insert(query);
        }
        await tx.commit();
    }
    tx = await session.transaction(TransactionType.READ);
    const results = tx.query().get("match $u isa user; get;");
} finally {
    if (tx) await tx.close();
    if (session) await session.close();
    if (driver) await driver.close();
}
----

For more code examples, see the Tutorial and Driver API links below.

== Learn more

[cols-2]
--
.xref:drivers::nodejs/tutorial.adoc[Tutorial]
[.clickable]
****
This tutorial will help you learn how to use the Node.Js driver.
****

.xref:nodejs/api-reference.adoc[API reference]
[.clickable]
****
Driver API reference for the Node.Js language.
****
--

include::drivers::partial$drivers2discord.adoc[]

//Use the xref:nodejs/api-reference.adoc[API reference] page for the documentation of the methods and objects used in the driver.

[#_version_compatibility]
== Version Compatibility

[cols="^.^3,^.^2,^.^3,^.^3,^.^1"]
|===
| Node.js driver | Protocol encoding version | TypeDB Core | TypeDB Cloud | Node

| 2.26.5
| 3
| 2.26.3
| 2.26.0
| >= 14.15

| 2.25.8
| 3
| 2.25.7
| 2.25.7
| >= 14.15

| 2.24.15
| 2
| 2.24.17
| 2.24.17
| >= 14.15

| 2.18.1, 2.18.2
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0
| >= 14.15

| 2.17.0
| N/A
| 2.17.0
| 2.17.0
| >= 14.15

| 2.16.1
| N/A
| 2.16.1
| 2.16.1
| >= 14.15

| 2.14.2
| N/A
| 2.12.0 to 2.15.0
| 2.13.0 to 2.15.0
| >= 14.15

| 2.9.0 to 2.11.1
| N/A
| 2.9.0 to 2.11.1
| 2.9.0 to 2.11.2
| >= 14.15

| 2.8.0
| N/A
| 2.8.0
| N/A
| >= 14.15

| 2.6.0 to 2.6.2
| N/A
| 2.6.0 to 2.7.1
| N/A
| >= 14.15

| 2.4.0 to 2.5.0
| N/A
| 2.1.2 to 2.5.0
| 2.5.0
| >= 14.15

| 2.1.0 to 2.2.0
| N/A
| 2.1.2 to 2.5.0
| 2.1.2 to 2.3.0
| >= 14.15

| 2.0.1
| N/A
| 2.0.2
| 2.0.2
| >= 14.15

| 2.0.0
| N/A
| 2.0.0, 2.0.1
| 2.0.0, 2.0.1
| >= 14.15

| 1.8.0
| N/A
| 1.8.0 to 1.8.4
| N/A
| >= 6.5
|===
