= TypeDB manual
:keywords: typedb, guides, how, installation, tutorial
:pageTitle: TypeDB Manual
:page-aliases: {page-component-version}@manual::overview.adoc
:summary: How-to guides and tutorials

The TypeDB manual contains practice-oriented guides on using TypeDB, covering all aspects of the database lifecycle.

You can run TypeDB database servers in the following environments:

[cols-2]
--
.https://cloud.typedb.com[TypeDB Cloud]
[.clickable]
****
The fully managed service for TypeDB deployments in the cloud.
****

.xref:manual::self-managed/index.adoc[TypeDB Community Edition]
[.clickable]
****
The self-hosted, open-source, free-to-use version of TypeDB.
****

.xref:manual::self-managed/enterprise.adoc[TypeDB Enterprise]
[.clickable]
****
The subscription-based, self-hosted version of TypeDB, designed for enterprise usage.
****
--


== Standalone clients

Standalone clients can be used to conveniently work and develop with TypeDB.

[cols-2]
--
.xref:{page-component-version}@manual::install/overview.adoc[]
[.clickable]
****
Installation guides for TypeDB Core, TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:{page-component-version}@manual::setup/overview.adoc[]
[.clickable]
****
A powerful CLI client for TypeDB.
****
--
////
[cols-1]
--
.xref:drivers::index.adoc[Drivers]
[.clickable]
****
xref:drivers::rust/index.adoc[Rust] |
xref:drivers::python/index.adoc[Python] |
xref:drivers::java/index.adoc[Java] |
xref:drivers::nodejs/index.adoc[Node.js] |
xref:drivers::cpp/index.adoc[C++]
****
--
////

== Using TypeDB

Learn how to perform common tasks with TypeDB.

[cols-2]
--
.xref:manual::connecting/index.adoc[]
[.clickable]
****
Connect to a TypeDB server and create a new database.
// Network connection to TypeDB Community Edition or Cloud, as well as database, session and transaction management.
// * xref:manual::connecting/connection.adoc[]
// * xref:manual::connecting/database.adoc[]
// * xref:manual::connecting/session.adoc[]
// * xref:manual::connecting/transaction.adoc[]
****

.xref:manual::defining/index.adoc[]
[.clickable]
****
Set and modify the schema of a database with a TypeQL query or driver API call.
// * xref:manual::defining/define.adoc[]
// * xref:manual::defining/undefine.adoc[]
// * xref:manual::defining/schema-editing.adoc[]
****

.xref:manual::writing/index.adoc[]
[.clickable]
****
Insert, delete, or update (replace) data in a TypeDB database with TypeQL queries.
// * xref:manual::writing/insert.adoc[]
// * xref:manual::writing/delete.adoc[]
// * xref:manual::writing/update.adoc[]
****

.xref:manual::reading/index.adoc[]
[.clickable]
****
Retrieve data as JSONs or stateful objects with TypeQL queries.
// * xref:manual::reading/fetch.adoc[]
// * xref:manual::reading/get.adoc[]
// * xref:manual::reading/infer.adoc[]
****
--

== Sending queries

TypeDB Drivers can be used to query TypeDB directly from within your application. For the TypeDB drivers documentation, see the xref:drivers::index.adoc[Drivers] category.

[cols-2]
--
.xref:manual::objects/index.adoc[]
[.clickable]
****
Guides on connecting to TypeDB Cloud and TypeDB Core deployments using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:manual::bulk-loading/index.adoc[]
[.clickable]
****
Guides on creating and deleting databases using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:{page-component-version}@manual::queries/overview.adoc[]
[.clickable]
****
Guides on controlling transactions, issuing queries, and processing responses using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****
--

== Database operations

[cols-3]
--
.xref:{page-component-version}@manual::schema/overview.adoc[]
[.clickable]
****
Guides on defining different schema components, and on best data modeling practices.
****

.xref:{page-component-version}@manual::writing/overview.adoc[]
[.clickable]
****
Guides on inserting, modifying, bulk-loading, and importing data.
****

.xref:{page-component-version}@manual::reading/overview.adoc[]
[.clickable]
****
Guides on retrieving data, using functions, and building data pipelines.
****
--

== Application building

[cols-3]
--
.xref:{page-component-version}@manual::maintainance/overview.adoc[]
[.clickable]
****
Guides on all aspects of database maintenance, including migrations, backups, upgrades, exports, and orchestration.
****

.xref:{page-component-version}@manual::users/overview.adoc[]
[.clickable]
****
Guides on managing databases users and creating access policies with roles and permissions.
****

.xref:{page-component-version}@manual::troubleshooting/overview.adoc[]
[.clickable]
****
Troubleshooting guides for common problems and pitfalls.
****
--
