= TypeDB manual
:keywords: typedb, guides, how, installation, tutorial
:pageTitle: TypeDB Manual
:summary: How to guides and tutorials

The TypeDB manual contains practice-oriented guides on using TypeDB, covering all aspects of the database lifecycle.

== Getting started

[cols-2]
--
.xref:{page-version}@manual::install/overview.adoc[]
[.clickable]
****
Installation guides for TypeDB Core, TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:{page-version}@manual::setup/overview.adoc[]
[.clickable]
****
Guides on starting, stopping, and configuring TypeDB Cloud and TypeDB Core deployments, and on setting up TypeDB Studio and TypeDB Console.
****
--

== Sending queries

[cols-3]
--
.xref:{page-version}@manual::connect/overview.adoc[]
[.clickable]
****
Guides on connecting to TypeDB Cloud and TypeDB Core deployments using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:{page-version}@manual::databases/overview.adoc[]
[.clickable]
****
Guides on creating and deleting databases using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****

.xref:{page-version}@manual::queries/overview.adoc[]
[.clickable]
****
Guides on controlling transactions, issuing queries, and processing responses using TypeDB Studio, TypeDB Console, and the TypeDB Drivers.
****
--

== Database operations

[cols-3]
--
.xref:{page-version}@manual::schema/overview.adoc[]
[.clickable]
****
Guides on defining different schema components, and on best data modeling practices.
****

.xref:{page-version}@manual::writing/overview.adoc[]
[.clickable]
****
Guides on inserting, modifying, bulk-loading, and importing data.
****

.xref:{page-version}@manual::reading/overview.adoc[]
[.clickable]
****
Guides on retrieving data, using functions, and building data pipelines.
****
--

== Application building

[cols-3]
--
.xref:{page-version}@manual::maintainance/overview.adoc[]
[.clickable]
****
Guides on all aspects of database maintenance, including migrations, backups, upgrades, exports, and orchestration.
****

.xref:{page-version}@manual::users/overview.adoc[]
[.clickable]
****
Guides on managing databases users and creating access policies with roles and permissions.
****

.xref:{page-version}@manual::troubleshooting/overview.adoc[]
[.clickable]
****
Troubleshooting guides for common problems and pitfalls.
****
--
