// tag::manual-install[]

Get the docker image from the https://hub.docker.com/r/vaticle/typedb/tags[Docker hub,window=_blank]
or
https://github.com/vaticle/typedb-driver/blob/development/rust/README.md#build-from-source[build,window=_blank]
it from https://github.com/vaticle/typedb/tags[source code,window=_blank] with Bazel.

// end::manual-install[]

// tag::install[]
To pull the latest TypeDB Docker image:

[source,console]
----
$ docker pull vaticle/typedb:latest
----

You can replace `latest` with a version number to get a specific version of TypeDB Core.
To check the list of available versions,
see the link:https://github.com/vaticle/typedb/releases[Releases,window=_blank] page.

// end::install[]

// tag::run[]
To create and run a new Docker container with TypeDB Core server:

[source,console]
----
$ docker run --name typedb -d -v typedb-data:/opt/ -p 1729:1729 --platform linux/amd64 vaticle/typedb:latest
----
// end::run[]
// tag::run-info[]
Where `typedb` -- the name of the container; `typedb-data` -- the name of the volume to persist data.

The `--platform linux/amd64` parameter is required to run the TypeDB container on macOS with the `arm64`
architecture.
//Support for `linux/arm64` will be released in a future version of TypeDB.
// end::run-info[]

// tag::stop[]
To stop a running Docker container:

[source,console]
----
$ docker stop typedb
----
// end::stop[]

// tag::start[]
To start an existing Docker container again:

[source,console]
----
$ docker start typedb
----
// end::start[]
