// tag::install-apt[]

. Add the TypeDB repository:
+
[source,console]
----
$ sudo apt install software-properties-common apt-transport-https gpg
$ gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 17507562824cfdcc
$ gpg --export 17507562824cfdcc | sudo tee /etc/apt/trusted.gpg.d/vaticle.gpg > /dev/null
$ echo "deb https://repo.typedb.com/public/public-release/deb/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/vaticle.list > /dev/null
$ sudo apt update
----
. Ensure Java 11+ is installed:
+
[source,console]
----
$ sudo apt install default-jre
----
+
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/#java11[Oracle JDK,window=_blank].
. Install `typedb`:
+
[source,console]
----
$ sudo apt install typedb
----
+
If you had an older version (≤`2.25.5`) of TypeDB installed, it might be needed to uninstall older packages to avoid
conflicts:
+
[source,console]
----
$ sudo apt remove typedb-server typedb-bin typedb-console
----
////
The `typedb-server` and `typedb-console` packages are updated more often than `typedb-bin`, so their
version numbers might differ. By default, APT will look for the exact same version of `typedb-bin`,
resulting in an error. To prevent this, use `apt show`, as shown above, to find a compatible version first, and then
invoke an `apt install` command with the specific version for every package.
////
// end::install-apt[]

// tag::manual-install[]

. Ensure Java 11+ is installed.
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/#java11[Oracle JDK,window=_blank].

. Extract the archive with TypeDB into a new directory:
+
[source,console]
----
$ mkdir /opt/typedb
$ tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB executable in the `/usr/local/bin` directory:
+
[source,console]
----
$ ln -s /opt/typedb/<filename>/typedb /usr/local/bin/typedb
----

// end::manual-install[]

// tag::start[]
To run TypeDB Core installed locally:

[source,console]
----
$ typedb server
----
// end::start[]

// tag::stop[]

To stop TypeDB Core server, close the terminal or press kbd:[Ctrl+C].

// end::stop[]
