// tag::install-apt[]

. Add the TypeDB repository:
+
[,bash]
----
sudo apt install software-properties-common apt-transport-https gpg
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 8F3DA4B5E9AEF44C
gpg --export 8F3DA4B5E9AEF44C | sudo tee /etc/apt/trusted.gpg.d/vaticle.gpg > /dev/null
echo "deb https://repo.vaticle.com/repository/apt/ trusty main" | sudo tee /etc/apt/sources.list.d/vaticle.list > /dev/null
----
. Update the package cache:
+
[,bash]
----
sudo apt update
----
. Ensure Java 11+ is installed:
+
[,bash]
----
sudo apt install openjdk-11-jre
----
//todo switch to sudo apt install default-jre after 2.25
+
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/[Oracle JDK,window=_blank].
. Check the latest version number for `typedb-server` and its dependencies:
+
[,bash]
----
apt show typedb-server
----
+
The above command's output:
+
[,bash]
----
Package: typedb-server
Version: 2.15.0
Priority: optional
Section: contrib/devel
Maintainer: Vaticle <community@vaticle.com>
Installed-Size: unknown
Depends: openjdk-11-jre, typedb-bin (=2.12.0)
Download-Size: 71.8 MB
APT-Sources: https://repo.vaticle.com/repository/apt trusty/main all Packages
Description: TypeDB (server)
----
+
Take note of the latest `typedb-server` version in the `Version` field and the corresponding `typedb-bin`
package version in the `Depends` field.
The `typedb-console` version can be seen with the command `apt show typedb-all=2.15.0`, where `2.15.0` is the version
of `typedb-server` from the output above.
. Install `typedb-server`, `typedb-console`, and `typedb-bin` packages using the versions from the previous commands:
+
[,bash]
----
sudo apt install typedb-server=2.15.0 typedb-console=2.15.0 typedb-bin=2.12.0
----

The `typedb-server` and `typedb-console` packages are updated more often than `typedb-bin`, so their
version numbers might differ. By default, APT will look for the exact same version of `typedb-bin`,
resulting in an error. To prevent this, use `apt show`, as shown above, to find a compatible version first, and then
invoke an `apt install` command with the specific version for every package.

// end::install-apt[]

// tag::manual-install[]

. Ensure Java 11+ is installed.
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/[Oracle JDK,window=_blank].

. Extract the archive with TypeDB into a new directory:
+
[,bash,subs=attributes+]
----
mkdir /opt/typedb
tar -xzf ~/Downloads/typedb-all-linux-{latest-version}.tar.gz -C /opt/typedb
----

. Add a symlink to the TypeDB executable in the `/usr/local/bin` directory:
+
[,bash,subs=attributes+]
----
ln -s /opt/typedb/typedb-all-linux-{latest-version}/typedb /usr/local/bin/typedb
----

// end::manual-install[]

// tag::start[]

[,shell]
----
typedb server
----

// end::start[]

// tag::stop[]

Close the terminal or press kbd:[Ctrl+C].

// end::stop[]
