= Statements
:page-aliases: {page-version}@typeql::statements/overview.adoc

A TypeQL statement is a building block of a TypeQL pattern.
Statements in TypeQL are always end with a semicolon.

== Simple statements

A simple statement is the smallest complete TypeQL block that can be used as a pattern in a query.

Most simple statements have two or three parts: `<PREDICATE> <SUBJECT>`, `<SUBJECT> <PREDICATE>` or `<SUBJECT> <PREDICATE> <OBJECT>`, where `<PREDICATE>` is a TypeQL keyword. However, there can be other more complex statements like xref:{page-version}@typeql::statements/let-in.adoc[].

[#_composite_statements]
== Composite statements

Multiple simple statements with the same subject can be combined into a composite statement.
A composite statement starts with a single subject, and multiple comma-separated simple statements with subject omitted.

.See an example
[%collapsible]
====
.Composite statement example
[,typeql]
----
include::{page-version}@typeql::example$tql/schema_statements_functions.tql[tags=define-keyword;entity-user]
----

The above example combines simple xref:{page-version}@typeql::statements/entity.adoc[`entity`], xref:{page-version}@typeql::statements/sub.adoc[`sub`], xref:{page-version}@typeql::statements/owns.adoc[`owns`], and xref:{page-version}@typeql::statements/plays.adoc[`plays`] statements to the same result without repeating the subject:

.Equal simple statements example
[,typeql]
----
include::{page-version}@typeql::example$tql/schema_statements_functions.tql[tags=define-keyword;entity-user-breakdown]
----
====

The comma separation is required before a `<PREDICATE>` if its `<SUBJECT>` already has another `<PREDICATE>` on its right side. Note how first two predicates do not require a comma in the previous example.

== Type definition statements

[cols-3]
--
.xref:{page-version}@typeql::statements/entity.adoc[]
[.clickable]
****
Used to define a new entity type.
****

.xref:{page-version}@typeql::statements/relation.adoc[]
[.clickable]
****
Used to define a new relation type.
****

.xref:{page-version}@typeql::statements/attribute.adoc[]
[.clickable]
****
Used to define a new attribute type.
****

.xref:{page-version}@typeql::statements/struct.adoc[]
[.clickable]
****
Used to define a new struct type.
****

.xref:{page-version}@typeql::statements/fun.adoc[]
[.clickable]
****
Used to define a new function.
****
--

== Constraint definition statements

[cols-3]
--
.xref:{page-version}@typeql::statements/sub.adoc[]
[.clickable]
****
Used to define the supertype of a type.
****

.xref:{page-version}@typeql::statements/relates.adoc[]
[.clickable]
****
Used to define a new role for a relation type.
****

.xref:{page-version}@typeql::statements/plays.adoc[]
[.clickable]
****
Used to define a new roleplayer for a role.
****

.xref:{page-version}@typeql::statements/value.adoc[]
[.clickable]
****
Used to define the value type of an attribute type.
****

.xref:{page-version}@typeql::statements/owns.adoc[]
[.clickable]
****
Used to define a new owner of an attribute type.
****

.xref:{page-version}@typeql::statements/alias.adoc[]
[.clickable]
****
Used to define an alias label for a type.
****
--

== Instance statements

[cols-3]
--
.xref:{page-version}@typeql::statements/isa.adoc[]
[.clickable]
****
Used to specify the type of a data instance.
****

.xref:{page-version}@typeql::statements/links.adoc[]
[.clickable]
****
Used to specify the roleplayers in a relation.
****

.xref:{page-version}@typeql::statements/has.adoc[]
[.clickable]
****
Used to specify an attribute of an entity or relation.
****

.xref:{page-version}@typeql::statements/is.adoc[]
[.clickable]
****
Used to specify that two variables represent the same data instance.
****

.xref:{page-version}@typeql::statements/let-eq.adoc[]
[.clickable]
****
Used to assign the result of an expression to a variable.
****

.xref:{page-version}@typeql::statements/let-in.adoc[]
[.clickable]
****
Used to assign a stream or list element to a variable.
****

.xref:{page-version}@typeql::statements/contains.adoc[]
[.clickable]
****
Used to specify that a stream or list contains a data instance.
****

.xref:{page-version}@typeql::statements/like.adoc[]
[.clickable]
****
Used to specify that a string matches a specified regex pattern
****
--

== Identity statements

[cols-2]
--
.xref:{page-version}@typeql::statements/label.adoc[]
[.clickable]
****
Used to identify a type by its label.
****

.xref:{page-version}@typeql::statements/iid.adoc[]
[.clickable]
****
Used to identify a data instance by its internal ID.
****
--
