[#_enum_ConnectionError]
=== ConnectionError

[caption=""]
.Enum variants
// tag::enum_constants[]
[cols="~"]
[options="header"]
|===
|Variant
a| `BrokenPipe(/* private fields */)`
a| `ConnectionFailed(/* private fields */)`
a| `ConnectionIsClosed(/* private fields */)`
a| `DatabaseDoesNotExist(String)`
a| `CloudAllNodesFailed(String)`
a| `CloudEndpointEncrypted(/* private fields */)`
a| `CloudReplicaNotPrimary(/* private fields */)`
a| `CloudSSLCertificateNotValidated(/* private fields */)`
a| `CloudTokenCredentialInvalid(/* private fields */)`
a| `InvalidResponseField(&'static str)`
a| `MissingResponseField(&'static str)`
a| `RPCMethodUnavailable(String)`
a| `ServerConnectionFailed(String)`
a| `ServerConnectionFailedStatusError(String)`
a| `ServerConnectionFailedWithError(String)`
a| `SessionCloseFailed(/* private fields */)`
a| `SessionIsClosed(/* private fields */)`
a| `TransactionIsClosed(/* private fields */)`
a| `TransactionIsClosedWithErrors(String)`
a| `UnexpectedResponse(String)`
a| `UnknownRequestId(ID)`
a| `UserManagementCloudOnly(/* private fields */)`
|===
// end::enum_constants[]

