= `@abstract` annotation
:page-aliases: {page-version}@typeql::statements/abstract.adoc

The `@abstract` annotation is used
// tag::overview[]
to specify that a type is abstract.
// end::overview[]

== Syntax

.Syntax
[,typeql]
----
<type label> @abstract;
----

The `@abstract` annotation does not accept any arguments.

== Usage

// tag::description[]
When defined for a type, the `@abstract` annotation enforces the `abstract` constraint, making the type abstract.
An abstract type cannot be a direct type for an instance.
Thus, a concrete subtype is required for instances creation, and an abstract type can be used as a query target to retrieve information about its subtypes.
// end::description[]

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;abstract-entity;]
----

=== Subtyping

The `abstract` constraint is not inherited.
This means all subtypes of an abstract type are concrete by default, enabling the creation of their instances.
However, it is possible to define an abstract subtype of an abstract type.

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;abstract-attribute]
----

It is impossible to define an abstract subtype of a concrete type.

.Wrong definition!
[,typeql]
----
define
  attribute categorized-username @abstract, sub username;
----

=== Specialization of role types

// TODO: Add a hyperlink to "relates as"
Similarly, abstract role types cannot be instantiated.
A concrete sub role type can be defined using **specialization** (keyword `as`).

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;abstract-relation]
----
