= `@independent` annotation

The `@independent` annotation is used
// tag::overview[]
to prevent attributes without owners from being deleted automatically.
// end::overview[]

== Syntax

.Syntax
[,typeql]
----
<type label> @independent;
----

The `@independent` annotation does not accept any arguments.

== Usage

The `@independent` annotation enforces the `independent` constraint for an attribute type, allowing the type to exist independently of an owner.

// TODO: Add a reference to attributes and their dependency on existing owners

By default, attributes (instances of attribute types) depend on their owners:
* Attributes cannot be inserted without a `has` clause.
* Attributes are automatically deleted when their owners are deleted.

In contrast, attributes of independent types can exist without owners.

.Independent attribute types definition
[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;independent-attribute;]
----

.Independent attributes insertion
[,typeql]
----
include::{page-version}@typeql::example$tql/data_annotations.tql[tags=insert-keyword;independent-attribute;]
----
