= `@range` annotation

The `@range` annotation is used
// tag::overview[]
to specify a range of permitted values for attributes.
// end::overview[]

== Syntax

.Value annotation syntax
[,typeql]
----
<type label> value <value type> @range(N..M);
<type label> value <value type> @range(N..);
<type label> value <value type> @range(..M);
----

.Ownership annotation syntax
[,typeql]
----
<type label> owns <attribute type label> @range(N..M);
<type label> owns <attribute type label> @range(N..);
<type label> owns <attribute type label> @range(..M);
----

The `@range` annotation can be defined for either an attribute type's value type or an ownership.

The `@range` annotation accepts either a range argument or a single scalar argument.
Arguments must match the value type of `<attribute type label>`.
See <<_value_types>> for the list of supported value types.

Partially unbounded ranges `N..` and `..M` represent ranges without an upper and lower bounds, respectively.

== Usage

The `@range` annotation adds a constraint on values of attributes of a given attribute type to be within the specified range.

include::{page-version}@typeql::annotations/values.adoc[tags=values-and-owns-annotations-description-values]

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;range-value]
----

[#_example_owns]
include::{page-version}@typeql::annotations/values.adoc[tags=values-and-owns-annotations-description-owns]
In the following example, an instance of the `creation-timestamp` type can contain any value, but a `post` can have (`has`) only the `creation-timestamp` s with the suitable values.

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;creation-timestamp-attribute;range-owns]
----

=== Subtyping for attribute types' values

The `range` constraint put on an attribute types' value type is inherited.
include::{page-version}@typeql::annotations/values.adoc[tags=value-constraints-subtyping]

A subtype can introduce an even stricter constraint to allow only a subrange of the inherited range for its values.

=== Subtyping for ownerships
The `range` constraint put on an ownership should be respected by all the sub attribute types owned by this owner. This way, any instance of any subtype of the `creation-timestamp` <<#_example_owns, owned by>> any instance of any subtype of the `post` should comply to the defined `range`.

Ownerships of these subtypes can have their own `range` constraints, and they will be respected similarly down the inheritance line.

== Limitations

See <<_value_types>> for the list of supported value types.

[#_references]
== References

[#_value_types]
=== Supported value types

The `@range` annotation is applicable only to value types with a defined ordering for their values.

.Supported value types
[cols=".^1,^.^1,1"]
|===
^| Value type ^| Supported? ^| Comment
| `boolean`
| ✓
|

| `integer`
| ✓
|

| `double`
| ✓
|

| `decimal`
| ✓
|

| `string`
| ✓
|

| `date`
| ✓
|

| `datetime`
| ✓
|

| `datetime-tz`
| ✓
|

| `duration`
| ✗
|

// | `struct`
// |
// | Custom value types do not currently support ordering
|===
