= `@regex` annotation
:page-aliases: {page-version}@typeql::statements/regex.adoc

The `@regex` annotation is used
// tag::overview[]
to specify a regex pattern for permitted values of attributes.
// end::overview[]

== Syntax

.Value annotation syntax
[,typeql]
----
<type label> value <value type> @regex("<regular expression>");
----

.Ownership annotation syntax
[,typeql]
----
<type label> owns <attribute type label> @regex("<regular expression>");
----

The `@regex` annotation can be defined for either an attribute type's value type or an ownership.

The `@range` annotation accepts a single string argument containing a regular expression.

== Usage

// tag::description[]
The `@regex` annotation adds a constraint on values of attributes of a given attribute type to be valid strings according to the regular expression.
// end::description[]

include::{page-version}@typeql::annotations/values.adoc[tags=values-and-owns-annotations-description-values]

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;regex-value]
----

[#_example_owns]
include::{page-version}@typeql::annotations/values.adoc[tags=values-and-owns-annotations-description-owns]
In the following example, an instance of the `phone` type can contain any `string` value, but a `user` can have (`has`) only the `phone` s with the suitable values.

[,typeql]
----
include::{page-version}@typeql::example$tql/schema_annotations.tql[tags=define-keyword;phone-attribute;regex-owns]
----

=== Subtyping

The `regex` constraint put on an attribute types' value type is inherited.
include::{page-version}@typeql::annotations/values.adoc[tags=value-constraints-subtyping]

A subtype can introduce another `regex` constraint to combine it with the inherited one and create a subset of allowed values based on the intersection of the specified regular expressions.

=== Subtyping for ownerships
The `regex` constraint put on an ownership should be respected by all the sub attribute types owned by this owner. This way, any instance of any subtype of the `phone` <<#_example_owns, owned by>> any instance of any subtype of the `user` should comply to the defined `regex`.

Ownerships of these subtypes can have their own `regex` constraints, and they will be respected similarly down the inheritance line.

== Limitations

Is only compatible with xref:{page-version}@typeql::values/string.adoc[`string` value type].
