= CRUD

CRUD operations create, read, update, and delete data in the TypeDB database.

== Create

When a database is created, it contains no data. The first step to building a rich, structured knowledge base is to insert data into the
database. This can be done in two primary ways: using an `insert` stage for unconditional creation, or a `put` stage for idempotent
creation. All creation operations must be performed in a write-capable transaction (i.e., `write` or `schema`).

===  Unconditional creation using `insert`

The `insert` stage is the fundamental command for creating new data. It adds the specified instances without first checking if they
already exist. If insert is the first stage in a pipeline, it runs just once. For these examples, consider this schema:

For these examples, consider the following schema:

[,typeql]
.Sample schema
----
define
  entity person,
    owns name @card(1),
    plays friendship:friend;
  relation friendship,
    relates friend;
  attribute name,
    value string;
----

If `insert` is the first stage in a pipeline, it runs just once and outputs a single row containing the newly created instances.

An example command to insert two people and a friendship between them would be:

[,typeql]
.Alice 🤝 Bob
----
insert
  $a-name isa name "Alice";
  $b-name isa name "Bob";
  $a isa person, has $a-name;
  $b isa person, has $b-name;
  $f isa friendship, links (friend: $a, friend: $b);
----

The output row will contain the newly created instances:

[,typeql]
----
   -------------
    $a      | isa person, iid 0x1e00000000000000000000
    $a-name | isa name "Alice"
    $b      | isa person, iid 0x1e00000000000000000001
    $b-name | isa name "Bob"
    $f      | isa friendship, iid 0x1f00000000000000000000
   -------------
----

When an `insert` stage is preceded by other stages, most commonly `match`, the `insert` stage will run once for each row it receives from
the previous stage, and its output rows will contain the newly created instances as well as the contents of the input rows.

In this example, Alice and Bob are already in the database, and we want to create a friendship between them.

[,typeql]
.Alice 🤝 Bob, v2
----
match
  $a isa person, has name "Alice";
  $b isa person, has name "Bob";
insert
  $f isa friendship, links (friend: $a, friend: $b);
----

For more detailed information on `insert` stages, see the xref:{page-version}@typeql::pipelines/insert.adoc[Insert query stage documentation in the
TypeQL reference].

=== Idempotent creation using `put`

The `put` stage represents an "insert if not exists" operation and provides a simple way to ensure data exists. It first attempts to match
the entire pattern against existing data. If a complete match is found, no changes are made. If _any part of the pattern_ does not match, the
query executes as if it were an insert stage for _the entire pattern._

[,typeql]
----
put
  $a isa person, has name "Alice";
  $b isa person, has name "Bob";
  $f isa friendship, links (friend: $a, friend: $b);
----

This query will attempt to match the given patterns against existing data in the database. If the patterns are matched, the query stage will
retrieve the matched instances and make no changes to the database. If the patterns are _not_ matched, however, the query will execute as if
it were an `insert` stage.

[IMPORTANT]
====
It's worth underlining: `put` stages are all-or-nothing. For example, in the query above, even if a `person` named`"Alice"` already exists
in the database, if there is no `person` named `"Bob"`, the query will insert a new `person` with the name `"Alice"`, a new `person` with
the name `"Bob"`, and a new friendship between them.
====

For more detailed information on `put` stages, see the xref:{page-version}@typeql::pipelines/put.adoc[put query stage] documentation in the TypeQL reference.

=== Bulk loading

You may already have a large amount of data that you wish to insert into the newly created database.
This section contains some suggestions on how to do that efficiently.

==== Query batching

There is a cost associated with opening and committing transactions. If you have a large number of queries to execute, you should consider
batching more than one query into a single transaction.

Care should be taken to ensure that the batches of queries are not too large. Long-running transactions can cause slowdowns as large sets of
data are validated against each other during commits.

As a rule of thumb, we recommend around 100-1000 inserts per transaction, though the exact numbers vary application to application.

==== Deferred resolution

Queries are performed asynchronously: when a query request is sent from the driver, the returned value is a _promise_ that needs to be
resolved to obtain the actual result.

This allows the driver to send multiple queries to the server to be executed concurrently. The suggested way to take advantage of this is to
open a number of concurrent transactions and send a batch of queries to each of them.

[tabs]
.Example
====
Python::
+
--
[,python]
----
# TODO
----
--

Rust::
+
--
The `futures` crate provides the way to concurrently execute tasks in batches of specified size.

[,rust]
----
let batch_tasks = batches.into_iter().map(|batch| {
    let driver = driver.clone();
    async move {
        let tx = driver.transaction(typedb_driver::TransactionType::Write).await?;
        let result = tx.query(batch_query(batch)).await?;
        tx.commit().await?;
        Ok(result)
    }
});
let results: Vec<typedb_driver::Result> =
    stream::iter(batch_tasks).buffered(parallelization).collect().await;
----
--
====

==== Duplication

A major concern when loading large amounts of data is duplication. In most cases, it can be avoided by using the `put` stage:

[,typeql]
.Insert a new user if there isn't already a user named `"john1"`
----
put
  $x isa user, has username "john_1";
----

==== Data dependencies and ordering

When batching and parallelizing be aware of data dependencies: for example, you can only insert a friendship between two users, if:

* either, the friendship is inserted as part of the same insert query as the users,
* or, the friendship is inserted as part of insert query is run _after_ the insert query for the users but in the _same transaction_,
* or, the friendship insert is part of a separated transaction that starts _after the transaction inserting the users has successfully
  committed_.

When insertions are performed in parallel, care must be taken that any transaction that is expected to have completed has successfully
committed.

== Read

All queries must be performede within a transaction. All transaction types, `read`, `write`, and `schema`, are read-capable.

=== Retrieving data in rows using `match`

A `match` stage is the fundamental command for retrieving data. They retrieve data by matching *patterns*. Patterns represent constraints
the variables are expected to satisfy. Match stages return _all combinations_ of data for their variables that satisfy the pattern, though
they will not rebind a variable already bound by previous stages.

Patterns can be combined into larger patterns by conjunction with `;`, disjuction with `or`, and negation with `not`. Patterns can also be
marked as optional by putting them in a `try` block, in which case any failure to match those patterns does not affect the rest of the
stage, and the variables that are newly introduced in the block are considered optionally bound (`$x?`). See the
xref:{page-version}@typeql::patterns/index.adoc[pattern reference] for more.

The stream of rows can then be processed using stream operators such as `sort`, `reduce`, and `limit`, or extended with more `match`
clauses.

When retrieving data from the database there is a basic distinction to keep in mind:

* *objects*, i.e. entities and relations, do not have a value that can be returned from the database; instead they are represented
  by an internal ID (see xref:{page-version}@typeql::data_model.adoc#representation[IID]).
* *attributes* are fully identified by their type and value.

For the full list of query stages and stream operators, consult the xref:{page-version}@typeql::pipelines/index.adoc[data pipelines]
documentation in the TypeQL reference.

=== Retrieving data in documents using `fetch`

A `fetch` stage converts each input row into a JSON-like document. The body of a `fetch` stage describes the structure of the document.

[,typeql]
----
match
  $p isa person;
fetch {
  "name": $p.name,
  "friends": [
    match ($p, $q) isa friendship; $q has name $friend-name;
    return { $friend-name };
  ],
};
----

The output of this stage would be:

== Update

=== `delete; insert`

[,typeql]
----
match
  $a isa person, has name $name;
  $name == "Alice";
delete
  has $name of $a;
insert
  $a has name "Alan";
----

=== Atomic updates with `update`

An attribute ownership or a roleplayer with cardinality `@card(1)` can be updated using an `update` stage.

[,typeql]
----
match
  $a isa person, has name "Alice";
update
  $a has name "Alan";
----

Unlike an `insert` stage, an `update` stage does not add a second ownership of `name` to `$a`, but rather replaces the existing ownership of
`name` with the new one.

== Delete

=== Deleting instances

[,typeql]
----
match
  $a isa person, has name "Alice";
delete
  $a;
----

[NOTE]
====
Non-`@independent` attributes are deleted automatically when the last instance that owns them is deleted.
====

=== Deleting ownerships and roleplayers

[,typeql]
----
match
  $a isa person, has name $name == "Alice";
delete
  has $name of $a;
----
