= CRUD

CRUD operations create, read, update, and delete data in the TypeDB database.

== Create

When a database is created, it contains no data. The first step to building a rich, structured knowledge base is to insert data into the database.

=== `insert`

In TypeDB, data is created using `insert` stages in *write pipelines*. To insert data, open a write-capable transaction (i.e. `write` or `schema`).

For these examples, consider the following schema:

[,typeql]
.Sample schema
----
define
  entity order,
    owns status,
    plays friendship:friend;
  relation friendship,
    relates friend;
  attribute status,
    value string;
----

If `insert` is the first stage in a pipeline, it runs just once and outputs a single row containing the newly created instances.

An example command to insert two people and a friendship between them would be:

[,typeql]
.Alice 🤝 Bob
----
insert
  $a-name isa name "Alice";
  $b-name isa name "Bob";
  $a isa person, has $a-name;
  $b isa person, has $b-name;
  $f isa friendship, links (friend: $a, friend: $b);
----

The output row will contain the newly created instances:

[,typeql]
----
   -------------
    $a      | isa person, iid 0x1e00000000000000000000
    $a-name | isa name "Alice"
    $b      | isa person, iid 0x1e00000000000000000001
    $b-name | isa name "Bob"
    $f      | isa friendship, iid 0x1f00000000000000000000
   -------------
----

When an `insert` stage is preceded by other stages (most commonly `match`), the `insert` stage will run once for each input row, and its
output rows will contain the newly created instances as well as the contents of the input rows.

In this example, Alice and Bob are already in the database, and we want to create a friendship between them.

[,typeql]
.Alice 🤝 Bob, v2
----
match
  $a isa person, has name "Alice";
  $b isa person, has name "Bob";
insert
  $f isa friendship, links (friend: $a, friend: $b);
----

For more detailed information on `insert` stages, see the xref:{page-version}@typeql::pipelines/insert.adoc[Insert query stage documentation in the
TypeQL reference].

=== `put`

Another way to insert data is by using a `put` query.

[,typeql]
----
put
  $a isa person, has name "Alice";
  $b isa person, has name "Bob";
  $f isa friendship, links (friend: $a, friend: $b);
----

This query will attempt to match the given patterns against existing data in the database. If the patterns are matched, the query stage will
retrieve the matched instances and make no changes to the database. If the patterns are _not_ matched, however, the query will execute as if
it were an `insert` stage.

[IMPORTANT]
====
`put` stages are all or nothing! For example, even if a `person` with the name `"Alice"` already exists in the database, if there is
no `person` with the name `"Bob"`, or no friendship between the two, the query will insert a new `person` with the name `"Alice"`, a new
`person` with the name `"Bob"`, and a new friendship between them.
====

For more detailed information on `put` stages, see the xref:{page-version}@typeql::pipelines/put.adoc[Put query stage documentation in the
TypeQL reference].

=== Bulk loading

You may already have a large amount of data that you wish to insert into the newly created database.
This section contains some suggestions on how to do that efficiently.

==== Query batching

There is a cost associated with opening and committing transactions. If you have a large number of queries to execute, you should consider
batching more than one query into a single transaction.

Care should be taken to ensure that the batches of queries are not too large. Long-running transactions can cause slowdowns as large sets of
data are validated against each other during commits.

As a rule of thumb, we recommend around 100-1000 inserts per transaction, though the exact numbers vary application to application.

==== Deferred resolution

Queries are performed asynchronously: when a query request is sent from the driver, the returned value is a _promise_ that needs to be
resolved to obtain the actual result.

This allows the driver to send multiple queries to the server to be executed concurrently. The suggested way to take advantage of this is to
open a number of concurrent transactions and send a batch of queries to each of them.

[tabs]
.Example
====
Python::
+
--
[,python]
----
# TODO
----
--

Rust::
+
--
The `futures` crate provides the way to concurrently execute tasks in batches of specified size.

[,rust]
----
let batch_tasks = batches.into_iter().map(|batch| {
    let driver = driver.clone();
    async move {
        let tx = driver.transaction(typedb_driver::TransactionType::Write).await?;
        let result = tx.query(batch_query(batch)).await?;
        tx.commit().await?;
        Ok(result)
    }
});
let results: Vec<typedb_driver::Result> =
    stream::iter(batch_tasks).buffered(parallelization).collect().await;
----
--
====


==== Other considerations


== Read

To retrieve data from the database, open a transaction (all transaction types are read-capable, `read`, `write`, and `schema`).

=== `fetch`

A `fetch` stage converts each input row into a JSON-like document. The body of a `fetch` stage describes the structure of the document.

[,typeql]
----
match
  $p isa person;
fetch {
  "name": $p.name,
  "friends": [
    match ($p, $q) isa friendship; $q has name $friend-name;
    return { $friend-name };
  ],
};
----

The output of this stage would be:

== Update

=== `delete; insert`

[,typeql]
----
match
  $a isa person, has name $name;
  $name == "Alice";
delete
  has $name of $a;
insert
  $a has name "Alan";
----

=== Atomic updates with `update`

An attribute ownership or a roleplayer with cardinality `@card(1)` can be updated using an `update` stage.

[,typeql]
----
match
  $a isa person, has name "Alice";
update
  $a has name "Alan";
----

Unlike an `insert` stage, an `update` stage does not add a second ownership of `name` to `$a`, but rather replaces the existing ownership of
`name` with the new one.

== Delete

=== Deleting instances

[,typeql]
----
match
  $a isa person, has name "Alice";
delete
  $a;
----

[NOTE]
====
Non-`@independent` attributes are deleted automatically when the last instance that owns them is deleted.
====

=== Deleting ownerships and roleplayers

[,typeql]
----
match
  $a isa person, has name $name == "Alice";
delete
  has $name of $a;
----
