= Quickstart
:keywords: start, learn, typedb, typeql, tutorial, quickstart, console, studio, database, create, insert, query
:page-aliases: typedb::quickstart-guide.adoc, typedb::quickstart.adoc
:pageTitle: Quickstart guide
:summary: Learn how to create a TypeDB database, load schema and data, perform queries.
:tabs-sync-option:
:experimental:

This Quickstart guide shows how to set up a TypeDB database and run queries using
xref:manual::studio.adoc[TypeDB Studio].

include::home::overview.adoc[tag=rust-rewrite]

== Run TypeDB

To start TypeDB, select the TypeDB edition below and follow the instructions.

[tabs]
====
Cloud::
+
--
// tag::cloud-run[]
Log in to https://cloud.typedb.com/[TypeDB Cloud,window=_blank] and create a new deployment on the Deployments page.
// end::cloud-run[]

// tag::self-hosted-run[]
For self-hosted TypeDB Cloud installation and setup,
see the xref:install/cloud-self-hosted.adoc[Self-hosted deployment] page.
// end::self-hosted-run[]
--

Core::
+
--
TypeDB Core needs to be xref:home::install/core.adoc[installed] first.

include::home::install/core.adoc[tag=core-run]

include::home::partial$docker.adoc[tags=run]
--
====

[#_typedb_studio]
== Connect to TypeDB
// tag::run_studio[]
There are several ways to connect to a running TypeDB server. In this quickstart guide we will use *TypeDB Studio*, a standalone TypeDB Client with GUI that needs to be
xref:home::install/studio.adoc[installed] and launched separately from a TypeDB server.

Find the TypeDB Studio binary and run it.
Click btn:[Connect to TypeDB] on the right side of the top toolbar.
// end::run_studio[]
include::manual::studio.adoc[tag=connect_studio]

=== Select a project folder

To enable TypeDB Studio's IDE functionality, you now need to select a project folder to store your project files. Select a xref:manual::studio.adoc#_select_a_project_directory[project folder]
by clicking either btn:[Open Project] in the *Project* panel or
image:home::studio-icons/svg/studio_projects.svg[width=24] Open Project Directory button in the top toolbar.

[#_create_a_database]
== Create a new database

Create a database to play with:

. Click the image:home::studio-icons/svg/studio_dbs.svg[width=24] btn:[database icon] in the top toolbar.
. Enter a name for a new database, for example, `typedb-1`, and click btn:[Create].
. Select the new database from the dropdown to the right of the database icon.

[#_define_a_schema]
== Define a schema

A new database needs a schema before we can load any data:

. Ensure the Session toggle (`schema` / `data`) is set to `schema` and
  the Transaction toggle (`write` / `read`) is set to `write`.
. Open a new tab and copy-paste the following Define query:
+
[,typeql]
----
include::attachment$crash-course-schema.tql[]
----
. Click the image:home::studio-icons/svg/studio_run.svg[width=24] btn:[Run Query] button.
. When the query has completed, click image:home::studio-icons/svg/studio_check.svg[width=24] btn:[Commit Transaction].

The schema has been defined, data can be inserted into the database.

[#_load_data]
== Load data

Let's insert sample data for our newly defined schema:

. Ensure the Session toggle is set to `data` and the Transaction toggle is set to `write`.
. Open a new tab and copy-paste the following Insert queries:
+
[,typeql]
----
include::attachment$crash-course-data.tql[]
----
. Execute all queries in the file by clicking the image:home::studio-icons/svg/studio_run.svg[width=24]
btn:[Run Query] button.
. When the queries have completed, click image:home::studio-icons/svg/studio_check.svg[width=24] btn:[Commit Transaction].

Assuming there were no errors in the process, the data is persisted in the database.
Now the database is ready to be queried.

== Read data

Let's send a Fetch query to retrieve all types of action permitted for a particular user on a particular file:

[,typeql]
----
match
$user isa user, has name "Bob";
$file isa file, has path "README.md";
(subject: $user, object: $file, action: $act) isa permission;
fetch
$act: name;
----

The query above uses a pattern to match a user with the name `Bob` and a file with the path `README.md`
that are playing roles of `subject` and `object` respectively in a relation of the type `permission`.
For any matched data, it fetches the name of action in the relation.

== Update data

To update data in a database, we need to match the existing data before deleting and replacing some of it.
Let's find a quickstart file that a user named `Alex` has access to and replace the file's path with a new one:

[,typeql]
----
match
$u1 isa user, has name "Bob";
$f2 isa file, has path "docs/quickstart-guide.adoc";
$read isa action, has name "read";
$pe (subject:$u1, object:$f2, action:$read) isa permission, has updated $date;
$write isa action, has name "write";
delete
$pe (action: $read);
$pe has $date;
insert
$pe (action: $write);
$pe has updated 2024-05-15T11:04:36;
----

The query matches the user, file, action types, and the `permission` relation for the user to read the file,
then deletes from the relation a roleplayer reference to the `read` action for the `action` role,
only to replace it with the `write` action.
The same query also replaces the `updated` attribute owned by the relation with a newer one.
After commiting the transaction,
the updated information is persisted in the database and becomes available for querying.

[#_learn_more]
== What's next?

Continue to explore interesting queries with a Crash course in TypeDB or see other sections of TypeDB documentation:

[cols-2]
--
.xref:home::crash-course.adoc[]
[.clickable]
****
Continue this quickstart guide and learn the basics of TypeDB.
****

.xref:learn::overview.adoc[]
[.clickable]
****
A comprehensive learning course for TypeDB comprising several individual lessons.
****

.xref:manual::overview.adoc[TypeDB manual]
[.clickable]
****
A collection of practice-oriented how-to guides for TypeDB.
****

.xref:drivers::overview.adoc[TypeDB drivers]
[.clickable]
****
Information on language-specific TypeDB drivers with native API.
****
--
