= Data pipelines
:page-aliases: {page-version}@typeql::pipelines.adoc

This reference covers the usage of data pipelines in TypeQL. Data pipeline read and modify data in stages.

[[pipeline_kinds]]
== Pipeline kinds

* A *write pipeline* may comprise stages that modify data in the database (such as `insert` or `delete`).
* A *read pipeline* only comprises stages that read data from the database but do not modify it.

[[combining_stages]]
== Combining stages

Each stage receives the stream of rows output by the previous stage, and only the variables in those rows are available to it.
Stages may be chained in any order permitted by their kind, and a stage kind may appear more than once -- for instance, a `match` may follow a `reduce`:

[,typeql]
----
match
  $user isa user;
  friendship($user, $friend);
reduce $friend-count = count groupby $user;
match
  $friend-count >= 2;
  $user has username $username;
select $username, $friend-count;
----

Here the second `match` sees only `$user` and `$friend-count`, the output of the `reduce`.
See xref:{page-version}@typeql-reference::pipelines/reduce.adoc#_using_reduced_values_in_later_stages[Using reduced values in later stages].

== Data manipulation stages

[cols-3]
--
.xref:{page-version}@typeql-reference::pipelines/match.adoc[]
[.clickable]
****
Used to match existing data instances in the database.
****

.xref:{page-version}@typeql-reference::pipelines/fetch.adoc[]
[.clickable]
****
Used to format the output of a data pipeline into JSON.
****

.xref:{page-version}@typeql-reference::pipelines/insert.adoc[]
[.clickable]
****
Used to add new data instances into the database.
****

.xref:{page-version}@typeql-reference::pipelines/delete.adoc[]
[.clickable]
****
Used to remove existing data instances from the database.
****

.xref:{page-version}@typeql-reference::pipelines/update.adoc[]
[.clickable]
****
Used to modify existing data instances in the database.
****

.xref:{page-version}@typeql-reference::pipelines/put.adoc[]
[.clickable]
****
Used to add new data instances to the database if they do not already exist.
****
--

== Stream manipulation stages

[cols-3]
--
.xref:{page-version}@typeql-reference::pipelines/select.adoc[]
[.clickable]
****
Used to keep specified variables for each element of the data stream and remove the rest.
****

.xref:{page-version}@typeql-reference::pipelines/require.adoc[]
[.clickable]
****
Used to remove elements from the data stream that do not contain specified optional variables.
****

.xref:{page-version}@typeql-reference::pipelines/distinct.adoc[]
[.clickable]
****
Used to remove duplicate elements from the data stream.
****

.xref:{page-version}@typeql-reference::pipelines/sort.adoc[]
[.clickable]
****
Used to order the elements of the data stream based on the value of specified variables.
****

.xref:{page-version}@typeql-reference::pipelines/limit.adoc[]
[.clickable]
****
Used to keep a specified number of elements of the data stream and remove the rest.
****

.xref:{page-version}@typeql-reference::pipelines/offset.adoc[]
[.clickable]
****
Used to remove a specified number of elements from the data stream.
****

.xref:{page-version}@typeql-reference::pipelines/reduce.adoc[]
[.clickable]
****
Used to perform reduction operations on the data stream according to specified groupings.
****
--

== Preamble stage

[cols-1]
--
.xref:{page-version}@typeql-reference::pipelines/with.adoc[]
[.clickable]
****
Used to define functions on an ad-hoc basis for use in the data pipeline.
****
--

== Query terminator

[cols-1]
--
.xref:{page-version}@typeql-reference::pipelines/end.adoc[]
[.clickable]
****
When writing multiple queries together (for example in TypeQL console scripts), used to explicitly mark the end of a query.
****
--
