= Enterprise deployment
:keywords: setup, getting started, typedb, download, install, server, linux, mac, windows, docker
:longTailKeywords: typeDB enterprise on linux, typeDB enterprise on mac, typeDB enterprise on windows, start typeDB enterprise, run typeDB enterprise
:pageTitle: Install and Run TypeDB Enterprise
:summary: Install and run the TypeDB Enterprise on Linux, Mac or Windows.
:experimental:
:!example-caption:

TypeDB Enterprise is a commercial offering that provides a production-grade experience -- high-availability, scalability,
and security. A license can be obtained from our mailto:sales@vaticle.com[sales team].

== System Requirements

TypeDB Enterprise runs on macOS, Linux, and Windows.
The only requirement is Java v.11+ (http://openjdk.java.net/install/[OpenJDK] or
https://www.oracle.com/java/technologies/downloads/#java11[Oracle Java]).

== Download and Install

TypeDB Enterprise is distributed and installed separately from TypeDB Core.

You can install it as a standalone server with <<_using_docker,Docker>> or manual
<<_manual_download_and_installation,download and installation>>.
A cluster of TypeDB Enterprise servers you can deploy either
<<_deploying_manually,manually>> or via <<_deploying_with_kubernetes,Kubernetes>>.

[#_using_docker]
=== Using Docker

TypeDB Enterprise Docker image is stored in a private repository.
Make sure to use `docker login` first, to get correct authentication.

To pull the TypeDB Enterprise Docker image, run:

[,bash]
----
docker pull vaticle/typedb-enterprise:latest
----

Use `docker run` to create a new container with the downloaded image.
By default, a TypeDB Enterprise server is expected to be running on port `1729`.
To ensure that data is preserved even when the container is killed or restarted, use a Docker volume:

[,bash]
----
docker run --name typedb -d -v $(pwd)/db/:/opt/ -p 1729:1729 vaticle/typedb-enterprise:latest
----

==== Start and Stop TypeDB Enterprise in Docker

To start the Docker container:

[,bash]
----
docker start typedb
----

To check the containers running:

[,bash]
----
docker ps
----

To stop the Docker container:

[,bash]
----
docker stop typedb
----

[#_manual_download_and_installation]
=== Manual download and installation

Download the https://repo.vaticle.com/#browse/browse:private-artifact[latest release], unzip it in a
location on your machine that is easily accessible via terminal.

If TypeDB Enterprise doesn't have a distribution you need, please open an issue
https://github.com/vaticle/typedb/issues[on GitHub].

==== Start and Stop TypeDB Enterprise manually

To start TypeDB Enterprise manually:

1. Navigate into the directory with unpacked files of TypeDB Enterprise.
2. Run:
+
[,bash]
----
./typedb enterprise
----

Now TypeDB Enterprise should show a welcome screen with its version, address, and bootup time.

To stop TypeDB Enterprise:

Close the terminal or press kbd:[Ctrl+C].

== Connecting

To check whether TypeDB Enterprise is working and interact with it, you can connect to it with any
xref:clients::overview.adoc[TypeDB Client].

You can use xref:clients:ROOT:console.adoc[] from your TypeDB Enterprise directory:

[,bash]
----
./typedb console --enterprise 127.0.0.1:1729 --username admin --password
----

To run TypeDB Console from a Docker container, run:

[,bash]
----
docker exec -ti typedb-enterprise bash -c '/opt/typedb-enterprise-all-linux-x86_64/typedb console --enterprise 127.0.0.1:1729 --username admin --password'
----

[#_deploying_manually]
== Deploying manually

While it's possible to run TypeDB Enterprise in a single-server mode, a truly highly available and fault-tolerant
production-grade setup includes setting up multiple servers to connect and form a cluster.
At any given point in time, one of those servers acts as a
xref:typedb::admin/ha.adoc#_primary_replica_failover[leader] and the others are followers.
Increasing the number of servers increases the
cluster's tolerance to failure: to tolerate N servers failing, a cluster needs to consist of `2N + 1` servers.
This section describes how you can set up a 3-server cluster (in this case,
one server can fail with no data loss).

Each TypeDB Enterprise server in a cluster binds to three ports:
a client port which TypeDB Drivers connect to (`1729` by default), and two server ports
(`1730` and `1731`) for server-to-server communication.

For this tutorial, it's assumed that all three servers are on the same virtual network, have the relevant ports open,
with no firewall interference, and the servers have IP addresses `10.0.0.1`, `10.0.0.2` and `10.0.0.3` respectively.

[NOTE]
====
If you're using a single machine to host all nodes,
it may be easier to use `localhost` or `127.0.0.1` address, but prefix the port with the node number; this way the
ports `1729`, `1730`, `1731` would turn into:

* `11729`, `11730`, `11731`;
* `21729`, `21730`, `21731`;
* `31729`, `31730`, `31731`.
====

=== Starting

TypeDB servers working in a cluster shall be configured specifically to know all servers in the cluster (peers).
This could be done through `peers` key in the server config, or with command-line arguments when starting the server.
Command-line arguments have priority over config file.

See below an example of how 3-server TypeDB Enterprise would be started on three separate machines to be in a cluster.

.Server #1
====
The first machine with the IP address of `10.0.0.1`.

To run TypeDB server #1:

[,bash]
----
./typedb enterprise \
    --server.address=10.0.0.1:1729 \
    --server.internal-address.zeromq=10.0.0.1:1730 \
    --server.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-1.address=10.0.0.1:1729 \
    --server.peers.peer-1.internal-address.zeromq=10.0.0.1:1730 \
    --server.peers.peer-1.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-2.address=10.0.0.2:1729 \
    --server.peers.peer-2.internal-address.zeromq=10.0.0.2:1730 \
    --server.peers.peer-2.internal-address.grpc=10.0.0.2:1731 \
    --server.peers.peer-3.address=10.0.0.3:1729 \
    --server.peers.peer-3.internal-address.zeromq=10.0.0.3:1730 \
    --server.peers.peer-3.internal-address.grpc=10.0.0.3:1731
----
====

.Server #2
====
The first machine with the IP address of `10.0.0.2`.

To run TypeDB server #2:

[,bash]
----
./typedb enterprise \
    --server.address=10.0.0.2:1729 \
    --server.internal-address.zeromq=10.0.0.2:1730 \
    --server.internal-address.grpc=10.0.0.2:1731 \
    --server.peers.peer-1.address=10.0.0.1:1729 \
    --server.peers.peer-1.internal-address.zeromq=10.0.0.1:1730 \
    --server.peers.peer-1.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-2.address=10.0.0.2:1729 \
    --server.peers.peer-2.internal-address.zeromq=10.0.0.2:1730 \
    --server.peers.peer-2.internal-address.grpc=10.0.0.2:1731 \
    --server.peers.peer-3.address=10.0.0.3:1729 \
    --server.peers.peer-3.internal-address.zeromq=10.0.0.3:1730 \
    --server.peers.peer-3.internal-address.grpc=10.0.0.3:1731
----
====

.Server #3
====
The first machine with the IP address of `10.0.0.3`.

To run TypeDB server #3:

[,bash]
----
./typedb enterprise \
    --server.address=10.0.0.3:1729 \
    --server.internal-address.zeromq=10.0.0.3:1730 \
    --server.internal-address.grpc=10.0.0.3:1731 \
    --server.peers.peer-1.address=10.0.0.1:1729 \
    --server.peers.peer-1.internal-address.zeromq=10.0.0.1:1730 \
    --server.peers.peer-1.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-2.address=10.0.0.2:1729 \
    --server.peers.peer-2.internal-address.zeromq=10.0.0.2:1730 \
    --server.peers.peer-2.internal-address.grpc=10.0.0.2:1731 \
    --server.peers.peer-3.address=10.0.0.3:1729 \
    --server.peers.peer-3.internal-address.zeromq=10.0.0.3:1730 \
    --server.peers.peer-3.internal-address.grpc=10.0.0.3:1731
----
====

The above example assumes
the application (TypeDB Client) accessing TypeDB Enterprise resides on the same private network as the cluster.

If this is *not* the case,
TypeDB Enterprise also supports using different IP addresses for client and server communication.

.Example of using separate network for client connection
====

The relevant external hostname should be passed as arguments using the `--server.address` and
`--server.peers` flags as below.

[,bash]
----
./typedb enterprise \
    --server.address=external-host-1:1729 \
    --server.internal-address.zeromq=10.0.0.1:1730 \
    --server.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-1.address=external-host-1:1729 \
    --server.peers.peer-1.internal-address.zeromq=10.0.0.1:1730 \
    --server.peers.peer-1.internal-address.grpc=10.0.0.1:1731 \
    --server.peers.peer-2.address=external-host-2:1729 \
    --server.peers.peer-2.internal-address.zeromq=10.0.0.2:1730 \
    --server.peers.peer-2.internal-address.grpc=10.0.0.2:1731 \
    --server.peers.peer-3.address=external-host-3:1729 \
    --server.peers.peer-3.internal-address.zeromq=10.0.0.3:1730 \
    --server.peers.peer-3.internal-address.grpc=10.0.0.3:1731
----

And so on for servers #2 and #3.

In this case, port `1729` would need to be open to public and clients would use the `external-host-1`, `external-host-2`
and `external-host-3` hostnames to communicate with TypeDB Enterprise; inter-server communication would be done over a
private network using ports `1730` and `1731`.
====

=== Stopping

Stopping TypeDB Enterprise is done the same way as on a single server:
to stop TypeDB Enterprise, close the terminal or press kbd:[Ctrl+C].
All nodes must be shut down independently in the same way.

[#_deploying_with_kubernetes]
== Kubernetes

To deploy a TypeDB Enterprise cluster with Kubernetes, we can use https://helm.sh/[Helm] package manager.

include::partial$kubernetes.adoc[leveloffset=+1]
