= TypeDB REST API

The TypeDB REST API can be used to perform database management, user management, transaction management, and querying operations through HTTP.

== Server configuration

TypeDB server by runs both a gRPC (standard for most of the client applications) and an HTTP endpoint by default. Both endpoints have common authentication and xref:{page-version}@manual::configure/encryption.adoc[encryption settings]. Additionally, it is possible to disable the HTTP endpoint and change its default port.

Please visit xref:{page-version}@manual::configure/server.adoc#_command_line_arguments[Server configuration] for the configuration specification.

== Access the API

Mostly all methods require Token-based authorization. These temporary tokens can be generated through a `POST` request to `localhost:8000/v1/signin`. Provide your TypeDB user credentials in the request's body.

Change the xref:{page-version}@manual::configure/server.adoc#_command_line_arguments[`server.authentication.token_ttl_seconds`] parameter in the server's configuration to modify the time the tokens will remain valid before a new sign in request is required.

# TODO: Example! make everything below...

. Make a `POST` request to `\https://cloud.typedb.com/api/auth`,
with the client ID and client secret in a Basic authorization header, separated by a `:`.
+
[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/auth \
    --header 'Authorization: Basic {CLIENT-ID}:{CLIENT-SECRET}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/auth"

headers = {
    "Authorization": "Basic {CLIENT-ID}:{CLIENT-SECRET}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("https://cloud.typedb.com/api/auth")
        .header(reqwest::header::AUTHORIZATION, "Basic {CLIENT_ID}:{CLIENT_SECRET}")
        .send().await;
    Ok(())
}
----
====
The response body will be your access token.
+
[NOTE]
====
For security, your access token will expire after 1 hour.
====
. Make an API request to list clusters in the project you selected for your API token.
The example below targets the `default` project in an organization called `my-org`.
You will use the access token you generated in the previous step to authenticate this request.
+
[tabs]
====
curl::
+
[source,console]
----
curl --request GET \
    --url https://cloud.typedb.com/api/org/ORG_ID/projects/PROJECT_ID/clusters \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/org/my-org/projects/default/clusters"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("https://cloud.typedb.com/api/org/my-org/projects/default/clusters")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====
It will return information about the clusters in a JSON format, as below
+
[source,json]
----
[
    {
        "id":"my-cluster",
        "serverCount":1,
        "storageSizeGB":10,
        "isFree":true,
        "status":"running",
        "createdAt":1738256490070,
        "organizationID":"my-org",
        "projectID":"default",
        "version":"3.0.6",
        "provider":"gcp",
        "region":"europe-west2",
        "machineType":"c2d-highcpu-2",
        "storageType":"standard-rwo",
        "servers": [
            {
              "address": "abc123-0.cluster.typedb.com:80",
              "status": "running"
            }
        ]
    }
]
----

== Next Steps

Now that you know how to list the clusters in your project from the API,
you can explore TypeDB Cloud further, either through further API use or back on the website.

[cols-2]
--
.https://cloud.typedb.com[TypeDB Cloud,window=_blank]
[.clickable]
****
Head back to TypeDB Cloud to keep exploring there.
****

.xref:{page-version}@manual::cloud/api/reference.adoc[]
[.clickable]
****
View the API reference for more detail on what you can do with it.
****
--
