= Node.js API reference
:Summary: API Reference of TypeDB Client Node.js.
:keywords: typedb, client, node.js
:longTailKeywords: typedb node.js client, typedb client node.js, client node.js, node.js client
:pageTitle: Node.js API Reference
:templatePath: 02-clients/references/
:toc: true

== Query section

{% include api/generic.html data=site.data.03_client_api.references.typedb language="javascript" %}

=== Client methods

{% include api/generic.html data=site.data.03_client_api.references.client language="javascript" %}

=== Session methods

{% include api/generic.html data=site.data.03_client_api.references.session language="javascript" %}

=== Options methods

{% include api/generic.html data=site.data.03_client_api.references.options language="javascript" %}

=== Transaction methods

{% include api/generic.html data=site.data.03_client_api.references.transaction language="javascript" %}

=== Query methods

{% include api/generic.html data=site.data.03_client_api.references.query_manager language="javascript" %}

== Response section

{% include api/answers.html data=site.data.03_client_api.references.answer language="javascript" %}

=== Concept methods

`Concept` is inherited and extended by <<type-methods,`Type`>> and <<data-methods,`Data`>>.

{% include api/generic.html data=site.data.04_concept_api.references.concept language="javascript" %}

{% include api/generic.html data=site.data.04_concept_api.references.concept_manager language="javascript" %}

=== Future methods

{% include api/generic.html data=site.data.03_client_api.references.query_future language="javascript" %}

=== Type methods

`Type` has all the <<concept-methods,`Concept` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.type language="javascript" %}

==== ThingType methods

// #todo Update the Thing keyword as soon as API implementation update will change it -

`ThingType` has all the <<type-methods,`Type` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.thing_type language="javascript" %}

==== EntityType methods

`EntityType` has all the <<thingtype-methods,`ThingType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.entity_type language="javascript" %}

==== RelationType methods

`RelationType` has all the <<thingtype-methods,`ThingType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.relation_type language="javascript" %}

===== RoleType methods

`RoleType` has all the <<type-methods,`Type` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.role_type language="javascript" %}

==== AttributeType methods

`AttributeType` has all the <<thingtype-methods,`ThingType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.attribute_type language="javascript" %}

===== BooleanAttributeType methods

`BooleanAttributeType` has all the <<attributetype-methods,`AttributeType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.boolean_attribute_type language="javascript" %}

===== LongAttributeType methods

`LongAttributeType` has all the <<attributetype-methods,`AttributeType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.long_attribute_type language="javascript" %}

===== DoubleAttributeType methods

`DoubleAttributeType` has all the <<attributetype-methods,`AttributeType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.double_attribute_type language="javascript" %}

===== StringAttributeType methods

`StringAttributeType` has all the <<attributetype-methods,`AttributeType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.string_attribute_type language="javascript" %}

===== DateTimeAttributeType methods

`DateTimeAttributeType` has all the <<attributetype-methods,`AttributeType` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.datetime_attribute_type language="javascript" %}

=== Rule methods

{% include api/generic.html data=site.data.04_concept_api.references.rule language="javascript" %}

{% include api/generic.html data=site.data.04_concept_api.references.logic_manager language="javascript" %}

=== Data methods

`Data` has all the <<concept-methods,`Concept` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.thing language="javascript" %}

==== Entity methods

`Entity` has all the <<data-methods,`Data` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.entity language="javascript" %}

==== Attribute methods

`Attribute` has all the <<data-methods,`Data` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.attribute language="javascript" %}

==== Relation methods

`Relation` has all the <<data-methods,`Data` methods>> plus what follows.

{% include api/generic.html data=site.data.04_concept_api.references.relation language="javascript" %}
