= Undefine query
:Summary: Undefine schema types and rules with TypeQL.
:keywords: typeql, schema, model, undefine, delete, remove, truncate, type, rule
:pageTitle: Undefine query

An Undefine query removes type and rule definition from a schema.
For a practical guide on how to send an Undefine query to TypeDB,
see the xref:{page-version}@manual::defining/undefine.adoc[] page of the TypeDB Manual.

// For more information on the limitations of schema manipulation, see the
// xref:{page-version}@home::acid.adoc#_schema_integrity[Schema integrity enforcement].

[#_syntax]
== Syntax

// tag::syntax[]
An Undefine query consists of a single `undefine` clause and always starts with the `undefine` keyword.

Undefine queries are written in TypeQL with the following syntax:

[,typeql]
----
undefine <schema_definitions>
----

Where `<schema_definitions>` are valid TypeQL schema-specific statements:
xref:{page-version}@typeql::statements/sub.adoc[],
xref:{page-version}@typeql::statements/abstract.adoc[],
xref:{page-version}@typeql::statements/owns.adoc[],
xref:{page-version}@typeql::statements/value.adoc[],
xref:{page-version}@typeql::statements/regex.adoc[],
xref:{page-version}@typeql::statements/relates.adoc[],
xref:{page-version}@typeql::statements/plays.adoc[],
xref:{page-version}@typeql::statements/rule.adoc[],
and annotations: xref:{page-version}@typeql::statements/key.adoc[] and xref:{page-version}@typeql::statements/unique.adoc[]. Schema statements in a `undefine` clause can't use any variables or values, except for xref:statements/rule.adoc[rules].
// end::syntax[]

// For more information on defining rules, see the xref:schema/rule-definitions.adoc[] page.
// For more information on defining types, ownerships, and roleplayers,
// see below and the xref:{page-version}@typeql::schema/type-definitions.adoc[].

== Behavior

// tag::behavior[]
An Undefine query deletes the parts of the schema specified in its `undefine` clause, including types, rules, roles, and ownerships. Undefining a type also undefines all ownerships of attribute types and all roles of that type. 

=== Query execution

[#_undefine_a_type_with_a_subtype]
For an undefine query to succeed, the following must be satisfied:

* Types that are to be deleted must _exist_.
* Types that are to be deleted can have neither _subtypes_ nor _instances of data_. 
* An undefine query must result in a _valid_ schema state.

Undefining the same definition twice will result in an error.

=== Query response

Undefine queries return a promise of an empty response.
// end::behavior[]

== Undefine types

include::{page-version}@typeql::partial$iam-database-links.adoc[]

Use a schema statement to delete from a schema in an Undefine query:

.Undefine type example
[,typeql]
----
undefine

number sub attribute;
database owns name;
----

The above example deletes from a schema the attribute type `number` and ownership of the attribute type `name` by the
entity type `database`.

== Undefine rules

include::{page-version}@typeql::partial$iam-database-links.adoc[]

To delete a rule, use the `rule` keyword with rule's label:

.Undefine a rule example
[,typeql]
----
undefine

rule add-view-permission;
----

== Learn more

[cols-2]
--
.xref:{page-version}@academy::5-defining-schemas/index.adoc[]
[.clickable]
****
Learn more about defining a schema in TypeDB Academy.
****

.xref:{page-version}@manual::defining/undefine.adoc[]
[.clickable]
****
See how to send an Undefine query to TypeDB.
****
--
