= Lesson 3: Reading data
:page-aliases: learn::3-reading-data/3-reading-data.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to read pre-inserted data in the sample database using *Fetch queries*. We'll begin by seeing how we can retrieve *entities* and *relations* in a similar way to how we do with relational databases. We'll then see how we can retrieve data in unique ways using TypeDB: by writing declarative *polymorphic* queries, by leveraging *rule inference*, and by retrieving *types* from the schema. Finally, we'll look at a few examples of *type inference* at work by seeing how TypeDB validates queries.

== Recommended prerequisites

* You should complete xref:learn::2-environment-setup/overview.adoc[Lesson 2] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::3-reading-data/3.1-fetching-simple-data.adoc[]
[.clickable]
****
Learn how to retrieve the attributes of entities and relations.
****

.xref:learn::3-reading-data/3.2-fetching-polymorphic-data.adoc[]
[.clickable]
****
Learn how to retrieve data with polymorphic queries.
****

.xref:learn::3-reading-data/3.3-fetching-inferred-data.adoc[]
[.clickable]
****
Learn how to retrieve data generated by rule inference.
****

.xref:learn::3-reading-data/3.4-fetching-schema-types.adoc[]
[.clickable]
****
Learn how to retrieve typing information from the schema.
****

.xref:learn::3-reading-data/3.5-query-validation.adoc[]
[.clickable]
****
Learn about how queries are validated against the schema.
****
--

== Running examples

To run a Fetch query, make sure to use a *data* session and *read* transaction. The examples and exercises featured in this lesson are annotated with one of the following instructions to indicate how they should be run.

image:home::studio-icons/svg/studio_run.svg[width=24] *_Run_*:: *Run* this query. Read transactions do not need to be committed.
image:home::studio-icons/svg/studio_run.svg[width=24] *_Try running_*:: *Run* this query to see the error generated.

For information on how to control sessions, transactions, and queries using TypeDB Studio, refer back to xref:learn::2-environment-setup/2.2-using-typedb-studio.adoc[Lesson 2.2].

== TypeQL keywords introduced

* `match`
* `fetch`
* `attribute`
* `isa`
* `has`
* `entity`
* `relation`
* `isa!`
* `sub`
* `sub!`
* `owns`
* `relates`
* `plays`
