= Response interpretation
:Summary: TypeDB query response interpretation.
:keywords: typeql, query, response, result, answer, concept
:longTailKeywords: typeql response, concept map, typeql variables
:pageTitle: Response interpretation

TypeDB can return a response to a TypeQL query in different formats, depending on a type of query.
The server response will be processed by a TypeDB Client.
TypeDB Client provides classes and methods for different response types respectively. Please
see the table below for mapping of response format to a type of query that has been sent.

[cols="^.^1,^.^4,^.^4"]
|===
| *#* | *Query type* | *Response format*

a| {counter:query_types}
| xref:typeql::data/fetch.adoc[Fetch query]
| Stream/Iterator of *JSON*

a| {counter:query_types}
| xref:typedb::developing/read.adoc#_get[Get query]
| Stream/Iterator of *ConceptMap*

a| {counter:query_types}
| Get query with xref:typeql::data/get.adoc#_aggregation[aggregation]
| *Promise* of *Value*

a| {counter:query_types}
| Get query with xref:typeql::data/get.adoc#_grouping[grouping]
| Stream/Iterator of *ConceptMapGroup*

a| {counter:query_types}
| Get query with xref:typeql::data/get.adoc#_grouping[grouping] and
xref:typeql::data/get.adoc#_aggregation[aggregation]
| Stream/Iterator of *ValueGroup*

a| {counter:query_types}
| xref:typedb::developing/write.adoc#_insert[Insert query]
| Stream/Iterator of *ConceptMap*

a| {counter:query_types}
| xref:typedb::developing/write.adoc#_delete_query[Delete query]
| *Promise* (of empty response)

a| {counter:query_types}
| xref:typedb::developing/write.adoc#_update_query[Update query]
| Stream/Iterator of *ConceptMap*

a| {counter:query_types}
| xref:typedb::developing/defining-schema.adoc#_define_types[Define]
| *Promise* (of empty response)

a| {counter:query_types}
| xref:typedb::developing/defining-schema.adoc#_undefine[Undefine]
| *Promise* (of empty response)

a| {counter:query_types}
| xref:typedb::developing/infer.adoc#_explain_query[Explain]
| Stream/Iterator of *Explanation*
|===

TypeDB driver API methods can be used to process the objects returned: get values of attributes,
get <<_json,JSON>> representation of data, or even get other concepts from a database.

== Expected results

See the table above for an overview of response formats. For more details see the <<_response_formats,Response formats>>
section below.

=== Get query

The ordinary xref:typeql::data/get.adoc[Get query] (without
xref:typeql::data/get.adoc#_aggregation[aggregation] or
xref:typeql::data/get.adoc#_group[grouping]) returns a stream/iterator of a <<_conceptmap,ConceptMap>> objects.

=== Get query with aggregation

The get query with *aggregation* can only return a singular value (aggregated result). Hence, it returns a Promise
object of Value.

Use <<_promise,Promise>> object's method to wait and retrieve the <<_value,Value>> object when it's ready.

=== Get query with grouping

The get query with *grouping* returns a stream/iterator of ConceptMapGroup objects.

Every iteration should return the result as a <<_conceptmapgroup,ConceptMapGroup>> object.

Use ConceptMapGroup object to retrieve <<_conceptmap,ConceptMap>>.

=== Get query with grouping and aggregation

The get query with *grouping* and *aggregation* returns a stream/iterator of a ValueGroup objects.

Every iteration should return the result as a <<_valuegroup,ValueGroup>> object.

Use ValueGroup object to retrieve <<_value,Value>>.

[#_insert_query]
=== Insert query

An insert query returns a stream/iterator of a ConceptMap objects.

Every iteration should return the result as a <<_conceptmap,ConceptMap>> object.

[#_delete_query]
=== Delete query

Delete query can only return a Promise object of a void (empty response).

We can't retrieve any useful data from the Promise object of a delete query.

=== Update (match-delete-insert) query

Similar to an <<_insert_query,insert>> query.

=== Define query

Similar to a <<_delete_query,delete>> query.

=== Undefine query

Similar to a <<_delete_query,delete>> query.

=== Explain

Explain query returns a stream/iterator of an Explanation objects.

For more information on inference explanation please see the xref:developing/infer.adoc[Inferring data] page.

[#_response_formats]
== Response formats

xref:connecting/studio.adoc[TypeDB Studio] and xref:connecting/console.adoc[TypeDB Console] process the
responses automatically to present the results (in GUI and CLI respectively) to the user.

For xref:drivers::overview.adoc#_typedb_drivers[TypeDB drivers]: the specific methods/calls used to interpret the
response depend on the TypeDB driver used.

The following is a very basic description of objects used to interpret the results from the TypeDB query response.
For more information, see the TypeDB driver pages for the
xref:drivers:ROOT:rust/api-reference.adoc[Rust],
xref:drivers:ROOT:python/api-reference.adoc[Python],
xref:drivers:ROOT:java/api-reference.adoc[Java], and
xref:drivers:ROOT:nodejs/api-reference.adoc[Node.js].

[#_conceptmap]
=== ConceptMap

ConceptMap is a special object, made for mapping of variables from a query to concepts in a database. Its methods
provide a way to interact with the concepts.

Usually represents a single solution/answer from a stream of answers for a TypeDB query.

[#_conceptmapgroup]
=== ConceptMapGroup

It's a container for a <<_conceptmap,ConceptMap>> object with an owner.

[#_concept]
=== Concept

Object to represent a type or an instance of a type (data) from a database.

There are separate methods for every built-in type and for instances of every built-in type.

[#_json]
[NOTE]
====
To get
====

[#_value]
=== Value

Value object represents a value.

[#_valuegroup]
=== ValueGroup

ValueGroup object has not only a Value object but also an owner.

[#_promise]
=== Promise

Promise object represents an asynchronous query result to be able to get the value later when query execution completes.

=== Explanation

Explanation is a special object returned as a response to an explain query.
These are used to explain xref:developing/infer.adoc[data inference]. To perform an
xref:developing/infer.adoc#_explain_query[explain query] use `explainables` and `explainable` objects.

== Number of answers

If the query type can return *multiple* results (e.g., a Get query) then the result of such query type is a
*stream/iterator* to iterate through all the results. Even if the actual query of such type returns one result or no
results at all -- it returns a stream/iterator with one or zero iterations respectively.

Query types that can return only a single answer or a void (an empty response) are executed fully asynchronous on the
server. To wait for a query to finish execution, and return its result if there is one, use the `get()` method of the
*Promise* object returned by the query.

== Best practice

=== Asynchronous queries

Invoking a TypeQL query sends it to a TypeDB server, where it will be completed in the background. Local processing
can take place while waiting for responses to be received. Take advantage of these asynchronous queries to mask network
round-trip costs and increase throughput.

For example, if we are performing 10 get queries in a transaction, it's best to send them all to the server before
iterating over any of their answers.
