= TypeDB drivers installation guide

Most drivers are implemented as thin wrappers of the Rust driver.
But every driver is unique in its installation process.
Find installation guides for every driver below.

For Linux OS: the minimum version of `glibc` is `2.25.0`.

include::guides::partial$questions2discord.adoc[]

== Installation

[tabs]
====
Rust::
+
--
Use `cargo` to install TypeDB Rust driver:

.async
[,bash]
----
cargo add typedb-driver
----

By default, the Rust driver works for asynchronous code only. +
To run synchronous code, enable the `sync` feature:

.sync
[,bash]
----
cargo add typedb-driver -F sync
----
--

Python::
+
--
Use `pip` to install TypeDB Python driver:

[,bash]
----
pip install typedb-driver
----
--

Java::
+
--
Add the code below to the `pom.xml` file in the Maven project.
Make sure to replace the `\{version}` placeholder tag with the version of the Java driver you want to install.

[,xml]
----

<repositories>
    <repository>
        <id>repo.vaticle.com</id>
        <url>https://repo.vaticle.com/repository/maven/</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>com.vaticle.typedb</groupId>
        <artifactId>typedb-driver</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----
--

Node.js::
+
--
Use `npm` to install TypeDB Node.js driver:

[,bash]
----
npm install typedb-driver
----
--

C++::
+
--

To install TypeDB C++ driver:

. https://github.com/vaticle/typedb-driver/releases[Download] and extract the latest release of `typedb-driver-cpp-*`
for you OS (`linux`/`mac`/`windows`) and architecture (`x86_64`/`arm64`).
. Include the header file `typedb_driver.hpp` from the `include` directory.
See an example of `CMakeLists.txt` below:
+
.CMakeLists.txt example
[,source]
----
cmake_minimum_required(VERSION 3.27)
project(cpp_driver_test)

set(CMAKE_CXX_STANDARD 17)
link_directories(${PROJECT_SOURCE_DIR}/lib)
include_directories(${PROJECT_SOURCE_DIR}/include)

add_executable(cpp_driver_test typedb_test.cpp)
IF (WIN32)
    target_link_libraries(cpp_driver_test ${PROJECT_SOURCE_DIR}/lib/typedb-driver-cpp.if.lib)
ELSE()
    target_link_libraries(cpp_driver_test typedb-driver-cpp)
ENDIF()
----
--
====

== Additional resources

See our https://github.com/vaticle/typedb-driver/tree/development/rust[GitHub repository,window=_blank]
for drivers' source code and issues.
For downloadable artifacts, see the https://github.com/vaticle/typedb-driver/releases[Releases page,window=_blank].

////
[#_rust_driver]
== Rust driver

=== Prerequisites

To use the TypeDB Rust driver, you need a compatible version of TypeDB running.
See the
<<_version_compatibility>> table to check what version you need, depending on the TypeDB version being used.

=== Installation

Use `cargo` to install TypeDB Rust driver:

[tabs]
====
async::
+
--
[,bash]
----
cargo add typedb-driver
----
--

sync::
+
--
[,bash]
----
cargo add typedb-driver -F sync
----
--
====

[#_python_driver]
== Python driver

=== Prerequisites

A compatible version of TypeDB.
See the
<<_version_compatibility>> table to check what version you need, depending on the TypeDB version being used.

=== Installation

Use `pip` to install TypeDB Python driver:

[,bash]
----
pip install typedb-driver
----

.See command for older versions (<2.24.0)
[%collapsible]
====
[,bash]
----
pip install typedb-client
----
====

[#_java_driver]
== Java driver

=== Prerequisites

A compatible version of TypeDB.
See the
<<_version_compatibility>> table to check what version you need, depending on the TypeDB version being used.

=== Add a repository with TypeDB Java driver to Maven

Add the code below to the `pom.xml` file in the Maven project.

[IMPORTANT]
====
Be sure to replace the `\{version}` placeholder tag with the version of the Java driver we want to install.
====

[,xml]
----

<repositories>
    <repository>
        <id>repo.vaticle.com</id>
        <url>https://repo.vaticle.com/repository/maven/</url>
    </repository>
</repositories>
<dependencies>
<dependency>
    <groupId>com.vaticle.typedb</groupId>
    <artifactId>typedb-driver</artifactId>
    <version>{version}</version>
</dependency>
</dependencies>
----

If we want to depend on snapshot versions of Client Java, by referring to the GitHub commit `sha`, we can add our
snapshot repository to our list of Maven repositories.

[,xml]
----

<repositories>
    <repository>
        <id>repo.vaticle.com.snapshot</id>
        <name>repo.vaticle.comai</name>
        <url>https://repo.vaticle.com/repository/maven-snapshot/</url>
    </repository>
</repositories>
----

=== (Optional) Logging setup

By default, the Java driver uses Logback to print errors and debugging info to standard output. As it is quite verbose,
use the following steps to set the minimum log level to `ERROR`:

. Create a file in the `resources` path (`src/main/resources` by default in a Maven project) named `logback.xml`.
. Copy the following document into the `logback.xml`:

[,xml]
----

<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="ERROR">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
----

[#_node_js_driver]
== Node.js driver

=== Prerequisites

A compatible version of TypeDB.
See the
<<_version_compatibility>> table to check what version you need, depending on the TypeDB version being used.

=== Installation

Use `npm` to install TypeDB Node.js driver:

[,bash]
----
npm install typedb-driver
----

.See command for older versions (<2.24.0)
[%collapsible]
====
[,bash]
----
npm install typedb-client
----
====

[#_cpp_driver]
== C++ driver

=== Prerequisites

A compatible version of TypeDB.
See the
<<_version_compatibility>> table to check what version you need, depending on the TypeDB version being used.

=== Installation

To install TypeDB C++ driver:

1. https://github.com/vaticle/typedb-driver/releases[Download] the latest release of `typedb-driver-cpp-*`
for you OS (`linux`/`mac`/`windows`) and architecture (`x86_64`/`arm64`).
2. Include the header file `typedb_driver.hpp` from the `include` directory. See an example of `CMakeLists.txt` below.
+
.CMakeLists.txt example
[,source]
----
cmake_minimum_required(VERSION 3.27)
project(cpp_driver_test)

set(CMAKE_CXX_STANDARD 17)
link_directories(${PROJECT_SOURCE_DIR}/lib)
include_directories(${PROJECT_SOURCE_DIR}/include)

add_executable(cpp_driver_test typedb_test.cpp)
IF (WIN32)
    target_link_libraries(cpp_driver_test ${PROJECT_SOURCE_DIR}/lib/typedb-driver-cpp.if.lib)
ELSE()
    target_link_libraries(cpp_driver_test typedb-driver-cpp)
ENDIF()
----
////

[#_version_compatibility]
== Version compatibility

[cols="^.^1,^.^2,^.^1,^.^1,^.^1,^.^1,^.^1,^.^1,^.^1"]
|===
| Driver version | Protocol encoding version | TypeDB Core | TypeDB Cloud | Rust | Python | Java (JDK) |  Node.js | C++

| 2.26.5
| 3
| 2.26.3
| 2.26.0
| 1.68.0+
| 3.8 to 3.11
| 11+
| >= 14.15
| 17

| 2.25.8
| 3
| 2.25.7
| 2.25.7
| 1.68.0+
| 3.9 to 3.11
| 11+
| >= 14.15
| -

| 2.24.15
| 2
| 2.24.17
| 2.24.17
| 1.68.0+
| 3.9 to 3.11
| 11+
| >= 14.15
| -
|===

.See older versions
[%collapsible]
====

*Python driver older versions*

.Python driver older versions
[cols="^.^3,^.^2,^.^3,^.^3,^.^1"]
|===
| Python driver | Protocol encoding version | TypeDB Core | TypeDB Cloud | Python

| 2.18.0 to 2.18.2
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0
| >= 3.6

| 2.17.0
| N/A
| 2.17.0
| 2.17.0
| >= 3.6

| 2.16.1
| N/A
| 2.16.1
| 2.16.1
| >= 3.6

| 2.12.0 to 2.14.3
| N/A
| 2.12.0 to 2.15
| 2.13.0 to 2.15
| >= 3.6

| 2.9.0 to 2.11.1
| N/A
| 2.9.0 to 2.11.1
| 2.9.0 to 2.11.2
| >= 3.6

| 2.8.0
| N/A
| 2.8.0
| N/A
| >= 3.6

| 2.6.0 to 2.6.3
| N/A
| 2.6.0 to 2.7.1
| N/A
| >= 3.6

| 2.4.0 to 2.5.0
| N/A
| 2.1.2 to 2.5.0
| 2.5.0
| >= 3.6

| 2.2.0
| N/A
| 2.1.2 to 2.5.0
| 2.1.2 to 2.3.0
| >= 3.6

| 2.1.1
| N/A
| 2.1.2
| 2.1.2
| >= 3.6

| 2.1.0
| N/A
| 2.1.0
| 2.1.0
| >= 3.6

| 2.0.1
| N/A
| 2.0.2
| 2.0.2
| >= 3.6

| 2.0.0
| N/A
| 2.0.0 to 2.0.1
| 2.0.0 to 2.0.1
| >= 3.6

| 1.8.0
| N/A
| 1.8.0 to 1.8.4
| N/A
| >= 3.5, < 3.8
|===

*Java driver older versions*

.Java driver older versions
[cols="^.^2,^.^1,^.^2,^.^2"]
|===
| Java driver | Protocol encoding version | TypeDB Core | TypeDB Cloud

| 2.18.0, 2.18.1
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0

| 2.17.0 to 2.17.1
| N/A
| 2.17.0
| 2.17.0

| 2.16.1
| N/A
| 2.16.1
| 2.16.1

| 2.14.1 to 2.14.3
| N/A
| 2.14.1 to 2.15
| 2.14.1 to 2.15.0

| 2.12.0
| N/A
| 2.12.0 to 2.13.0
| 2.13.0

| 2.9.0 to 2.11.1
| N/A
| 2.9.0 to 2.11.1
| 2.9.0 to 2.11.2

| 2.8.0
| N/A
| 2.8.0
| N/A

| 2.6.0 to 2.6.2
| N/A
| 2.6.0 to 2.7.1
| N/A

| 2.5.0
| N/A
| 2.1.2 to 2.5.0
| 2.5.0

| 2.1.0 to 2.4.0
| N/A
| 2.1.2 to 2.5.0
| 2.1.2 to 2.3.0

| 2.0.1
| N/A
| 2.0.2
| 2.0.2

| 2.0.0
| N/A
| 2.0.0, 2.0.1
| 2.0.0, 2.0.1

| 1.8.3
| N/A
| 1.8.0 to 1.8.4
| N/A

| 1.8.2
| N/A
| 1.8.0, 1.8.1
| N/A

| 1.8.0 to 1.8.1
| N/A
| 1.8.0
| N/A
|===

*Node.js driver older versions*

.Node.js driver versions
[cols="^.^3,^.^2,^.^3,^.^3,^.^1"]
|===
| Node.js driver | Protocol encoding version | TypeDB Core | TypeDB Cloud | Node

| 2.26.5
| 3
| 2.26.3
| 2.26.0
| >= 14.15

| 2.25.8
| 3
| 2.25.7
| 2.25.7
| >= 14.15

| 2.24.15
| 2
| 2.24.17
| 2.24.17
| >= 14.15

| 2.18.1, 2.18.2
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0
| >= 14.15

| 2.17.0
| N/A
| 2.17.0
| 2.17.0
| >= 14.15

| 2.16.1
| N/A
| 2.16.1
| 2.16.1
| >= 14.15

| 2.14.2
| N/A
| 2.12.0 to 2.15.0
| 2.13.0 to 2.15.0
| >= 14.15

| 2.9.0 to 2.11.1
| N/A
| 2.9.0 to 2.11.1
| 2.9.0 to 2.11.2
| >= 14.15

| 2.8.0
| N/A
| 2.8.0
| N/A
| >= 14.15

| 2.6.0 to 2.6.2
| N/A
| 2.6.0 to 2.7.1
| N/A
| >= 14.15

| 2.4.0 to 2.5.0
| N/A
| 2.1.2 to 2.5.0
| 2.5.0
| >= 14.15

| 2.1.0 to 2.2.0
| N/A
| 2.1.2 to 2.5.0
| 2.1.2 to 2.3.0
| >= 14.15

| 2.0.1
| N/A
| 2.0.2
| 2.0.2
| >= 14.15

| 2.0.0
| N/A
| 2.0.0, 2.0.1
| 2.0.0, 2.0.1
| >= 14.15

| 1.8.0
| N/A
| 1.8.0 to 1.8.4
| N/A
| >= 6.5
|===

====
