= Java driver
:page-aliases: clients::java-driver.adoc, clients::java-driver/overview.adoc
:Summary: Overview for TypeDB Java driver.
:keywords: typedb, driver, java
:pageTitle: TypeDB Java driver

The Java driver was developed by Vaticle to enable TypeDB support for Java software and developers.

[cols-2]
--
.link:https://github.com/vaticle/typedb-driver/tree/development/java[GitHub,window=_blank]
[.clickable]
****

****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/detail/maven/typedb-driver/latest/a=noarch;xg=com.vaticle.typedb/#versions[Maven,window=_blank]
[.clickable]
****

****
--

[#_install_java]
== Install

See the
<<_version_compatibility>> table to check what versions of TypeDB and Java driver are compatible.

For Linux: the minimum version of `glibc` is `2.25.0`.

Add the code below to the `pom.xml` file in the Maven project.

[IMPORTANT]
====
Be sure to replace the `\{version}` placeholder tag with the version of the Java driver you want to install.
====

[,xml]
----

<repositories>
    <repository>
        <id>repo.typedb.com</id>
        <url>https://repo.typedb.com/public/public-release/maven/</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>com.vaticle.typedb</groupId>
        <artifactId>typedb-driver</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----

For other build systems: see the
https://cloudsmith.io/~typedb/repos/public-release/packages/detail/maven/typedb-driver/latest/a=noarch;xg=com.vaticle.typedb/#install[setup]
page.

=== (Optional) Add logging config

By default, the Java driver uses Logback to print errors and debugging info to standard output. As it is quite verbose,
use the following steps to set the minimum log level to `ERROR`:

. Create a file in the `resources` path (`src/main/resources` by default in a Maven project) named `logback.xml`.
. Copy the following document into the `logback.xml`:

[,xml]
----

<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    <root level="ERROR">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
----

== Quickstart

See below a short example of Java code that connects to a local TypeDB Core,
creates a database named `access-management-db`, defines a schema, inserts some data, and then reads it.

[,java]
----
try (TypeDBDriver driver = TypeDB.coreDriver("localhost:1729")) {
    driver.databases().create("access-management-db");

    try (TypeDBSession session = client.session("access-management-db", SessionType.SCHEMA)) {
        try (TypeDBTransaction tx = session.transaction(TransactionType.WRITE)) {
            tx.query().define(accessManagementSchema);
            tx.commit();
        }
    }
    try (TypeDBSession session = client.session("access-management-db", SessonType.DATA)) {
        for (var batch of accessManagementDataBatches) {
            try (TypeDBTransaction tx = session.transaction(TransactionType.WRITE)) {
                for (var query of batch) {
                    tx.query().insert(query);
                }
                tx.commit();
            }
        }
        try (TypeDBTransaction tx = session.transaction(TransactionType.READ)) {
            Stream<ConceptMap> results = tx.query().get(TypeQL.match(var("u").isa("user")).get());
        }
    }
}
----

For more code examples, see the Tutorial and Driver API links below.

== Learn more

[cols-3]
--
.xref:drivers::java/tutorial.adoc[Tutorial]
[.clickable]
****
This tutorial will help you learn how to use the Java driver.
****

.xref:java/api-reference.adoc[API reference]
[.clickable]
****
Driver API reference for the Java language.
****

.xref:java/query-builder.adoc[Query builder]
[.clickable]
****
Learn to use native Java syntax to build TypeQL queries.
****
--

include::drivers::partial$drivers2discord.adoc[]

//Use the xref:java/api-reference.adoc[API reference] page for the documentation of the methods and objects used in the driver.

[#_version_compatibility]
== Version Compatibility
//#todo Consider showing first 5 entries and the rest is shown in a separate collapsible

[cols="^.^2,^.^1,^.^2,^.^2"]
|===
| Java driver | Protocol encoding version | TypeDB Core | TypeDB Cloud

| 2.26.5
| 3
| 2.26.3
| 2.26.0

| 2.25.8
| 3
| 2.25.7
| 2.25.7

| 2.24.15
| 2
| 2.24.17
| 2.24.17

| 2.18.0, 2.18.1
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0

| 2.17.0 to 2.17.1
| N/A
| 2.17.0
| 2.17.0

| 2.16.1
| N/A
| 2.16.1
| 2.16.1

| 2.14.1 to 2.14.3
| N/A
| 2.14.1 to 2.15
| 2.14.1 to 2.15.0

| 2.12.0
| N/A
| 2.12.0 to 2.13.0
| 2.13.0

| 2.9.0 to 2.11.1
| N/A
| 2.9.0 to 2.11.1
| 2.9.0 to 2.11.2

| 2.8.0
| N/A
| 2.8.0
| N/A

| 2.6.0 to 2.6.2
| N/A
| 2.6.0 to 2.7.1
| N/A

| 2.5.0
| N/A
| 2.1.2 to 2.5.0
| 2.5.0

| 2.1.0 to 2.4.0
| N/A
| 2.1.2 to 2.5.0
| 2.1.2 to 2.3.0

| 2.0.1
| N/A
| 2.0.2
| 2.0.2

| 2.0.0
| N/A
| 2.0.0, 2.0.1
| 2.0.0, 2.0.1

| 1.8.3
| N/A
| 1.8.0 to 1.8.4
| N/A

| 1.8.2
| N/A
| 1.8.0, 1.8.1
| N/A

| 1.8.0 to 1.8.1
| N/A
| 1.8.0
| N/A
|===
