= Java query builder
:Summary: Query builder for TypeDB Java driver.
:page-aliases: clients::java-driver/query-builder.adoc
:keywords: typedb, driver, java, install, repository
:pageTitle: Java query builder

The Java query builder library can be used to programmatically construct TypeQL queries with native Java code.

== Import

To use TypeQL, add it as a dependency to the `pom.xml` file.

The latest version of the `typeql-lang` can be found in the
https://cloudsmith.io/~typedb/repos/public-release/packages/detail/maven/typeql-lang/latest/a=noarch;xg=com.vaticle.typeql/#versions[Vaticle's public Maven repository,window=_blank].

[IMPORTANT]
====
Replace the `\{version}` placeholder with the exact version of the library.
====

[,xml]
----
<repositories>
    <repository>
        <id>repo.typedb.com</id>
        <url>https://repo.typedb.com/public/public-release/maven/</url>
    </repository>
</repositories>
<dependencies>
    <dependency>
        <groupId>com.vaticle.typeql</groupId>
        <artifactId>typeql-lang</artifactId>
        <version>{version}</version>
    </dependency>
</dependencies>
----

Then, import `TypeQL` in the source code:

[,java]
----
import com.vaticle.typeql.lang.TypeQL;
----

You are now ready to construct TypeQL queries, using the methods available for the `TypeQL` class.

== Usage

Using the Java query builder library is quite simple as it produces a TypeQL string.
See the examples below.

//1
=== Example {counter:example}: A get query

[,java]
----
TypeQLGet getQuery = TypeQL.match(
        cVar("u").isa("user").has("full-name", "Kevin Morrison"),
        cVar("p").rel(cVar("u")).rel(cVar("pa")).isa("permission"),
        cVar("o").isa("object").has("path", cVar("fp")),
        cVar("pa").rel(cVar("o")).rel(cVar("va")).isa("access")
).get(cVar("fp"));
----

As the result of the above example you should get a TypeQL query string in a `getQuery` variable that can be used for a
get query.
The resulted string should be similar to the following:

[,java]
----
String getQuery = "match $u isa user, has full-name 'Kevin Morrison'; $p($u, $pa) isa permission; " +
                  "$o isa object, has path $fp; $pa($o, $va) isa access; get $fp;";
----

[NOTE]
====
In versions prior to `2.18.0` the `var()` keyword was used instead of `cVar()` as there were no value variables.
====

Send the query:

[,java]
----
readTransaction.query().get(getQuery);
----

//2
=== Example {counter:example}: A get query with additional parameters

The following example showcases the usage of sorting, offsetting and limiting a get query.

[,java]
----
TypeQLGet getQuery = TypeQL.match(
        cVar("u").isa("user").has("full-name", "Kevin Morrison"),
        cVar("p").rel(cVar("u")).rel(cVar("pa")).isa("permission"),
        cVar("o").isa("object").has("path", cVar("fp")),
        cVar("pa").rel(cVar("o")).rel(cVar("va")).isa("access"),
        cVar("va").isa("action").has("name", "view_file")
).get(cVar("fp")).sort(cVar("fp")).offset(0).limit(5);
----

//3
=== Example {counter:example}: Value variables

[,java]
----
TypeQLGet query = match(
        cVar("x").isa("triangle").has("base", cVar("b")).has("height", cVar("h")),
        vVar("area").assign(Expression.constant(0.5).mul(cVar("b").mul(cVar("h"))))))
);
----

//4
=== Example {counter:example}: An insert query

The following example showcases the usage of insert query.

[,java]
----
insertQuery = TypeQL.match(
        cVar("f").isa("file").has("path", filepath),
        cVar("vav").isa("action").has("name", "view_file")
)
.insert(cVar("pa").rel(cVar("vav")).rel(cVar("f")).isa("access"));
----
