= Lesson 6: Building applications

== Overview

In this lesson, we'll learn how to use the TypeDB native language drivers to build applications on TypeDB. We'll start by seeing how to *manage databases*, then move onto *using sessions* and *controlling transactions*. We'll see how we use different session and transaction types to *execute queries*, and how we can *process results* that are returned.

The examples and exercises in this lesson feature the official *TypeDB Python driver*.

== Recommended prerequisites

* You should complete xref:learn::5-defining-schemas/5-defining-schemas.adoc[Lesson 5] before starting this lesson.

== Using different driver languages

Official drivers are also available for Rust, Java, Node.js, C++, and C. All official drivers offer very similar APIs, so it is recommended to use the Python driver while following this course, as the skills learned will be easily transferable to the other drivers.

Information and tutorials on all drivers can be found in the xref:drivers::overview.adoc[TypeDB Driver documentation].
