= Explanation objects

TypeDB has explainable rule-based data inference feature.
This page covers programmatic usage of explanations.
To learn how to use explanations in TypeDB Studio, see the xref:manual::studio.adoc#_explanation[explanation]
section of the TypeDB Studio Manual.

This page assumes you've already followed instructions from the xref:manual::reading/infer.adoc[] page.

== Explainables

[tabs]
====
Rust::
+
--
.Example
[,rust]
----

----

For more information,
see the xref:drivers::rust/api-reference.adoc#_struct_Explainables[Explainables class] methods.
--

Python::
+
--
.Example
[,python]
----
response = transaction.query.get(get_query)
for ConceptMap in response:
    explainable_relations = ConceptMap.explainables().relations()
----
For more information,
see the xref:drivers::python/api-reference.adoc#_Explainables[Explainables class] methods.
--

Java::
+
--
.Example
[,java]
----

----
For more information,
see the xref:drivers::java/api-reference.adoc#_ConceptMap_Explainables[Explainables class] methods.
--

Node.js::
+
--
.Example
[,js]
----

----
For more information,
see the xref:drivers::nodejs/api-reference.adoc#_Explainables[Explainables class] methods.
--

C++::
+
--
.Example
[,cpp]
----

----
For more information,
see the xref:drivers::cpp/api-reference.adoc#_Explainables[Explainables class] methods.
--
====

== Explain query

To get an explanation object, use one of the explainables to send a special type of query -- an explain query:

[tabs]
====
Rust::
+
--
.Example
[,rust]
----

----

For more information,
see the xref:drivers::rust/api-reference.adoc#_struct_Explainable[Explainable class] methods.
--

Python::
+
--
.Example
[,python]
----
for explainable in explainable_relations:
    explain_iterator = transaction.query.explain(explainable_relations[explainable])
----
For more information,
see the xref:drivers::python/api-reference.adoc#_Explainable[Explainable class] methods.
--

Java::
+
--
.Example
[,java]
----

----
For more information,
see the xref:drivers::java/api-reference.adoc#_ConceptMap_Explainable[Explainable class] methods.
--

Node.js::
+
--
.Example
[,js]
----

----
For more information,
see the xref:drivers::nodejs/api-reference.adoc#_Explainable[Explainable class] methods.
--

C++::
+
--
.Example
[,cpp]
----

----
For more information,
see the xref:drivers::cpp/api-reference.adoc#_Explainable[Explainable class] methods.
--
====

== Explanation

An explanation object has information on which rule was used for inferring the explained concept,
the condition of the rule, the conclusion of the rule,
and the mapping of variables between the query and the rule’s conclusion.

[tabs]
====
Rust::
+
--
.Example
[,rust]
----

----

For more information,
see the xref:drivers::rust/api-reference.adoc#_struct_Explanation[Explanation class] methods.
--

Python::
+
--
.Example
[,python]
----
for explanation in explain_iterator:
    print("Rule: ", explanation.rule().label)
    print("Condition: ", explanation.condition())
    print("Conclusion: ", explanation.conclusion())
    print("Variable mapping: ")
    for var in explanation.query_variables():
        print(f"  Query variable {var} maps to the rule variable {explanation.query_variable_mapping(var)}")
----
For more information,
see the xref:drivers::python/api-reference.adoc#_Explanation[Explanation class] methods.
--

Java::
+
--
.Example
[,java]
----

----
For more information,
see the xref:drivers::java/api-reference.adoc#_Explanation[Explanation class] methods.
--

Node.js::
+
--
.Example
[,js]
----

----
For more information,
see the xref:drivers::nodejs/api-reference.adoc#_Explanation[Explanation class] methods.
--

C++::
+
--
.Example
[,cpp]
----

----
For more information,
see the xref:drivers::cpp/api-reference.adoc#_Explanation[Explanation class] methods.
--
====
