= Lesson 9: Modeling schemas
:page-aliases: learn::9-modeling-schemas/9-modeling-schemas.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to design TypeDB schemas using the conceptual *PERA data model*. We'll start with an overview of the PERA model and see how it is implemented by TypeDB and TypeQL. We'll then work through the design of a small part of the bookstore schema and cover major design decisions like choosing *object types*, using *type hierarchies*, and using *interface hierarchies*. We'll also see how we can avoid some specific problems like *data redundancies*, *inheritance overuse*, and *interface redundancies*.

== Recommended prerequisites

* You should complete xref:learn::7-understanding-query-patterns/overview.adoc[Lesson 7] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::9-modeling-schemas/9.1-the-pera-model.adoc[]
[.clickable]
****
Learn about the basic building blocks of TypeDB's polymorphic data model.
****

.xref:learn::9-modeling-schemas/9.2-determining-object-types.adoc[]
[.clickable]
****
Learn how to effectively choose entity and relation types.
****

.xref:learn::9-modeling-schemas/9.3-avoiding-data-redundancies.adoc[]
[.clickable]
****
Learn how to prevent redundant and inconsistent data.
****

.xref:learn::9-modeling-schemas/9.4-using-type-hierarchies.adoc[]
[.clickable]
****
Learn how to effectively arrange types into hierarchies.
****

.xref:learn::9-modeling-schemas/9.5-composition-over-inheritance.adoc[]
[.clickable]
****
Learn when not to use type hierarchies in data models.
****

.xref:learn::9-modeling-schemas/9.6-using-interface-hierarchies.adoc[]
[.clickable]
****
Learn how to effectively use ownerships and roles in schemas.
****

.xref:learn::9-modeling-schemas/9.7-avoiding-interface-redundancies.adoc[]
[.clickable]
****
Learn how to build schemas that maximise interface polymorphism.
****
--
