= Crash course

This crash course is designed to give a concise overview of the main aspects of working with TypeDB and TypeQL for users coming from document databases. If you do not have experience with document databases, you can check out our xref:home::crash-course/overview.adoc[other crash courses] instead. Document query examples in this crash course use MongoDB syntax.

== Coming from document databases



== What's next?

Continue learning how to use TypeDB with TypeDB Academy, or explore other sections of the documentation.

[cols-2]
--
.xref:academy::overview.adoc[]
[.clickable]
****
An end-to-end learning experience for TypeDB and TypeQL, showing how to take advantage of TypeDB's unique features.
****

.xref:manual::overview.adoc[TypeDB manual]
[.clickable]
****
Practice-oriented guides on using TypeDB, including the TypeDB Studio and TypeDB Console manuals.
****

.xref:drivers::overview.adoc[TypeDB drivers]
[.clickable]
****
Installation guides, tutorials, and API references for the official TypeDB drivers in all supported languages.
****

.xref:typeql::overview.adoc[TypeQL reference]
[.clickable]
****
Complete language reference for TypeQL, covering all query types, pattern elements, and keywords.
****
--
