= Crash course

This crash course is designed to give a concise overview of the main aspects of working with TypeDB and TypeQL for users who are new to databases. If you already have experience with databases, you might want to check out our xref:home::crash-course/overview.adoc[other crash courses] instead.

== Introduction to databases

A database is a system for storing data in an organised format, and making that data available for retrieval. A database is used to store data for a specific purpose, known as a *data domain*. Some examples are:

* A bookstore database, containing data on books, customers, and orders.
* A university database, containing data on students, classes, and grades.
* An airline database, containing data on aircraft, flights, and cargo.

Databases are designed to meet a number of organisational goals:

* To provide a centralised store that acts as a source-of-truth for the data.
* To enable concurrent access to data by multiple parties across the organisation.
* To enforce that the data is not corrupted and conforms to the correct business logic.
* To securely regulate access to different categories of data to different users.

=== Database management systems

The software a database runs on is called a *database management system* (DBMS). Sometimes, the term "database" is used to refer to the DBMS rather than a specific database. A single DBMS is capable of hosting multiple individual databases. DBMSs are typically categorised by the data storage format. Some common categories include:

* Relational databases, which store data as rows in tables.
* Document databases, which store data as documents in collections.
* Graph databases, which store data as vertices and edges in a graph.

TypeDB is a DBMS, but it does not fall into any of these categories. In TypeDB, data is stored as *entities* in the data domain, *relations* between entities, and *attributes* of entities and relations. It shares many properties with relational, document, and graph databases, but also has a number of distinctions and unique features.

=== Database operations

There are four key data operations that can be used to manipulate data in a database:

* Create -- the insertion of new data into the database.
* Read -- the retrieval of data from the database.
* Update -- the modification of existing data in the database.
* Delete -- the removal of data from the database.

Together, these are known as the *CRUD operations*, by their initials.

=== Query languages

An instruction sent to a database to perform a CRUD operation is known as a *query*. In the same way that programs are written using a programming language, queries are written in a *query language*. Each database uses a specific query language, the most common of which is SQL. The query language of TypeDB is *TypeQL*. The following is an example of a TypeQL query for a bookstore database, which retrieves the title and page count of a specific paperback book.

[,typeql]
----
match
  $book isa paperback, has isbn-13 "9780446310789";
fetch
  $book: title, page-count;
----

Queries are categorised by the type of CRUD operation they perform. The above is an example of a TypeQL *Fetch query*, which is used to perform a _read operation_ in TypeDB.

=== Database schemas

Many databases, including TypeDB, require users to specify permitted data structures before data can be inserted into them, similar to defining classes before instantiating them in object-oriented programming. This comes with a number of benefits, including data integrity guarantees and more powerful querying capabilities. The specification of data structures is known as a *schema*.

In databases with a schema, the query language comprises two parts: the *data definition language* (DDL), which is used to define a schema, and the *data manipulation language* (DML), which is used to perform CRUD operations on data.



== What's next?

Continue learning how to use TypeDB with TypeDB Academy, or explore other sections of the documentation.

[cols-2]
--
.xref:academy::overview.adoc[]
[.clickable]
****
An end-to-end learning experience for TypeDB and TypeQL, showing how to take advantage of TypeDB's unique features.
****

.xref:manual::overview.adoc[TypeDB manual]
[.clickable]
****
Practice-oriented guides on using TypeDB, including the TypeDB Studio and TypeDB Console manuals.
****

.xref:drivers::overview.adoc[TypeDB drivers]
[.clickable]
****
Installation guides, tutorials, and API references for the official TypeDB drivers in all supported languages.
****

.xref:typeql::overview.adoc[TypeQL reference]
[.clickable]
****
Complete language reference for TypeQL, covering all query types, pattern elements, and keywords.
****
--
