= TypeQL reference
:keywords: typeql, overview
:pageTitle: TypeQL overview
:page-aliases: {page-component-version}@typeql::overview.adoc
:summary: A birds-eye view of TypeQL documentation.

The TypeQL reference contains a complete reference for the TypeQL query language, used for both defining schemas and manipulating data.

== Introduction

For a high-level overview of the TypeQL query language and its features, read the xref:{page-component-version}@typeql::introduction.adoc[introduction].

== Queries

TypeQL queries for schema and data manipulation differ in structure. Specific query types are used to manipulate the schema, whereas data manipulation queries comprise a sequence of pipeline stages, which operate on streams of data.

[cols-2]
--
.xref:{page-component-version}@typeql::schema/overview.adoc[]
[.clickable]
****
Reference for Define, Undefine, and Redefine queries for schema manipulation.
****

.xref:{page-component-version}@typeql::pipelines/overview.adoc[]
[.clickable]
****
Reference for building data pipelines, including all read and write pipeline stages.
****
--

== Language components

Schema queries and data pipelines are built up from a number of components:

- Functions are used to build re-usable abstractions for processing data.
- Patterns form the body of most schema queries and pipeline stages, made of a combination of statements.
- Statements are individual constraints that describe schema or data elements.
- Annotations are used to modify the behaviour of particular statements or pipeline stages.
- Data elements are stored and processed using a range of value types and value-based operations.

[cols-2]
--
.xref:typeql::patterns/index.adoc[Patterns]
[.clickable]
****
Reference for writing functions, including single-return and stream-return.
****

.xref:typeql::statements/index.adoc[Statements]
[.clickable]
****
Reference for query pattern construction using logical operations and optionals.
****

.xref:typeql::modifiers/index.adoc[Modifiers]
[.clickable]
****
Reference for all individual TypeQL statements, covering schema and data.
****

.xref:typeql::concepts/index.adoc[Concepts]
[.clickable]
****
Reference for all annotations, used for modifying schema and pipeline behaviour.
****

.xref:typeql::values/index.adoc[Values]
[.clickable]
****
Reference for different value types and operations, including primitives, lists, and structs.
****
--

== Glossary

For a complete list of TypeQL keywords used at various levels of query construction, consult the xref:{page-component-version}@typeql::keywords.adoc[keyword glossary].
