= Introduction
:page-aliases: {page-version}@typeql::concepts/concept-variables.adoc, {page-version}@typeql::concepts/data-instances.adoc, {page-version}@typeql::concepts/overview.adoc, {page-version}@typeql::concepts/types.adoc

This page gives an overview of the TypeQL query language. For an overview of the data model on which TypeQL queries are built see xref:{page-version}@typeql::data_model.adoc[here].

[[queries]]
== Queries and functions

The main way of interacting with your TypeDB database is through queries written in *TypeQL*, the query language of TypeDB. Queries fall into two categories.

1. *Schema queries* comprise a *single stage*, indicated by the corresponding keywords shown in the <<table1, table>> below. Schema queries modify the schema of your database, and produces no outputs.
1. *Data pipelines* may comprise *multiple stages*, indicated by the keywords shown in the <<table1, table>> below. Data pipelines read and write data from the database, and always return outputs (though the set of outputs may be empty).

[[table1]]
[cols="^~,^~,^~" , options="header"]
.Query types and keywords
|===
| Query type | Stage keywords | Multi-stage?
| *Schema queries* |
`define`

`undefine`

`redefine`
| no
| *Data pipelines* |
`match`

`insert`

`delete`

`select`

`sort`

`reduce`

...

| yes
| *Functions* |
`match`

`select`

`sort`

`reduce`

...

| yes
|===

Table 1 also mentions *functions*: functions are data pipeline templates that take typed input arguments. Functions *cannot write or delete* data, and thus they cannot contain write stages like `insert` or `delete`.

[cols-2]
--
.xref:{page-version}@typeql::schema/index.adoc[]
[.clickable]
****
Reference for Define, Undefine, and Redefine queries for schema manipulation.
****

.xref:{page-version}@typeql::pipelines/index.adoc[]
[.clickable]
****
Reference for building data pipelines, including all read and write pipeline stages.
****
--

[cols-2]
--
.xref:{page-version}@typeql::functions/index.adoc[]
[.clickable]
****
Reference for writing all types of functions.
****
--

[[statements]]
== Statements and patterns

The body of a stage comprises appropriate statement *statements*. For example:

* The body of a `define` stage comprises statements such as `user owns username`.
* The body of a `match` stage comprises statements such as `$u has username $n` or `$type owns username`.

Which statements can be used depends on the stage.

A _key distinction_ between statements is whether they contain variables or not.

* Statements without variables are called *definitions*.
* Statements with variables are called (elementary) *patterns*. Elementary patterns can be combined into larger pattern by *pattern operations*, such as *conjunction* ("`chaining`"), *disjunction* ("`branching`"), *negation* ("`exclusion`"), etc.

[NOTE]
====
1. *_Schema queries always work with (lists of) definitions._*
1. *_Data pipelines always work with patterns._*
====

As a simple example, compare:
[,typeql]
----
define
  entity user, plays friendship:friend;
  relation friendship, relates friend @card(2);
----
with
[,typeql]
----
match
  $some-type plays $some-role;
  friendship relates $some-role;
----

Definitions in schema queries concern type, inheritance, and capability definitions. In contrast, patterns support a wide variety of syntax, including for:

* References between data instance via attribute ownerships and relations (e.g., `has`, `links`, and anonymous versions thereof)
* Function calls (`let $a, $b in <FUN-CALL>`)
* Computation with values (`let $x = <EXPR>`)
* ... and many more.

The semantics of many statements can be further modified with the use of *annotations*.

[cols-2]
--
.xref:{page-version}@typeql::patterns/index.adoc[]
[.clickable]
****
Reference for query pattern construction using logical operations and optionals.
****

.xref:{page-version}@typeql::statements/index.adoc[]
[.clickable]
****
Reference for all individual TypeQL statements, covering schema and data.
****

.xref:{page-version}@typeql::annotations/index.adoc[]
[.clickable]
****
Annotations modify the semantics of specific TypeQL statements.
****
--

The TypeQL reference contains a complete reference for the TypeQL query language, used for both defining schemas and manipulating data.

== Expressions and value types

TypeQL supports various build in operators to manipulate and combine data types, which can be used in the construction of statements (such as assignments and comparisons).

[cols-2]
--
.xref:{page-version}@typeql::expressions/index.adoc[]
[.clickable]
****
Reference for supported operators and expressions.
****

.xref:{page-version}@typeql::values/index.adoc[]
[.clickable]
****
Reference for different value type.
****
--

== Index and glossary

For a complete list of TypeQL keywords used at various levels of query construction, consult the xref:{page-version}@typeql::keywords.adoc[keyword glossary].
