= Annotations
:page-no-toc: 1

[#_blank_heading]
== {blank}
Annotations can be used in TypeQL to annotate statements for the purpose of modifying their behavior
or adding additional constraints.

The following annotations are available in TypeQL v.3.0+:

[cols-3]
--
.xref:annotations/abstract.adoc[]
[.clickable]
****
To declare a type as abstract.
****

.xref:annotations/cardinality.adoc[]
[.clickable]
****
To add a cardinality constraint.
****

.xref:annotations/cascade.adoc[]
[.clickable]
****
To enable cascade deletes.
****

.xref:annotations/compound-key.adoc[]
[.clickable]
****
To use compound keys.
****

.xref:annotations/debug.adoc[]
[.clickable]
****
To enable debug output.
****

.xref:annotations/distinct.adoc[]
[.clickable]
****
To add a distinction constraint.
****

.xref:annotations/independent.adoc[]
[.clickable]
****
To allow for orphaned attributes.
****

.xref:annotations/key.adoc[]
[.clickable]
****
To add a key constraint.
****

.xref:annotations/regex.adoc[]
[.clickable]
****
To add a constraint for the values to match a regular expression pattern.
****

.xref:annotations/replace.adoc[]
[.clickable]
****
To replace on insert.
****

.xref:annotations/unique.adoc[]
[.clickable]
****
To add a uniqueness constraint.
****

.xref:annotations/values.adoc[]
[.clickable]
****
To limit possible values.
****
--


