@startuml

!define ENTITY01(x) [#02DAC9] entity-x
!define ATTRIBUTE01(x) [#02DAC9] attribute-x
!define RELATION01(x) [#02DAC9] relation-x
!define ROLE01(x) [#02DAC9] role-x

entity "entity" as entity <<ENTITY01(entity)>> {
  entity "person" as person <<ENTITY01(person)>>
  entity "vehicle" as vehicle <<ENTITY01(vehicle)>> {
    entity "car" as car <<ENTITY01(car)>>
    entity "motorcycle" as motorcycle <<ENTITY01(motorcycle)>>
    entity "bicycle" as bicycle <<ENTITY01(bicycle)>>
  }
}

entity "relation" as relation entity-relation {
  entity "using" as using <<ENTITY01(using)>> {
    entity "driving" as driving <<ENTITY01(driving)>>
    entity "riding" as riding <<ENTITY01(riding)>>
    },
  entity "owning" as owning <<ENTITY01(owning)>>
  },

entity "attribute" as attribute <<ENTITY01(attribute)>> {
  entity "name" as name <<ENTITY01(name)>>
  entity "model" as model <<ENTITY01(model)>>}

entity "role" as role <<ENTITY01(role)>> {
  entity "driver" as driver <<ENTITY01(driver)>>
  entity "owner" as owner <<ENTITY01(owner)>>
  entity "passenger" as passenger <<ENTITY01(passenger)>>
  entity "vehicle" as role_vehicle <<ENTITY01(vehicle)>>}

entity --{ relation
relation --{ using
using --{ driving
using --{ riding
relation --{ owning
entity --{ attribute
entity --{ role

@enduml