= Lesson 12: Advanced modeling
:page-aliases: learn::12-advanced-modeling/12-advanced-modeling.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to use the PERA model to design TypeDB schemas that eliminate mismatch with application models. We'll begin by reviewing the fundamentals of the *entity-centric framework* of the PERA model, and how PERA types can be mapped onto to OOP types using the *type-theoretic framework*. We'll then have a close look at using relations in this framework, and learn about the *reification* and *de-reification* processes. Finally, we'll see how we can implement design by contract as a schema design strategy using *interface contracts*.

The application classes featured in this lesson are written in Python.

== Recommended prerequisites

* You should complete xref:learn::9-modeling-schemas/overview.adoc[Lesson 9] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::12-advanced-modeling/12.1-using-dependent-types.adoc[]
[.clickable]
****
Learn about the type-theoretic framework of the PERA model.
****

.xref:learn::12-advanced-modeling/12.2-using-type-theoretic-relations.adoc[]
[.clickable]
****
Learn how to represent application classes with relations.
****

.xref:learn::12-advanced-modeling/12.3-reifying-interfaces.adoc[]
[.clickable]
****
Learn how to safely substitute binary relations for roles.
****

.xref:learn::12-advanced-modeling/12.4-using-interface-contracts.adoc[]
[.clickable]
****
Learn how to apply design-by-contract to data models.
****
--
