= TypeDB Academy: Advanced
:page-aliases: academy::course-summary.adoc, :page-aliases: academy::summary.adoc

== Summary

Congratulations on completing the Advanced module of TypeDB Academy!

In this module, you will have learned how to:

* Retrieve data as stateful objects using Get queries.
* Eliminate mismatch with application models.

As with any technology, you will continue learning as you use TypeDB, and you can always return to this course to recap. There are also plenty of other resources available, some of which are listed below.

Good luck on your TypeDB journey!

== Further learning

[cols-3]
--
.https://typedb.com/fundamentals[Fundamentals]
[.clickable]
****
Technical articles on the foundations of TypeDB and TypeQL, and the philosophy that has gone into their design.
****

.https://typedb.com/lectures[Lectures]
[.clickable]
****
Live lectures covering the motivations and type-theoretic principles on which TypeDB and TypeQL were built.
****

.https://typedb.com/blog[Blog]
[.clickable]
****
Articles from the TypeDB team and contributors from across the community, voicing opinions on a variety of topics.
****
--

== Documentation

[cols-3]
--
.xref:{page-component-version}@manual::overview.adoc[TypeDB Manual]
[.clickable]
****
Practice-oriented guides on using TypeDB, including the TypeDB Studio and TypeDB Console manuals.
****

.xref:{page-component-version}@drivers::overview.adoc[TypeDB Drivers]
[.clickable]
****
Installation guides, tutorials, and API references for the official TypeDB drivers in all supported languages.
****

.xref:{page-component-version}@typeql::overview.adoc[TypeQL Reference]
[.clickable]
****
Complete language reference for TypeQL, covering all query types, pattern elements, and keywords.
****
--

== Support

[cols-3]
--
.https://typedb.com/discord[Discord]
[.clickable]
****
Join the TypeDB Discord server to chat with the TypeDB team and likeminded developers from around the world.
****

.https://forum.typedb.com[Forum]
[.clickable]
****
Collaborate with other users on projects, and find solutions to commonly experienced problems.
****

.https://typedb.com/support[Enterprise]
[.clickable]
****
Explore the options for priority support, tailored to the needs of your business.
****
--
