= TypeDB introduction
:keywords: typedb, database, documentation, introduction, overview
:longTailKeywords: typedb introduction, typedb overview, learn typedb, learn typeql, typedb schema, typedb data model
:pageTitle: TypeDB introduction
:summary: A birds-eye view of TypeDB.
:toc: false

== Brief intro

TypeDB:

* Is a strongly typed database. Unique in many ways:
 ** Has its own special link:../02-dev/02-schema.md#types[strong type system]. Supports subtyping and inheritance like
object-oriented programming languages.

+
// - #todo add link to the types article
 ** Uses link:../02-dev/02-schema.md#entity-types[Entity-Relationship model], extended with
link:../02-dev/02-schema.md#attribute-types[Attributes] and Rules.
 ** Uses declarative queries with its own query language: link:../02-dev/03-match.md#patterns-overview[TypeQL]. We set the
requirements for results but not how to achieve it.
* Is a transactional (https://en.wikipedia.org/wiki/Online_transaction_processing[OLTP]) database with
link:../02-dev/01-connect.md#acid-guarantees[ACID] guarantees.
* Has data separated by link:../02-dev/01-connect.md#databases[databases], each one having its own
xref:../02-dev/02-schema.adoc[schema].

Comparison of TypeDB with most common types of databases:

* xref:../../12-comparisons/00-sql-and-typeql.adoc[SQL]
* xref:../../12-comparisons/01-semantic-web-and-typedb.adoc[Semantic web]
* xref:../../12-comparisons/02-graph-databases-and-typedb.adoc[Graph]

We have prepared a xref:../01-start/03-quickstart.adoc[Quickstart guide] to start with some practice and deploy an
environment for exploring TypeDB.

== Introduction

TypeDB is a new kind of database, that utilizes type systems to help us break down complex problems into a meaningful
and logical system. Its own query language, TypeQL, gives us powerful abstractions over low-level and complex data
patterns. By combining TypeQL and TypeDB, we can close the gap between the language of our domain, and what the
database can interpret and respond to.

TypeDB guarantees data integrity and safety while enabling data-level inferences within the database. This new paradigm
gives a higher level of expressivity to simplify our work and tackle domains that seemed impossibly complex before.

TypeQL and TypeDB allow us to build a data model out of entity, relation, and attribute types. Inheritance allows
subtypes to be defined simply and reduce complexity, while roles and rules further enhance our schema. These
abstractions provide a higher-level framework to build intuitive and understandable models.

We can use the power of https://en.wikipedia.org/wiki/Hypergraph[hypergraphs]
without the need to understand graphs! In other databases, relations may be implemented with a join table
(xref:../../12-comparisons/00-sql-and-typeql.adoc[SQL]), or an edge between two vertices
(xref:../../12-comparisons/02-graph-databases-and-typedb.adoc[graph] databases). TypeDB relations generalize both: they
flexibly relate one, two, or any number of data instances at the same time.

This expanded idea of a relation is more powerful than either SQL or graph relations. However, we can further
improve: if we allow relations to not just specify which instances relate to each other, but also _how_ by adding
context.
