// tag::install-homebrew[]

[,bash]
----
brew install typedb
----

For older versions (prior to `2.19.0`) and `ARM64`/`AArch64` architecture (e.g., a MacBook with the `M1` processor),
we don't recommend using Homebrew; see the
https://forum.vaticle.com/t/running-typedb-on-an-m1-macbook/[Running TypeDB on an M1 MacBook,window=_blank] and
use the <<_manual,manual>> installation instead.

// end::install-homebrew[]

// tag::install-manual[]

TypeDB runs natively on both `ARM` and `Intel` architectures.
For the best performance, make sure both TypeDB and Java SDK match your native architecture and don't run via
https://en.wikipedia.org/wiki/Rosetta_(software)[Rosetta].

. Ensure Java 11+ is installed.
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/[Oracle JDK,window=_blank].
+
To check the Java SDK version:
+
[,bash]
----
/usr/libexec/java_home -V
----

. Get the latest TypeDB Core release for macOS:
include::typedb:resources:partial$latest-version.adoc[tag=mac]

. Extract the archive into a new directory:
+
[,bash,subs=attributes+]
----
sudo mkdir /opt/typedb
unzip ~/Downloads/typedb-all-mac-{latest-version}.zip -d /opt/typedb
----

. Add a symlink to the TypeDB executable in the `/usr/local/bin` directory:
+
[,bash,subs=attributes+]
----
ln -s /opt/typedb/typedb-all-mac-{latest-version}/typedb /usr/local/bin/typedb
----

// end::install-manual[]

// tag::start[]

[,bash]
----
typedb server
----

// end::start[]

// tag::stop[]

Close the terminal or press kbd:[Ctrl+C].

// end::stop[]
