== Retrieve valuetype (Local)

=== Syntax

[source,java]
----
attributeType.getValueType();
----

=== Description

Retrieves the valuetype of this AttributeType.

=== Returns

* AttributeType.ValueType (STRING | DATETIME | LONG | DOUBLE | BOOLEAN)

== Set supertype

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).setSupertype(AttributeType attributeType);
----

=== Description

Sets the supplied AttributeType as the supertype of the current AttributeType

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| attributeType | The AttributeType to set as the supertype of this AttributeType | AttributeType | True | N/A
|===

=== Returns

* void

== Retrieve all subtypes

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).getSubtypes();
----

=== Description

Retrieves all direct and indirect subtypes of the AttributeType.

=== Returns

* Stream<xref:java/java-api-ref.adoc#_attribute_type[`AttributeType`]>

== Retrieve all instances of this AttributeType

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).getInstances();
----

=== Description

Retrieves all direct and indirect Attributes that are instances of this Type.

=== Returns

* Stream<xref:java/java-api-ref.adoc#_attribute[`Attribute`]>

== Retrieve direct and inherited owners of this Type of Attribute

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).getOwners(Set<TypeQLToken.Annotation> annotations);
----

=== Description

Retrieve all Things that own an attribute of this type. +
Optionally, filtered by annotations provided.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value

| annotations
| Only retrieve things that have an attribute of this type with annotations (KEY or UNIQUE).
| set of `Annotation`
| False
| Collections.emptySet();

|===

=== Returns

* Stream<xref:java/java-api-ref.adoc#_thing[`Thing`]>

== Retrieve direct owners of this Type of Attribute

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).getOwnersExplicit(Set<TypeQLToken.Annotation> annotations);
----

=== Description

Retrieve all Things that directly own an attribute of this type. +
Optionally, filtered by annotations provided.

=== Input parameters

[options="header"]
|===
| annotations
| Only retrieve things that have an attribute of this type with annotations (KEY or UNIQUE).
| set of `Annotation`
| False
| Collections.emptySet();
|===

=== Returns

* Stream<xref:java/java-api-ref.adoc#_thing[`Thing`]>

== Get a Remote version of the AttributeType.

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| transaction | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `AttributeType.Remote`

== Check if value is of type boolean

=== Syntax

[source,java]
----
attributeType.isBoolean();
----

=== Description

Returns true if the value for attributes of this type is of type boolean. Otherwise, returns false.

== Check if value is of type long

=== Syntax

[source,java]
----
attributeType.isLong();
----

=== Description

Returns true if the value for attributes of this type is of type long. Otherwise, returns false.

== Check if value is of type double

=== Syntax

[source,java]
----
attributeType.isDouble();
----

=== Description

Returns true if the value for attributes of this type is of type double. Otherwise, returns false.

== Check if value is of type string

=== Syntax

[source,java]
----
attributeType.isString();
----

=== Description

Returns true if the value for attributes of this type is of type string. Otherwise, returns false.

== Check if value is of type datetime

=== Syntax

[source,java]
----
attributeType.isDateTime();
----

=== Description

Returns true if the value for attributes of this type datetime. Otherwise, returns false.

