== Put instance

=== Syntax

[source,java]
----
datetimeAttributeType.asRemote(Transaction tx).put(LocalDateTime value);
----

=== Description

Puts and returns a new instance of this DateTimeAttributeType with the specified value. If an attribute with this value does not yet exist, it will be created.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| value | The value of the instance to be put | LocalDateTime | True | N/A
|===

=== Returns

* DateTimeAttribute object

== Get instance

=== Syntax

[source,java]
----
datetimeAttributeType.asRemote(Transaction tx).get(LocalDateTime value);
----

=== Description

Returns the instance, if it exists, of this DateTimeAttributeType with the specified value.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| value | The value of the instance to be retrieved | LocalDateTime | True | N/A
|===

=== Returns

* DateTimeAttribute object

== Set Supertype

=== Syntax

[source,java]
----
attributeType.asRemote(Transaction tx).setSupertype(AttributeType.DateTime datetimeAttributeType);
----

=== Description

Sets the supplied DateTimeAttributeType as the supertype of the current DateTimeAttributeType

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| dateTimeAttributeType | The AttributeType to set as the supertype of this DateTimeAttributeType | DateTimeAttributeType | True | N/A
|===

=== Returns

* void

== Retrieve all subtypes

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSubtypes();
----

=== Description

Retrieves all direct and indirect subtypes of the DateTimeAttributeType.

=== Returns

* Stream<[`AttributeType.DateTime`] >

== Retrieve all instances of this DateTimeAttributeType

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getInstances();
----

=== Description

Retrieves all direct and indirect DateTimeAttributes that are instances of this Type.

=== Returns

* Stream<[`DateTimeAttribute`] >

== Get a Remote version of the DateTimeAttributeType.

=== Syntax

[source,java]
----
dateTimeAttributeType.asRemote(Transaction tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| transaction | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `DateTimeAttributeType.Remote`

