== Create instance

=== Syntax

[source,java]
----
entityType.asRemote(Transaction tx).create();
----

=== Description

Creates and returns a new instance of this EntityType.

=== Returns

* [`Entity`] 

== Set supertype

=== Syntax

[source,java]
----
entityType.asRemote(Transaction tx).setSupertype(EntityType entityType);
----

=== Description

Sets the supplied EntityType as the supertype of the current EntityType

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| entityType | The EntityType to set as the supertype of this EntityType | EntityType | True | N/A
|===

=== Returns

* void

== Retrieve all subtypes

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSubtypes();
----

=== Description

Retrieves all direct and indirect subtypes of the EntityType.

=== Returns

* Stream<[`EntityType`] >

== Retrieve all instances of this EntityType

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getInstances();
----

=== Description

Retrieves all direct and indirect Entity objects that are instances of this Type.

=== Returns

* Stream<[`Entity`] >

== Get a Remote version of the EntityType.

=== Syntax

[source,java]
----
entityType.asRemote(Transaction tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| transaction | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `EntityType.Remote`

