== Create instance

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).create();
----

=== Description

Creates and returns an instance of this RelationType.

=== Returns

* [`Relation`] 

== Retrieve roles

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).getRelates();
----

=== Description

Retrieve roles that this RelationType relates to directly or via inheritance.

=== Returns

* [Stream] <[`RoleType`] >

== Retrieve direct roles

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).getRelatesExplicit();
----

=== Description

Retrieve roles that this RelationType relates to directly.

=== Returns

* [Stream] <[`RoleType`] >

== Retrieve specific role

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).getRelates(String label);
----

=== Description

Retrieve the role that this RelationType relates to, if it exists, with the specified label.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| label | Label of the role we wish to retrieve. | string | True |  
|===

=== Returns

* [`RoleType`] 

== Set new role

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).setRelates(String label, String overriddenRoleLabel);
----

=== Description

Sets the new role that this RelationType relates to. If we are setting an overriding type this way, we have to also
pass the overridden type as a second argument.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| label | The new role for the RelationType to relate to. | string | True | N/A
| overriddenRoleLabel | The label being overridden, if applicable | string | False | N/A
|===

=== Returns

* void

== Remove role

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).unsetRelates(RoleType role);
----

=== Description

Disallows this RelationType from relating to the given role.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| role | The role to not relate to the relation type. | RoleType | True | N/A
|===

=== Returns

* void

== Set supertype

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx).setSupertype(RelationType relationType);
----

=== Description

Sets the supplied RelationType as the supertype of the current RelationType

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| relationType | The RelationType to set as the supertype of this RelationType | RelationType | True | N/A
|===

=== Returns

* void

== Retrieve all subtypes

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSubtypes();
----

=== Description

Retrieves all direct and indirect subtypes of the RelationType.

=== Returns

* Stream<[`RelationType`] >

== Retrieve all instances of this RelationType

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getInstances();
----

=== Description

Retrieves all direct and indirect Relations that are instances of this Type.

=== Returns

* Stream<[`Relation`] >

== Get a Remote version of the RelationType.

=== Syntax

[source,java]
----
relationType.asRemote(Transaction tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| transaction | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `RelationType.Remote`

