== Get a Remote version of the role type.

=== Syntax

[source,java]
----
roleType.asRemote(tx);
----

=== Description

The remote version uses the given transaction to execute every method call.

=== Input parameters

[options="header"]
|===
|Name |Description |Type |Required |Default Value
| tx | The transaction to be used to make method calls. | Transaction | True | N/A
|===

=== Returns

* `RoleType.Remote`

== Retrieve scope (Local)

=== Syntax

[source,java]
----
roleType.getLabel().scope();
----

=== Description

Retrieves the scope (defined relation label) of the role type.

=== Returns

* String

== Retrieve scoped label (Local)

=== Syntax

[source,java]
----
roleType.getLabel().scopedName();
----

=== Description

Retrieves the scoped label (relation:role) of the role type.

=== Returns

* String

== Retrieve direct supertype

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSupertype();
----

=== Description

Retrieves the most immediate supertype of the role type.

=== Returns

* [`RoleType`] 
* `null`

== Retrieve all supertypes

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSupertypes();
----

=== Description

Retrieves all supertypes of the role type.

=== Returns

* Stream<[`RoleType`] >

== Retrieve all subtypes

=== Syntax

[source,java]
----
type.asRemote(Transaction tx).getSubtypes();
----

=== Description

Retrieves all direct and indirect subtypes of the type.

=== Returns

* Stream<[`RoleType`] >

== Retrieve relation

=== Syntax

[source,java]
----
role.asRemote(Transaction tx).getRelationType();
----

=== Description

Retrieves the Relation instance that this role is directly related to.

=== Returns

* [`RelationType`] >

== Retrieve relation types

=== Syntax

[source,java]
----
role.asRemote(Transaction tx).getRelationTypes();
----

=== Description

Retrieves the RelationTypes that this role is related to.

=== Returns

* Stream<[`RelationType`] >

== Retrieve role players

=== Syntax

[source,java]
----
role.asRemote(Transaction tx).getPlayers();
----

=== Description

Retrieves the ThingTypes whose instances play this role.

=== Returns

* Stream<[`ThingType`](/docs/concept-api/type?tab=java)>

