= Lesson 10: Using inference
:page-aliases: learn::10-using-inference/10-using-inference.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to write and use rules effectively. We'll start by seeing how rules can be used like views in order to *abstract complex query patterns* into more maintainable forms. Then we'll explore how we can use rules to build networks of logic, covering *rule chaining* and *rule branching*, allowing us to create complex behaviour from simple rules. As part of this, we'll also examine *rule recursion*.

== Recommended prerequisites

* You should complete xref:learn::8-structuring-query-results/overview.adoc[Lesson 8] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::10-using-inference/10.1-rules-as-views.adoc[]
[.clickable]
****
Learn how to create simple abstractions for complex patterns.
****

.xref:learn::10-using-inference/10.2-rule-chaining.adoc[]
[.clickable]
****
Learn how to chain rules, into each other and recursively.
****

.xref:learn::10-using-inference/10.3-rule-branching.adoc[]
[.clickable]
****
Learn how to use rules to create branching logic.
****
--
