@startmindmap

<style>
arrow {
    LineStyle 0
    LineThickness 3
    LineColor #E96464
}
</style>

*[#02DAC9] entity
**[#D7D4E5] person
**[#D7D4E5] vehicle
***[#D7D4E5] car
***[#D7D4E5] motorcycle
***[#D7D4E5] bicycle

*[#02DAC9] relation
**[#D7D4E5] using
***[#D7D4E5] driving
***[#D7D4E5] traveling
**[#D7D4E5] owning

*[#02DAC9] attribute
**[#D7D4E5] name
***[#D7D4E5] Full-name
***[#D7D4E5] Nickname
**[#D7D4E5] model

/'*[#02DAC9] role
**[#D7D4E5] driving:driver
**[#D7D4E5] owning:owner
**[#D7D4E5] riding:passenger
**[#D7D4E5] driving:vehicle
**[#D7D4E5] owning:vehicle
**[#D7D4E5] riding:vehicle'/

@endmindmap
