= Patterns
:page-aliases: {page-version}@typeql::patterns.adoc

This reference covers the usage of patterns in TypeQL.

== Scopes and operations
// TODO: Must update.
Pattern comprise statements containing variables. Given a pattern, the *scope* of a variable is:

* the block `{ ... }` in which variable appears at top-level (i.e., not nested in further `{...}`) but it does not appear outside of the block,
- Exceptionally, if the variable appears in all branches of a disjunction, it counts as appearing in the parent conjunction.
* or, the entire pattern itself if the variable appears at the top-level of the pattern itself.

A key principle of valid TypeQL pattern is:

> *_Every variable must have a unique scope._*

While a statement by itself is an (elementary) patterns, *operations* allow us to construct larger and more interesting patterns from smaller ones, and they create new scopes of variables.

== Operation reference

[cols-3]
--
.xref:{page-version}@reference::typeql/patterns/conjunctions.adoc[]
[.clickable]
****
Use of conjunctions to join patterns into a single query pattern that combines all given constraints.
****

.xref:{page-version}@reference::typeql/patterns/disjunction.adoc[]
[.clickable]
****
Use of disjunctions to allow for several branches in a query to be executed in parallel.
****

.xref:{page-version}@reference::typeql/patterns/negations.adoc[]
[.clickable]
****
Use of negations to exclude patterns from your query results.
****
--
