= is

The `is` keyword statement is used in TypeQL data queries to specify equality between two concepts.

== Syntax

The syntax of an `is` statement includes:

.Syntax
[,typeql]
----
<concept> "is" <concept>;
----

where `<concept` is a variable representing a concept .

== Behavior

TypeQL statements with the `is` keyword are used in data queries
to set an equality constraint for any two variables.
That makes two variables equal both by type and value, so we could replace one of the variables with another.
//#todo Check whether we still need the `is` statement at all. It was used mostly as a workaround for a problem that doesn't exist anymore

== Usage for equality

include::partial$iam-database-links.adoc[]

Let's match different concept variables that are set to be equal and fetch values of the same attribute type:

.Example
[,typeql]
----
match
$p1 has full-name $f1;
$p2 has full-name $f2;
$p1 is $p2;
$f1 < $f2;
fetch
$f1 as first; $f2 as second;
----

.Output example
[,json]
----
{
    "first": { "value": "Kevin Morrison", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } },
    "second": { "value": "Kevin M.", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } }
}
----

It can be used for simplifying patterns or combining two different patterns into a single one.

== Usage with negation

include::partial$iam-database-links.adoc[]

The most common use of an `is` statement is to exclude some results.

For example, let's find all users that have similar emails.
To do that, match two data instances of the `user` type, both having the same `email` attribute.
But to exclude the results where the same entity matches both concept variables,
add a negated `is` statement with these variables.

.Negation example
[,typeql]
----
match
$u1 isa user, has email $e;
$u2 isa user, has email $e;
not {$u1 is $u2;};
fetch
$e;
----

In our IAM database
link:https://github.com/vaticle/typedb-docs/blob/master/drivers-src/modules/ROOT/partials/tutorials/iam-data-single-query.tql[sample dataset]
that query returns no results.

== Learn more

[cols-2]
--
.xref:statements/isa.adoc[]
[.clickable]
****
Learn more about `isa` statement in TypeQL.
****

.xref:concepts/data.adoc[]
[.clickable]
****
Learn about data instances in TypeQL.
****
--
