= isa

The `isa` keyword is used to specify a type for data instances, taking into account type inference.
For specifying only a direct type, see the xref:typeql::statements/isa-em.adoc[] statement instead.

== Syntax

The syntax of an `isa` statement includes:

* subject -- a concenpt-variable representing a data instance
* predicate -- the `isa` keyword
* object -- a type label or a concept variable representing a type

.Syntax
[,typeql]
----
<concept variable> isa <type>;
----

== Behaviour

TypeQL statements with the `isa` keyword are used in data queries and rules.

The `isa` keyword adds a constraint of a type (including subtypes) to data instances, represented by a concept variable.

When used in a `match` or `delete` clause pattern,
the `isa` keyword uses all subtypes of the provided type via type inference.

However, when used in an `insert` clause pattern, the `isa` keyword doesn't use subtypes and
its behavior is the same as the xref:typeql::statements/isa-em.adoc[isa!] keyword.

// tag::example-schema-data[]
To run the examples below, you can use a database with the IAM
link:https://github.com/vaticle/typedb-docs/blob/master/drivers-src/modules/ROOT/partials/tutorials/iam-schema.tql[schema]
and
link:https://github.com/vaticle/typedb-docs/blob/master/drivers-src/modules/ROOT/partials/tutorials/iam-data-single-query.tql[sample data]
loaded.
// end::example-schema-data[]

== In a match pattern

In a `match` clause pattern an isa statement can be used to match data instance of a selected type
or any of its subtype (via type inference).




== In a delete pattern


== In an insert pattern



=== Simple statement example

To match all data instances of the `path` attribute type (or any of its subtypes),
use the simple `isa` statement with a concept variable on the left from the keyword
and the `path` attribute type label on the right.
We then can fetch value of every matched attribute directly with a `fetch` clause:

.isa statement example
[,typeql]
----
match
$p isa path;
fetch $p;
----

.See output
[%collapsible]
====
.Output example
[,json]
----
{ "p": { "value": "LICENSE", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "p": { "value": "zlckt.ts", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "p": { "value": "README.md", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
----
====


== Learn more

[cols-2]
--
.xref:typeql::statements/isa-em.adoc[]
[.clickable]
****
Learn more about `isa!` statement in TypeQL.
****

.xref:typeql::statements/has.adoc[]
[.clickable]
****
Learn more about `has` statement in TypeQL.
****

.xref:typeql::concepts/types.adoc[]
[.clickable]
****
Learn about types in TypeQL.
****

.xref:typeql::concepts/data-instances.adoc[]
[.clickable]
****
Learn about data instances in TypeQL.
****
--
