= Statements overview

A TypeQL statement is a building block of a TypeQL pattern.
Statements in TypeQL are always end with a semicolon.
By default, a conjunction combines all statements in a pattern.
There is a specific syntax to use for a
xref:patterns/disjunction.adoc[disjunction] or
xref:patterns/negation.adoc[negation].
//# todo Add links to disjunction and negation

== Simple statements

A simple statement is the smallest complete TypeQL block that can be used as a pattern in a clause.

Most simple statements have three parts: *Subject*, *Predicate*, and *Object*.
Where the predicate is a TypeQL keyword.

Some notable exceptions are:
xref:annotations/overview.adoc[annotations],
xref:modifiers/overview.adoc[modifiers], and
xref:statements/value.adoc[value statement].

[#_composite_statements]
== Composite statements

Multiple simple statements with the same subject can be combined into a composite statement.
A composite statement starts with a single subject, followed by comma-separated simple statements with
the subject omitted.

.See an example
[%collapsible]
====
.Composite statement example
[,typeql]
----
$p isa person, has full-name "Kevin Morrison", has email $e;
----

The above example combines simple xref:statements/isa.adoc[] and xref:statements/has.adoc[] statements
to the same result without repeating the subject (`$p`):

.Equal simple statements example
[,typeql]
----
$p isa person;
$p has full-name "Kevin Morrison";
$p has email $e;
----
====

== Statement types

[cols-3]
--
.xref:statements/isa.adoc[]
[.clickable]
****

****

.xref:statements/is.adoc[]
[.clickable]
****

****

.xref:statements/has.adoc[]
[.clickable]
****

****

.xref:statements/sub.adoc[]
[.clickable]
****

****

.xref:statements/type.adoc[]
[.clickable]
****

****

.xref:statements/owns.adoc[]
[.clickable]
****

****

.xref:statements/value.adoc[]
[.clickable]
****

****

.xref:statements/relates.adoc[]
[.clickable]
****

****

.xref:statements/plays.adoc[]
[.clickable]
****

****

.xref:statements/links.adoc[]
[.clickable]
****

****

.xref:statements/in.adoc[]
[.clickable]
****

****
--

// * isa
// * isa!
// * is
// * has
// * sub
// * sub!
// * type
// * abstract
// * owns
// * value
// * regex
// * @key
// * @unique
// * relates
// * plays
// * as
// * rule (when/then)
