= owns

The `owns` keyword is used in TypeQL schema to declare that a subject type can own instances of a given type.

== Syntax

The syntax of a `owns` statement includes:

.Syntax
[,typeql]
----
<owner> "owns" <attribute-type> [<annotation>] ["as" <overridden-type>];
----

where `<owner>` is the type that can own attributes of a given attribute type.

For more information about annotations, see the xref:annotations/overview.adoc[] page.

An optional <<_usage_with_override,override>> can be added at the end.

== Behavior

The `owns` keyword declares an ability for the subject type to own attributes of
a given attribute type.

TypeQL statements with the `owns` keyword can be used in schema queries to modify a schema,
or in data queries to match data using types information.

== Usage in a schema definition

include::partial$iam-database-links.adoc[]

Since in Define and Undefine queries you can't use variables,
both subject and object can only be type labels.

For example, to define a new type `pdf` with an ability to own attributes of the `name` attribute type, use:

.Define query example
[,typeql]
----
define
pdf sub file, owns name;
----

To remove the ability to own attributes of the `name` type, but keep the `pdf` type, use:

.Undefine query example
[,typeql]
----
undefine
pdf owns name;
----

[#_usage_with_override]
== Usage with override

include::partial$iam-database-links.adoc[]

By default, a subtype inherits all attribute types that were defined as owned for its supertype.
To override an inherited attribute type ownership, use the `as` keyword when defining an ownership.
The overridden attribute type must be a subtype of the inherited attribute type.

Let's see an example, of a schema, where the `name` attribute type gets overridden by the `full-name` attribute:

.Override owned attribute type example
[,typeql]
----
define

name sub attribute, abstract, value string;
full-name sub name;

person sub entity, abstract, owns name;
user sub person, owns full-name as name;
----

== Usage in data queries

Let's retrieve all attribute types that can be owned by the `person` entity type:

.Owns statement in a data query
[,typeql]
----
match
$p type person, owns $a;
$a type $type;
fetch
$type;
----

== Learn more

[cols-2]
--
.xref:statements/type.adoc[]
[.clickable]
****
Learn more about `type` statement in TypeQL.
****

.xref:concepts/types.adoc[]
[.clickable]
****
Learn about types in TypeQL.
****
--
