= owns

The `owns` keyword is used in TypeQL schema to define an owner type for an attribute type.

== Syntax

The syntax of a `owns` statement includes:

* subject -- type label of the owner type
* predicate -- the `owns` keyword
* object -- type label of an attribute type

.Syntax
[,typeql]
----
<type> owns <attribute-type>;
----

== Behaviour

TypeQL statements with the `owns` keyword can be used only in Define and Undefine queries.

The `owns` keyword adds an ability for the subject type to own attributes of
the object attribute type to the schema.

== Usage in a schema definition

Since in Define and Undefine queries you can't use variables,
both subject and object can only be type labels.

For example, to define a new type `pdf` with an ability to own attributes of the `name` attribute type, use:

.Define query example
[,typeql]
----
define
pdf sub file, owns name;
----

To remove the ability to own attributes of the `name` type, but keep the `pdf` type, use:

.Undefine query example
[,typeql]
----
undefine
pdf owns name;
----

== Learn more

[cols-2]
--
.xref:typeql::statements/type.adoc[]
[.clickable]
****
Learn more about `type` statement in TypeQL.
****

.xref:typeql::concepts/types.adoc[]
[.clickable]
****
Learn about types in TypeQL.
****
--
