= relates

The `relates` keyword is used in TypeQL schema to declare a role for a relation type.

== Syntax

The syntax of a `relates` statement includes:

.Syntax
[,typeql]
----
<relation-type> relates <role> [as overridden-type];
----

An optional <<_usage_with_override,override>> can be added at the end.

== Behavior

The `relates` keyword declares a role for a relation type.

TypeQL statements with the `relates` keyword can be used in schema queries to modify a schema
or in data queries to retrieve types information.

== Usage in a schema definition

include::partial$iam-database-links.adoc[]

Since in Define and Undefine queries you can't use variables,
both subject and object can only be type labels.

For example, to define a new role `subject` for the `permission` relation type, use:

.Define role query example
[,typeql]
----
define
permission relates subject;
----

To remove the new role, use:

.Undefine query example
[,typeql]
----
undefine
permission relates subject;
----

[#_usage_with_override]
== Usage with override

By default, a subtype of a relation type inherits all roles that were defined for its supertype.
To override an inherited role, use the `as` keyword.

Let's see an example, of a schema, where the `owned` role of the `ownership` relation type gets overridden by
the `object` role:

.Override owned attribute type example
[,typeql]
----
define

object-ownership sub ownership,
    owns ownership-type,
    relates object as owned;
----

== Learn more

[cols-2]
--
.xref:statements/type.adoc[]
[.clickable]
****
Learn more about `type` statement in TypeQL.
****

.xref:concepts/types.adoc[]
[.clickable]
****
Learn about types in TypeQL.
****
--
