= @unique

The `@unique` keyword is an annotation, that can be used with an
xref:typeql::statements/owns.adoc[owns statement] to specify, that the selected attribute type must be uniquely owned by data instances of a given type.

== Syntax

The syntax of a `@unique` statement includes:

* xref:typeql::statements/owns.adoc[owns statement]
* the `@unique` keyword

.Syntax
[,typeql]
----
<type> owns <attribute-type> @unique;
----

== Behavior

TypeQL statements with the `@unique` keyword can be used only in Define queries.

The `@unique` keyword adds a uniqueness constraint for all attributes of the attribute type
owned by data instances of the subject type.

A uniqueness constraint means that every attribute of an attribute type can be owned by no more than one
data instance of the subject type.
That makes every owned attribute unique among all data instances of the subject type.

== Usage in a schema definition

include::typeql::partial$iam-database-links.adoc[]

Since in Define and Undefine queries you can't use variables,
both subject and object of an owns statement can only be type labels.

For example, to define that the `object` type owns the `object-type` attribute type
with the `@unique` annotation, use:

.Define unique query example
[,typeql]
----
define
object sub entity, owns object-type @unique;
----

== Learn more

[cols-2]
--
.xref:typeql::statements/type.adoc[]
[.clickable]
****
Learn more about `type` statement in TypeQL.
****

.xref:typeql::concepts/types.adoc[]
[.clickable]
****
Learn about types in TypeQL.
****
--

