= Lesson 10.2: Function chaining

== Simple function chaining

Much like views in a relational database, which can be generated from other views, functions in TypeDB can leverage answers generated by other functions.

[,typeql]
----
fun verified-reviews($book: book) -> { review }:
  match
  $review isa review;
  rating ($review, $book);
  order-line ($order, $book);
  $_ isa action-execution ($user, $review), has timestamp $review-time;
  $_ isa action-execution ($user, $order), has timestamp $order-time;
  $review-time > $order-time;
  return { $review };
----

[,typeql]
----
fun unverified-reviews($book: book) -> { review }:
  match
  $review isa review;
  rating ($review, $book);
  not {
    let $verified-review in verified-reviews($book);
    $review is $verified-review;
  };
  return { $review };
----

The unverified-reviews function can re-use the work of the first function, modularizing logic effectively and promoting re-use.

== Recursive function chaining

Functions can recurse as well! A recursive function is one which invokes itself.

[,typeql]
----
fun transitive_places($place: place) -> { place }:
  match
    {
      locating (located: $place, location: $parent);
    } or {
      locating (located: $place, location: $middle);
      let $parent in transitive_places($middle);
    };
  return { $parent };
----

This rule is a *recursive rule*. If we compare the conclusion, it actually matches _both_ statements in the condition. This means that when we infer `$x` to be located in `$parent` place, the facts that `$x` is located in `$child-place` and that `$child-place` is located in `$parent` place could both themselves be inferred.

Our data contains the following information encoded in `locating` relations:

* The user with ID "u0003" is located in Newark.
* Newark is located in New Jersey.
* New Jersey is located in the United States.

When we run the following query, we get the following result.

[,typeql]
----
match
$user isa user, has id "u0003";
(located: $user, location: $place) isa locating;
fetch
$place: name;
----

[,json]
----
{
    "place": {
        "name": [ { "value": "Newark", "value_type": "string", "type": { "label": "name", "root": "attribute" } } ],
        "type": { "label": "city", "root": "entity" }
    }
}
{
    "place": {
        "name": [ { "value": "New Jersey", "value_type": "string", "type": { "label": "name", "root": "attribute" } } ],
        "type": { "label": "state", "root": "entity" }
    }
}
{
    "place": {
        "name": [ { "value": "United States", "value_type": "string", "type": { "label": "name", "root": "attribute" } } ],
        "type": { "label": "country", "root": "entity" }
    }
}
----

To retrieve the first result (Newark), we do not need to use the rule at all, because the fact the user is located there is written to disk. To retrieve the second result (New Jersey), we need to apply the rule _once_. To retrieve the third result (United States) we need to apply the rule _twice_. Similarly, if we had another level in our location hierarchy (perhaps North America), we would need to apply the rule _three times_ to retrieve the result.

While the rule `transitive-location` is the easiest to understand of the rules in the bookstore schema, it is also the one with the most complex behaviour. Generating transitive relations is not the only use case for rule recursion, but it is by far the most common. Depending on the depth of recursion and the size of the dataset, recursive rules can be computationally intensive to resolve, so they should be used with caution.

// While the rule `transitive-location` is the easiest to understand of the rules in the bookstore schema, it is also the one with the most complex behaviour. Generating transitive relations is not the only use case for rule recursion, but it is by far the most common. Depending on the depth of recursion and the size of the dataset, recursive rules can be computationally intensive to resolve, so they should be used with caution. We will explore optimisation strategies for rules, including recursive ones, in Lesson 16 (coming soon).
