= TypeDB Java Driver overview
:Summary: Overview for TypeDB Driver Java.
:keywords: typedb, client, driver, java
:longTailKeywords: typedb java client, typedb java driver, client java, java driver
:pageTitle: Java TypeDB Driver overview

The Java Driver was developed by Vaticle to enable TypeDB support for Java software and developers.

For Driver installation guide -- see the xref:java/java-install.adoc[installation] page.

Explore the Java Driver xref:java/java-tutorial.adoc[tutorial] with example of connecting to TypeDB.

Use the xref:java/java-api-ref.adoc[API reference] page for documentation of the methods and objects used in the Driver.

Learn to use native Java syntax to build TypeQL queries with xref:java/java-query-builder.adoc[Java query builder].

// tag::questions[]
[NOTE]
====
Any more questions about the Driver after reading the documentation? Feel free to ask on our
https://vaticle.com/discord[Discord,window=_blank] community server.
====
// end::questions[]

For more information on version compatibility with TypeDB and TypeDB Studio -- see the
xref:clients::java/java-install.adoc#_version_compatibility[Version compatibility] table.
