[#_ThingType]
=== ThingType

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Type`
* `TypeDB::Concept`



Common super-type of EntityType, RelationType, and AttributeType.

// tag::methods[]
[#_virtual_VoidFuture_TypeDBThingTypedeleteType_Transaction_transaction]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::deleteType(Transaction& transaction)
----





Deletes this type from the database.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_virtual_stdstring_TypeDBThingTypegetLabel]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::ThingType::getLabel()
----





Retrieves the unique label of the type.


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual std::string`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType`` or ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_const_stdinitializer_list_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Variant of <<#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``ValueType``

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Variant of <<#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>> without filtering on ``Annotation``s

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdinitializer_list_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::initializer_list< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



See <<#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE,getOwns(Transaction&amp;, ValueType, const std::vector&lt;Annotation&gt;&amp;, Transitivity)>>

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptIterable_AttributeType_TypeDBThingTypegetOwns_Transaction_transaction_ValueType_valueType_const_stdvector_Annotation_annotations_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getOwns

[source,cpp]
----
ConceptIterable< AttributeType > TypeDB::ThingType::getOwns(Transaction& transaction, ValueType valueType, const std::vector< Annotation >& annotations, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves ``AttributeType`` that the instances of this ``ThingType`` are allowed to own directly or via inheritance.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `valueType` a| If specified, only attribute types of this ``ValueType`` will be retrieved. a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and inherited ownership, ``Transitivity::EXPLICIT`` for direct ownership only a| 
a| `annotations` a| Only retrieve attribute types owned with annotations. a| 
|===

[caption=""]
.Returns
`ConceptIterable< AttributeType >`

[#_ConceptPtrFuture_AttributeType_TypeDBThingTypegetOwnsOverridden_Transaction_transaction_AttributeType_PTR_attributeType]
==== getOwnsOverridden

[source,cpp]
----
ConceptPtrFuture< AttributeType > TypeDB::ThingType::getOwnsOverridden(Transaction& transaction, AttributeType* attributeType)
----



Retrieves an ``AttributeType``, ownership of which is overridden for this ``ThingType`` by a given ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` that overrides requested ``AttributeType`` a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< AttributeType >`

[#_ConceptIterable_RoleType_TypeDBThingTypegetPlays_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getPlays

[source,cpp]
----
ConceptIterable< RoleType > TypeDB::ThingType::getPlays(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and inherited (or direct only) roles that are allowed to be played by the instances of this ``ThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| transitivity: ``Transitivity::TRANSITIVE`` for direct and indirect playing, ``Transitivity::EXPLICIT`` for direct playing only a| 
|===

[caption=""]
.Returns
`ConceptIterable< RoleType >`

[#_ConceptPtrFuture_RoleType_TypeDBThingTypegetPlaysOverridden_Transaction_transaction_RoleType_PTR_roleType]
==== getPlaysOverridden

[source,cpp]
----
ConceptPtrFuture< RoleType > TypeDB::ThingType::getPlaysOverridden(Transaction& transaction, RoleType* roleType)
----



Retrieves a ``RoleType`` that is overridden by the given ``role_type`` for this ``ThingType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The ``RoleType`` that overrides an inherited role a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< RoleType >`

[#_ConceptIterable_ThingType_TypeDBThingTypegetSubtypes_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getSubtypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----





Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_ConceptPtrFuture_ThingType_TypeDBThingTypegetSupertype_Transaction_transaction]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< ThingType > TypeDB::ThingType::getSupertype(Transaction& transaction)
----





Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< ThingType >`

[#_ConceptIterable_ThingType_TypeDBThingTypegetSupertypes_Transaction_transaction]
==== getSupertypes

[source,cpp]
----
ConceptIterable< ThingType > TypeDB::ThingType::getSupertypes(Transaction& transaction)
----





Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< ThingType >`

[#_StringFuture_TypeDBThingTypegetSyntax_Transaction_transaction]
==== getSyntax

[source,cpp]
----
StringFuture TypeDB::ThingType::getSyntax(Transaction& transaction)
----



Produces a pattern for creating this ``ThingType`` in a ``define`` query.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`StringFuture`

[#_virtual_bool_TypeDBThingTypeisAbstract]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::ThingType::isAbstract()
----





Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implements TypeDB::Type.

[caption=""]
.Returns
`virtual bool`

[#_virtual_BoolFuture_TypeDBThingTypeisDeleted_Transaction_transaction]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::ThingType::isDeleted(Transaction& transaction)
----





Check if the type has been deleted


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual BoolFuture`

[#_bool_TypeDBThingTypeisRoot]
==== isRoot

[source,cpp]
----
bool TypeDB::ThingType::isRoot()
----



Checks if the type is a root type.


[caption=""]
.Returns
`bool`

[#_VoidFuture_TypeDBThingTypesetAbstract_Transaction_transaction]
==== setAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::setAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be abstract, meaning it cannot have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_virtual_VoidFuture_TypeDBThingTypesetLabel_Transaction_transaction_const_stdstring_newLabel]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::ThingType::setLabel(Transaction& transaction, const std::string& newLabel)
----





Renames the label of the type. The new label must remain unique.


Implements TypeDB::Type.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_const_stdinitializer_list_Annotation_annotations]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::initializer_list< Annotation >& annotations = {})
----





Variant of <<#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_AttributeType_PTR_overriddenType_const_stdvector_Annotation_annotations,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_const_stdvector_Annotation_annotations]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, const std::vector< Annotation >& annotations)
----



Variant of <<#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_AttributeType_PTR_overriddenType_const_stdvector_Annotation_annotations,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>> with no overridden attribute type

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_AttributeType_PTR_overriddenType_const_stdinitializer_list_Annotation_annotations]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::initializer_list< Annotation >& annotations = {})
----



See <<#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_AttributeType_PTR_overriddenType_const_stdvector_Annotation_annotations,setOwns(Transaction&amp;, AttributeType*, AttributeType*, const std::vector&lt;Annotation&gt;&amp;)>>

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetOwns_Transaction_transaction_AttributeType_PTR_attributeType_AttributeType_PTR_overriddenType_const_stdvector_Annotation_annotations]
==== setOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::setOwns(Transaction& transaction, AttributeType* attributeType, AttributeType* overriddenType, const std::vector< Annotation >& annotations)
----



Allows the instances of this ``ThingType`` to own the given ``AttributeType``. Optionally, overriding a previously declared ownership. Optionally, adds annotations to the ownership.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` to be owned by the instances of this type. a| 
a| `overriddenType` a| The ``AttributeType`` that this attribute ownership overrides, if applicable. a| 
a| `annotations` a| Adds annotations to the ownership. a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetPlays_Transaction_transaction_RoleType_PTR_roleType]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType)
----



Variant of <<#_VoidFuture_TypeDBThingTypesetPlays_Transaction_transaction_RoleType_PTR_roleType_RoleType_PTR_overriddenRoleType,setPlays(Transaction&amp;, RoleType*, RoleType*)>> with no overridden role type.

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypesetPlays_Transaction_transaction_RoleType_PTR_roleType_RoleType_PTR_overriddenRoleType]
==== setPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::setPlays(Transaction& transaction, RoleType* roleType, RoleType* overriddenRoleType)
----



Allows the instances of this ``ThingType`` to play the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to be played by the instances of this type a| 
a| `overriddenType` a| The role type that this role overrides, if applicable a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypeunsetAbstract_Transaction_transaction]
==== unsetAbstract

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetAbstract(Transaction& transaction)
----



Set a ``ThingType`` to be non-abstract, meaning it can have instances.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypeunsetOwns_Transaction_transaction_AttributeType_PTR_attributeType]
==== unsetOwns

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetOwns(Transaction& transaction, AttributeType* attributeType)
----



Disallows the instances of this ``ThingType`` from owning the given ``AttributeType``.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `attributeType` a| The ``AttributeType`` to not be owned by the type. a| 
|===

[caption=""]
.Returns
`VoidFuture`

[#_VoidFuture_TypeDBThingTypeunsetPlays_Transaction_transaction_RoleType_PTR_roleType]
==== unsetPlays

[source,cpp]
----
VoidFuture TypeDB::ThingType::unsetPlays(Transaction& transaction, RoleType* roleType)
----



Disallows the instances of this ``ThingType`` from playing the given role.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `roleType` a| The role to not be played by the instances of this type. a| 
|===

[caption=""]
.Returns
`VoidFuture`

// end::methods[]

