[#_Type]
=== Type

*Package*: `TypeDB`

*Supertypes:*

* `TypeDB::Concept`



Common super-type of RoleType &amp; ThingType.

// tag::methods[]
[#_virtual_VoidFuture_TypeDBTypedeleteType_Transaction_transaction]
==== deleteType

[source,cpp]
----
virtual VoidFuture TypeDB::Type::deleteType(Transaction& transaction)
----



Deletes this type from the database.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

[#_virtual_stdstring_TypeDBTypegetLabel]
==== getLabel

[source,cpp]
----
virtual std::string TypeDB::Type::getLabel()
----



Retrieves the unique label of the type.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Returns
`virtual std::string`

[#_ConceptIterable_Type_TypeDBTypegetSubtypes_Transaction_transaction_Transitivity_transitivity_TransitivityTRANSITIVE]
==== getSubtypes

[source,cpp]
----
ConceptIterable< Type > TypeDB::Type::getSubtypes(Transaction& transaction, Transitivity transitivity = Transitivity::TRANSITIVE)
----



Retrieves all direct and indirect (or direct only) subtypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `transitivity` a| ``Transitivity::TRANSITIVE`` for direct and indirect subtypes, ``Transitivity.EXPLICIT`` for direct subtypes only a| 
|===

[caption=""]
.Returns
`ConceptIterable< Type >`

[#_ConceptPtrFuture_Type_TypeDBTypegetSupertype_Transaction_transaction]
==== getSupertype

[source,cpp]
----
ConceptPtrFuture< Type > TypeDB::Type::getSupertype(Transaction& transaction)
----



Retrieves the most immediate supertype of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptPtrFuture< Type >`

[#_ConceptIterable_Type_TypeDBTypegetSupertypes_Transaction_transaction]
==== getSupertypes

[source,cpp]
----
ConceptIterable< Type > TypeDB::Type::getSupertypes(Transaction& transaction)
----



Retrieves all supertypes of the type.


[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`ConceptIterable< Type >`

[#_virtual_bool_TypeDBTypeisAbstract]
==== isAbstract

[source,cpp]
----
virtual bool TypeDB::Type::isAbstract()
----



Checks if the type is prevented from having data instances (i.e., ``abstract``).


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Returns
`virtual bool`

[#_virtual_BoolFuture_TypeDBTypeisDeleted_Transaction_transaction]
==== isDeleted

[source,cpp]
----
virtual BoolFuture TypeDB::Type::isDeleted(Transaction& transaction)
----



Check if the type has been deleted


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
|===

[caption=""]
.Returns
`virtual BoolFuture`

[#_virtual_VoidFuture_TypeDBTypesetLabel_Transaction_transaction_const_stdstring_newLabel]
==== setLabel

[source,cpp]
----
virtual VoidFuture TypeDB::Type::setLabel(Transaction& transaction, const std::string& newLabel)
----



Renames the label of the type. The new label must remain unique.


Implemented in TypeDB::RoleType, and TypeDB::ThingType.

[caption=""]
.Input parameters
[cols="~,~,~"]
[options="header"]
|===
|Name |Description |Type
a| `transaction` a| The current transaction a| 
a| `label` a| The new ``Label`` to be given to the type. a| 
|===

[caption=""]
.Returns
`virtual VoidFuture`

// end::methods[]

