= Sample application
:keywords: getting started, typedb, typeql, tutorial, quickstart, application, app, example, sample
:longTailKeywords: get started with typedb, typedb tutorial, typedb quickstart, learn typedb, sample app, sample application
:pageTitle: Sample application
:summary: A simple example with a prototype application to run against a TypeDB database.
:tabs-sync-option:

In this tutorial, we'll use a sample application to showcase how to define a schema, insert initial data,
read data, apply pagination and inference, and add additional data.

== Prerequisites

xref:home::install.adoc#_core[Install] and
xref:home::install.adoc#_run_typedb_core[run] TypeDB Core.
By default, it should be available for connection at `127.0.0.1:1729`.

Select one of the available languages below and proceed:

[tabs]
====
Rust::
+
--
Follow the Rust driver xref:drivers::rust/overview.adoc#_install_rust[installation guide].
--

Python::
+
--
Follow the Python driver xref:drivers::python/overview.adoc#_install_python[installation guide].
--

Java::
+
--
Follow the Java driver xref:drivers::java/overview.adoc#_install_java[installation guide].
--

Node.js::
+
--
Follow the Node.js driver xref:drivers::nodejs/overview.adoc#_install_nodejs[installation guide].
--
====

[WARNING]
====
Running the sample app will result in a deletion of a database named `iam` if it exists already on the server.
Make sure to create a backup copy of all your data from such a database,
or change the default database name in the source code if necessary.
====

== Source code

See the full source code of the sample app below:

[tabs]
====
Rust::
+
--
include::partial$sample-app-rust.adoc[]
--

Python::
+
--
include::partial$sample-app-python.adoc[]
--

Java::
+
--
include::partial$sample-app-java.adoc[]
--

Node.js::
+
--
include::partial$sample-app-node.adoc[]
--
====

== Additional files

[#_schema_and_initial_data]
=== Schema and initial data

For running the sample application, use the following
https://github.com/vaticle/typedb-docs/blob/master/typedb-src/modules/ROOT/attachments/iam-schema.tql[define query,window=_blank]
for a schema definition and an
https://github.com/vaticle/typedb-docs/blob/master/typedb-src/modules/ROOT/attachments/iam-data.tql[insert query,window=_blank]
for a sample dataset insertion.

=== Auxiliary files

[tabs]
====
Rust::
+
--
You can specify dependencies in a `Cargo.tonl` file. See an example below.

.Cargo.toml
[,toml]
----
[package]
name = "sample-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
typedb-driver = { version = "2.26.1", features = ["sync"] }
----
--

Python::
+
--
You don't need any files other than the source code, schema, and data.
--

Java::
+
--
You can specify dependencies in a `pom.xml` file. See an example below.

.pom.xml
[,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example2</groupId>
    <artifactId>java-app2</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>19</maven.compiler.source>
        <maven.compiler.target>19</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <repositories>
        <repository>
            <id>repo.vaticle.com</id>
            <url>https://repo.vaticle.com/repository/maven/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.vaticle.typedb</groupId>
            <artifactId>typedb-driver</artifactId>
            <version>2.25.2</version>
        </dependency>
    </dependencies>

</project>
----
--

Node.js::
+
--
You don't need any files other than the source code, schema, and data.
--
====

== Building and running

To run the sample app follow the instructions below:

[tabs]
====
Rust::
+
--
Run the Rust application with `cargo`:

[,bash]
----
cargo run
----

The TypeQL files with Define and Insert queries should be placed at the top level of the project directory,
side by side with the `Cargo.toml` file.
--

Python::
+
--
Place all the files in the same folder and run:

[,bash]
----
python .\sample.py
----
--

Java::
+
--
Build and run a maven project from within your IDE. +
Alternatively, to build a `.jar` file, run:

[,bash]
----
mvn clean install
----

The TypeQL files with Define and Insert queries should be placed at the top level of the project directory,
side by side with the `pom.xml` file.
--

Node.js::
+
--

Run the Node.js application:

[,bash]
----
node sample.js
----

The TypeQL files with define and insert queries should be placed at the top level of the project directory,
side by side with the `package.json` file.
--
====

[#_explanation]
== Explanation

This section is for comments and explanation of the sample application implementation details.

=== Database setup

First of all, we connect to a TypeDB Core server by initializing a driver instance.

We proceed to check whether a database named `iam` exists on the server already.
We delete such a database if it exists to prevent any possible schema or data conflicts.
Then we create a new database with the name `iam`.

We open a schema session to this database, open a write transaction, read the `iam-schema.tql` file,
and send its contents as a xref:typeql::schema/define-types.adoc[Define query].
Next, we commit the transaction to persist the resulted schema.

After that we open a data session, a write transaction, read the `iam-data-single-query.tql` file,
and send its contents as an xref:typeql::data/insert.adoc[Insert query].
We commit the transaction again and re-using the same data session to open a read transaction.

With the new read transaction, we test the resulted database by retrieving the number of users in it.

For more information on server connections, sessions, and transactions, see the xref:typedb::connecting/overview.adoc[]
page.

=== Request #1: User listing

We open a data session that will be re-used for multiple requests, open a read transaction,
and send a simple TypeQL query to get all users with `full-name` and `email` attributes.

[,typeql]
----
match
$u isa user,
    has full-name $n,
    has email $e;
get;
----

We iterate through results to print every user and the total count of users.

[discrete]
==== Query explanation

This is a xref:typeql::data/get.adoc[Get query] that includes `match` and `get` clauses.

We go through all entities of the `user` type that have a `full-name` attribute and `email` attribute.

A `get` clause with no variables and just a semicolon means,
that we are retrieving concepts for all variables from the preceding `match` clause pattern in every result.

=== Request #2: Files

We open a new read transaction in the same data session and send a TypeQL query to get paths of all filenames that
user with the `full-name` of `Kevin Morrison` has access to.

[,typeql]
----
match
$u isa user, has full-name 'Kevin Morrison';
$p($u, $pa) isa permission;
$o isa object, has path $fp;
$pa($o, $va) isa access;
get $fp;
----

For Java implementation, we use xref:drivers::java/query-builder.adoc[Java query builder]
syntax to programmatically build a TypeQL query string.

.Java query builder syntax
[,java]
----
TypeQLGet getQuery = TypeQL.match( // Java query builder to prepare TypeQL query string
                                    cVar("u").isa("user").has("full-name", "Kevin Morrison"),
                                    cVar("p").rel(cVar("u")).rel(cVar("pa")).isa("permission"),
                                    cVar("o").isa("object").has("path", cVar("fp")),
                                    cVar("pa").rel(cVar("o")).rel(cVar("va")).isa("access")
                            ).get(cVar("fp"));
----

We iterate through results to print every file and the total count of files.

[discrete]
==== Query explanation

This is a xref:typeql::data/get.adoc[Get query] that includes `match` and `get` clauses.
//#todo Replace with Fetch!

A `match` clause pattern looks for a `user` (variable `$u`) with attribute `full-name` of value `Kevin Morrison` assigned,
a `permission` relation (`$p`) in between this user `$u` and potential access `$pa`.
Additionally, we state that an `object` (`$o`) with a path `$fp` should be a part of `$pa` `access` relation, without
having to specify what kind of action `$va` it should be.

A `get` clause filters response to only contain the matched `path` attributes (`$fp`).

[NOTE]
====
According to the xref:tutorials/iam-schema.adoc[IAM schema],
we need two relations to connect users to files: `permission` and `access`.
====

=== Request #3: Inference

We start with opening a new transaction with the xref:typedb::developing/infer.adoc[inference] option enabled.

Then we send a query to get Kevin's files, but this time we specify the access action to be `view_file`,
since the permission for this access wasn't inserted in the <<_schema_and_initial_data,sample dataset>>
and must be inferred by the `add-view-permission` rule.
We also add xref:typeql::data/get.adoc#_sort_the_results[sort],
xref:typeql::data/get.adoc#_offset_the_results[offset] and
xref:typeql::data/get.adoc#_limit_the_results[limit] modifiers to the query to manage pagination.
This request consists of two queries splitting the results between queries.

.Query 1
[,typeql]
----
match
$u isa user, has full-name 'Kevin Morrison';
$p($u, $pa) isa permission;
$o isa object, has path $fp;
$pa($o, $va) isa access;
$va isa action, has name 'view_file';
get $fp;
sort $fp asc;
offset 0;
limit 5;
----

And then, we repeat the query with different offset to get the rest of results.

.Query 2
[,typeql]
----
match
$u isa user, has full-name 'Kevin Morrison';
$p($u, $pa) isa permission;
$o isa object, has path $fp;
$pa($o, $va) isa access;
$va isa action, has name 'view_file';
get $fp;
sort $fp asc;
offset 5;
limit 5;
----

For Java implementation, we use xref:drivers::java/query-builder.adoc[Java query builder]
syntax to programmatically build a TypeQL query string.

.Java query builder syntax for the Query 1
[,java]
----
TypeQLGet getQuery = TypeQL.match( // Java query builder to prepare TypeQL query string
                                    cVar("u").isa("user").has("full-name", "Kevin Morrison"),
                                    cVar("p").rel(cVar("u")).rel(cVar("pa")).isa("permission"),
                                    cVar("o").isa("object").has("path", cVar("fp")),
                                    cVar("pa").rel(cVar("o")).rel(cVar("va")).isa("access"),
                                    cVar("va").isa("action").has("name", "view_file")
                            ).get(cVar("fp")).sort(cVar("fp")).offset(0).limit(5);
----

.Java query builder syntax for the Query 2
[,java]
----
getQuery = TypeQL.match( // Java query builder to prepare TypeQL query string
                        cVar("u").isa("user").has("full-name", "Kevin Morrison"),
                        cVar("p").rel(cVar("u")).rel(cVar("pa")).isa("permission"),
                        cVar("o").isa("object").has("path", cVar("fp")),
                        cVar("pa").rel(cVar("o")).rel(cVar("va")).isa("access"),
                        cVar("va").isa("action").has("name", "view_file")
                 ).get(cVar("fp")).sort(cVar("fp")).offset(5).limit(5);
----

[discrete]
==== Query explanation

We update the previous query to set the type of action (`$va`) to the `view_file` value.
We still get only `path` (`$fp`), but now we add sorting and pagination: we set offset and limit for the results.

[NOTE]
====
Note that Kevin has been assigned only `modify_file` access, and the `view_file` access is being inferred by a
xref:basics/inference.adoc#_rules[rule].
To use xref:typedb::developing/infer.adoc[inference] in this query,
we modify TypeDB options and send the modified set of options to the transaction call.
====

=== Request #4: Add a new file

To be able to insert new data, we open a write transaction this time.
Then we generate a filename from current time and date and insert an instance of the `file` type that owns the
attribute of type `path` and value of the generated filename.

[,typeql]
----
insert $f isa file, has path 'logs/2023-12-19-19-11-36.log';
----

After that we do another query to match the new file we just inserted and add a relation of the `access` type with it:

[,typeql]
----
match
$f isa file, has path 'logs/2023-12-19-19-11-36.log';
$vav isa action, has name 'view_file';
insert
($vav, $f) isa access;
----

For Java implementation, we use xref:drivers::java/query-builder.adoc[Java query builder]
syntax to programmatically build a TypeQL query string.

.Java query builder syntax for the Query 1
[,java]
----
TypeQLInsert insertQuery = TypeQL.insert(cVar("f").isa("file").has("path", filepath));
----

.Java query builder syntax for the Query 2
[,java]
----
insertQuery = TypeQL.match(
                            cVar("f").isa("file").has("path", filepath),
                            cVar("vav").isa("action").has("name", "view_file")
                    ).insert(
                            cVar("pa").rel(cVar("vav")).rel(cVar("f")).isa("access")
);
----

[discrete]
==== Query explanation

The first query inserts a file entity that owns a `path` attribute with the value of a generated filename.

With the second query, we look for a `file` entity that has the attribute `path` with the value we generated before.
And we find an `action`, that has a `name` attribute with the value of `view_file`.
Finally, we insert an `access` relation between the `file` and the `action`.

After both requests are done, we commit the write transaction to persist new information.

[NOTE]
====
Note that we create the `file` first.
If we try to insert an `access` to a nonexistent `file` our query will run but will not insert any new data (relation)
because its `match` clause will find no matches in a database.
====
