= Data model
:Summary: PERA model for data modelling in TypeDB.
:keywords: typedb, data, model, modelling, pera, polymorphic
:pageTitle: Data model
:!example-caption:
:!table-caption:

Every TypeDB database has a schema that contains definitions of all types and rules used in that database.
Schema defines everything that is possible in a database: types define data model and rules define embedded logic.
A type can be added by subtyping any existing type from a schema and inheriting features of a supertype(parent).

All data inserted to a database by creating instances of types from a schema.
Just like an object as an instance of a class in OOP.

== PERA

Schema types use a Polymorphic Entity-Relation-Attribute (or *PERA*) model with three root types:
`entity`, `relation`, and `attribute`.
All user-defined types are direct or non-direct subtypes of one of the root types.
That divides all types into three categories with different capabilities.

.Root types
[cols="^.^1, ^.^3, ^.^4",options="header"]
|===
| Root type label | A subtype of the root type | An instance of data

| `entity`
| Entity type
| Instance of an entity type or an entity

| `relation`
| Relation type
| Instance of a relation type or a relation

| `attribute`
| Attribute type
| Instance of an attribute type or an attribute
|===

//#todo Add a picture of three root types

Entities represent independent objects.
Relations represent relationships between data.
Relations have roles that other instances of data can play.
Attributes represent properties with value.
Attributes can be owned by other instances of data.

For more information about type system and polymorphism, see the xref:typedb::basics/plymorphic-type-system.adoc[] page.

//Mention ER-model comparison
