= Data model
:Summary: PERA model for data modelling in TypeDB.
:keywords: typedb, data, model, modelling, pera, polymorphic
:pageTitle: Data model
:!example-caption:
:!table-caption:

Every TypeDB database has a schema that contains definitions of all types and rules used in that database.
Schema defines everything that is possible in a database: types for a data model and rules for an embedded logic.
A type can be added by subtyping any existing type from a schema and inheriting features of a supertype (parent).

All data is inserted to a database by creating instances of types from a schema.
Just like an object as an instance of a class in OOP.

== PERA

Schema types use a Polymorphic Entity-Relation-Attribute (or *PERA*) model with three root types:
`entity`, `relation`, and `attribute`.
All user-defined types are direct or non-direct subtypes of one of the root types.
That divides all types into three categories with different capabilities.

.Root types
[cols="^.^1, ^.^3, ^.^4",options="header"]
|===
| Root type label | A subtype of the root type | An instance of data

| `entity`
| Entity type
| Instance of an entity type or an entity

| `relation`
| Relation type
| Instance of a relation type or a relation

| `attribute`
| Attribute type
| Instance of an attribute type or an attribute
|===

//#todo Add a picture of three root types

== Strong type system

TypeDB employs a strong and polymorphic type system.

All queries are validated not only for syntax errors, but also for type violations.
Schema definitions include constraints on what types (and their instances) can do.
For example, for an entity to be able to have ownership of an attribute,
entity's type definition must have ownership of attribute's type declared in a schema.

For more information about queries, see the xref:typedb::basics/query-language.adoc[] page. +
For more information about polymorphism, see the xref:typedb::basics/polymorphic-patterns.adoc[] page.

Any type can be an owner of an attribute type and can play a role in a relation type.

[WARNING]
====
While it is possible for attribute types to own other attribute types and to play roles in relation types,
it is considered a bad data modeling practice to do so.
Consider these features deprecated and planned for removal in the TypeDB 3.0 release.
====

== Entities

Entities represent independent objects in a data model.
By creating a type hierarchy for entities,
we're effectively creating a classification system of independent objects in our domain.

An entity can play a role in a relation and can have ownership of an attribute, but it can't have its own value or role.

== Relations

Relations represent relationships between data instances.
A relation can't exist without its roleplayers.

Roles of a relation are set in its type definition.
To play a role in a relation, a data instance must have this ability defined in a schema for its type.

Relations are mutable: you can change relation by adding or removing roleplayers for its roles.
A relation without a single roleplayer for one of its roles usually represents an incomplete data state.
For example, marriage can't exist without spouses.

== Attributes

Attributes represent properties with value that other types can own.
Values of attributes are limited to the value type set in a definition of their type.
//An attribute type's definition includes a value type that constraints possible values for attributes of that attribute type.

An attribute is immutable: its value is fixed and can't be altered.
Attribute's value is unique among other attributes of the same type.
Hence, an attribute can be uniquely addressed by its type and value.

Other types can own an attribute type.
That means that an instance of these other types can own an instance of this attribute type.
This usually means that an object in our domain has a property with the matching value.
For example, a person has name "Bob", where an entity of the `person` type has attribute of type `name` and value `Bob`.

//Mention ER-model comparison
