= Polymorphic patterns
:Summary: Strong and polymorphic type system of TypeDB.
:keywords: typedb, type, polymorphic, polymorphism, pattern, statement, conjunction, solve, match
:pageTitle: Polymorphic patterns
:!example-caption:
:!table-caption:

Data queries use patterns to match data and types from a database.
TypeQL patterns utilize a strong and polymorphic type system based on the
xref:typedb::basics/data-model.adoc[PERA] model.

[#_patterns]
== Patterns

include::typeql::data/match.adoc[tags=patterns_overview]

////
The exact operation performed by a pattern depends on the type of clause it is used in:

* A xref:typeql::data/match.adoc#_match_clause[match clause] matches all variables to concepts in a database,
finding all combinations that solve a given pattern.
* An xref:typeql::data/insert.adoc#_insert_clause[insert clause] creates instances of data, specified by a given pattern.
* A xref:typeql::data/delete.adoc#_delete_clause[delete clause] deletes instances of data, specified by a given pattern.
* A xref:typeql::data/fetch.adoc#_fetch_clause[fetch clause] projects specified values, types, and results of subqueries
to JSON output.
* A xref:typeql::data/get.adoc#_get_clause[get clause] returns concepts from a database for specified variables
as objects accessible via driver API.

Schema definitions that are used in xref:typeql::schema/rule-definitions.adoc[define] and
xref:typeql::schema/undefine.adoc[undefine] clauses are limited to schema statements only
and can't use any variables and values.
////
== Polymorphism

In TypeQL we can use polymorphism to return results of different types for the same variable in a query pattern.

There are three types of polymorphism that can be used in a query pattern:

- Inheritance polymorphism
- Interface polymorphism
- Parametric polymorphism

=== Inheritance polymorphism
// We can query all subtypes with their common supertype
Inheritance polymorphism lets us query for subtypes of a type used in a query.
By using a supertype in a pattern, we can get results for the supertype itself, as well as results for all its subtypes.

.Inheritance polymorphism query example
[,typeql]
----
match
$x isa user;
get
$x;
----

The xref:typeql::data/get.adoc[Get] query above matches `$x` by its type.
`$x` must by an instance of either the `user` type or any subtype of the `user`.
In case of the Quickstart
https://github.com/vaticle/typedb-docs/blob/master/typedb-src/modules/ROOT/attachments/quickstart-schema.tql[schema,window=_blank]
and
https://github.com/vaticle/typedb-docs/blob/master/typedb-src/modules/ROOT/attachments/quickstart-data.tql[data,window=_blank]
we will have exactly one instance of the `person` type as the result.
Note that `person` is a subtype of a `user` in that schema.

You can easily avoid inheritance polymorphism by using the `isa!` keyword (with an exclamation mark) instead.
That prohibits subtypes from being used for results.

=== Interface polymorphism
// Types can own the same attribute types and play the same roles, even if they share no common supertypes
// And we can query them
Interface polymorphism lets us query for any types that implement a given interface.
By implementing a given interface, we mean owning an attribute type or playing a role in a relation type.

.Interface polymorphism query example
[,typeql]
----
match
$x has email $e;
fetch
$x: full-name;
----

The above query matches every instance (`$x`), that has any email attribute.
The same approach could be used with playing a role in a relationship.
It then returns a JSON with full names of every matched `$x`.
Note, that we do not specify the type of `$x`, so it can be an instance of any type,
as long as it has an email attribute.

.JSON output example
[,js]
----
{
    "x": {
        "full-name": [ { "value": "Kevin Morrison", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } ],
        "type": { "label": "person", "root": "entity" }
    }
}
----

In the above output example, we see that the type of `$x` in one of the results is `person`.

////
//#todo Double-check this extension for attribute type ownership
We can adjust the query to get those instances that are allowed to have an email attribute but wasn't assigned one yet.
To do so, you need to use a new variable for the type of `$x`
and then set a constraint of having an ownership of the `email` attribute type on the variable.

.Type constraint interface polymorphism example
[,typeql]
----
match
$x isa $type;
$type owns email;
fetch
$x: full-name;
----

The output of the above query looks similar as the previous one, but it can include new results.

.JSON output example
[,js]
----
{
    "x": {
        "full-name": [ { "value": "Pearle Goodman", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } ],
        "type": { "label": "person", "root": "entity" }
    }
}
----

In the first example we check the instances bound to `$x` variable for having an attribute of the `email` type.
For the second example we check for the type of `$x` to allow it to potentially own an attribute of the `email` type.
////

=== Parametric polymorphism
//No type labels in a query
Parametric polymorphism lets us look for a value of an attribute regardless of its type.

.Parametric polymorphism example
[,typeql]
----
match
$a contains "r";
fetch
$a;
----

In the above example `$a` is matched by its value for the value to contain a substring of single letter: `r`.
All attributes of any type that have a value that contains letter `r` are matched by this pattern.

.JSON output example
[,js]
----
{ "a": { "value": "Kevin Morrison", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "a": { "value": "kevin.morrison@vaticle.com", "type": { "label": "email", "root": "attribute", "value_type": "string" } } }
{ "a": { "value": "Pearle Goodman", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "a": { "value": "pearle.goodman@vaticle.com", "type": { "label": "email", "root": "attribute", "value_type": "string" } } }
----

As you can see in the output example above, in our sample dataset we can match two attributes of the type `full-name`
and two of the type `email`.
