= Aggregation

This page covers an aggregation of TypeQL Get query results.

== Usage

A Get query without aggregation or grouping returns a stream of ConceptMaps
to represent every matched solution for its pattern.
With aggregation, the query performs calculation on the collection of ConceptMaps and returns a single value.
Aggregation can be used alongside grouping and in subqueries, which affects the output.

TypeDB supports the following types of aggregation:

* <<_count>> -- Use the `count` keyword to get the total number of results returned.
* <<_sum>> -- Use the `sum` keyword to get the *sum* of the `long` or `double` values of the specified variable.
* <<_maximum>> -- Use the `max` keyword to get the *maximum* value among the `long` or `double` values of the specified variable.
* <<_minimum>> -- Use the `min` keyword to get the *minimum* value among the `long` or `double` values of the specified variable.
* <<_mean>> -- Use the `mean` keyword to get the average value of the `long` or `double` values of the specified variable.
* <<_median>> -- Use the `median` keyword to get the median value among the `long` or `double` values of the matched variable.
* <<_standard_deviation>> -- Use the `std` keyword to get the *sample standard deviation* value among
the `long` or `double` values of the matched variable.

== Examples

[#_count]
=== Count

.Count example
[,typeql]
----
match
$o isa object, has path $fp;
get $o, $fp;
count;
----

[#_sum]
=== Sum

.Sum example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
sum $s;
----

[WARNING]
====
Omitting the variable `$f` in the `get` clause of the above query will result in missing all duplicated values
of `$s` from the aggregation.
For more information,
see the xref:typeql::data/get.adoc#_number_of_results[number of results] section on the Get query page.
====

[#_maximum]
=== Maximum

.Maximum example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
max $s;
----

[#_minimum]
=== Minimum

.Minimum example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
min $s;
----

[#_mean]
=== Mean

.Mean example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
mean $s;
----

[#_median]
=== Median

.Median example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
median $s;
----

[#_standard_deviation]
=== Standard deviation

.Standard deviation example
[,typeql]
----
match
$f isa file, has size-kb $s;
get $f, $s;
std $s;
----

== Learn more

[cols-2]
--
.xref:typeql::modifiers/grouping.adoc[]
[.clickable]
****
Learn about results grouping in TypeQL.
****

.xref:typeql::data/get.adoc[]
[.clickable]
****
Learn about Get queries in TypeQL.
****
--