= Limit

This page covers the limit modifier for limiting the number of results returned by a data processing clause.
The limit modifier is often used with xref:modifiers/sort.adoc[] and xref:modifiers/offset.adoc[] modifiers for pagination.

== Syntax

A limit modifier syntax consists of the `limit` keyword followed by a natural number of results to return:

[,typeql]
----
limit <number> ;
----

where `<number>` is a positive whole number.

== Behavior

A limit modifier specifies the number of results to return in the output of a clause.
If there are more results, only the specified number of results are returned.
If there are fewer or the same number of results, then all results are returned.

[#_limit_the_results]
=== Limit the number of results

include::partial$iam-database-links.adoc[]

Use the `limit` keyword followed by the number of results to return.

.Limit example
[,typeql]
----
match
$p isa person, has full-name $n;
limit 2;
----

The above example has no `sort` modifier,
so it returns only two almost random names owned by entities of the `person` type.

== Usage

include::partial$iam-database-links.adoc[]

Combine `offset` and `limit` to paginate the results of a query.
By knowing the limit amount, we can use offset to get the full set of results in batches.
Make sure to also use sorting, as otherwise you can't guarantee the continuity of results between queries.

.Pagination example query 1
[,typeql]
----
match
$p isa person, has full-name $n;
sort $n;
limit 2;
----

The above query returns the first two results.

.Pagination example query 2
[,typeql]
----
match
$p isa person, has full-name $n;
sort $n;
offset 2;
limit 2;
----

The second query returns the next two results (skips two and returns another two).

By continuing to increase the `offset` value by the `limit` value we can traverse the results.
When we receive fewer results than set by the `limit` value, it should be a signal that we got all possible results.

== Learn more

[cols-2]
--
.xref:modifiers/sort.adoc[]
[.clickable]
****
Learn about sorting results in TypeQL.
****

.xref:modifiers/offset.adoc[]
[.clickable]
****
Learn about offsetting results in TypeQL.
****
--
