= Offset

This page covers the offset modifier for skipping the specified number of results from the beginning of the output
of a data processing clause.
The offset modifier is often used with xref:modifiers/sort.adoc[] and xref:modifiers/limit.adoc[] modifiers for pagination.

== Syntax

An offset modifier syntax consists of the `offset` keyword followed by a natural number of results to skip:

[,typeql]
----
offset <number> ;
----

where `<number>` is a positive whole number.

== Behavior

An offset modifier specifies the number of results to skip in the output of a clause.
If there are fewer or the same number of results, as the number specified for the `offset` clause,
then an empty stream of results is returned.

[#_offset_the_results]
=== Offset the results

include::partial$iam-database-links.adoc[]

Use the `offset` keyword followed by the number of results to skip.

.Offset example
[,typeql]
----
match
$p isa person, has full-name $n;
sort $n;
offset 2;
----

The above example sorts the `full-name` attributes of all `person` entities in ascending order (as default),
skips the first two results, and returns the rest of results.
