= Offset

== Behavior

Pagination in TypeQL queries makes it possible to return a range of results, rather than retrieving all results at once.
By <<_limit_the_results,limiting>> the query to return the first `x` results,
processing them, and then sending subsequent queries with an <<_offset_the_results,offset>>, incremented by `x`,
you can iterate through the entire result set in manageable batches.

xref:modifiers/sorting.adoc[Sorting] the results is strongly advised, but is not mandatory.
Without sorting, the ordering of results is not guaranteed and can be unpredictable.
Pagination relies on sorting to traverse the full set of results.

[#_offset_the_results]
=== Offset the results

include::partial$iam-database-links.adoc[]

Use the `offset` keyword followed by the number of results to skip.

.Offset example
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
sort $n;
offset 2;
----

The above example sorts the `full-name` attributes of all `person` entities in ascending order (as default),
skips the first two results, and returns the rest of results.