= Pagination

Pagination in TypeQL queries is possible with the usage of two modifiers: `offset` and `limit`.
The usage of the `sort` modifier to sort the results is highly recommended, but is not mandatory.

Without sorting, the order of results is not guaranteed.
That makes ordering unpredictable,
hence combination of `offset` and `limit` ineffective at traversing the full set of results.

== Offset the results

Use the `offset` keyword followed by the number of results to skip.

.Offset example
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
sort $n;
offset 2;
----

The above example sorts the `full-name` attributes of all `person` entities in ascending order (as default),
skips the first two results, and returns the rest of results.

[#_limit_the_results]
== Limit the number of results

Use the `limit` keyword followed by the number of results to return.

.Limit example
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
limit 2;
----

The above example has no `sort` modifier,
so it returns only two almost random names owned by entities of the `person` type.

== Using pagination

Combine `offset` and `limit` to paginate the results of a query.
By knowing the limit amount, we can use offset to get the full set of results in batches.
Make sure to also use sorting, as you can't guarantee the continuity of results between queries otherwise.

.Pagination example query 1
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
sort $n;
limit 2;
----

The above query returns the first two results.

.Pagination example query 2
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
sort $n;
offset 2;
limit 2;
----

The second query returns the next two results (skips two and returns another two).

By continuing to increase the `offset` value by the `limit` value we can traverse the results.
When we receive fewer results than set by the `limit` value, it should be a signal that we got all possible results.

== Learn more

[cols-2]
--
.xref:typeql::modifiers/sorting.adoc[]
[.clickable]
****
Learn about sorting results in TypeQL.
****

.xref:typeql::modifiers/aggregation.adoc[]
[.clickable]
****
Learn about aggregation of query results in TypeQL.
****
--
