= Sorting

== Usage

This page covers sorting query results by using the `sort` keyword in a TypeQL query.

Be default, query results are streamed by a TypeDB server in no particular guaranteed order.
This is the fastest way to retrieve results,
as they are being sent as soon as a new solution for the pattern used in a query found.

You can use a query modifier to sort them by one or multiple of the query variables.
That way, TypeDB server will need to collect all results first to guarantee the correct order.

To sort query results, use the `sort` keyword, followed by a variable.
You can sort by multiple variables by providing them as a comma-separated list.
Each variable can have an optional sorting order: `asc` for ascending or `desc` for descending.
By default, the ascending order is assumed to be ascending.

Sorting of the results can be important, for example, to preserver reproducibility of the result.
Without sorting, there are no guarantees for the ordering of the query results.

Sorting is often used in combination with pagination.
In this case, sorting goes before pagination in TypeQL query syntax.
For example, see the xref:typeql::modifiers/pagination.adoc[] page.

== Examples

Let's see an example of sorting results of a Get query:

.Get query sorting example
[,typeql]
----
match
$p isa person, has full-name $n;
get $n;
sort $n asc;
----

The above Get query returns sorted `full-name` attributes owned by entities of the `person` type.

For the Fetch query results sorting, you can see the example below:

.Fetch query sorting example
[,typeql]
----
match
$p isa person, has full-name $n;
fetch $p: full-name;
sort $n asc;
----

The above Fetch query returns sorted `full-name` attributes owned by entities of the `person` type.
Notice that there is no `$n` variable in the `fetch` clause of this query.
Sorting is performed on the results of the `match` clause,
so `fetch` clause determines only what data is projected into JSONs.
In this case, we are projecting all attributes of the `full-name` type owned by the `$p` already.
Adding `$n` to the `fetch` clause is possible, but redundant in this case.

== Learn more

[cols-2]
--
.xref:typeql::modifiers/pagination.adoc[]
[.clickable]
****
Learn about result pagination in TypeQL.
****

.xref:typeql::modifiers/aggregation.adoc[]
[.clickable]
****
Learn about aggregation of query results in TypeQL.
****
--
