= Introduction
:keywords: typedb, database, cloud, service, documentation, introduction, overview
:longTailKeywords: typedb cloud introduction, learn typedb cloud, typedb cloud vs typedb
:pageTitle: Introduction
:summary: A birds-eye view of TypeDB Cloud.

TypeDB Cloud is a DBaaS (Database as a service) specific for the TypeDB DBMS. Specifically TypeDB Enterprise clusters.

For more information on the difference between TypeDB editions, see the https://typedb.com/deploy[Deploy] page.

include::cloud::overview.adoc[tag=alpha-test-warning]

During the alpha test stage, user registration is limited to invite-only participants.

To request an invitation, use the following link:
https://typedb.com/deploy?dialog=cloud-waitlist[Join TypeDB Cloud Waitlist].

TypeDB Cloud manages infrastructure and TypeDB Enterprise clusters to provide a user-friendly web interface for
controlling and using deployments with minimum effort.

Fully automated cluster deployment and management lets us create, suspend, resume, and destroy a TypeDB Enterprise
cluster with a click of a button.

Automatic failover and replication ensure the data is safe and accessible.

End-to-end encryption ensures the security of operations.

Grouping of users in teams and organizations, as well as resources in projects provide scalability of processes and
billing details.
