= Quickstart guide
:keywords: start, typedb, cloud, quickstart, tutorial, registration
:longTailKeywords: getting started, get started with typedb cloud, typedb cloud tutorial, typedb cloud quickstart
:pageTitle: Quickstart guide
:summary: How to start using TypeDB Cloud.
:experimental:

== Overview

In this Quickstart guide, we will find out how to start using TypeDB Cloud:

* Get an account
* Log In
* Create a deployment
* Connect to a TypeDB Enterprise cluster

== Get an account

include::cloud::account.adoc[tag=create-account]

== Log in

include::cloud::account.adoc[tag=log-in]

== Create a deployment

include::cloud::deployments/management.adoc[tag=create]

Now that the deployment is being created all we need is to wait for the status of the deployment to become
`Fully available`.

== Connect to a deployment

To work with the deployment's TypeDB servers, we need to set up a TypeDB Client and connect it to the
deployment cluster.

// tag::default-credentials[]
[NOTE]
====
At this stage of alpha testing, all TypeDB Cloud deployments are created with the listening port of `1729`
and a default user with the following credentials:

Username: `admin` +
Password: `password`
====
// end::default-credentials[]

To connect to a TypeDB Cloud deployment we can use any TypeDB Client: see the xref:deployments/connect.adoc[] page
for more options.

For example, to connect via TypeDB Console:

// tag::console-connect[]
[,bash]
----
typedb console --cluster=<address> --username=admin --password=password --tls-enabled=true --tls-root-ca=<path_to_ca>
----

where:

*  `<address>` -- is the address of a server in the TypeDB Cloud installation we are connecting to,
including the port number. +
For example, `deployment-78678ca6-afda-4792-b5b8-0cb6b540d8ee-0.deployment-78678ca6-afda-4792-b5b8-0cb6b540d8ee.cloud.typedb.com:1729`.
* `admin` -- is the default username for the default user.
* `password` -- is the default password for the default user.
* `true` -- is the TLS encryption setting. It's true (enabled) by default.
* `<path_to_ca>` -- the path to the CA certificate.

.See example
[%collapsible]
====
[,bash]
----
typedb console --cluster=deployment-78678ca6-afda-4792-b5b8-0cb6b540d8ee-0.deployment-78678ca6-afda-4792-b5b8-0cb6b540d8ee.cloud.typedb.com:1729  --username=admin --password=password --tls-enabled=true --tls-root-ca=./typedb-cloud-root-ca.pem
----
====

As a result, we get a welcome message from TypeDB Console, and if the connection is successful,
it's followed by a command line prompt.

[,bash]
----
Welcome to TypeDB Console. You are now in TypeDB Wonderland!
Copyright (C) 2022 Vaticle

>
----

For more information on how to use TypeDB Console, see the xref:clients::console.adoc[] page.
// end::console-connect[]

For more information on how to connect with other TypeDB Clients, see the
xref:cloud::deployments/connect.adoc#_connection[Connect to a deployment] page.

== Learn more

Check the current account details on the xref:cloud::account.adoc[] page.

Find out how to manage deployments in the *Deployment management* section:

* xref:cloud::deployments/management.adoc[] -- how to create, destroy, suspend, and resume deployments.
* xref:cloud::deployments/connect.adoc[] -- how to connect to a server in a deployment with TypeDB Clients.
* xref:cloud::deployments/projects.adoc[] -- how to group deployments for easier management.

Explore the user management options in the *User management* section:

* xref:cloud::user-management/user.adoc[] -- how to create, delete, and see details of a user.
* xref:cloud::user-management/team.adoc[] -- how to group users in teams for easier management.
* xref:cloud::user-management/organization.adoc[] -- how to manage an organization.
