= Crash course - document database users

This crash course pathway is designed to give a concise overview of the main aspects of working with TypeDB and TypeQL for users coming from document databases. If you do not have experience with document databases, you can check out our xref:home::crash-course/index.adoc#_pathways[other pathways] instead. Document query examples in this crash course use MongoDB syntax.

[NOTE]
====
If you would like to follow along with the examples in this crash course, make sure you have completed the xref:home::crash-course/index.adoc[environment setup].
====

== Coming from document databases

== Key similarities and differences

== Terminology comparison

== What's next?

Continue learning how to use TypeDB with TypeDB Academy, or explore other sections of the documentation.

[cols-2]
--
.xref:academy::index.adoc[]
[.clickable]
****
An end-to-end learning experience for TypeDB and TypeQL, showing how to take advantage of TypeDB's unique features.
****

.xref:manual::index.adoc[TypeDB manual]
[.clickable]
****
Practice-oriented guides on using TypeDB, including the TypeDB Studio and TypeDB Console manuals.
****

.xref:drivers::index.adoc[TypeDB drivers]
[.clickable]
****
Installation guides, tutorials, and API references for the official TypeDB drivers in all supported languages.
****

.xref:typeql::index.adoc[TypeQL reference]
[.clickable]
****
Complete language reference for TypeQL, covering all query types, pattern elements, and keywords.
****
--
