= C++ driver
:Summary: Overview for TypeDB C++ driver.
:keywords: typedb, client, driver, c++, cpp, clang
:pageTitle: TypeDB C++ driver

The C\++ driver was developed by Vaticle to enable TypeDB support for C++ software and developers.

[cols-2]
--
.link:https://github.com/vaticle/typedb-driver/tree/development/cpp[GitHub,window=_blank]
[.clickable]
****

****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%27%5Etypedb-driver-cpp%27&sort=-version[Downloads,window=_blank]
[.clickable]
****

****
--

[#_install_cpp]
== Install

=== Prerequisites

See the
<<_version_compatibility>> table to check what versions of TypeDB and Python driver are compatible.

For Linux: the minimum version of `glibc` is `2.25.0`.

To install TypeDB C++ driver:

1. https://github.com/vaticle/typedb-driver/releases[Download] the latest release for you architecture (`x86_64`/`arm64`)
and OS (Linux/macOS/Win).
2. Include the header file `typedb_driver.hpp` from the `include` directory. See an example of `CMakeLists.txt` below.
+
.CMakeLists.txt example
[,source]
----
cmake_minimum_required(VERSION 3.27)
project(cpp_driver_test)

set(CMAKE_CXX_STANDARD 17)
link_directories(${PROJECT_SOURCE_DIR}/lib)
include_directories(${PROJECT_SOURCE_DIR}/include)

add_executable(cpp_driver_test typedb_test.cpp)
IF (WIN32)
    target_link_libraries(cpp_driver_test ${PROJECT_SOURCE_DIR}/lib/typedb-driver-cpp.if.lib)
ELSE()
    target_link_libraries(cpp_driver_test typedb-driver-cpp)
ENDIF()
----

== Quickstart

See below a short example of Python code that connects to a local TypeDB Core,
creates a database named `access-management-db`, defines a schema, inserts some data, and then reads it.

[,cpp]
----
TypeDB::Driver driver = TypeDB::Driver::coreDriver("localhost:1729");
    TypeDB::Options options;
    driver.databases.create("access-management-db");
    {
        TypeDB::Session sess = driver.session("access-management-db", TypeDB::SessionType::SCHEMA, options);
        TypeDB::Transaction tx = sess.transaction(TypeDB::TransactionType::WRITE, options);
        tx.query.define(accessManagementSchema, options).wait();
        tx.commit();
    }
    {
        TypeDB::Session sess = driver.session("access-management-db", TypeDB::SessionType::DATA, options);

        for (auto& batch: accessManagementDataBatches) {
            TypeDB::Transaction tx = sess.transaction(TypeDB::TransactionType::WRITE, options);
            for (auto& query: batch) {
                tx.query.insert(query, options);
            }
            tx.commit();
        }
        {
            TypeDB::Transaction tx = sess.transaction(TypeDB::TransactionType::READ, options);
            ConceptMapIterable results = tx.query.get("match $o1 has $o2; get;", options);
        }
    }
----
//#todo Add the code above

For more code examples, see the Tutorial and Driver API links below.

== Learn more

[cols-2]
--
////
.xref:drivers::python/tutorial.adoc[Tutorial]
[.clickable]
****
This tutorial will help you learn how to use the Python driver.
****
////
.xref:python/api-reference.adoc[API reference]
[.clickable]
****
Driver API reference for the Python language.
****
--

include::drivers::partial$drivers2discord.adoc[]

[#_version_compatibility]
== Version Compatibility

[cols="^.^3,^.^2,^.^3,^.^3,^.^1"]
|===
| C++ driver | Protocol encoding version | TypeDB Core | TypeDB Cloud | C++

| 2.26.5
| 3
| 2.26.3
| 2.26.0
| https://www.iso.org/standard/68564.html[17]
|===
