= TypeDB Console installation guide

TypeDB Console is the default CLI client for TypeDB.
Both TypeDB Core and TypeDB Cloud are usually distributed with a compatible version of TypeDB Console.
To install TypeDB Console separately, use the guide below.
If you are unsure of the exact version you need,
check the <<_version_compatibility,compatibility table>> below.

[cols-3]
--
.link:https://github.com/vaticle/typedb-console[GitHub,window=_blank]
[.clickable]
****
See source code and release notes.
****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console&sort=-version[Downloads]
[.clickable]
****
See downloadable packages.
****

.xref:manual::console.adoc[TypeDB Console Manual]
[.clickable]
****
See documentation.
****
--

== Install

Make sure Java 11+ is installed.
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/#java11[Oracle JDK,window=_blank].

For installation instructions, follow the steps below for your OS:

[tabs]
====
macOS::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-console-latest-links.adoc[tag=mac]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-mac&sort=-version[Downloads repository] page.
. Extract the archive into a new directory:
+
[source,console]
----
$ sudo mkdir /opt/typedb-console
$ unzip ~/Downloads/<filename>.zip -d /opt/typedb-console
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB Console executable in the `/usr/local/bin` directory:
+
[source,console]
----
$ ln -s /opt/typedb-console/<filename>/typedb /usr/local/bin/typedb
----
--

Linux::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-console-latest-links.adoc[tag=linux]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-linux&sort=-version[Downloads repository] page.
. Extract the archive into a new directory:
+
[source,console]
----
$ mkdir /opt/typedb-console
$ tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb-console
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB Console executable in the `/usr/local/bin` directory:
+
[source,console]
----
$ ln -s /opt/typedb-console/<filename>/typedb /usr/local/bin/typedb
----
--

Windows::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-console-latest-links.adoc[tag=windows]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-win&sort=-version[Downloads repository] page.

. Extract the archive into a new directory:
+
[source,console]
----
$ mkdir "C:\Program Files\TypeDB Console"
$ tar xvf "C:\Users\username\Downloads\<filename>.zip" -C "C:\Program Files\TypeDB Console"
----
+
Where `<filename>` is the name of the archive.
. Update the `PATH` environment variable:
+
[source,console]
----
$ setx /M PATH "%path%;C:\Program Files\TypeDB Console\<filename>"
----

Restart the terminal window for the changes to environment variables to take effect.
--
====

== Run

To run TypeDB Console:

[source,console]
----
$ typedb console
----

For more information on how to use TypeDB Console, see the xref:manual::console.adoc[] page.

[#_version_compatibility]
== Version Compatibility

include::manual::console.adoc[tags="latest-compatibility,older-compatibility"]
