= TypeDB Console installation guide

TypeDB Console is the default CLI client for TypeDB.
Both TypeDB Core and TypeDB Cloud are usually distributed with a compatible version of TypeDB Console.
To install TypeDB Console separately, use the guide below.

If you are unsure of the exact version you need,
check the <<_version_compatibility,compatibility table>> below.

[cols-3]
--
.link:https://github.com/vaticle/typedb-console[GitHub,window=_blank]
[.clickable]
****
See source code and release notes.
****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console&sort=-version[Downloads]
[.clickable]
****
See downloadable packages.
****

.xref:manual::console.adoc[TypeDB Console Manual]
[.clickable]
****
See documentation.
****
--

== Install

Make sure Java 11+ is installed.
TypeDB supports https://jdk.java.net[OpenJDK,window=_blank] and
https://www.oracle.com/java/technologies/downloads/#java11[Oracle JDK,window=_blank].

For installation instructions, follow the steps below for your OS:

[tabs]
====
macOS::
+
--
. Download the latest package for your systems architecture:
https://repo.typedb.com/public/public-release/raw/names/typedb-console-mac-x86_64/versions/2.26.6/typedb-console-mac-x86_64-2.26.6.zip[x86/x64] |
https://repo.typedb.com/public/public-release/raw/names/typedb-console-mac-arm64/versions/2.26.6/typedb-console-mac-arm64-2.26.6.zip[arm64]. +
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-mac&sort=-version[Downloads repository] page.
. Extract the archive into a new directory:
+
[,bash]
----
sudo mkdir /opt/typedb-console
unzip ~/Downloads/<filename>.zip -d /opt/typedb-console
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB Console executable in the `/usr/local/bin` directory:
+
[,bash]
----
ln -s /opt/typedb-console/<filename>/typedb /usr/local/bin/typedb
----
--

Linux::
+
--
. Download the latest package for your systems architecture:
https://repo.typedb.com/public/public-release/raw/names/typedb-console-linux-x86_64/versions/2.26.6/typedb-console-linux-x86_64-2.26.6.tar.gz[x86/x64] |
https://repo.typedb.com/public/public-release/raw/names/typedb-console-linux-arm64/versions/2.26.6/typedb-console-linux-arm64-2.26.6.tar.gz[arm64]. +
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-linux&sort=-version[Downloads repository] page.
. Extract the archive into a new directory:
+
[,bash]
----
mkdir /opt/typedb-console
tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb-console
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB executable in the `/usr/local/bin` directory:
+
[,bash,subs=attributes+]
----
ln -s /opt/typedb-console/<filename>/typedb /usr/local/bin/typedb
----
--

Windows::
+
--
. Download the latest package for your systems architecture:
https://repo.typedb.com/public/public-release/raw/names/typedb-console-windows-x86_64/versions/2.26.6/typedb-console-windows-x86_64-2.26.6.zip[x86/x64]. +
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=format%3Araw+name%3A%5Etypedb-console-win&sort=-version[Downloads repository] page.

. Extract the archive into a new directory:
+
[,shell]
----
mkdir "C:\Program Files\TypeDB Console"
tar xvf "C:\Users\username\Downloads\<filename>.zip" -C "C:\Program Files\TypeDB Console"
----
+
Where `<filename>` is the name of the archive.
. Update the `PATH` environment variable:
+
[,shell]
----
setx /M PATH "%path%;C:\Program Files\TypeDB Console\<filename>"
----

Restart the terminal window for the changes to environment variables to take effect.
--
====

== Run

To run TypeDB Console:

[,bash]
----
typedb console
----

For more information on how to use TypeDB Console, see the xref:manual::console.adoc[] page.

[#_version_compatibility]
== Version Compatibility

[cols="^.^2,^.^1,^.^2,^.^2"]
|===
| TypeDB Console | Protocol encoding version | TypeDB Core | TypeDB Cloud

| https://github.com/vaticle/typedb-console/releases/tag/2.26.6[2.26.6]
| 3
| 2.26.6
| 2.26.6

| https://github.com/vaticle/typedb-console/releases/tag/2.25.7[2.25.7]
| 3
| 2.25.7
| 2.25.7

| https://github.com/vaticle/typedb-console/releases/tag/2.24.15[2.24.15]
| 2
| 2.24.17
| 2.24.17

| https://github.com/vaticle/typedb-console/releases/tag/2.18.0[2.18.0]
| 1
| 2.18.0 to 2.23.0
| 2.18.0 to 2.23.0

| https://github.com/vaticle/typedb-console/releases/tag/2.17.0[2.17.0]
| N/A
| 2.17.0
| 2.17.0
|===

.See older versions
[%collapsible]
====
[cols="^.^2,^.^1,^.^2,^.^2"]
|===
| TypeDB Console | Protocol encoding version | TypeDB Core | TypeDB Cloud

| 2.16.1
| N/A
| 2.16.1
| 2.16.1 to 2.16.2

| 2.15.0
| N/A
| 2.15.0
| 2.15.0

| 2.14.2
| N/A
| 2.14.2 to 2.14.3
| 2.14.1

| 2.14.0
| N/A
| 2.14.0 to 2.14.1
| 2.14.1

| 2.12.0
| N/A
| 2.12.0 to 2.13.0
| 2.12.0 to 2.13.0

| 2.11.0
| N/A
| 2.11.0 to 2.11.1
| 2.11.1 to 2.11.2

| 2.10.0
| N/A
| 2.10.0
| 2.10.0

| 2.9.0
| N/A
| 2.9.0
| 2.9.0

| 2.8.0
| N/A
| 2.8.0 to 2.8.1
| 2.5.0

| 2.6.1
| N/A
| 2.6.1 to 2.7.1
| 2.5.0

| 2.6.0
| N/A
| 2.6.0
| 2.5.0

| 2.5.0
| N/A
| 2.5.0
| 2.3.0

| 2.4.0
| N/A
| 2.4.0
| 2.3.0

| 2.3.2
| N/A
| 2.3.2 to 2.3.3
| 2.3.0

| 2.3.1
| N/A
| 2.3.1
| 2.3.0

| 2.3.0
| N/A
| 2.3.0
| 2.3.0

| 2.1.3
| N/A
| 2.1.3 to 2.2.0
| 2.1.2

| 2.1.2
| N/A
| 2.1.2
| 2.0.3

| 2.1.1
| N/A
| 2.1.1
| 2.0.3

| 2.1.0
| N/A
| 2.1.0
| 2.0.3

| 2.0.1
| N/A
| 2.0.1 to 2.0.2
| 2.0.1 to 2.0.2

| 2.0.0
| N/A
| 2.0.0
| 2.0.0

| 1.0.8
| N/A
| 1.1.0 to 1.8.4
| -
|===
====
