= TypeDB Core installation guide
:tabs-sync-option:
// Goal – Install TypeDB Core

This page is an installation guide for TypeDB Core.
TypeDB Core can be installed in multiple ways: using <<_docker,Docker>>, via <<_package,package manager>>, or by
<<_manual,manual installation>>.

For self-hosted TypeDB Cloud installation and setup,
see the xref:home::install/cloud-self-hosted.adoc[Self-hosted deployment] page.

[#_docker]
== Docker

include::home::partial$docker.adoc[tag=install]

[#_package]
== Package manager

[tabs]
====
macOS::
+
--
include::home::partial$macos.adoc[tag=install-homebrew]
--

Linux::
+
--
include::home::partial$linux.adoc[tag=install-apt]
--

Windows::
+
--
No package manager option is available for Windows. See the <<_manual>> section below.
--
====

//To learn how to run TypeDB Core, see the xref:home::quickstart.adoc[] guide.

[#_manual]
== Manual install

Download the latest version of TypeDB Core from the table below.

[cols="^.^1,^.^1,^.^1,^.^1",caption="",options="header"]
|===
|Release notes |macOS |Linux |Windows

include::manual:resources:partial$latest-version.adoc[]
|===

For all versions, see the xref:manual:resources:releases.adoc[] page.

[tabs]
====
macOS::
+
--
include::home::partial$macos.adoc[tag=manual-install]
--

Linux::
+
--
include::home::partial$linux.adoc[tag=manual-install]
--

Windows::
+
--
include::home::partial$win.adoc[tag=manual-install]
--
====

////
[#_run_typedb_core]
== Run TypeDB Core

=== Start

// tag::core-run[]
To start a local TypeDB Core server:

[,bash]
----
typedb server
----

To run TypeDB Core in a new Docker container:

[,bash]
----
docker run --name typedb -d -v typedb-data:/opt/ -p 1729:1729 --platform linux/amd64 vaticle/typedb:latest
----
// end::core-run[]

[NOTE]
====
To learn how to use TypeDB, see the xref:home::quickstart.adoc[] guide,
xref:home::25-queries.adoc[] page, and the xref:learn::course-overview.adoc[Learn] category.
====

=== Stop

To stop a local TypeDB server, close the terminal with it or press kbd:[Ctrl+C].

For a Docker container:

include::home::partial$docker.adoc[tag=stop]
////

== Learn more


[cols-2]
--
.xref:home::install/studio.adoc[]
[.clickable]
****
Install an IDE that facilitates the development process for TypeDB.
****

.xref:home::quickstart.adoc[]
[.clickable]
****
Learn how to run TypeDB, connect to it, and run queries.
****

.xref:home::25-queries.adoc[]
[.clickable]
****
Try the features of TypeDB with these carefully selected queries.
****

.xref:learn::course-overview.adoc[Learning course]
[.clickable]
****
Check out our dedicated Learning course for TypeDB.
****
--
