= Installation

include::home::overview.adoc[tag=rust-rewrite]

== Deploy TypeDB

TypeDB is available in two editions: Cloud and Core.

[cols-2]
--
.link:https://cloud.typedb.com/[TypeDB Cloud]
[.clickable]
****
Create a new production-ready deployment of TypeDB Cloud with advanced security and high-availability features.
****

.xref:home::install/core.adoc[TypeDB Core]
[.clickable]
****
Install a 100% open source version of TypeDB with everything developers need to start building on TypeDB.
****
--

== TypeDB clients

There are three types of clients available for TypeDB: Studio, Console, and language-specific drivers.

[cols-2]
--
.xref:home::install/studio.adoc[Studio]
[.clickable]
****
Install an IDE that facilitates the development process for TypeDB databases.
****

.xref:home::install/console.adoc[Console]
[.clickable]
****
Install a powerful CLI tool with interactive(REPL) and non-interactive (script) modes.
****
--

== Drivers

[cols-3]
--
.xref:drivers::rust/overview.adoc[Rust]
[.clickable]
****

****
.xref:drivers::python/overview.adoc[Python]
[.clickable]
****

****
.xref:drivers::java/overview.adoc[Java]
[.clickable]
****

****
.xref:drivers::nodejs/overview.adoc[Node.js]
[.clickable]
****

****
.xref:drivers::cpp/overview.adoc[C++]
[.clickable]
****

****
--
