= TypeDB Studio installation guide

TypeDB Studio is a standalone IDE for TypeDB.
If you are unsure of the exact version you need,
check the <<_version_compatibility,compatibility table>> below.

[cols-3]
--
.link:https://github.com/vaticle/typedb-studio[GitHub,window=_blank]
[.clickable]
****
See source code and release notes.
****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio&sort=-version[Downloads]
[.clickable]
****
See downloadable packages.
****

.xref:manual::studio.adoc[TypeDB Studio Manual]
[.clickable]
****
See documentation.
****
--

[#_studio_install]
== Install

For installation instructions, follow the steps below for your OS:

[tabs]
====
macOS::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=mac]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-mac&sort=-version[Downloads repository] page.
. Open the downloaded `.dmg` file and accept the license agreement.
. Drag and drop TypeDB Studio executable to the Applications folder.

Alternatively, you can use Brew to install TypeDB Studio:

[source,console]
----
$ brew tap vaticle/tap
$ brew install --cask vaticle/tap/typedb-studio
----
--

Linux::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=linux]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-linux&sort=-version[Downloads repository] page.
. Extract the archive with TypeDB Studio into a new directory, for example:
+
[source,console]
----
$ mkdir /opt/typedb-studio
$ tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb-studio
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB Studio executable in the `/usr/local/bin` directory, for example:
+
[source,console]
----
$ ln -s /opt/typedb-studio/<filename>/typedb-studio /usr/local/bin/typedb-studio
----
--

Windows::
+
--
. Download the latest installer:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=windows]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-windows&sort=-version[Downloads repository] page.
. Run the downloaded `.exe` file and follow the installation wizard.
--
====

== Run

To launch TypeDB Studio, locate its executable/binary file and run it.

For more information on how to use TypeDB Studio, see the xref:manual::studio.adoc[] manual.

[#_version_compatibility]
== Version Compatibility

include::manual::studio.adoc[tags="latest-compatibility,older-compatibility"]
