= TypeDB Studio installation guide

TypeDB Studio is a standalone IDE for TypeDB. If you are unsure of the version you need, check the <<_version_compatibility,compatibility table>> below.

[cols-3]
--
.link:https://github.com/typedb/typedb-studio[GitHub,window=_blank]
[.clickable]
****
See source code and release notes.
****

.link:https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio&sort=-version[Downloads]
[.clickable]
****
See downloadable packages.
****

.xref:{page-component-version}@manual::studio.adoc[TypeDB Studio Manual]
[.clickable]
****
See documentation.
****
--

[#_package]
== Package manager

[tabs]
====
macOS::
+
--
To install TypeDB Studio via Homebrew:

[source,console]
----
brew tap typedb/tap
brew install --cask typedb/tap/typedb-studio
----
--

Linux::
+
--
. Add the TypeDB repository:
+
[source,console]
----
sudo apt install software-properties-common apt-transport-https gpg
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 17507562824cfdcc
gpg --export 17507562824cfdcc | sudo tee /etc/apt/trusted.gpg.d/typedb.gpg > /dev/null
echo "deb https://repo.typedb.com/public/public-release/deb/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/typedb.list > /dev/null
sudo apt update
----
. Install TypeDB Studio:
+
[source,console]
----
sudo apt install typedb-studio
----
--

Windows::
+
--
No package manager option is available for Windows. See the <<_manual>> section below.
--
====

[#_manual]
== Manual install

[tabs]
====
macOS::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=mac]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-mac&sort=-version[Downloads repository] page.
. Open the downloaded `.dmg` file and accept the license agreement.
. Drag and drop TypeDB Studio executable to the Applications folder.
--

Linux::
+
--
. Download the latest package for your system architecture:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=linux]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-linux&sort=-version[Downloads repository] page.
. Extract the archive with TypeDB Studio into a new directory, for example:
+
[source,console]
----
mkdir /opt/typedb-studio
tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb-studio
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB Studio executable in the `/usr/local/bin` directory, for example:
+
[source,console]
----
ln -s /opt/typedb-studio/<filename>/typedb-studio /usr/local/bin/typedb-studio
----
--

Windows::
+
--
. Download the latest installer:
include::manual:resources:partial$typedb-studio-latest-links.adoc[tag=windows]
+
For other versions, see the
https://cloudsmith.io/~typedb/repos/public-release/packages/?q=name%3A%5Etypedb-studio-windows&sort=-version[Downloads repository] page.
. Run the downloaded `.exe` file and follow the installation wizard.
--
====

== Run

To launch TypeDB Studio, locate its executable/binary file and run it.

For more information on how to use TypeDB Studio, see the xref:{page-component-version}@manual::studio.adoc[] manual.

[#_version_compatibility]
== Version Compatibility

include::{page-component-version}@manual::studio.adoc[tags="latest-compatibility,older-compatibility"]
