= How to create a new TypeDB Client
:Summary: Tutorial on how to build a new TypeDB Client.
:keywords: typedb, client, driver, grpc
:longTailKeywords: TypeDB client, building new client, developing new driver
:pageTitle: How to create a new TypeDB Client

This tutorial can guide us through the very beginning of creating a new TypeDB Client. We strongly recommend
using one of the existing TypeDB Clients first to gain some experience with the TypeDB. See the list of available
Clients on the xref:../../02-clients/00-clients.adoc[Clients overview] page.

There are many places we could start building a TypeDB Client.
In this tutorial, we start by attempting to make a single gRPC call to a TypeDB server to create a database.

== Step 1: Create the main function to connect to a server

Create a `TypeDB` source file in the root of the project, which should expose a function named `coreClient`,
taking `address` as a parameter.

////
#todo add the imports!

// TypeDB.java
# moved it outside the next code block. To test whether it will fix the indentation
-
////

[Important] Import statements are not included in this tutorial, except when importing from external libraries such as the TypeDB protobuf definitions.

[tab:Java]

== Step 2: Database manager

`TypeDBClient` is not yet defined. Create a new directory named `api/connection` and create a `TypeDBClient` file there:

[Note] if your language doesn't have interfaces or abstract classes, make `TypeDB.coreClient` return `CoreClient` instead, and skip this step.

[tab:Java]

== Step 3: gRPC connection implementation

The next step is to implement `connection/TypeDBClient` and its subclass `connection/core/CoreClient`.
Create the directory structure: `connection/core` in the root of your project.

Name the classes depending on language conventions: in Java/TypeScript, `TypeDBClientImpl` and `CoreClient`; in Python,
`_TypeDBClient` and `_CoreClient`.

Ensure that you've imported gRPC into your project, and refer to the https://grpc.io/docs/languages/[gRPC docs] to
learn how to create a Channel - the code varies by language.

[Note] In languages with no inheritance, adhere to this project structure as closely as possible, perhaps by writing top-level functions in the respective locations.

[tab:Java]

== Step 4: Implementing database creation

Finally, we implement `DatabaseManager`, and `CoreStub` to set up gRPC calls to the server.

[Important] You'll need to compile TypeDB's [protocol](https://github.com/vaticle/typedb-protocol) in order to do this. Most languages have protobuf compilers that you can use to generate a TypeDB protocol library for your language.

[tab:Java]

== Step 5: Testing

At this point, we have all the necessary components to create a database!
xref:../01-start/02-installation.adoc[Run the TypeDB server locally] and
create a test function:

[tab:Java]

Run the test function.

Now we can verify that the database was created successfully using
link:../../02-clients/02-console.md#database-management-commands[TypeDB Console] `database list` command, or
by running the test again (which will throw an error saying that the database already exists).

That concludes the basics tutorial for creating a new TypeDB Client.

Refer to the xref:../../02-clients/07-new-client.adoc[Developing a new TypeDB Client] page for more information of the
remaining components needed to open transactions, run queries, and take the client to 100% completion.

We recommend using one of our existing Clients as a reference, and copying the implementation into your chosen language.
