= Undefine clause
:Summary: Undefine schema types and functions from a schema
:keywords: typeql, schema, undefine, clause, delete, remove, truncate, type, function
:pageTitle: Undefine clause

An Undefine clause removes type and function definition from a schema.

For a practical guide on how to send an Undefine query to TypeDB,
see the xref:{page-component-version}@manual::defining/undefine.adoc[] page of the TypeDB Manual.

// For more information on the limitations of schema manipulation, see the
// xref:{page-component-version}@home::acid.adoc#_schema_integrity[Schema integrity enforcement].

[#_syntax]
== Syntax

// tag::syntax[]
An Undefine clause consists of a single `undefine` clause and always starts with the `undefine` keyword.

Undefine queries are written in TypeQL with the following syntax:

[,typeql]
----
undefine <schema_definitions>
----

Where `<schema_definitions>` are valid TypeQL schema-specific statements:
xref:statements/sub.adoc[],
xref:statements/owns.adoc[],
xref:statements/value.adoc[],
xref:statements/relates.adoc[],
xref:statements/plays.adoc[],
and annotations: xref:annotations/key.adoc[] and xref:annotations/unique.adoc[].
Schema statements in a `undefine` clause can't use any variables or values.
// end::syntax[]

== Behavior

// tag::behavior[]
An Undefine clause deletes the parts of the schema specified in its `undefine` clause, including types, functions,
roles, and ownerships.
Undefining a type also undefines all ownerships of attribute types and all roles of that type.

=== Clause execution

[#_undefine_a_type_with_a_subtype]
For an undefine clause to succeed, the following must be satisfied:

* Types that are to be deleted must _exist_.
* Types that are to be deleted can have neither _subtypes_ nor _instances of data_. 
* An undefine clause must result in a _valid_ schema state.

Undefining the same definition twice will result in an error.

=== Clause response

Undefine queries return a promise of an empty response.
// end::behavior[]

== Undefine types

include::partial$iam-database-links.adoc[]

Use a schema statement to delete from a schema in an Undefine clause:

.Undefine type example
[,typeql]
----
undefine

number sub attribute;
database owns name;
----

The above example deletes from a schema the attribute type `number` and ownership of the attribute type `name` by the
entity type `database`.

== Undefine functions

include::partial$iam-database-links.adoc[]

To delete a function, use the `fun` keyword with function's label:

.Undefine a function example
[,typeql]
----
undefine

fun add-view-permission;
----

== Learn more

[cols-2]
--
.xref:{page-component-version}@learn::5-defining-schemas/overview.adoc[]
[.clickable]
****
Learn more about defining a schema in the TypeDB Learning course.
****

.xref:{page-component-version}@manual::defining/undefine.adoc[]
[.clickable]
****
See how to send an Undefine query to TypeDB.
****
--
