= Conjunction (AND)

A conjunction is a pattern operation that requires that all patterns to be true simultaneously.

== Syntax

There is no specific syntax to apply conjunctions:
conjunctions are applied implicitly to all statements or patterns delineated by a semicolon `;`:

.Syntax
[,typeql]
----
<pattern>; <pattern>; [ <pattern>; ... ]
----

where `<pattern>` is _any valid pattern_.
We added the semicolon `;` to emphasize that patterns _always end_ with a semicolon `;`.
Note, each `<pattern>` itself may be a conjunction of smaller patterns or individual
xref:statements/overview.adoc[statements].

[IMPORTANT]
====
Conjunction is used by default in any pattern:
it is implicitly applied between all statements separated with a semicolon.
====

== Behavior

All patterns in a conjunction must be true for the conjunction itself to be true.
Thus, if any statement in a conjunction is false, then the whole pattern is false.
//#todo expand disjunction behavior with detailed explanation

The ordering of statements in a conjunction is irrelevant,
as every statement is equally important for the whole pattern.

== Usage in a match clause

include::partial$iam-database-links.adoc[]

Let's fetch a `path` attribute for every file that a user with full-name "Kevin Morrison" has a permission to modify.
There are multiple statements we need to combine with a conjunction for them all to be matched by every solution:

// .Conjunction example
// [,typeql]
// ----
// match
// $p isa person, has full-name $name;
// $name contains "kevin";
// $p has email $email;
// fetch
// $email;
// ----

.Conjunction example
[,typeql]
----
$user isa user, has full-name 'Kevin Morrison';
($user, $access) isa permission;
$obj isa object, has path $path;
$access($obj, $act) isa access;
$act isa action, has name 'modify_file';
----

In the above example, all statements must be True for the solution to be found.

.See fetch output example
[%collapsible]
====
For example, if we use this pattern in a `match` clause with a subsequent `fetch $path` post-processing,
we would get the following or similar results:

.Output example (partial)
[,json]
----
{ "path": { "value": "iopvu.java", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "path": { "value": "README.md", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "path": { "value": "budget_2021-08-01.xlsx", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
----
====

== Learn more

[cols-2]
--
.xref:patterns/disjunction.adoc[]
[.clickable]
****
Learn more about disjunction in TypeQL.
****

.xref:patterns/negation.adoc[]
[.clickable]
****
Learn more about negation in TypeQL.
****

.xref:statements/overview.adoc[]
[.clickable]
****
Learn more about statements used in TypeQL patterns.
****
--
