= Disjunction (OR)

A disjunction is a pattern operation that requires that at least one of its patterns to be true.

== Syntax

A disjunction block of two or more pattern has the following syntax:

.Syntax
[,typeql]
----
"{" <pattern> "}" or "{" <pattern> "}" [ or "{" <pattern> "}" ... ] ;
----

where `<pattern>` can be _any valid pattern_.
Note that _at least one variable_ in the `<pattern>` must be bound outside the disjunction.

== Behavior

Disjunctions can be used in a data clause or function to create alternative constraints.
Matching one of the branches is enough for the solution to be returned.
//#todo expand disjunction behavior with detailed explanation

=== Optional variables with disjunction

Disjunction of patterns can create optional variables, existing only for some results in a stream of Concept Maps.
For more information on ragged streams and optionals, see the xref:patterns/optionality.adoc[] page.

== Disjunction of statements

include::partial$iam-database-links.adoc[]

One of the uses of a disjunction is to retrieve instances of different types.
As a simple and one of the most common examples,
let's retrieve all data from a database by using a disjunction with all three root types:

.Data retrieval example
[,typeql]
----
match
$s isa $t;
{$t type entity;} or {$t type relation;} or {$t type attribute;};
----

The above query returns all data instances from a database and their types as stateful objects.

== Disjunction of patterns

Let's retrieve entities that can be of either `person` or `file` entity type and fetch their attributes, either
a `full-name` or a `path` respectively:

.Disjunction example
[,typeql]
----
match
$x isa $type;
{$type type person; $x has full-name $name;} or {$type type file; $x has path $name;};
fetch
$name;
----

.See example output
[%collapsible]
====
.Output example (partial)
[,json]
----
{ "name": { "value": "Kevin Morrison", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "name": { "value": "Masako Holley", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "name": { "value": "Pearle Goodman", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
{ "name": { "value": "axidw.java", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "name": { "value": "budget_2021-08-01.xlsx", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
{ "name": { "value": "README.md", "type": { "label": "path", "root": "attribute", "value_type": "string" } } }
----
====

== Learn more

[cols-2]
--
.xref:patterns/conjunction.adoc[]
[.clickable]
****
Learn more about conjunction in TypeQL.
****

.xref:patterns/negation.adoc[]
[.clickable]
****
Learn more about negation in TypeQL.
****

.xref:statements/overview.adoc[]
[.clickable]
****
Learn more about statements used in TypeQL patterns.
****
--
