= Negation

Negation pattern block is used to exclude some concepts from a result.

== Syntax

The syntax of a negation block:

.Syntax
[,typeql]
----
not { <negated-pattern> };
----

Where `<negated-pattern>` can be any valid pattern with at least one variable bound outside the negation.

== Behaviour

Negations can be used in a `match` clause or a condition of a rule
to set a constraint of not matching the negated pattern.
//#todo expand negation behaviour with detailed explanation

We understand pattern negation in terms of computation of *set differences*.
The set-difference semantics is different to the perhaps familiar semantics of Negation-as-Failure of Prolog.

include::typeql::partial$iam-database-links.adoc[]

== Usage in a match clause

The most direct approach to using negation is to specify a pattern for all results that need to be excluded.

Let's try to get all users except those who have a `full-name` attribute with a particular value:

.Negation exclusion example
[,typeql]
----
match
$u isa user;
not {$u has full-name "Kevin Morrison";};
fetch
$u as "Not Kevin": full-name;
----

.See example output
[%collapsible]
====
.Output example (partial)
[,json]
----
{
    "Not Kevin": {
        "full-name": [ { "value": "Bob Fake", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } ],
        "type": { "label": "person", "root": "entity" }
    }
}
----
====

== Usage in a rule condition

Negation can be used in a rule condition in the same way as it can be used in a `match` clause.

There is no need to negate the conclusion of a rule, as the rule will not repeat itself if there is nothing to change.

Let's create a rule to create complementary valued attributes for the `validity` of `permission` relations:

.Negation in a rule example
[,typeql]
----
define
rule permission-non-validity: when {
    $permission isa permission;
    not { $permission has validity true; };
} then {
    $permission has validity false;
};
----

== Learn more

[cols-2]
--
.xref:typeql::patterns/conjunction.adoc[]
[.clickable]
****
Learn more about conjunction in TypeQL.
****

.xref:typeql::patterns/disjunction.adoc[]
[.clickable]
****
Learn more about disjunction in TypeQL.
****

.xref:typeql::statements/overview.adoc[]
[.clickable]
****
Learn more about statements in TypeQL patterns.
****
--
