= Negation (NOT)

A negation is a pattern operation that requires that the negated pattern to be false.

== Syntax

A negation of a pattern has the following syntax:

.Syntax
[,typeql]
----
not "{" <pattern> "}" ;
----

where `<pattern>` can be any valid pattern.
Note that _at least one variable_ of `<pattern>` must be bound outside the negation.

== Behavior

A negation is true, if its negated pattern is false. 
Negations can be used in a `match` clause or a function
to set a constraint of not matching the negated pattern. 
//#todo expand negation behavior with detailed explanation
//
// When using negations in rules, complicated logical behavior can arise: we use the theory of https://en.wikipedia.org/wiki/Syntax_and_semantics_of_logic_programming#Stratified_negation[stratified negation] to compute the behavior of patterns in these cases.

== Negation of statement

include::partial$iam-database-links.adoc[]

The most direct approach to using negation is to specify a pattern for all results that need to be excluded.

Let's try to get all users except those who have a `full-name` attribute with a particular value:

.Negation exclusion example
[,typeql]
----
match
$u isa user;
not {$u has full-name "Kevin Morrison";};
fetch
$u as "Not Kevin": full-name;
----

.See example output
[%collapsible]
====
.Output example (partial)
[,json]
----
{
    "Not Kevin": {
        "full-name": [ { "value": "Bob Fake", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } ],
        "type": { "label": "person", "root": "entity" }
    }
}
----
====

== Learn more

[cols-2]
--
.xref:patterns/conjunction.adoc[]
[.clickable]
****
Learn more about conjunction in TypeQL.
****

.xref:patterns/disjunction.adoc[]
[.clickable]
****
Learn more about disjunction in TypeQL.
****

.xref:statements/overview.adoc[]
[.clickable]
****
Learn more about statements used in TypeQL patterns.
****
--
