= Patterns overview

== What is a pattern?

A pattern is a set of declarative constraints.
Patterns are used in data clauses and functions to specify constraints on concepts to be matched,
processed, or retrieved.

Patterns are built from xref:statements/overview.adoc[statements] using <<_pattern_operations,pattern operations>>.

[#_pattern_operations]
== Pattern operations

[cols-3]
--
.xref:patterns/conjunction.adoc[]
[.clickable]
****
Add more elements to an equal list of mandatory constraints in a pattern with conjunction.
****

.xref:patterns/disjunction.adoc[]
[.clickable]
****
Create alternative branches in a pattern with disjunction.
****

.xref:patterns/optionality.adoc[]
[.clickable]
****
Add optional elements to enrich results with additional optional data.
****

.xref:patterns/negation.adoc[]
[.clickable]
****
Exclude results with a negation pattern.
****
--

[#_composable_patterns]
== Composing patterns

You can combine two patterns by joining their statements together in a new pattern.
All semicolon-separated statements are combined with an implicit
xref:patterns/conjunction.adoc[conjunction].
That makes the order of statements irrelevant.
Hence, it's easy to change the results by adding new constraints to the pattern.

For example, in the following pattern
the `$u` variable is specified to be a user with a `full-name` attribute, which value is equal to `Kevin Morrison`,
the `$f` variable is a file with a `path` equal to `zlckt.ts`.
Finally, there are two relations that specify a connection between the `$u` and the `$f`.

.Composable pattern example
[,typeql]
----
$u isa user, has full-name "Kevin Morrison";
$f isa file, has path "zlckt.ts";
$acc ($f, $act) isa access;
$per ($u, $acc) isa permission;
----