define

marriage sub relationship
  has picture,
  relates spouse;

parentship sub relationship
  relates parent
  relates child;

person sub entity,
  has first-name,
  has middle-name,
  has surname,
  has picture,
  has age,
  has birth-date,
  has death-date,
  has gender,
  plays parent,
  plays child,
  plays spouse;

name sub attribute,
  datatype string;
first-name sub name,
  datatype string;
middle-name sub name,
  datatype string;
surname sub name,
  datatype string;
picture sub attribute,
  datatype string;
age sub attribute,
	datatype long;
event-date sub attribute,
	datatype date;
birth-date sub event-date,
	datatype date;
death-date sub event-date,
	datatype date;
gender sub attribute,
  datatype string;