= Connect to server
:tabs-sync-option:
:experimental:

// TypeDB uses a gRPC-based protocol for external communications, including queries.
// TypeDB clients, like Studio and Console, as well as language-specific drivers with native APIs,
// have been developed to implement this protocol.

This guide covers connecting to
<<_connect_to_typedb_cloud,TypeDB Cloud>>,
<<_connect_to_typedb_core,TypeDB Community Edition>> and
<<_connect_to_typedb_enterprise,TypeDB Enterprise>> servers with Studio, Console, and Driver SDKs.

////
TypeDB accepts connections via gRPC based
https://github.com/typedb/typedb-protocol[TypeDB RPC protocol,window=_blank].
It is implemented by TypeDB drivers and TypeDB clients.

All released clients and drivers support connection to TypeDB Cloud, TypeDB Enterprise and TypeDB Community Edition.
////

//To connect to TypeDB, you can use any TypeDB client or driver.
//Select a client/driver, make sure it's installed,
//and see below a practical guide on how to connect to TypeDB Community Edition, TypeDB Enterprise, and TypeDB Cloud.

== Understanding connections

TypeDB uses a *gRPC*-based protocol for external communications, including queries.
*TypeDB clients*, like Studio and Console, as well as language-specific *drivers* with native APIs,
have been developed to implement this protocol.


[#_connect_to_typedb_cloud]
== Connect to TypeDB Cloud

The TypeDB Cloud dashboard provides connection instructions.

[tabs]
====
Studio::
+
--
Run Studio and follow instructions below:

include::{page-component-version}@manual::studio.adoc[tag=connect_cloud_studio]
--

Console::
+
--
Run TypeDB Console using the `--cloud` argument to set a list of addresses and ports to connect to:

include::{page-component-version}@manual::console.adoc[tag=connect_cloud_console]
--
====

For programmatic access, use one of the TypeDB xref:{page-component-version}@drivers::index.adoc[drivers] via native API:

.Drivers
[tabs]
====
Rust::
+
--
.Connect to TypeDB Cloud
[,rust,indent=0]
----
include::{page-component-version}@manual::partial$rust-manual-code.rs[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Python::
+
--
.Connect to TypeDB Cloud
[,python,indent=0]
----
include::{page-component-version}@manual::partial$python-manual-code.py[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
Node.js::
+
--
.Connect to TypeDB Cloud
[,js,indent=0]
----
include::{page-component-version}@manual::partial$nodejs-manual-code.js[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Java::
+
--
.Connect to TypeDB Cloud
[,java,indent=0]
----
include::{page-component-version}@manual::partial$java-manual-code.java[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C#::
+
--
.Connect to TypeDB Cloud
[,csharp,indent=0]
----
include::{page-component-version}@manual::partial$csharp-manual-code.cs[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C++::
+
--
.Connect to TypeDB Cloud
[,cpp,indent=0]
----
include::{page-component-version}@manual::partial$cpp-manual-code.cpp[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C::
+
--
.Connect to TypeDB Cloud
[,c,indent=0]
----
include::{page-component-version}@manual::partial$c-manual-code.c[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
====

After connecting to TypeDB Cloud, see how to xref:connecting/database.adoc[create a database] and manage
xref:connecting/session.adoc[sessions] and
xref:connecting/transaction.adoc[transactions].


[#_connect_to_typedb_core]
== Connect to TypeDB Community Edition

A network connection to TypeDB Community Edition requires the address and port of the server to connect to.

[tabs]
====
Studio::
+
--
Run Studio and follow instructions below:

include::{page-component-version}@manual::studio.adoc[tag=connect_core_studio]
--

Console::
+
--
Run Console using the `--core` argument to set the address and port to connect to:

include::{page-component-version}@manual::console.adoc[tag=connect_core_console]
--
====

For programmatic access, use one of the TypeDB xref:{page-component-version}@drivers::index.adoc[drivers] via native API:

[tabs]
====
Rust::
+
--
.Connect to TypeDB Community Edition
[,rust,indent=0]
----
include::{page-component-version}@manual::partial$rust-manual-code.rs[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Python::
+
--
.Connect to TypeDB Community Edition
[,python,indent=0]
----
include::{page-component-version}@manual::partial$python-manual-code.py[tag=connect_core]
----
//include::{page-component-version}@manual::partial$python-manual-code.py[tags=driver]
Where `127.0.0.1:1729` is the address and port to connect to.
--

Node.js::
+
--
.Connect to TypeDB Community Edition
[,js,indent=0]
----
include::{page-component-version}@manual::partial$nodejs-manual-code.js[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Java::
+
--
.Connect to TypeDB Community Edition
[,java,indent=0]
----
include::{page-component-version}@manual::partial$java-manual-code.java[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C#::
+
--
.Connect to TypeDB Community Edition
[,csharp,indent=0]
----
include::{page-component-version}@manual::partial$csharp-manual-code.cs[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C++::
+
--
.Connect to TypeDB Community Edition
[,cpp,indent=0]
----
include::{page-component-version}@manual::partial$cpp-manual-code.cpp[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C::
+
--
.Connect to TypeDB Community Edition
[,c,indent=0]
----
include::{page-component-version}@manual::partial$c-manual-code.c[tag=connect_core]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
====

After connecting to TypeDB Community Edition, see how to xref:connecting/database.adoc[create a database] and manage
xref:connecting/session.adoc[sessions] and
xref:connecting/transaction.adoc[transactions].


[#_connect_to_typedb_enterprise]
== Connect to TypeDB Enterprise

A network connection to a TypeDB Enterprise cluster requires address and port of at least one server in the cluster, as well as username and password of a user.

[tabs]
====
Studio::
+
--
Run Studio and follow instructions below:

include::{page-component-version}@manual::studio.adoc[tag=connect_cloud_studio]
--

Console::
+
--
Run TypeDB Console using the `--cloud` argument to set a list of addresses and ports to connect to:

include::{page-component-version}@manual::console.adoc[tag=connect_cloud_console]
--
====

For programmatic access, use one of the TypeDB xref:{page-component-version}@drivers::index.adoc[drivers] via native API:

.Drivers
[tabs]
====
Rust::
+
--
.Connect to TypeDB Cloud
[,rust,indent=0]
----
include::{page-component-version}@manual::partial$rust-manual-code.rs[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Python::
+
--
.Connect to TypeDB Cloud
[,python,indent=0]
----
include::{page-component-version}@manual::partial$python-manual-code.py[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
Node.js::
+
--
.Connect to TypeDB Cloud
[,js,indent=0]
----
include::{page-component-version}@manual::partial$nodejs-manual-code.js[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

Java::
+
--
.Connect to TypeDB Cloud
[,java,indent=0]
----
include::{page-component-version}@manual::partial$java-manual-code.java[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C#::
+
--
.Connect to TypeDB Cloud
[,csharp,indent=0]
----
include::{page-component-version}@manual::partial$csharp-manual-code.cs[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C++::
+
--
.Connect to TypeDB Cloud
[,cpp,indent=0]
----
include::{page-component-version}@manual::partial$cpp-manual-code.cpp[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--

C::
+
--
.Connect to TypeDB Cloud
[,c,indent=0]
----
include::{page-component-version}@manual::partial$c-manual-code.c[tag=connect_cloud]
----

Where `127.0.0.1:1729` is the address and port to connect to.
--
====

After connecting to TypeDB Enterprise, see how to xref:connecting/database.adoc[create a database] and manage
xref:connecting/session.adoc[sessions] and
xref:connecting/transaction.adoc[transactions].


== Learn more

[cols-2]
--
.xref:{page-component-version}@manual::connecting/database.adoc[]
[.clickable]
****
See how to create a new database in TypeDB.

****

.xref:{page-component-version}@manual::connecting/session.adoc[]
[.clickable]
****
See how to manage sessions in TypeDB.
****
--
