= C driver
:Summary: Overview for the TypeDB C driver.
:keywords: typedb, client, driver, c
:pageTitle: TypeDB C driver

The C language driver was developed by Vaticle to enable TypeDB support for C language software and developers.

[cols-2]
--
.link:https://github.com/vaticle/typedb-driver/tree/development/c[GitHub,window=_blank]
[.clickable]
****
The GitHub repository with the driver's source code and release notes.
****

.link:https://cloudsmith.io/~typedb/packages/?q=clib&sort=-version[Downloads,window=_blank]
[.clickable]
****
See the driver's downloadable packages.
****
--

[#_install_c]
== Install

For Linux: the minimum version of `glibc` is `2.25.0`.

See the
<<_version_compatibility>> table to check what versions of TypeDB and C driver are compatible.

The C driver is distributed as an archive containing the headers & a shared library.

To install TypeDB C driver:

. https://cloudsmith.io/~typedb/packages/?q=clib&sort=-version[Download] the latest release for your
architecture (`x86_64`/`arm64`) and OS (Linux/macOS/Win).
. Place the library file in the `lib` directory inside your project folder
and the header files in the `include` directory.
. Configure the build and include the header file `typedb_driver.hpp` from the `include` directory.
See an example of `CMakeLists.txt` below:
+
.CMakeLists.txt example
[,source]
----
include::partial$tutorials/c/CMakeLists.txt[]
----

== Quickstart

See below a short example of C code that connects to a local TypeDB Core,
creates a database named `access-management-db`, defines a schema, inserts some data, and then reads it.

[,c]
----
include::partial$tutorials/c/quickstart.c[]
----

For more information on methods used above and other capabilities, see the API reference link below.

== Troubleshooting

=== dyld error: library not loaded

If you encounter the following error:

[,bash]
----
dyld[54800]: Library not loaded: bazel-out/darwin-opt/bin/c/libtypedb_driver_clib.dylib
----

Use the following command to set the path for your TypeDB C driver library to the `lib` directory inside your project:

[source,console]
----
$ export DYLD_LIBRARY_PATH=./lib
----

== Learn more

[cols-2]
--
.xref:drivers::c/tutorial.adoc[Tutorial]
[.clickable]
****
This tutorial will help you learn how to use the C driver.
****

.xref:c/api-reference.adoc[API reference]
[.clickable]
****
Driver API reference for the C language.
****
--

include::drivers::partial$drivers2discord.adoc[]

[#_version_compatibility]
== Version Compatibility

[cols="^.^3,^.^2,^.^3,^.^3"]
|===
| C driver | Protocol encoding version | TypeDB Core | TypeDB Cloud

| 2.28.0
| 3
| 2.28.0
| 2.28.0

| 2.27.0
| 3
| 2.27.0
| 2.27.0

| 2.26.6
| 3
| 2.26.6
| 2.26.6
|===
