= Security features
:keywords: typedb, security, auth, authentication, encryption, tls, vulnerability
:page-aliases: typedb::admin/security.adoc
:pageTitle: Security features
:summary: TypeDB high availability guarantees and solution.

[NOTE]
====
Most of the security features are available only in TypeDB Cloud.
====

== Access control

[NOTE]
====
Access control features are specific to TypeDB Cloud.
====

TypeDB Cloud has the following security features:

* https://en.wikipedia.org/wiki/Discretionary_access_control[Discretionary access control],
* User account management,
* User identification and authentication,
* Password hashing with salt,
* Password complexity requirements and expiration settings.

=== User authentication

All external connections to a cluster of TypeDB (TypeDB Cloud) require user account credentials.

Users can use usernames and passwords to identify and authenticate themselves. Passwords are stored only as
irreversible *password hash + salt*.

Administrators can adjust settings for *password strength requirements* and reset users passwords.

[NOTE]
====
For TypeDB auth we should use the user account from the cluster we are connecting to, not the user account from
TypeDB Cloud web portal.
====

=== User management

See the xref:typedb::managing/user-management.adoc[] page.

[#_encryption]
== Encryption

TypeDB Cloud encrypts all network traffic:

* TLS encryption is used for client/server communication.
* CurveZMQ is used for cluster communication (TypeDB Cloud).

== Cluster security

TypeDB Cloud clusters accept external communications only with valid credentials and internal
cluster communications only from servers that are set to be a part of the cluster.

All external and internal communications are <<_encryption,encrypted>> on the fly.

Set a CA certificate explicitly to be able to use a self-signed certificate or to avoid using
default certificates from an operating system.
If no certificate is provided then the default operating system root certificates will be used to establish TLS
encryption.
