= Lesson 4: Writing data
:page-aliases: learn::4-writing-data/4-writing-data.adoc
:page-preamble-card: 1

In this lesson, we'll learn how to write data to the sample database using *Insert* queries, *Delete* queries, and *Update* queries. We'll explore examples of both simple and *polymorphic* data writes. We'll also see how *type inference* ensures that any data written is validated against the schema.

== Recommended prerequisites

* You should complete xref:learn::3-reading-data/overview.adoc[Lesson 3] before starting this lesson.

== Lesson contents

[cols-2]
--
.xref:learn::4-writing-data/4.1-inserting-simple-data.adoc[]
[.clickable]
****
Learn how to insert new entities, relations, and attributes.
****

.xref:learn::4-writing-data/4.2-inserting-polymorphic-data.adoc[]
[.clickable]
****
Learn how to insert data with polymorphic queries.
****

.xref:learn::4-writing-data/4.3-deleting-data.adoc[]
[.clickable]
****
Learn how to delete entities, relations, and attributes.
****

.xref:learn::4-writing-data/4.4-updating-data.adoc[]
[.clickable]
****
Learn how to update the attributes of entities and relations.
****

.xref:learn::4-writing-data/4.5-data-validation.adoc[]
[.clickable]
****
Learn about how new data is validated against the schema.
****
--

== Running examples

To run an Insert, Delete, or Update query, make sure to use a *data* session and *write* transaction. The examples and exercises featured in this lesson are annotated with one of the following instructions to indicate how they should be run. Each write query should only be run once. Running write queries more than once may have unintended effects, such as inserting duplicate data.

image:home::studio-icons/svg/studio_run.svg[width=24] *_Run_*:: *Run* this query without committing the transaction afterward. Write transactions will remain open for further queries, and changes will not be persisted until a commit.
image:home::studio-icons/svg/studio_run.svg[width=24]image:home::studio-icons/svg/studio_check.svg[width=24] *_Run and commit_*:: *Run* this query and then *commit* the transaction, persisting the changes to the database.
image:home::studio-icons/svg/studio_fail.svg[width=24] *_Do not run_*:: Do not run this query, which is shown for information only. To rollback an open transaction, *close* it without committing.
image:home::studio-icons/svg/studio_run.svg[width=24] *_Try running_*:: *Run* this query to see the error generated.

For information on how to control sessions, transactions, and queries using TypeDB Studio, refer back to xref:learn::2-environment-setup/2.2-using-typedb-studio.adoc[Lesson 2.2].

== TypeQL keywords introduced

* `insert`
* `delete`

