= TypeQL
:keywords: typeql, overview
:pageTitle: TypeQL overview
:summary: A birds-eye view of TypeQL documentation.

Welcome to the *TypeQL* documentation: TypeQL is the query language of TypeDB!

== Introduction

To learn about the principles and design of TypeQL, see our xref:introduction.adoc[] page.

== Queries

TypeQL queries are distinguished by the purpose they fulfil.

[cols-2]
--
.xref:schema/define.adoc[]
[.clickable]
****
A Define query to add types and rules to a schema.
****

.xref:schema/undefine.adoc[]
[.clickable]
****
An Undefine query to delete types and rules to a schema.
****

.xref:data/insert.adoc[]
[.clickable]
****
An Insert query to add data into a database.
****

.xref:data/delete.adoc[]
[.clickable]
****
A Delete query to delete data from a database.
****

.xref:output-formatting/fetch.adoc[]
[.clickable]
****
A Fetch query to fetch values and types from a database.
****

--

== Components

Each query is build from various components.

[cols-2]
--
.xref:patterns/overview.adoc[Patterns]
[.clickable]
****
Conjunction, Disjunction, Negation, and Matching patterns.
****

.xref:statements/overview.adoc[Statements]
[.clickable]
****
isa, has, sub, owns, abstract, relates, annotations, etc.
****

.xref:modifiers/overview.adoc[Modifiers]
[.clickable]
****
Sorting, pagination, aggregation, grouping.
****

.xref:concepts/overview.adoc[Concepts]
[.clickable]
****
Types, data instances, concept variables.
****

.xref:values/overview.adoc[Values]
[.clickable]
****
Value-types, value variables, comparators, arithmetic, functions.
****
--

== Terminology

A list of TypeQL keywords used in clauses, schema statements, and data statements, can be found on our xref:keywords.adoc[] page.