= TypeQL overview
:keywords: typeql, documentation, overview, query, queries, examples, DDL, DML, language, learn, reference
:pageTitle: Documentation overview
:summary: A birds-eye view of TypeQL and TypeDB

This is the TypeQL documentation portal. It has the following pages:

* xref:fundamentals.adoc[] -- essential knowledge and terminology
* xref:queries.adoc[] -- querying with TypeQL

[#_schema]
* Schema -- How to define a schema with TypeQL:
** xref:schema/define-types.adoc[]
** xref:schema/define-rules.adoc[]
** xref:schema/modify.adoc[]

[#_data]
* Data -- How to read & write Data with TypeQL:
** xref:data/basic-patterns.adoc[]
** xref:data/insert.adoc[]
** xref:data/delete.adoc[]
** xref:data/update.adoc[]
** xref:data/fetch.adoc[]
** xref:data/get.adoc[]
** xref:data/advanced.adoc[]

//* xref:grammar.adoc[]

== Where to go from here?

See the xref:typeql::fundamentals.adoc[] page for essential knowledge about TypeQL and the xref:typeql::queries.adoc[]
page for an overview of all query types.

Explore the <<_schema,Schema>> section for the in-detail documentation of the TypeQL as a Data definition language
(DDL) -- how to define a TypeDB database schema.

Check the <<_data,Data>> section for the documentation of TypeQL as a Data manipulation language (DML) --
how to build queries to a TypeDB database.

There are also separate documentation portal sections for:

* xref:typedb::overview.adoc[TypeDB]
* xref:clients::overview.adoc[TypeDB Clients]
