= TypeQL
:keywords: typeql, overview
:pageTitle: TypeQL overview
:summary: A birds-eye view of TypeQL documentation.

Welcome to the *TypeQL* documentation: TypeQL is the query language of TypeDB!

== Introduction

To learn about the principles and design of TypeQL, see our xref:introduction.adoc[] page.

== Queries

TypeQL queries are distinguished by the purpose they fulfil.


[cols-2]
--
.xref:query-design/schema.adoc[]
[.clickable]
****
An overview of Define and Undefine queries to modify the schema of a database.
****

.xref:query-design/data.adoc[]
[.clickable]
****
An overview of data manipulation queries in TypeQL.
****

.xref:query-design/pre-processing.adoc[]
[.clickable]
****
An overview of pre-processing in data manipulation.
****

.xref:query-design/post-processing.adoc[]
[.clickable]
****
An overview of post-processing in data manipulation.
****
--

== Schema definition clauses

[cols-2]
--
.xref:schema/define.adoc[]
[.clickable]
****
A Define query to add types and functions to a schema.
****

.xref:schema/undefine.adoc[]
[.clickable]
****
An Undefine query to delete types and functions from a schema.
****
--

== Data manipulation clauses

[cols-2]
--
.xref:data/match.adoc[]
[.clickable]
****
A match clause to match data from a database.
****

.xref:data/insert.adoc[]
[.clickable]
****
An insert clause to add data into a database.
****

.xref:data/delete.adoc[]
[.clickable]
****
A delete clause to delete data from a database.
****

.xref:data/put.adoc[]
[.clickable]
****
A put clause to match existing data or add it if it doesn't exist in a database yet.
****

.xref:data/assert.adoc[]
[.clickable]
****
An assert clause to check a condition before returning a result.
****
--

== Output formatting

[cols-2]
--
.xref:output-formatting/reduce.adoc[]
[.clickable]
****
An aggregation or other post-processing to reduce a stream to a single value.
****

.xref:output-formatting/fetch.adoc[]
[.clickable]
****
A fetch clause to project a stream of Concept Maps to a stream of JSONs.
****
--

== Other elements of a query

Smaller query elements of TypeQL.

[cols-2]
--
.xref:modifiers/overview.adoc[Modifiers]
[.clickable]
****
Filtering, sorting, and pagination.
****

.xref:patterns/overview.adoc[Patterns]
[.clickable]
****
Conjunction, Disjunction, Negation, and Optionality.
****

.xref:statements/overview.adoc[Statements]
[.clickable]
****
Simple TypeQL statements, like isa, has, sub, owns, relates, etc.
****

.xref:functions/overview.adoc[Functions]
[.clickable]
****
Functions definitions, calls, and output.
****

.xref:annotations/overview.adoc[Annotations]
[.clickable]
****
TypeQL statement annotations, like @key, @abstract, @card, @replace, etc.
****

.xref:concepts/overview.adoc[Concepts]
[.clickable]
****
Types, data instances, and variables.
****

.xref:values/overview.adoc[Values]
[.clickable]
****
Primitive values, structs, lists, comparators, arithmetic, and other built-in operations.
****
--

== Terminology

A list of TypeQL keywords used in clauses and statements can be found on the xref:keywords.adoc[] page.
