= TypeQL
:keywords: typeql, overview
:pageTitle: TypeQL overview
:summary: A birds-eye view of TypeQL documentation.

Welcome to the *TypeQL* documentation: TypeQL is the query language of TypeDB!

== Introduction

To learn about the principles and design of TypeQL, see our xref:typeql::introduction.adoc[] page.

== Queries

TypeQL queries are distinguished by the purpose they fulfil.

[cols-2]
--
.xref:typeql::queries/define.adoc[]
[.clickable]
****
A Define query to add types and rules to a schema.
****

.xref:typeql::queries/undefine.adoc[]
[.clickable]
****
An Undefine query to delete types and rules to a schema.
****

.xref:typeql::queries/insert.adoc[]
[.clickable]
****
An Insert query to add data into a database.
****

.xref:typeql::queries/delete.adoc[]
[.clickable]
****
A Delete query to delete data from a database.
****

.xref:typeql::queries/update.adoc[]
[.clickable]
****
An Update query to replace data in a database.
****

.xref:typeql::queries/fetch.adoc[]
[.clickable]
****
A Fetch query to fetch values and types from a database.
****

.xref:typeql::queries/get.adoc[]
[.clickable]
****
A Get query to get data and types as stateful objects from a database.
****
--

== Components

Each query is build from various components.

[cols-2]
--
.xref:typeql::patterns/overview.adoc[Patterns]
[.clickable]
****
Conjunction, Disjunction, Negation, and Matching patterns.
****

.xref:typeql::statements/overview.adoc[Statements]
[.clickable]
****
isa, has, sub, owns, abstract, relates, annotations, etc.
****

.xref:typeql::modifiers/overview.adoc[Modifiers]
[.clickable]
****
Sorting, pagination, aggregation, grouping.
****

.xref:typeql::concepts/overview.adoc[Concepts]
[.clickable]
****
Types, data instances, concept variables.
****

.xref:typeql::values/overview.adoc[Values]
[.clickable]
****
Value-types, value variables, comparators, arithmetic, functions.
****
--

== Terminology

A list of TypeQL keywords used in clauses, schema statements, and data statements, can be found on our xref:typeql::keywords.adoc[] page.