= TypeQL overview
:keywords: typeql, overview
:pageTitle: TypeQL overview
:summary: A birds-eye view of TypeQL documentation.

[cols-1]
--
.xref:typeql::introduction.adoc[]
[.clickable]
****
Introduction for the near-natural fully declarative query language of TypeDB.
****
--

== Queries

[cols-2]
--
.xref:typeql::queries/define.adoc[]
[.clickable]
****
A Define query to add types and rules to a schema.
****

.xref:typeql::queries/undefine.adoc[]
[.clickable]
****
An Unefine query to delete types and rules to a schema.
****

.xref:typeql::queries/insert.adoc[]
[.clickable]
****
An Insert query to add data into a database.
****

.xref:typeql::queries/delete.adoc[]
[.clickable]
****
A Delete query to delete data from a database.
****

.xref:typeql::queries/update.adoc[]
[.clickable]
****
An Update query to replace data in a database.
****

.xref:typeql::queries/fetch.adoc[]
[.clickable]
****
A Fetch query to fetch values and types from a database.
****

.xref:typeql::queries/get.adoc[]
[.clickable]
****
A Get query to get data and types as stateful objects from a database.
****
--

== TypeQL building blocks

[cols-2]
--
.xref:typeql::patterns/overview.adoc[]
[.clickable]
****
Conjunction, Disjunction, Negation.
****

.xref:typeql::statements/overview.adoc[]
[.clickable]
****
isa, has, sub, owns, abstract, relates, annotations, etc.
****

.xref:typeql::modifiers/overview.adoc[]
[.clickable]
****
Sorting, pagination, aggregation, grouping.
****

.xref:typeql::concepts/overview.adoc[]
[.clickable]
****
Types, data instances, concept variables.
****

.xref:typeql::values/overview.adoc[]
[.clickable]
****
Value-types, value variables, comparators, arithmetic, functions.
****
--

== Terminology

[cols-1]
--
.xref:typeql::keywords.adoc[]
[.clickable]
****
A list of TypeQL keywords used in clauses, schema statements, and data statements.
****
--
