= Queries
:Summary: Querying with TypeQL.
:keywords: typeql, typedb, query, match, get, insert, delete, update
:longTailKeywords: typeql match, typeql query, typedb query, match clause
:pageTitle: Queries

// tag::body[]
TypeQL is a *declarative* query language used by TypeDB.

A TypeQL query consists of clauses, that use patterns consisting of statements.
For all query types and their clauses, see the table below.

//== Query types

[cols="^.^2,^.^1,^.^2,^.^2,^.^1"]
|===
|Query type | № of clauses | Clause(s) | Keyword | Mandatory

5.+| Schema queries

|xref:typeql::schema/define-types.adoc[Define]
|1
|xref:typeql::schema/define-types.adoc#_define_clause[Define]
|`define`
|Yes

|xref:typeql::schema/undefine.adoc[Undefine]
|1
|xref:typeql::schema/undefine.adoc#_undefine_clause[Undefine]
|`undefine`
|Yes

5.+| Data queries

.2+|xref:typeql::data/insert.adoc[Insert]
.2+|1-2

|xref:typeql::data/match.adoc[Match]
|`match`
|*No*
|xref:typeql::data/insert.adoc#_insert_clause[Insert]
|`insert`
|Yes

.2+|xref:typeql::data/delete.adoc[Delete]
.2+|2

|xref:typeql::data/match.adoc[Match]
|`match`
|Yes
|xref:typeql::data/delete.adoc#_delete_clause[Delete]
|`delete`
|Yes

.3+|xref:typeql::data/update.adoc[Update]
.3+|3

|xref:typeql::data/match.adoc[Match]
|`match`
|Yes
|xref:typeql::data/delete.adoc#_delete_clause[Delete]
|`delete`
|Yes
|xref:typeql::data/insert.adoc#_insert_clause[Insert]
|`insert`
|Yes

.2+|xref:typeql::data/fetch.adoc[Fetch]
.2+|2

|xref:typeql::data/match.adoc[Match]
|`match`
|Yes
|xref:typeql::data/fetch.adoc#_fetch_clause[Fetch]
|`fetch`
|Yes

.2+|xref:typeql::data/get.adoc#_get_clause[Get]
.2+|2

|xref:typeql::data/match.adoc[Match]
|`match`
|Yes
|xref:typeql::data/get.adoc#_get_clause[Get]
|`get`
|Yes

|===
// end::body[]

// tag::examples[]
== Examples

The following simple query examples are to demonstrate the basic syntax of TypeQL.
To try more interesting queries showcasing capabilities of TypeQL and TypeDB, see the xref:home::25-queries.adoc[] page.
For more information on the behavior and syntax of every query, see the links below.

To try the following examples, you can use TypeDB Studio or TypeDB Console as it is shown in the
xref:home::quickstart.adoc[] guide.

[tabs]
====
Define::
+
--
To define a simple schema, create a new database and use the following Define query:

.Define query example
[,typeql]
----
include::home::attachment$quickstart-schema.tql[]
----

The above Define query contains a complete schema and does not rely on any pre-existing types in a schema,
so it can be applied to an empty database.
You can at any moment extend an existing schema by sending another Define query to the same database:

.Extending schema example
[,typeql]
----
define

credential sub attribute, value string;
path sub attribute, value string;

user owns credential;

file sub entity, owns path;
----

The above query defines two attribute types, one entity type,
and an ability to own one of the new attribute types to a pre-existing `user` type.
Unlike the first example, this one requires a `user` type to be present in the current database,
so it can't be applied to an empty database, as type `user` will be missing.
For more information about defining types in a schema, see the xref:typeql::schema/define-types.adoc[] page.
For information about defining rules in a schema, see the xref:typeql::schema/define-rules.adoc[] page.
--

Undefine::
+
--
To remove types or rules from your schema, use an Undefine query:

.Undefine query example
[,typeql]
----
undefine

credential sub attribute, value string;
path sub attribute, value string;

user owns credential;
file sub entity;
----

For more information about undefining types and rules in a schema, see the xref:typeql::schema/undefine.adoc[] page.
--

Insert::
+
--
To add data to a TypeDB database, you need to use types from its schema.
You can insert instances of types and assign them with ownership of some attributes.
To insert completely new data, use an Insert query with just an `insert` clause:

.Insert query example
[,typeql]
----
insert $p isa person, has id 100, has full-name "Bob";
----

To add some information to existing data in a database,
you need to match the existing data from a database first with a `match` clause in an Insert query:

.Inserting more information example
[,typeql]
----
match
$p isa person, has id 100, has full-name "Bob";
insert
$p has email "bob@gmail.com";
----

The above query finds a person entity having `id` = `100` and `full-name` = `Bob`,
then it inserts for every such person an ownership of `email` = `bob@gmail.com`.
For more information about Insert queries, see the xref:typeql::data/insert.adoc[] page.
--

Delete::
+
--
To remove data from a TypeDB database,
you need to match it with a `match` clause and specify what data to delete with a `delete` clause:

.Delete query example
[,typeql]
----
match
$p isa person, has id 100, has full-name "Bob", has email $email;
$email == "bob@gmail.com";
insert
$p has $email;
----

The above query finds a person entity having `id` = `100` and `full-name` = `Bob`
that has an `email` with the value equal to `bob@gmail.com`,
then for every such person it deletes an ownership of such `email` attribute.
For more information on Delete queries, see the xref:typeql::data/delete.adoc[] page.
--

Update::
+
--
You can update information in a database by matching an existing data,
deleting some data, and then inserting some other data.

.Update query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
delete
$p has $fn;
insert
$p has full-name "Bob2";
----

The above query finds a person entity having `id` = `100` and any `full-name`,
then for every such person it deletes an ownership of such `full-name` attribute, and
inserts an ownership of the `full-name` attribute with the value `Bob2`.
For more information on Update queries, see the xref:typeql::data/update.adoc[] page.
--

Fetch::
+
--
You can retrieve types and values from a database as a JSON with a Fetch query.

.Fetch query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
fetch
$fn as name;
----

The above query returns JSONs with a `name` key containing the value and the type of the `$fn` attribute.
See the result example below.

.Fetch query result example
[,js]
----
{ "name": { "value": "Bob2", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
----

For more information on Fetch queries, see the xref:typeql::data/fetch.adoc[] page.
--

Get::
+
--
You can retrieve concepts from a database in a programmatically accessible format with a Get query.
xref:drivers::overview.adoc[TypeDB driver] API lets you further process these concepts
to retrieve values or to explore relevant data.

.Get query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
get
$p, $fn;
----

The above query returns a Stream/Iterator of ConceptMaps of `$p`, `$fn` and their relative Concepts from a database.
Concepts have methods to process them according to their root type.

For more information on Get queries, see the xref:typeql::data/get.adoc[] page.
For information on the driver API, see the relevant language for driver API reference:
xref:drivers::rust/api-reference.adoc[Rust],
xref:drivers::python/api-reference.adoc[Python],
xref:drivers::java/api-reference.adoc[Java], and
xref:drivers::nodejs/api-reference.adoc[Node.js].
--
====
// end::examples[]

////
[#_define_query]
=== Define query

To define a simple schema, create a new database and use the following query:

.Define query example
[,typeql]
----
include::home::attachment$quickstart-schema.tql[]
----

The above query defines three attribute types and two entity types in a schema.
You can at any moment extend an existing schema by sending another Define query to the same database:

.Extending schema example
[,typeql]
----
define

credential sub attribute, value string;
path sub attribute, value string;

user owns credential;

file sub entity, owns path;
----

The above query defines two attribute types, one entity type,
and an ability to own one of the new attribute types to a pre-existing `user` type.
This query requires a `user` type to be present in the current database.
For more information about defining types in a schema, see the xref:typeql::schema/define-types.adoc[] page.
For information about defining rules in a schema, see the xref:typeql::schema/define-rules.adoc[] page.

[#_undefine_query]
=== Undefine query

To remove types or rules from your schema, use an Undefine query:

.Undefine query example
[,typeql]
----
undefine

credential sub attribute, value string;
path sub attribute, value string;

user owns credential;
file sub entity;
----

For more information about undefining types and rules in a schema, see the xref:typeql::schema/undefine.adoc[] page.

[#_insert_query]
=== Insert query

To add data to a TypeDB database, you need to use types from its schema.
You can insert instances of types and assign them with ownership of some attributes.
To insert completely new data, use an Insert query with just an `insert` clause:

.Insert query example
[,typeql]
----
insert $p isa person, has id 100, has full-name "Bob";
----

To add some information to existing data in a database,
you need to match the existing data from a database first with a `match` clause in an Insert query:

.Inserting more information example
[,typeql]
----
match
$p isa person, has id 100, has full-name "Bob";
insert
$p has email "bob@gmail.com";
----

The above query finds a person entity having `id` = `100` and `full-name` = `Bob`,
then it inserts for every such person an ownership of `email` = `bob@gmail.com`.
For more information about Insert queries, see the xref:typeql::data/insert.adoc[] page.

[#_delete_query]
=== Delete query

To remove data from a TypeDB database,
you need to match it with a `match` clause and specify what data to delete with a `delete` clause:

.Delete query example
[,typeql]
----
match
$p isa person, has id 100, has full-name "Bob", has email $email;
$email == "bob@gmail.com";
insert
$p has $email;
----

The above query finds a person entity having `id` = `100` and `full-name` = `Bob`
that has an `email` with the value equal to `bob@gmail.com`,
then for every such person it deletes an ownership of such `email` attribute.
For more information on Delete queries, see the xref:typeql::data/delete.adoc[] page.

[#_update_query]
=== Update query

You can update information in a database by matching an existing data,
deleting some data, and then inserting some other data.

.Update query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
delete
$p has $fn;
insert
$p has full-name "Bob2";
----

The above query finds a person entity having `id` = `100` and any `full-name`,
then for every such person it deletes an ownership of such `full-name` attribute, and
inserts an ownership of the `full-name` attribute with the value `Bob2`.
For more information on Update queries, see the xref:typeql::data/update.adoc[] page.

[#_fetch_query]
=== Fetch query

You can retrieve types and values from a database as a JSON with a Fetch query.

.Fetch query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
fetch
$fn as name;
----

The above query returns JSONs with a `name` key containing the value and the type of the `$fn` attribute.
See the result example below.

.Fetch query result example
[,js]
----
{ "name": { "value": "Bob2", "type": { "label": "full-name", "root": "attribute", "value_type": "string" } } }
----

For more information on Fetch queries, see the xref:typeql::data/fetch.adoc[] page.

[#_get_query]
=== Get query

You can retrieve concepts from a database in a programmatically accessible format with a Get query.
xref:drivers::overview.adoc[TypeDB driver] API lets you further process these concepts
to retrieve values or to explore relevant data.

.Get query example
[,typeql]
----
match
$p isa person, has id 100, has full-name $fn;
get
$p, $fn;
----

The above query returns a Stream/Iterator of ConceptMaps of `$p`, `$fn` and their relative Concepts from a database.
Concepts have methods to process them according to their root type.

For more information on Get queries, see the xref:typeql::data/get.adoc[] page.
For information on driver API, see the releavant language for driver API reference:
xref:drivers::rust/api-reference.adoc[Rust],
xref:drivers::python/api-reference.adoc[Python],
xref:drivers::java/api-reference.adoc[Java], and
xref:drivers::nodejs/api-reference.adoc[Node.js].
////

== Learn more

To find out more about the queries, see the
xref:typeql::schema/define-types.adoc[Define query],
xref:typeql::schema/undefine.adoc[Undefine query],
xref:typeql::data/insert.adoc[],
xref:typeql::data/delete.adoc[],
xref:typeql::data/update.adoc[],
xref:typeql::data/fetch.adoc[], and
xref:typeql::data/get.adoc[] pages.

For more information about practical aspects of using TypeDB, see the xref:typedb::overview.adoc[TypeDB Documentation].
