= TypeDB overview
:keywords: typedb, documentation, docs, overview, introduction, outline, structure
:pageTitle: Documentation overview
:summary: A birds-eye view of TypeQL and TypeDB

Welcome to the TypeDB technical documentation.

//* xref:introduction.adoc[] -- a brief description of TypeDB and its capabilities

[#_fundamentals]
== Basics of TypeDB

Learn essential knowledge needed to work with TypeDB:

[cols-2]
--
.xref:typedb::basics/data-model.adoc[]
[.clickable]
****
Learn about the Polymorphic ERA model used in all TypeDB databases.
****

.xref:typedb::basics/query-language.adoc[]
[.clickable]
****
Read an introduction to TypeQL's query types and syntax.
****

.xref:typedb::basics/polymorphic-patterns.adoc[]
[.clickable]
****
Discover pattern matching and different types of polymorphism.
****

.xref:typedb::basics/acid.adoc[]
[.clickable]
****
See the transaction safety guarantees and schema integrity restrictions.
****
--

[#_connecting]
== Connecting to TypeDB

See a xref:typedb::connecting/overview.adoc[guide on how to connect] to TypeDB, learn database, session, and transaction
management or see documentation for:

[cols-2]
--
.xref:typedb::connecting/studio.adoc[]
[.clickable]
****
The special IDE for TypeDB with TypeQL syntax highlighting and query response visualisation.
****

.xref:typedb::connecting/console.adoc[]
[.clickable]
****
A powerful CLI tool for TypeDB for management and queries.
****
--

[#_developing]
== Developing with TypeDB

Using TypeDB to its full potential in your own application:

[cols-3]
--
.xref:typedb::developing/creating-database.adoc[]
[.clickable]
****
Start with basic database management: how to create or delete a database in TypeDB.
****

.xref:typedb::developing/defining-schema.adoc[]
[.clickable]
****
Learn about a schema, what is the default schema, how to define new types and rules in a schema.
****

.xref:typedb::developing/write.adoc[]
[.clickable]
****
Insert, Delete, or Update data in a database with a write query.
****

.xref:typedb::developing/read.adoc[]
[.clickable]
****
Fetch or Get data from a TypeDB database with a read query.
****

.xref:typedb::developing/infer.adoc[]
[.clickable]
****
Utilise rule-based reasoning engine to infer new data in a read query.
****

.xref:typedb::developing/response.adoc[]
[.clickable]
****
Find out how to convert and interpret results of a query.
****

.xref:typedb::developing/best.adoc[]
[.clickable]
****
Learn about best practices in schema and query design.
****
--

[#_managing]
== Managing TypeDB

TypeDB deployment configuration and management.

[cols-3]
--
.xref:typedb::managing/configuration.adoc[]
[.clickable]
****
TypeDB server configuration parameters and host machine requirements.
****

.xref:typedb::managing/export-import.adoc[]
[.clickable]
****
Exporting and importing database schema and data.
****

.xref:typedb::managing/upgrading.adoc[]
[.clickable]
****
How to migrate to a newer version of TypeDB.
****

.xref:typedb::managing/ha.adoc[]
[.clickable]
****
Description of TypeDB high availability features.
****

.xref:typedb::managing/security.adoc[]
[.clickable]
****
Description of TypeDB security features.
****
--

[#_tutorials]
== Tutorials

General tutorials for TypeDB:

[cols-3]
--
.xref:typedb::tutorials/iam-schema.adoc[]
[.clickable]
****
A brief description of IAM schema that is widely used throughout the documentation.
****

.xref:typedb::tutorials/sample-app.adoc[]
[.clickable]
****
A simple example of how to use TypeDB with Java, Python, and Node.js.
****

.xref:typedb::tutorials/data-migration.adoc[]
[.clickable]
****
How to load a dataset from an intermediate input format into a TypeDB database.
****
--

// ** xref:tutorials/new-driver-tutorial.adoc[New client] -- how to create a new client

== Where to go from here?

//What is TypeDB? See the xref:introduction.adoc[] page.

xref:home:ROOT:install.adoc[Install] TypeDB and use xref:home::quickstart.adoc[] to try it yourself.

Check the xref:home::25-queries.adoc[] page for more interesting queries.

To learn more about TypeDB, check the major sections of the documentation:

* the <<_fundamentals,Basics>> for essential knowledge about TypeDB,
* the <<_connecting,Connecting to TypeDB>> for information about how to connect to TypeDB,
* the <<_developing,Developing with TypeDB>> for the in-detail documentation of the TypeDB development workflow,
* the <<_managing,Managing TypeDB>> for the instructions for setting up a production environment, or
* the <<_tutorials,Tutorials>> for how-to guides and the xref:tutorials/iam-schema.adoc[].

Check our documentation for xref:typeql::overview.adoc[TypeQL] and xref:drivers::overview.adoc[TypeDB drivers].
