= Python driver tutorial
:Summary: Tutorial for TypeDB Python driver.
:page-aliases: clients::python-driver/tutorial.adoc
:keywords: typedb, driver, python, tutorial
:pageTitle: Python driver tutorial

== Prerequisites

Make sure to install the Python driver as per the xref:python/overview.adoc#_install_python[Installation] guide.
The TypeDB server also needs to be xref:home::install.adoc#_core[installed] and running.

== Importing

In the interpreter or in the source code, import everything from `typedb.driver`.

// test-example social_network_python_driver_a.py

[,python]
----
from typedb.driver import *
----

== Connecting

Instantiate a TypeDB Core driver and open a xref:typedb:ROOT:connecting/overview.adoc#_sessions[session] to a
xref:typedb:ROOT:connecting/overview.adoc#_databases[database].

[NOTE]
====
Find out how to create a database in TypeDB on the
xref:home::quickstart.adoc#_create_a_database[Quickstart guide] page.

The name for the database should be `social_network`. +
The database should have the following schema loaded: xref:attachment$schema.tql[schema.tql]. +
The database should have the following data inserted: xref:attachment$data.tql[data.tql].
====

[,python]
----
from typedb.driver import *

with TypeDB.core_driver("localhost:1729") as driver:
    with driver.session("social_network", SessionType.DATA) as session:
        ## session is open
        pass
    ## session is closed
## driver is closed
----

== Creating transactions

Create transactions to use for reading and writing data.

// test-example social_network_python_driver_c.py

[,python]
----
from typedb.driver import *

with TypeDB.core_driver("localhost:1729") as driver:
    with driver.session("social_network", SessionType.DATA) as session:
        ## creating a write transaction
        with session.transaction(TransactionType.WRITE) as write_transaction:
            ## write transaction is open
            ## write transaction must always be committed (closed)
            write_transaction.commit()

        ## creating a read transaction
        with session.transaction(TransactionType.READ) as read_transaction:
            ## read transaction is open
            ## if not using a `with` statement, we must always close the read transaction like so
            # read_transaction.close()
            pass
----

== Querying

Running basic retrieval and insertion queries.

// test-example social_network_python_driver_d.py

[,python]
----
from typedb.driver import *

with TypeDB.core_driver("localhost:1729") as driver:
    with driver.session("social_network", SessionType.DATA) as session:
        ## Insert a Person using a WRITE transaction
        with session.transaction(TransactionType.WRITE) as write_transaction:
            insert_iterator = write_transaction.query.insert('insert $x isa person, has email "x@email.com";')
            concepts = [ans.get("x") for ans in insert_iterator]
            print("Inserted a person with id: {0}".format(concepts[0].as_entity().get_iid()))
            ## to persist changes, write transaction must always be committed (closed)
            write_transaction.commit()

        ## Read the person using a READ only transaction
        with session.transaction(TransactionType.READ) as read_transaction:
            answer_iterator = read_transaction.query.get("match $x isa person; get $x; limit 10;")

            for answer in answer_iterator:
                person = answer.get("x")
                print("Retrieved person with id " + person.as_entity().get_iid())

        ## Or query and consume the iterator immediately collecting all the results
        with session.transaction(TransactionType.READ) as read_transaction:
            answer_iterator = read_transaction.query.get("match $x isa person; get $x; limit 10;")
            persons = [ans.get("x") for ans in answer_iterator]
            for person in persons:
                print("Retrieved person with id " + person.as_entity().get_iid())

        ## if not using a `with` statement, then we must always close the session and the read transaction
        # read_transaction.close()
        # session.close()
        # driver.close()
----

[IMPORTANT]
====
Remember that transactions always need to be closed. The safest way is to use the `with \...` syntax which auto-closes
at the end of the `with` block. Otherwise, remember to call `transaction.close()` explicitly.
====

== Where to go next

Check out the xref:python/api-reference.adoc#_answer_header[Answer] section of API reference page to learn
about the available methods on the concepts retrieved as the answers to queries.

To view examples of various TypeQL queries, head over to
xref:typedb::developing/write.adoc[Writing data] and
xref:typedb::developing/read.adoc[Reading data] pages.

For some more Python driver examples -- see the
xref:typedb:ROOT:tutorials/sample-app.adoc#_python_implementation[Python implementation] on the Sample application
page.
