= Patterns
:page-aliases: {page-version}@typeql::patterns.adoc

This reference covers the usage of patterns in TypeQL.

== Combining patterns

TypeQL allows us to construct larger and more interesting patterns from smaller ones,
allowing us to express more than simple conjunctions.

[cols-3]
--
.xref:{page-version}@typeql-reference::patterns/conjunctions.adoc[]
[.clickable]
****
Use of conjunctions to join patterns into a single query pattern that combines all given constraints.
****

.xref:{page-version}@typeql-reference::patterns/disjunction.adoc[]
[.clickable]
****
Use of disjunctions to allow for several branches in a query to be executed in parallel.
****

.xref:{page-version}@typeql-reference::patterns/negations.adoc[]
[.clickable]
****
Use of negations to exclude patterns from your query results.
****

.xref:{page-version}@typeql-reference::patterns/optionals.adoc[]
[.clickable]
****
Use of optionals for optionally matching subpatterns.
****
--

.xref:{page-version}@typeql-reference::patterns/conditional_writes.adoc[]
[.clickable]
****
Conditionally inserting or deleting data.
****
--

== Variables
Pattern comprise statements containing variables.
The principles behind variable scoping, typing and optionality merits a page of its own.

.xref:{page-version}@typeql-reference::patterns/variables.adoc[]
[.clickable]
****
The rules behind scoping of variable names, its category, optionality and whether it's an input to a pattern or bound by it.
****
