= Troubleshooting

This section provides general recommendations and solutions to common issues faced while interacting with TypeDB.

Please, refer to the section closest to your problem.
If you cannot find a solution, do not hesitate to send us a message on https://discord.com/channels/665254494820368395/983769458269114408[Discord]!

[cols-2]
--
.xref:{page-version}@manual::troubleshooting/installation.adoc[]
[.clickable]
****
Addressing setup issues.
****

.xref:{page-version}@manual::troubleshooting/server.adoc[]
[.clickable]
****
Common server problems and solutions.
****

.xref:{page-version}@manual::troubleshooting/connection.adoc[]
[.clickable]
****
Resolve connection issues.
****

.xref:{page-version}@manual::troubleshooting/stopping-queries.adoc[]
[.clickable]
****
A query runs indefinitely?
Stop it.
****

.xref:{page-version}@manual::troubleshooting/optimising-queries.adoc[]
[.clickable]
****
Optimize your queries for the best performance.
****

.xref:{page-version}@manual::troubleshooting/debugging-queries.adoc[]
[.clickable]
****
Tips for query debugging.
****
--
