= Assert
:Summary: Assert condition to continue data processing
:keywords: typeql, typedb, clause, assert, condition
:pageTitle: Assert

An `assert` clause is used to assert condition and return the inputted stream only if the condition is True.

// For a practical guide on how to send a query with an insert clause to TypeDB,
// see the xref:{page-component-version}@manual::writing/insert.adoc[Insert] page of the TypeDB Manual.

== Syntax

// tag::syntax[]
An `assert` clause starts with the `insert` keyword, followed by the pattern declaring data that is to be inserted:

[,typeql]
----
assert <condition>
----
// end::syntax[]
where `<condition>` is a statement with a comparator.
//#todo Double-check whether anything else rather a comparator would do

[#_behavior]
== Behavior
[#_insert_clause]
// tag::assert_clause[]
An `assert` clause checks the condition to be met by the inputted Concept Map.
The data to be inserted is specified using _new variables_
// end::assert_clause[]

=== Clause execution
[#_match_clause]
An `assert` clause is executed exactly once for every inputted Concept Map.

=== Clause response

An `assert` clause returns a stream of Concept Maps that satisfy the condition.

== Asserting

[,typeql]
----
match
$p isa person, has name $name
assert count($x)==2 @or_log("something is wrong");
----
