= Delete query
:Summary: Deleting data from a TypeDB database.
:keywords: typeql, typedb, query, delete, remove
:pageTitle: Delete query

A Delete query removes data from a TypeDB database.
You can delete an instance of a type, ownership of an attribute,
or a role player reference of a relation.

Delete queries can be used only with write transactions.

== Behavior

A Delete query removes concepts, ownerships, and role player references from a database.

After matching existing data with a `match` clause,
use a `delete` clause with another TypeQL pattern to specify exact data to delete.

A Delete query doesn't return any useful information.

== Syntax

A Delete query consists of a
<<_match_clause,match>> clause and a
<<_delete_clause,delete>> clause.

Delete queries are written in TypeQL with the following syntax:

[,typeql]
----
match <pattern>
delete <pattern>
----

A `delete` clause pattern uses variables from a preceding `match` clause pattern.

[#_match_clause]
== Match clause

A `match` clause is mandatory in a Delete query.
You can use a declarative and composable TypeQL pattern in a `match` clause and TypeDB will find data that matches
specified pattern.

For more information on a `match` clause, see the
//#todo update the link after introducing the Match clause page!
xref:typeql::queries.adoc#_match[Match clause] description on the Queries page.

For more information on patterns used in a `match` clause, see the
xref:data/basic-patterns.adoc#_patterns_overview[Pattern syntax] section.

[#_delete_clause]
== Delete clause

A `delete` clause is used in a Delete query to specify exact data to remove from a database.
deleted data should be matched first in a preceding `match` clause.

A `delete` clause can have multiple statements in its pattern to delete in one query. But it can't delete types (use
xref:schema/modify.adoc#_undefine_a_type[undefine] to delete types) and can't have the following:

- Conjunction
- Disjunction
- Negation
- `is` keyword

This clause is executed exactly once for every result matched by the preceding `match` clause of the same query.
If there are no matches for a `match` clause in a `delete` query, then there will be no deletes.

A `delete` clause returns a Promise of an empty response.

[WARNING]
====
Prior to TypeDB v.`2.22.0`, a Delete query would fail (throw an error) if its `delete` clause would try to delete
a previously deleted or non-existent data.
====

=== Deleting instances

To delete an entity, attribute, or relation, you need to match them with a `match` clause and then
use the following pattern in a `delete` clause of the same query:

.Deleting an instance of data pattern syntax
[,typeql]
----
<variable> isa <type>;
----

Where `<variable>` (e.g., `$x`) -- a query variable of a matched instance to delete;
`<type>` (e.g., `person`) -- type or supertype of the deleted instance.

With this pattern, the instance of data is removed completely,
including all roles played and attributes owned by the deleted instance.

Deleting an attribute will result in all owners of such attribute to lose ownership of it.
Deleting a relation will result in all instances that played roles in the relation
to no longer play that role in the deleted relation.

See an <<_simple_example,example>> of deleting instances of data below.

=== Deleting ownership

To delete an ownership of an attribute, match both the attribute and its owner and then use the following pattern
in a `delete` clause of the same query:

.Deleting an ownership pattern syntax
[,typeql]
----
<owner-variable> has <attribute-variable>;
----

With this pattern an attribute itself is not removed,
but rather an ownership of that attribute by that owner is removed.

Attributes are immutable. Rather than changing the value of an owned attribute,
you can delete an ownership of it and replace with an ownership of another attribute with different value.

=== Deleting role players from a relation

To delete a role player from a relation, match both the relation and the instance of data that plays a role
and then use the following pattern in a `delete` clause of the same query:

.Deleting a role player from a relation pattern syntax
[,typeql]
----
<relation-variable> (<role>:<instance-variable>);
----

Where `<relation-variable>` -- a query variable of the relation to modify;
`<role>` -- an optional specification of a role of a role player to remove;
`<instance-variable>` -- a query variable of a role player instance.

With this pattern, an instance that plays role in a relation is not removed,
but rather the information of that role player is removed from a relation.

== Examples

[#_simple_example]
=== Simple example

Instances of data (entities, attributes, and relations) can be deleted by matching them first,
then using a `delete` clause with the `isa` pattern.
Let's try to match and delete an entity.

.Deleting an entity example
[,typeql]
----
match
$p isa person, has email "john.parkson@gmail.com";
delete
$p isa person;
----

In the above query, `match` clause finds a `person` entity that has the `email` attribute with the value of
`john.parkson@gmail.com`.
Then, it removes the matched entity from a database.

=== Deleting without a direct type

One can delete an instance by using not only its exact type in the `delete` clause pattern,
but also any of its supertypes.
It can be especially useful with matching using inheritance polymorphism.

.Deleting an attribute by its supertype
[,typeql]
----
match
$fn == "Bob";
delete
$fn isa attribute;
----

In the above example we are matching all concepts of any type with the value of `Bob`.
Since only attributes can have a value, all matched concepts are instances of attribute types.
So we can delete all of them be using their common supertype, in this case -- root type `attribute`.

=== Attributes

A Delete query can remove an attribute itself or delete an ownership of it from another instance.

==== Deleting an attribute

To delete an attribute, match it in a database and then use a `delete` clause with an `isa` pattern:

.Deleting an attribute
[,typeql]
----
match
$fn isa full-name;
$fn == "Bob";
delete
$fn isa full-name;
----

The above example matches the attribute by its type (`full-name`) and value (`Bob`)
and assigns it a query variable (`$fn`).
Then it deletes the matched attribute.

==== Deleting an ownership

To delete an ownership of an attribute from any instance, match both the owner and the attribute and then use a `delete`
clause with a `has` pattern:

.Deleting an ownership
[,typeql]
----
match
$p has full-name $fn;
$fn == "Bob";
delete
$p has $fn;
----

The above query finds all `person` entities (`$p`) that have a `full-name` attribute (`$fn`)
whose value is equal to `Bob`.
For every matched pair of `$p` and `$fn` it deletes an ownership of `$fn` by `$p`.

[NOTE]
====
We are not using `isa person` statement in the `delete` clause above because we don't want `$p` to be deleted,
only its ownership of `$fn`.
====

=== Relations

We can delete a relation or a role player reference from a relation.

==== Deleting a relation

To delete a relation, match it in a database and then use a `delete` clause with an `isa` pattern:

[,typeql]
----
match
$p isa subject, has full-name "Pearle Goodman";
$pe (subject: $p) isa permission;
delete
$pe isa permission;
----

The above query does the following:

. Finds the `subject` entity (`$p`), with `full-name` attribute value of `Pearle Goodman`.
. Finds all `permission` relations (`$pe`) relating the `subject` entity `$p` (as the `subject` role).
. Deletes all matched permissions `$pe`.

In short, it removes all permissions for `Pearle Goodman`.

[NOTE]
====
We didn't specify all roles of a `permission` relation, e.g., the `object` role.
====

==== Role players

To delete a role player reference from a relation,
match it in a database and then use a `delete` clause without an `isa` pattern,
specifying just the relation variable and the role player reference in parentheses:

[,typeql]
----
match
$p isa subject, has full-name "Pearle Goodman";
$pe (subject: $p) isa permission;
delete
$pe ($p);
----

The above query does the following:

. Finds the `subject` entity (`$p`), with `full-name` attribute value of `Pearle Goodman`.
. Finds all `permission` relations (`$pe`) relating the `subject` entity `$p` (as the `subject` role).
. From all matched relation deletes the reference to the `$p`.

In short, it removes `Pearle Goodman` as the `subject` from all of its `permission` relations.
However, the relations are not deleted, and any other role player references are left intact.

[WARNING]
====
The existence of a relation often implies the existence of all of its role players.
So, deleting a role player reference from a relation can mean an incomplete data state.
Like a marriage with only one known spouse.
====

[NOTE]
====
We are not using `isa permission` statement in the `delete` clause above
because we don't want any `$pe` relations to be deleted, only modified by deleting a role player reference from them.
====
