= Put
:Summary: Mach data if it exists or insert if it doesn't
:keywords: typeql, typedb, clause, put, condition, insert
:pageTitle: Put

A `put` clause is used to either match existing data or insert new data if it doesn't exist yet.

// For a practical guide on how to send a query with an insert clause to TypeDB,
// see the xref:{page-component-version}@manual::writing/insert.adoc[Insert] page of the TypeDB Manual.

== Syntax

// tag::syntax[]
A `put` clause starts with the `put` keyword, followed by a pattern declaring data that is to be matched or inserted:

[,typeql]
----
put <pattern>
----
// end::syntax[]
where `<pattern>` is a valid data pattern.

[#_behavior]
== Behavior
// tag::put_clause[]
A `put` clause tries to match existing data by the pattern provided.
If no data can be matched, then such data is inserted as per insert clause.
// end::put_clause[]

=== Clause execution
[#_match_clause]
A `put` clause is executed exactly once for every inputted Concept Map.

=== Clause response

A `put` clause returns a stream of Concept Maps.

== Putting

[,typeql]
----
put
$p isa person, has name $name;
$name = "Bob";
----

