= Schema editing
:experimental:

This page assumes you've already followed instructions from the xref:connecting/overview.adoc[] section pages.
Here, you'll see how to modify an existing schema without TypeQL queries.
For a Define query, see the xref:manual::defining/define.adoc[] page.

There are two ways of modifying the schema of a database without TypeQL Define/Undefine queries:
with Studio's <<_modify_with_type_editor,Type Editor>> and with <<_modify_with_driver_api,driver API>> methods.

[#_modify_with_type_editor]
== Modify with Type Editor

include::manual::studio.adoc[tag=type-editor]

[#_modify_with_driver_api]
== Modify with driver API

Driver API has methods can be used to work with schema types and rules.
These methods can vary from driver to driver due to language-specific details.

=== Example

See below an example of schema manipulation using driver API methods.

:code-caption: Driver API schema modification
[tabs]
====
Rust::
+
--
.{code-caption}
[,rust]
----
use typedb_driver::{
    concept::{Transitivity, ValueType}, transaction::concept::api::{EntityTypeAPI, ThingTypeAPI}, Connection, DatabaseManager, Error, Promise, Session, SessionType, TransactionType
};

fn main() -> Result<(), Error> {
    let driver = Connection::new_core("127.0.0.1:1729")?;
    let databases = DatabaseManager::new(driver);
    Ok({
        let session = Session::new(databases.get("schema-api-db")?, SessionType::Schema)?;
        let tx = session.transaction(TransactionType::Write)?;
        let tag = tx.concept().put_attribute_type("tag".to_owned(),ValueType::String).resolve()?;
        let entities = tx.concept().get_entity_type("entity".to_owned()).resolve().unwrap().unwrap().get_subtypes(&tx, Transitivity::Explicit).unwrap();
        for res in entities {
            let mut entity = res.unwrap();
            if !{entity.is_abstract()} {
                _ = entity.set_owns(&tx, tag.clone(),None,vec![]).resolve();
            }
        }
        tx.commit().resolve()?;
    })
}
----

For more details about these and other API methods, see the xref:drivers::rust/api-reference.adoc[API reference].
--

Python::
+
--
.{code-caption}
[,python]
----
from typedb.driver import TypeDB, SessionType, TransactionType, ValueType, Transitivity

with TypeDB.core_driver("127.0.0.1:1729") as driver:
    with driver.session("sample_db", SessionType.SCHEMA) as session:
        with session.transaction(TransactionType.WRITE) as transaction:
            tag = transaction.concepts.put_attribute_type("tag", ValueType.STRING).resolve()
            entities = transaction.concepts.get_root_entity_type().get_subtypes(transaction, Transitivity.EXPLICIT)
            for entity in entities:
                print(entity.get_label())
                if not entity.is_abstract():
                    entity.set_owns(transaction, tag).resolve()
            transaction.commit()
----

For more details about these and other API methods, see the xref:drivers::python/api-reference.adoc[API reference].
--

Java::
+
--
.{code-caption}
[,java]
----
package org.example;

import com.vaticle.typedb.driver.api.TypeDBDriver;
import com.vaticle.typedb.driver.api.TypeDBSession;
import com.vaticle.typedb.driver.api.TypeDBTransaction;
import com.vaticle.typedb.driver.TypeDB;
import com.vaticle.typedb.driver.api.concept.Concept;
import com.vaticle.typedb.driver.api.concept.type.AttributeType;
import com.vaticle.typedb.driver.api.concept.value.Value;

public class Main {
    public static void main(String[] args) {
        TypeDBDriver driver = TypeDB.coreDriver("0.0.0.0:1729");
        try (TypeDBSession session = driver.session("sample_db", TypeDBSession.Type.SCHEMA)) {
            try (TypeDBTransaction writeTransaction = session.transaction(TypeDBTransaction.Type.WRITE)) {
                AttributeType tag = writeTransaction.concepts().putAttributeType("tag", Value.Type.STRING).resolve();
                writeTransaction.concepts().getRootEntityType().getSubtypes(writeTransaction, Concept.Transitivity.EXPLICIT).forEach(result -> {
                    if (! result.isAbstract()) {
                        result.setOwns(writeTransaction,tag).resolve();
                    }
                });
                writeTransaction.commit();
            }
        }
        driver.close();
    }
}
----

For more details about these and other API methods, see the xref:drivers::java/api-reference.adoc[API reference].
--

Node.js::
+
--
.{code-caption}
[,js]
----
const { TypeDB } = require("typedb-driver/TypeDB");
const { SessionType } = require("typedb-driver/api/connection/TypeDBSession");
const { TransactionType } = require("typedb-driver/api/connection/TypeDBTransaction");
const { Concept } = require("typedb-driver/api/concept/Concept");

async function main() {
    const driver = await TypeDB.coreDriver("127.0.0.1:1729");
    try {
        session = await driver.session("sample_db", SessionType.SCHEMA);
        try {
            transaction = await session.transaction(TransactionType.WRITE);
            let tag = await transaction.concepts.putAttributeType("tag", Concept.ValueType.STRING);
            let rootEntity = await transaction.concepts.getRootEntityType();
            let entites = await rootEntity.getSubtypes(transaction, Concept.Transitivity.EXPLICIT);
            await entites.forEach(entity => entity.setOwns(transaction, tag));
            await transaction.commit();
        }
        catch(e) {console.log(e);}
        finally {if (transaction.isOpen()) {await transaction.close()};}
    }
    catch(e) { console.log(e);}
    finally {await session?.close();}
}
main();
----

For more details about these and other API methods, see the xref:drivers::nodejs/api-reference.adoc[API reference].
--

C++::
+
--
.{code-caption}
[,cpp]
----
#include <iostream>
#include <typedb_driver.hpp>

int main() {
    try {
        TypeDB::Driver driver = TypeDB::Driver::coreDriver("127.0.0.1:1729");
        TypeDB::Options options;
        {
            auto session = driver.session("sample_db", TypeDB::SessionType::SCHEMA, options);
            auto tx = session.transaction(TypeDB::TransactionType::WRITE, options);
            auto tag = tx.concepts.putAttributeType("tag", TypeDB::ValueType::STRING).get();
            auto root_entity = tx.concepts.getRootEntityType();
            auto entities = root_entity -> getSubtypes(tx, TypeDB::Transitivity::EXPLICIT);
            for (auto& entity : entities) {
                    if (!(entity->isAbstract())) {
                        (void) entity->setOwns(tx, tag.get());
                    }
                }
            tx.commit();
        }
    } catch (TypeDB::DriverException e ) {return 2;}
    return 0;
}
----

For more details about these and other API methods, see the xref:drivers::cpp/api-reference.adoc[API reference].
--
====

The above example adds an attribute type `tag` of a String value type and adds ownership over it for
all non-abstract entity types that directly subtype the root `entity` type.

== Learn more

[cols-2]
--
.xref:typeql::schema/define.adoc[]
[.clickable]
****
Learn more about Define queries in TypeQL: syntax, behaviour, and query examples.
****

.xref:manual::writing/overview.adoc[]
[.clickable]
****
Learn how to write some data to a database with the schema you just defined.
****

.xref:learn::4-designing-schemas/4-designing-schemas.adoc[Designing schema curriculum]
[.clickable]
****
* xref:learn::4-designing-schemas/4.1-conceptual-modeling.adoc[]
* xref:learn::4-designing-schemas/4.2-the-bookstore-model.adoc[]
* xref:learn::4-designing-schemas/4.3-defining-entity-types.adoc[]
* xref:learn::4-designing-schemas/4.4-defining-relation-types.adoc[]
* xref:learn::4-designing-schemas/4.5-defining-attribute-types.adoc[]
* xref:learn::4-designing-schemas/4.6-defining-owners-and-roleplayers.adoc[]
* xref:learn::4-designing-schemas/4.7-the-bookstore-schema.adoc[]
****

.xref:drivers::overview.adoc[TypeDB drivers]
[.clickable]
****
* xref:drivers::rust/overview.adoc[] -- xref:drivers::rust/api-reference.adoc[Rust API reference]
* xref:drivers::python/overview.adoc[] -- xref:drivers::python/api-reference.adoc[Python API reference]
* xref:drivers::java/overview.adoc[] -- xref:drivers::java/api-reference.adoc[Java API reference]
* xref:drivers::nodejs/overview.adoc[] -- xref:drivers::nodejs/api-reference.adoc[Node.js API reference]
* xref:drivers::cpp/overview.adoc[] -- xref:drivers::cpp/api-reference.adoc[C++ API reference]
****
--
