= Schema editing
:experimental:

This page assumes you've already followed instructions from the xref:connecting/overview.adoc[] section pages.
Here, you'll see how to modify an existing schema without TypeQL queries.
For a Define query, see the xref:manual::defining/define.adoc[] page.

There are two ways of modifying the schema of a database without TypeQL Define/Undefine queries:
with Studio's <<_modify_with_type_editor,Type Editor>> and with <<_modify_with_driver_api,driver API>> methods.

[#_modify_with_type_editor]
== Modify with Type Editor

include::manual::studio.adoc[tag=type-editor]

[#_modify_with_driver_api]
== Modify with driver API

Driver API has methods can be used to work with schema types and rules.
These methods can vary from driver to driver due to language-specific details.

=== Example

See below an example of schema manipulation using driver API methods.

:code-caption: Driver API schema modification
[tabs]
====
Rust::
+
--
.{code-caption}
[,rust, indent=0]
----
include::manual::partial$rust-manual-code.rs[tags=types-editing]
----

For more details about these and other API methods, see the xref:drivers::rust/api-reference.adoc[API reference].
--

Python::
+
--
.{code-caption}
[,python, indent=0]
----
include::manual::partial$python-manual-code.py[tags=types-editing]
----

For more details about these and other API methods, see the xref:drivers::python/api-reference.adoc[API reference].
--

Java::
+
--
.{code-caption}
[,java, indent=0]
----
include::manual::partial$java-manual-code.java[tags=types-editing]

----

For more details about these and other API methods, see the xref:drivers::java/api-reference.adoc[API reference].
--

Node.js::
+
--
.{code-caption}
[,js]
----
const { TypeDB } = require("typedb-driver/TypeDB");
const { SessionType } = require("typedb-driver/api/connection/TypeDBSession");
const { TransactionType } = require("typedb-driver/api/connection/TypeDBTransaction");
const { Concept } = require("typedb-driver/api/concept/Concept");

async function main() {
    const driver = await TypeDB.coreDriver("127.0.0.1:1729");
    try {
        session = await driver.session("sample_db", SessionType.SCHEMA);
        try {
            transaction = await session.transaction(TransactionType.WRITE);
            let tag = await transaction.concepts.putAttributeType("tag", Concept.ValueType.STRING);
            let rootEntity = await transaction.concepts.getRootEntityType();
            let entites = await rootEntity.getSubtypes(transaction, Concept.Transitivity.EXPLICIT);
            await entites.forEach(entity => entity.setOwns(transaction, tag));
            await transaction.commit();
        }
        catch(e) {console.log(e);}
        finally {if (transaction.isOpen()) {await transaction.close()};}
    }
    catch(e) { console.log(e);}
    finally {await session?.close();}
}
main();
----

For more details about these and other API methods, see the xref:drivers::nodejs/api-reference.adoc[API reference].
--

C++::
+
--
.{code-caption}
[,cpp]
----
#include <iostream>
#include <typedb_driver.hpp>

int main() {
    try {
        TypeDB::Driver driver = TypeDB::Driver::coreDriver("127.0.0.1:1729");
        TypeDB::Options options;
        {
            auto session = driver.session("sample_db", TypeDB::SessionType::SCHEMA, options);
            auto tx = session.transaction(TypeDB::TransactionType::WRITE, options);
            auto tag = tx.concepts.putAttributeType("tag", TypeDB::ValueType::STRING).get();
            auto root_entity = tx.concepts.getRootEntityType();
            auto entities = root_entity -> getSubtypes(tx, TypeDB::Transitivity::EXPLICIT);
            for (auto& entity : entities) {
                    if (!(entity->isAbstract())) {
                        (void) entity->setOwns(tx, tag.get());
                    }
                }
            tx.commit();
        }
    } catch (TypeDB::DriverException e ) {return 2;}
    return 0;
}
----

For more details about these and other API methods, see the xref:drivers::cpp/api-reference.adoc[API reference].
--
====

The above example adds an attribute type `tag` of a String value type and adds ownership over it for
all non-abstract entity types that directly subtype the root `entity` type.

== Learn more

[cols-2]
--
.xref:typeql::schema/define.adoc[]
[.clickable]
****
Learn more about Define queries in TypeQL: syntax, behaviour, and query examples.
****

.xref:manual::writing/overview.adoc[]
[.clickable]
****
Learn how to write some data to a database with the schema you just defined.
****

.xref:learn::4-designing-schemas/4-designing-schemas.adoc[Designing schema curriculum]
[.clickable]
****
Learn how to write some data to a database with the schema you just defined.
****

.xref:drivers::overview.adoc[TypeDB drivers]
[.clickable]
****
Learn more about existing TypeDB drivers for various programming languages/frameworks.
****
--
