= Values overview
:page-no-toc: 1
:page-aliases: {page-component-version}@typeql::values/overview.adoc

[#_blank_heading]
== {blank}

In TypeQL, values can be represented by literal values,
value variables, or concept variables that represent attributes.
You can perform comparison, arithmetic operations, and call functions on values.

[cols-2]
--
.xref:{page-component-version}@typeql::values/value-types.adoc[]
[.clickable]
****
Long, double, string, boolean, and date-time.
****

.xref:{page-component-version}@typeql::values/value-variables.adoc[]
[.clickable]
****
Query variables to store values.
****

.xref:{page-component-version}@typeql::values/comparators.adoc[]
[.clickable]
****
Set constraints on values in a pattern.
****

.xref:{page-component-version}@typeql::values/arithmetic.adoc[]
[.clickable]
****
Perform basic arithmetic operations on values.
****

.xref:{page-component-version}@typeql::values/functions.adoc[]
[.clickable]
****
Built-in functions that take value(s) as input.
****
--
