== Check the transaction's type

=== Syntax

[source,java]
----
transaction.type();
----

=== Description

Checks the transaction's type (READ or WRITE)

=== Returns

* Transaction.Type

== Check if the transaction is open

=== Syntax

[source,java]
----
transaction.isOpen();
----

=== Returns

* boolean

== Access Concept API methods

=== Syntax

[source,java]
----
transaction.concepts();
----

=== Description

Gets the xref:java/java-api-ref.adoc#_conceptmanager[`ConceptManager`] for this Transaction, providing access to all
xref:java/java-api-ref.adoc#_concept[Concept] methods.

=== Returns

* xref:java/java-api-ref.adoc#_conceptmanager[`ConceptManager`]

[#_logic_methods]
== Logic methods

=== Syntax

[source,java]
----
transaction.logic();
----

=== Description

Gets the xref:java/java-api-ref.adoc#_logicmanager[`LogicManager`] for this Transaction, providing access to all
xref:java/java-api-ref.adoc#_logic_methods[Logic] methods.

=== Returns

* xref:java/java-api-ref.adoc#_logicmanager[`LogicManager`]

== Access Query API methods

=== Syntax

[source,java]
----
transaction.query();
----

=== Description

Gets the [`QueryManager`]  for this Transaction, from which any TypeQL query can be executed.

=== Returns

* [`QueryManager`] 

== Commit a write transaction

=== Syntax

[source,java]
----
transaction.commit();
----

=== Description

Commits the changes made via this transaction to the TypeDB database.
**Whether or not the transaction is commited successfully, it gets closed after the commit call.**

=== Returns

* void

== Rollback a write transaction

=== Syntax

[source,java]
----
transaction.rollback();
----

=== Description

Rolls back the uncommitted changes made via this transaction.

=== Returns

* void

== Close a read transaction

=== Syntax

[source,java]
----
transaction.close();
----

=== Description

Closes the transaction.

=== Returns

* void

