= Inference
:experimental:
:tabs-sync-option:


In this guide, you'll see how to retrieve inferred data from a database using Studio, Console, or one of the drivers.

== Understanding inference

Rule-based inference can derive new facts from matching patterns in the existing data.
It can be used in read transactions only, so no new facts get to be persisted in the database.

== How to define a rule

Before you begin, make sure you followed instructions from the xref:{page-component-version}@manual::reading/get.adoc[] page. Inference uses rules defined in the schema of a database.
Since our schema from the
xref:{page-component-version}@manual::defining/define.adoc[] page has no rules in it, let's add a new rule to the schema first:

.Simple rule example
[,typeql]
----
rule users:
when {
    $u isa user;
} then {
    $u has name "User";
};
----

Add the `define` keyword at the beginning and send it as a Define query.
See xref:{page-component-version}@manual::defining/define.adoc#_how_to_send_a_define_query[How to send a Define query] for exact instructions.

[#_how_to_send_a_query_with_inference]
== How to send a query with inference

Inference can be enabled as a transaction option for any `read` transaction.

The easiest way to send a read query with inference is to use Studio or Console:

[tabs]
====
Studio::
+
--
Follow the xref:{page-component-version}@manual::studio.adoc#_prepare_a_query[Studio manual]
to connect to TypeDB and select a project folder.
Then use the steps below:

. Use a drop-down list in the top toolbar to select a database.
. Switch to `data` session and `read` transaction types.
. Enable the inference transaction option, by toggling on the `infer` button.
. Open a new tab and insert or type in an Insert query, for example:
+
.TypeQL Fetch query
[,typeql]
----
match
$u isa user;
fetch
$u: name;
----
. Run the query by clicking the image:{page-component-version}@home::studio-icons/svg/studio_run.svg[width=24]
btn:[Run Query] button.
--

Console::
+
--
. Open a `data` session and `read` transaction to the selected database (e.g., `sample_db`)
with the `infer` transaction option enabled:
+
[,bash]
----
transaction sample_db data read --infer true
----
. Send the Fetch query:
+
[,bash]
----
match
$u isa user;
fetch
$u: name;
----
+
Push btn:[Enter] twice to send the query.
. Close the transaction:
+
[,bash]
----
close
----
--
====

The resulted Log output should look like this:

.Results example
[,js]
----
{
    "u": {
        "name": [
            { "value": "Alice", "type": { "label": "name", "root": "attribute", "value_type": "string" } },
            { "value": "User", "type": { "label": "name", "root": "attribute", "value_type": "string" } }
        ],
        "type": { "label": "user", "root": "entity" }
    }
}
{
    "u": {
        "name": [
            { "value": "Bob", "type": { "label": "name", "root": "attribute", "value_type": "string" } },
            { "value": "User", "type": { "label": "name", "root": "attribute", "value_type": "string" } }
        ],
        "type": { "label": "user", "root": "entity" }
    }
}
{
    "u": {
        "name": [
            { "value": "Charlie", "type": { "label": "name", "root": "attribute", "value_type": "string" } },
            { "value": "User", "type": { "label": "name", "root": "attribute", "value_type": "string" } }
        ],
        "type": { "label": "user", "root": "entity" }
    }
}
----

To send a fetch query with inference programmatically, use xref:{page-component-version}@drivers::overview.adoc[drivers]:

[tabs]
====
Rust::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::rust/api-reference.adoc#_struct_QueryManager_fetch__[transaction.query().fetch()] or
xref:{page-component-version}@drivers::rust/api-reference.adoc#_struct_QueryManager_get__[transaction.query().get()]
method to retrieve data with inference:


[,rust,indent=0]
----
include::{page-component-version}@manual::partial$rust-manual-code.rs[tags=databases,indent=8]
include::{page-component-version}@manual::partial$rust-manual-code.rs[tags=infer-fetch]
----
--

Python::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::python/api-reference.adoc#_QueryManager_fetch__query_str__options_TypeDBOptions__None[transaction.query.fetch()] or
xref:{page-component-version}@drivers::python/api-reference.adoc#_QueryManager_get__query_str__options_TypeDBOptions__None[transaction.query.get()]
method to retrieve data with inference:


[,python,indent=0]
----
include::{page-component-version}@manual::partial$python-manual-code.py[tags=infer-fetch]
----
--

Node.js::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::nodejs/api-reference.adoc#_QueryManager_fetch__query_string__options_TypeDBOptions[transaction.query.fetch()] or
xref:{page-component-version}@drivers::nodejs/api-reference.adoc#_QueryManager_get__query_string__options_TypeDBOptions[transaction.query.get()]
method to retrieve data with inference:


[,js,indent=0]
----
include::{page-component-version}@manual::partial$nodejs-manual-code.js[tags=infer-fetch]
----
--

Java::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::java/api-reference.adoc#_QueryManager_fetch__com_vaticle_typeql_lang_query_TypeQLFetch[transaction.query().fetch()] or
xref:{page-component-version}@drivers::java/api-reference.adoc#_QueryManager_get__com_vaticle_typeql_lang_query_TypeQLGet__TypeDBOptions[transaction.query().get()]
method to retrieve data with inference:


[,java,indent=0]
----
include::{page-component-version}@manual::partial$java-manual-code.java[tags=infer-fetch]
----
--

C#::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::csharp/api-reference.adoc#_IEnumerable__JObject___TypeDB_Driver_Api_IQueryManager_Fetch___string_query_[transaction.Query.Fetch()] or
xref:{page-component-version}@drivers::csharp/api-reference.adoc#_IEnumerable__IConceptMap___TypeDB_Driver_Api_IQueryManager_Get___string_query_[transaction.query.get()]
method to retrieve data with inference:


[,csharp,indent=0]
----
include::{page-component-version}@manual::partial$csharp-manual-code.cs[tags=infer-fetch]
----
--

C++::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::cpp/api-reference.adoc#_JSONIterable_TypeDBQueryManagerfetch___const_stdstring__query__const_Options__options__Options_____const[transaction.query.fetch()] or
xref:{page-component-version}@drivers::cpp/api-reference.adoc#_ConceptMapIterable_TypeDBQueryManagerget___const_stdstring__query__const_Options__options__Options_____const[transaction.query.get()]
method to retrieve data with inference:


[,cpp,indent=0]
----
include::{page-component-version}@manual::partial$cpp-manual-code.cpp[tags=infer-fetch,indent=0]
----
--

C::
+
--
Follow the xref:{page-component-version}@manual::connecting/connection.adoc[connection guide]
to connect the `driver` to TypeDB Cloud or TypeDB Core.


Open a read transaction, and use the
xref:{page-component-version}@drivers::c/api-reference.adoc#_query_fetch[query_fetch()] or
xref:{page-component-version}@drivers::c/api-reference.adoc#_query_get[query_get()]
method to retrieve data with inference:


[,c,indent=0]
----
include::{page-component-version}@manual::partial$c-manual-code.c[tags=infer-fetch]
----
--
====

== Learn more

[cols-2]
--
.xref:{page-component-version}@typeql::queries/get.adoc[]
[.clickable]
****
Learn more about Get queries in TypeQL: syntax, behavior, and query examples.
****

.xref:{page-component-version}@typeql::queries/fetch.adoc[]
[.clickable]
****
Learn more about Fetch queries in TypeQL: syntax, behavior, and query examples.
****

.xref:{page-component-version}@academy::10-using-inference/overview.adoc[]
[.clickable]
****
Check out the Using inference section of TypeDB Academy.
****
--
