= Tools
:page-aliases: {page-version}@manual::tools.adoc

Explore the tools available for working with TypeDB.

[cols-2]
--
.xref:{page-version}@tools::studio.adoc[]
[.clickable]
****
TypeDB Studio - the visual web client for TypeDB.
****

.xref:{page-version}@tools::console.adoc[]
[.clickable]
****
TypeDB Console - the CLI client for TypeDB.
****

.xref:{page-version}@tools::console.adoc[]
[.clickable]
****
TypeDB Loader - the CLI tool for loading datasets into TypeDB
****

.xref:{page-version}@tools::admin.adoc[]
[.clickable]
****
TypeDB Admin Tool - local-only CLI for inspecting and managing a running TypeDB server.
****

.xref:{page-version}@tools::ide-plugins.adoc[]
[.clickable]
****
IDE plugins for TypeDB development.
****

.xref:{page-version}@tools::mcp-server.adoc[]
[.clickable]
****
TypeDB MCP Server - enable AI assistants to interact with TypeDB.
****

.xref:{page-version}@tools::typedb-cloud-api.adoc[]
[.clickable]
****
API for programmatically interacting with TypeDB Cloud.
****
--
