= Tutorials

In this section, you will find tutorials for accomplishing specific TypeDB tasks.

**New users** - We recommend new users begin with the xref:{page-version}@home::get-started/index.adoc[get started] guide
in the home section.

[cols-2]
--
.xref:{page-version}@tutorials::deploy-through-api.adoc[]
[.clickable]
****
Set up a script for launching TypeDB from the TypeDB Cloud API
****

.xref:{page-version}@tutorials::use-github-actions.adoc[]
[.clickable]
****
Run TypeDB from your GitHub Actions CI pipeline
****

.xref:{page-version}@tutorials::pipelines-read.adoc[]
[.clickable]
****
Read data from TypeDB
****

.xref:{page-version}@tutorials::pipelines-crud.adoc[]
[.clickable]
****
Write and update data in TypeDB
****

.xref:{page-version}@tutorials::pipelines-advanced.adoc[]
[.clickable]
****
Advanced TypeDB pipelines and patterns
****
--

Got other tutorials you'd like to see?
Get in touch at link:mailto:community@typedb.com?subject=Request%20new%20tutorial[community@typedb.com]
or link:https://typedb.com/discord[join our discord server].
