= Redefine query
:test-typeql: linear

Redefine queries are used
// tag::overview[]
to modify existing types, capabilities, annotations, or functions in the schema, or to rename types.
// end::overview[]

== Syntax

Redefine queries start with the `redefine` keyword following by a single xref:{page-version}@typeql-reference::schema/define.adoc[definition statement] of the define queries format, or a single type renaming statement.

[,typeql]
----
redefine
  <definition_statement>
----

.Type renaming statement
[,typeql]
----
[<kind>] <label> label <new label>;
----

.Role type renaming statement
[,typeql]
----
<relation label>:<role label> label <new role label>;
----

== Behavior

Redefine queries can be used to modify types and type capabilities, to rename types, or to override functions.

For clarity and precision, only one redefinition is allowed per query.

Renaming a type changes only its label: its data, capabilities, annotations, and position in the type hierarchy are preserved.
Functions are not updated to the new label, so if a stored function refers to a renamed type by its old label, the commit fails.

An error is returned (on execution or on commit), and no changes are preserved, if:

- There is no existing definition to redefine.
- The redefinition matches the definition and does nothing.
- There are multiple changes in the schema in the result of the redefinition.
- The query results in an invalid schema.
- The new label of a renamed type is already in use (for role types, within the same relation type hierarchy).

[#_statements_behavior]
=== Statements

* xref:{page-version}@typeql-reference::statements/label.adoc[`label` statements] rename entity, relation, attribute, and role types.
* xref:{page-version}@typeql-reference::statements/relates.adoc[`relates` statements] redefine role types specialization using `relates ... as`.
* xref:{page-version}@typeql-reference::statements/value.adoc[`value` statements] redefine value types of attribute types.
* xref:{page-version}@typeql-reference::statements/sub.adoc[`sub` statements] redefine supertypes of types.
* xref:{page-version}@typeql-reference::annotations/index.adoc[@annotations] redefine annotations with arguments, replacing their values.
* xref:{page-version}@typeql-reference::statements/fun.adoc[`fun` statements] redefine functions, replacing their capabilities and bodies.

== Examples

.Schema for the following examples
[%collapsible]
====
[,typeql]
----
#!test[schema, commit]
include::{page-version}@typeql-reference::example$tql/schema_statements_functions.tql[tags=define-keyword;entities;attributes;extended-attributes]
attribute tag value string;
entity post owns tag @card(0..);
relation parentship relates parent, relates child;
relation fathership sub parentship, relates father as child;
----
====

=== Redefining types' capabilities and annotations

.Redefining type's sub
[,typeql]
----
#!test[schema]
redefine user sub page;
----

.Redefining attribute type's value type
[,typeql]
----
#!test[schema]
redefine karma value integer;
----

.Redefining value type's annotation with arguments
[,typeql]
----
#!test[schema]
redefine email value string @regex("^.*@typedb\.com$");
----

.Redefining type capability's annotation with arguments
[,typeql]
----
#!test[schema]
redefine post owns tag @card(0..5);
----

.Redefining relates specialization
[,typeql]
----
#!test[schema]
redefine fathership relates father as parent;
----

=== Renaming types

.Renaming an entity type
[,typeql]
----
#!test[schema]
redefine entity post label article;
----

.Renaming an attribute type without specifying its kind
[,typeql]
----
#!test[schema]
redefine tag label hashtag;
----

.Renaming a role type
[,typeql]
----
#!test[schema]
redefine parentship:child label offspring;
----

=== Redefining functions

include::{page-version}@typeql-reference::functions/writing.adoc[tag=redefine]
